# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

MTSAFE

SWIGFLAGS = -I../..
INCLUDES = -I../.. $(MONETDB_INCS) $(RUBY_INCS)

# we need this flag to allow for a name that does not start with "lib"
MapiLib_la_LDFLAGS = -module

#  Both GNU's gcc and Intel's icc do not like to compile swig-generated code
#  with our strict X_CFLAGS.
#  Instead of diabling the strict X_CFLAGS completely,
#  we use GCC_SWIG_CFLAGS and ICC_SWIG_CFLAGS, respectively,
#  to disable only the problematic warnings/errors as locally as possbile.
#  See buildtools/conf/MonetDB.m4 for details.
#CFLAGS = $(GCC_SWIG_CFLAGS) $(ICC_SWIG_CFLAGS)
#
#  However, there are situations where user-chosen CFLAGS and/or X_CFLAGS
#  are beyond our control. Hence, for the sake of a smooth compilation, we
#  have to take the freedom to overrule the user's deliberate choice for
#  X_CFLAGS by locally disabling them indifferently.
X_CFLAGS =

lib_MapiLib = {
	PREFIX =
	NAME = MapiLib
	SOURCES = MapiLib.ruby.i
	LIBS = ../../mapilib/libMapi $(RUBY_LIBS) $(MATH_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
	DIR = $(prefix)/$(RUBY_LIBDIR)
}
