# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

MTSAFE

scripts_pl = {
	COND = HAVE_TESTING
	DIR = bindir
	SOURCES = sqlsample.pl malsample.pl
}

EXTRA_DIST = client.pl smack00.pl smack01.pl
