#!/bin/sh

# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

# if we have an older automake, patch our files a bit
case `automake --version | egrep "[0-9]\.[0-9](\.[0-9])?.*"` in
	*1.[56]*)
	mv configure.ac configure.ac.orig_bootstrap
	cp configure.ac.orig_bootstrap configure.ac
	patch << EOF
Index: configure.ac
===================================================================
RCS file: /cvsroot/monetdb/buildtools/mel/configure.ac,v
retrieving revision 1.4
diff -u -r1.4 configure.ac
--- configure.ac	13 Aug 2005 15:46:27 -0000	1.4
+++ configure.ac	27 Oct 2005 16:19:55 -0000
@@ -3,9 +3,9 @@

 AC_PREREQ(2.57)
 AC_INIT([mel], [1.0], [monet@cwi.nl])
-AM_INIT_AUTOMAKE
+AM_INIT_AUTOMAKE([mel], [1.0])
 AC_CONFIG_SRCDIR([mel.mx])
-AC_CONFIG_HEADER([mel_config.h])
+AM_CONFIG_HEADER([mel_config.h])
 AC_SET_MAKE
 
 # Checks for programs.
@@ -37,7 +37,6 @@
 fi
 AC_SUBST(MX)
 AC_CHECK_PROG(LOCKFILE,lockfile,lockfile -r 2,echo)
-AC_PROG_LEX
 AM_PROG_LEX()
 AC_PROG_YACC()
 AC_PROG_LN_S()
EOF
	;;
esac

aclocal || exit 1
autoheader || exit 1
autoconf || exit 1
automake --add-missing --copy --force-missing --foreign || exit 1

if [ -f configure.ac.orig_bootstrap ];
then
	mv configure.ac.orig_bootstrap configure.ac
fi

