#!/bin/bash

dirlst=${MONET_DBFARM:=${MONET_PREFIX}/var/MonetDB/dbfarm}

if [[ $# != 1 ]]
then echo Usage: cleardb \<dbname\>
     exit 1
fi

for d in ${dirlst/:/ }
do
   if [[ -d $d/$1 ]]
   then dbdir=$d
   fi
done

if [[ ${dbdir:-null} == null ]]
then echo Cannot find database $1 in $dirlst
     exit 2
fi

echo Clearing database $1
rm -rf $dbdir/$1
mkdir $dbdir/$1

