
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

SUBDIRS = xrpc

EXTRA_DIST_DIR = Tests

INCLUDES = \
	.. \
	../../monetdb4/monet \
	../../monetdb4/modules/plain \
	../../monetdb4/modules/contrib \
	../../monetdb4/modules \
	../../monetdb4/modules/calibrator \
	../../common/options \
	../../common/stream \
	../../common/utils \
	../../gdk \
	$(libxml2_CFLAGS)
PF_LIBS = $(libxml2_LIBS) $(DL_LIBS)

# these defines are needed to get shttpd to compile in the right way
CFLAGS = -DEMBEDDED -DMT -DNO_CGI -DNO_AUTH -DIO_MAX=10240

lib_serialize = {
	NOINST
	SOURCES = serialize_null.mx \
		  serialize.mx \
		  serialize_dflt.mx
}

lib_pf = {
	NOINST
	SOURCES = \
		ll_staircasejoin.mx \
		ll_upwards.mx \
		ll_prec_foll.mx \
		ll_sibling.mx \
		vx_index.mx
}

lib_xrpc_common = {
	NOINST
	SOURCES = xrpc_common.mx
}

lib__pf_support = {
	DIR = libdir/monetdb4
	SOURCES = \
		pf_support.mx \
		shredder.mx 
	LIBS = \
		libserialize libpf $(PF_LIBS) \
		../../gdk/libbat4 \
		../../common/stream/libstream4 \
		../../monetdb4/monet/libmonet \
		$(PTHREAD_LIBS) \
		../../monetdb4/modules/plain/lib_lock \
		../../monetdb4/modules/plain/lib_monettime \
		../../monetdb4/modules/plain/lib_streams \
		../../monetdb4/modules/plain/lib_builtin \
		../../monetdb4/modules/plain/lib_ascii_io \
		../../monetdb4/modules/plain/lib_algebra \
		../../monetdb4/modules/plain/lib_constant
}

lib__pf_standoff = {
	DIR = libdir/monetdb4
	SOURCES = \
		pf_standoff.mx 

	LIBS = \
		$(PF_LIBS) \
		../../gdk/libbat4 \
		../../common/stream/libstream4 \
		../../monetdb4/monet/libmonet \
		../../monetdb4/modules/plain/lib_streams \
		../../monetdb4/modules/plain/lib_builtin \
		../../monetdb4/modules/plain/lib_ascii_io \
		../../monetdb4/modules/plain/lib_algebra \
		../../monetdb4/modules/plain/lib_sys \
		../../monetdb4/modules/plain/lib_constant
}

lib__pathfinder = {
	DIR = libdir/monetdb4
	SOURCES = \
		pathfinder.mx

	LIBS = \
		../compiler/libcompiler1 \
		../compiler/schema/libschema \
		../compiler/debug/libdebug \
		../compiler/parser/libparser \
		../compiler/semantics/libsemantics \
		../compiler/core/libcore \
		../compiler/algebra/libalgebra \
		../compiler/algebra/map/libmap \
		../compiler/algebra/prop/libprop \
		../compiler/algebra/opt/libopt \
		../compiler/mil/libmil \
		../compiler/mem/libmem_embedded \
		../compiler/libcompiler2 \
		../compiler/sql/libsql \
		../compiler/xmlimport/libxmlimport \
		../compiler/utils/libstringutils \
		$(PF_LIBS) \
		../../gdk/libbat4 \
		../../common/stream/libstream4 \
		../../monetdb4/monet/libmonet \
		$(PTHREAD_LIBS) \
		../../monetdb4/modules/plain/lib_logger \
		../../monetdb4/modules/plain/lib_streams \
		../../monetdb4/modules/plain/lib_builtin \
		../../monetdb4/modules/plain/lib_ascii_io \
		../../monetdb4/modules/plain/lib_algebra \
		../../monetdb4/modules/plain/lib_sys \
		../../monetdb4/modules/plain/lib_constant \
		../../monetdb4/modules/mapi/lib_mapi
}

lib__xrpc_client = {
	DIR = libdir/monetdb4
	SOURCES = xrpc_client.mx
	LIBS = \
		libserialize libxrpc_common \
		lib_pf_support lib_pathfinder \
		$(PF_LIBS) $(SOCKET_LIBS) \
		../../gdk/libbat4 \
		../../common/stream/libstream4 \
		../../monetdb4/monet/libmonet \
		../../monetdb4/modules/plain/lib_streams \
		../../monetdb4/modules/plain/lib_builtin \
		../../monetdb4/modules/plain/lib_ascii_io
}

lib__xrpc_server = {
	DIR = libdir/monetdb4
	SOURCES = \
		shttpd.c shttpd.h \
		xrpc_server.mx
	LIBS = \
		libxrpc_common \
		lib_pf_support lib_pathfinder \
		$(PF_LIBS) $(SOCKET_LIBS) \
		../../gdk/libbat4 \
		../../common/stream/libstream4 \
		../../monetdb4/monet/libmonet \
		$(PTHREAD_LIBS) \
		../../monetdb4/modules/plain/lib_logger \
		../../monetdb4/modules/mapi/lib_mapi \
		../../monetdb4/modules/plain/lib_streams \
		../../monetdb4/modules/plain/lib_builtin \
		../../monetdb4/modules/plain/lib_ascii_io
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	SOURCES = pathfinder.mx pf_support.mx pf_standoff.mx xrpc_client.mx xrpc_server.mx 
}
