
# Copyright Notice:
# -----------------
# 
# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the ``Pathfinder'' system. The Initial
# Developer of the Original Code is the Database & Information
# Systems Group at the University of Konstanz, Germany. Portions
# created by U Konstanz are Copyright (C) 2000-2004 University
# of Konstanz. All Rights Reserved.
#
# Contributors:
#         Niels Nes <Niels.Nes@cwi.nl>
#

INCLUDES = $(MONETDB_INCS)

lib__pathfinder = {
	DIR = libdir/MonetDB
	SOURCES = \
		pathfinder.mx \
		staircasejoin.mx \
		prec_foll.mx \
		levelsteps.mx

	WINLIBS = -lbat -lmonet -lstream -l_streams -l_kernel -l_ascii_io -l_algebra
	LIBS = $(MONETDB_LIBS)
}

lib__pf_support = {
	DIR = libdir/MonetDB
	SOURCES = \
		pf_support.mx

	WINLIBS = -lbat -lmonet -lstream -l_streams -l_kernel -l_ascii_io -l_algebra
	LIBS = $(MONETDB_LIBS)
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = pathfinder.mx pf_support.mx
}
