
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Initial Developer of the Original Code is the Database &
# Information Systems Group at the University of Konstanz, Germany.
# Portions created by the University of Konstanz are Copyright (C)
# 2000-2005 University of Konstanz.  All Rights Reserved.
#

EXTRA_DIST_DIR = Tests

INCLUDES = $(MONETDB_INCS) $(LIBXML2_CFLAGS) ../compiler/include
PF_LIBS = $(LIBXML2_LDADD) $(LIBXML2_LIBS) $(DL_LIBS)

lib__pf_support = {
	DIR = libdir/MonetDB
	SOURCES = \
		pf_support.mx \
		staircasejoin.mx \
		ll_staircasejoin.mx \
		prec_foll.mx \
		levelsteps.mx \
		shredder.mx \
		serialize.mx

	LIBS = \
		$(PF_LIBS) $(MONETDB_LIBS) \
		-lbat -lmonet -lstream \
		-l_streams -l_builtin -l_ascii_io -l_algebra 
}

lib__pathfinder = {
	DIR = libdir/MonetDB
	SOURCES = \
		pathfinder.mx

	LIBS = \
		../compiler/libcompiler1 \
		../compiler/schema/libschema \
		../compiler/debug/libdebug \
		../compiler/mem/libmem \
		../compiler/parser/libparser \
		../compiler/semantics/libsemantics \
		../compiler/core/libcore \
		../compiler/algebra/libalgebra \
		../compiler/mil/libmil \
		../compiler/libcompiler2 \
		$(PF_LIBS) $(MONETDB_LIBS) \
		-lbat -lmonet -lstream \
		-l_streams -l_builtin -l_ascii_io -l_algebra 
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = pathfinder.mx pf_support.mx
}

