#!/bin/bash
#
# runMonet <dbname> [<script>]
#
# Run Monet database server on database <dbname> 
# and optionally execute MIL script <script>
#
# Copyright Notice:
# -----------------
# 
# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the ``Pathfinder'' system. The Initial
# Developer of the Original Code is the Database & Information
# Systems Group at the University of Konstanz, Germany. Portions
# created by U Konstanz are Copyright (C) 2000-2003 University
# of Konstanz. All Rights Reserved.
#
# Contributors:
#         Torsten Grust <torsten.grust@uni-konstanz.de>
#         Maurice van Keulen <M.van.Keulen@bigfoot.com>
#         Jens Teubner <jens.teubner@uni-konstanz.de>
#
# $Id$

if [[ $# == 2 ]]
then echo Executing script $2 on database $1
   Mserver --dbname $1 -c $HOME/.monet.conf $2
elif [[ $# == 1 ]]
then echo Starting Mserver on database $1\; no script
   Mserver --dbname $1 -c $HOME/.monet.conf 
else echo Usage: $0 \<dbname\> \[\<script\>\]
fi

