#!/bin/bash
#
# runMonet <dbname> [<script>]
#
# Run Monet database server on database <dbname> 
# and optionally execute MIL script <script>
#
# $Id$

if [[ $# == 2 ]]
then echo Executing script $2 on database $1
   Mserver --dbname $1 -c $HOME/.monet.conf $2
elif [[ $# == 1 ]]
then echo Starting Mserver on database $1\; no script
   Mserver --dbname $1 -c $HOME/.monet.conf 
else echo Usage: $0 \<dbname\> \[\<script\>\]
fi

