/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "09_like.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_09_like(Client c)
{
	size_t bufsize = 16384, pos = 0;
	char *buf = GDKmalloc(bufsize), *err = NULL;

	if (buf == NULL)
		throw(SQL, "sql.install_09_like", SQLSTATE(HY001) MAL_MALLOC_FAIL);
	pos += snprintf(buf + pos, bufsize - pos, " create filter function \"like\"(val string, pat string, esc string) external name algebra.\"like\"; create filter function \"ilike\"(val string, pat string, esc string) external name algebra.\"ilike\"; create filter function \"like\"(val string, pat string) external name algebra.\"like\"; create filter function \"ilike\"(val string, pat string) external name algebra.\"ilike\"; grant execute on filter function \"like\" (string, string, string) to public; grant execute on filter function \"ilike\" (string, string, string) to public; grant execute on filter function \"like\" (string, string) to public; grant execute on filter function \"ilike\" (string, string) to public;");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 09_like.sql\n");
	err = SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
	GDKfree(buf);
	return err;
}
