/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "20_vacuum.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_20_vacuum(Client c)
{
	size_t bufsize = 16384, pos = 0;
	char *buf = GDKmalloc(bufsize), *err = NULL;

	if (buf == NULL)
		throw(SQL, "sql.install_20_vacuum", SQLSTATE(HY001) MAL_MALLOC_FAIL);
	pos += snprintf(buf + pos, bufsize - pos, "   create procedure shrink(sys string, tab string) external name sql.shrink; create procedure reuse(sys string, tab string) external name sql.reuse; create procedure vacuum(sys string, tab string) external name sql.vacuum; ");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 20_vacuum.sql\n");
	err = SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
	GDKfree(buf);
	return err;
}
