/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#ifndef SQL_21_DEPENDENCY_VIEWS_H
#define SQL_21_DEPENDENCY_VIEWS_H

#include "monetdb_config.h"

#include "gdk.h"
#include "mal_client.h"

extern str sql_install_21_dependency_views(Client c);

#endif //SQL_21_DEPENDENCY_VIEWS_H
