/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "22_clients.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_22_clients(Client c)
{
	size_t bufsize = 16384, pos = 0;
	char *buf = GDKmalloc(bufsize), *err = NULL;

	if (buf == NULL)
		throw(SQL, "sql.install_22_clients", SQLSTATE(HY001) MAL_MALLOC_FAIL);
	pos += snprintf(buf + pos, bufsize - pos, " create function sys.password_hash (username string) returns string external name sql.password; create function sys.remote_table_credentials (tablename string) returns table (\"uri\" string, \"username\" string, \"hash\" string) external name sql.rt_credentials; create function sys.sessions() returns table(\"user\" string, \"login\" timestamp, \"sessiontimeout\" bigint, \"lastcommand\" timestamp, \"querytimeout\" bigint, \"active\" bool) external name sql.sessions; create view sys.sessions as select * from sys.sessions(); create procedure sys.shutdown(delay tinyint) external name sql.shutdown; create procedure sys.shutdown(delay tinyint, force bool) external name sql.shutdown; create procedure sys.settimeout(\"query\" bigint) external name clients.settimeout; create procedure sys.settimeout(\"query\" bigint, \"session\" bigint) external name clients.settimeout; create procedure sys.setsession(\"timeout\" bigint) external name clients.setsession;");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 22_clients.sql\n");
	err = SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
	GDKfree(buf);
	return err;
}
