/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "25_debug.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_25_debug(Client c)
{
	size_t bufsize = 16384, pos = 0;
	char *buf = GDKmalloc(bufsize), *err = NULL;

	if (buf == NULL)
		throw(SQL, "sql.install_25_debug", SQLSTATE(HY001) MAL_MALLOC_FAIL);
	pos += snprintf(buf + pos, bufsize - pos, " create function sys.optimizer_stats() returns table (optname string, count int, timing bigint) external name inspect.optimizer_stats;  create function sys.queryCache() returns table (query string, count int) external name sql.dump_cache; create procedure sys.querylog(filename string) external name sql.logfile; create function sys.optimizers () returns table (name string, def string, status string) external name sql.optimizers; create view sys.optimizers as select * from sys.optimizers(); create view sys.environment as select * from sys.env(); GRANT SELECT ON sys.environment TO PUBLIC; create function sys.bbp () returns table (id int, name string, ttype string, count BIGINT, refcnt int, lrefcnt int, location string, heat int, dirty string, status string, kind string) external name bbp.get; create function sys.malfunctions() returns table(\"module\" string, \"function\" string, \"signature\" string, \"address\" string, \"comment\" string) external name \"manual\".\"functions\"; create procedure sys.evalAlgebra( ra_stmt string, opt bool) external name sql.\"evalAlgebra\"; create procedure sys.flush_log () external name sql.\"flush_log\"; create function sys.debug(debug int) returns integer external name mdb.\"setDebug\";");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 25_debug.sql\n");
	err = SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
	GDKfree(buf);
	return err;
}
