/*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0.  If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*
* Copyright 1997 - July 2008 CWI, August 2008 - 2019 MonetDB B.V.
*/

// This file was generated automatically through bootstrap.py.
// Do not edit this file directly.

#include "monetdb_config.h"

#include "60_wlcr.sql.h"
#include "gdk.h"
#include "mal_client.h"
#include "sql_catalog.h"

#include <assert.h>

extern str SQLstatementIntern(Client c, str *expr, str nme, bit execute, bit output, res_table **result);

str
sql_install_60_wlcr(Client c)
{
	size_t bufsize = 16384, pos = 0;
	char *buf = GDKmalloc(bufsize), *err = NULL;

	if (buf == NULL)
		throw(SQL, "sql.install_60_wlcr", SQLSTATE(HY001) MAL_MALLOC_FAIL);
	pos += snprintf(buf + pos, bufsize - pos, "  create procedure master() external name wlc.master; create procedure master(path string) external name wlc.master; create procedure stopmaster() external name wlc.stopmaster; create procedure masterbeat( duration int) external name wlc.\"setmasterbeat\"; create function masterClock() returns string external name wlc.\"getmasterclock\"; create function masterTick() returns bigint external name wlc.\"getmastertick\"; create procedure replicate() external name wlr.replicate; create procedure replicate(pointintime timestamp) external name wlr.replicate; create procedure replicate(dbname string) external name wlr.replicate; create procedure replicate(dbname string, pointintime timestamp) external name wlr.replicate; create procedure replicate(dbname string, id tinyint) external name wlr.replicate; create procedure replicate(dbname string, id smallint) external name wlr.replicate; create procedure replicate(dbname string, id integer) external name wlr.replicate; create procedure replicate(dbname string, id bigint) external name wlr.replicate; create procedure replicabeat(duration integer) external name wlr.\"setreplicabeat\"; create function replicaClock() returns string external name wlr.\"getreplicaclock\"; create function replicaTick() returns bigint external name wlr.\"getreplicatick\"; ");

	pos += snprintf(buf + pos, bufsize - pos, "commit;\n");

	assert(pos < bufsize);
	printf("#Loading: 60_wlcr.sql\n");
	err = SQLstatementIntern(c, &buf, "install", 1, 0, NULL);
	GDKfree(buf);
	return err;
}
