# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

MT_SAFE

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 09_like.sql \
		10_math.sql \
		11_times.sql \
		12_url.sql \
		13_date.sql \
		14_inet.sql \
		15_querylog.sql \
		16_tracelog.sql \
		17_temporal.sql \
		18_index.sql \
		20_vacuum.sql \
		21_dependency_functions.sql \
		22_clients.sql \
		23_skyserver.sql \
		25_debug.sql \
		26_sysmon.sql \
		27_rejects.sql \
		39_analytics.sql \
		40_json.sql \
		41_md5sum.sql \
		45_uuid.sql \
		46_profiler.sql \
		51_sys_schema_extension.sql \
		60_wlcr.sql \
		75_storagemodel.sql \
		80_statistics.sql \
		99_system.sql
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 39_analytics_hge.sql 40_json_hge.sql
}
