## Process this file with automake to produce Makefile.in
#
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

EXTRA_DIST_DIR = Tests

PARSERNAME = pf
YFLAGS = -d -p $(PARSERNAME)
LFLAGS = -P$(PARSERNAME)

#  Some versions of flex & bison seem to generate code
#  that does not compile with `gcc -Wundef`;
#  we use GCC_BISON_CFLAGS to disable the respective warning as
#  locally as possible via "-Wno-undef"
#  (see also monetdb4/monet/Makefile.ag, sql/src/server/Makefile.ag,
#  buildtools/conf/monet.m4).
CFLAGS = $(GCC_BISON_CFLAGS)

CC = $(C99)
INCLUDES = \
	../include \
	../../../common/options \
	../../../gdk \
	$(libxml2_CFLAGS)

lib_parser = {
	NOINST
	DIR = libdir
	SOURCES = \
		scanner.l \
		parser.y \
		abssyn.c 
}

