## Process this file with automake to produce Makefile.in

YFLAGS = -d

## disable -Werror
X_CFLAGS = 

INCLUDES = $(MONET_INCS) ../include

lib_parser = {
	NOINST
	DIR = libdir
	SOURCES = \
		scanner.l \
		parser.y \
		abssyn.c 
}

