# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at 
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the Monet Database System.
# 
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2002 CWI.  
# All Rights Reserved.
# 
# Contributor(s):
# 		Martin Kersten <Martin.Kersten@cwi.nl>
# 		Peter Boncz <Peter.Boncz@cwi.nl>
# 		Niels Nes <Niels.Nes@cwi.nl>
# 		Stefan Manegold  <Stefan.Manegold@cwi.nl>


MTSAFE
INCLUDES = ../../common 

MAPI_LIBS = $(SOCKET_LIBS) 

EXTRA_DIST = \
	MapiClient.java  Mapi.hs \
	MapiClient.php   Mapi.php \
	MapiClient.pl    Mapi.pm \
	MapiClient.py    Mapi.py \
	MapiClient.tcl   Mapi.tcl \

EXTRA_DIST_DIR = mapi


lib_Mapi = {
	SOURCES = Mapi.mx 
	LIBS = $(MAPI_LIBS) ../../common/libmutils ../../common/libstream
	HEADERS = h
}

jar_mapi = {
	DIR = pkglibdir
	SOURCES = mapi/MapiException.java mapi/Mapi.java MapiClient.java
}

BINS = {
	SOURCES = MapiClient.mx
	LIBS = libMapi $(MAPI_LIBS) \	
		../../common/libmutils ../../common/libstream
	MapiClient_LIBS = libMapi $(MAPI_LIBS) $(READLINE_LIBS) \
		../../common/libmutils ../../common/libstream
}

scripts_mapi = {
	DIR = bindir
	SOURCES = Mshutdown.py.in MapiClient.py.in Mshutdown.py.bat MapiClient.py.bat
}

scripts_pl = {
	DIR = pkgdatadir/site_perl
	SOURCES = Mapi.pm MapiClient.pl
}

scripts_py = {
	DIR = pkgdatadir/python
	SOURCES = Mapi.py
}
