
MTSAFE
INCLUDES = ../../common 

MAPI_LIBS = $(SOCKET_LIBS) 

EXTRA_DIST = \
	MapiClient.java  Mapi.hs \
	MapiClient.php   Mapi.php \
	MapiClient.pl    Mapi.pm \
	MapiClient.py    Mapi.py \
	MapiClient.tcl   Mapi.tcl \

EXTRA_DIST_DIR = Mapi


lib_Mapi = {
	SOURCES = Mapi.mx 
	LIBS = $(MAPI_LIBS) ../../common/libmutils
	HEADERS = h
}

BINS = {
	SOURCES = Mshutdown.mx MapiClient.mx
	LIBS = libMapi ../../common/libmutils $(MAPI_LIBS)
	MapiClient_LIBS = libMapi ../../common/libmutils \
		$(MAPI_LIBS) $(READLINE_LIBS)
}

scripts_pl = {
	DIR = pkgdatadir/site_perl
	SOURCES = Mapi.pm MapiClient.pl
}

scripts_py = {
	DIR = pkgdatadir/python
	SOURCES = Mapi.py
}
