
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2010 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

headers_html = {
	HEADERS = html js css xml
	DIR = datadir/MonetDB/xrpc/demo
	SOURCES = \
		style.css \
        res1.xml \
        req1.xml \
		index.html
}

headers_xq = {
	HEADERS = xq
	DIR = datadir/MonetDB/xrpc/demo
	SOURCES = demo-mod.xq demo-xrpcmod.xq
}

headers_img = {
	HEADERS = bmp gif png gif map
	DIR = datadir/MonetDB/xrpc/demo
	SOURCES = \
		cwi.bmp \
		MultimediaN.png \
		monet.png \
        noquery.gif
}
