# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

INCLUDES = -I../../monet \
	$(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS) \
	$(PCRE_CFLAGS) $(ICONV_CFLAGS)
MTSAFE

lib__streams = {
	DIR = pkglibdir
	SOURCES = streams.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
}

lib__str = {
	DIR = pkglibdir
	SEP = _
	SOURCES = str.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(ICONV_LIBS)
}

lib__xtables = {
	DIR = pkglibdir
	SEP = _
	SOURCES = xtables.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet ./lib_algebra \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

lib__logger = {
	DIR = pkglibdir
	SEP = _
	SOURCES = logger.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet ./lib_bat \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		algebra.mx arith.mx bat.mx builtin.mx sys.mx trans.mx \
		mkey.mx profiler.mx constant.mx \
		aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx blob.mx \
		decimal.mx enum.mx lock.mx mmath.mx monettime.mx \
		stats.mx unix.mx url.mx pqueue.mx 
		#radix.mx tcpip.mx upgrade.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(MATH_LIBS)
}

lib__counters = {
	DIR = pkglibdir
	SOURCES = counters.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(HWCOUNTERS_LIBS)
}

lib__pcl = {
	DIR = pkglibdir
	SOURCES = pcl.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(PCL_LIBS)
}

lib__pcre = {
	DIR = pkglibdir
	SOURCES = pcre.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(PCRE_LIBS)
}

headers_mil = {
	HEADERS = mil
	DIR = pkglibdir
	SOURCES = streams.mx str.mx xtables.mx constant.mx \
         	algebra.mx arith.mx bat.mx builtin.mx sys.mx trans.mx \
                mkey.mx profiler.mx \
                aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx \
		blob.mx decimal.mx enum.mx lock.mx mmath.mx \
		monettime.mx stats.mx \
		unix.mx url.mx counters.mx pcl.mx pcre.mx pqueue.mx \
		logger.mx
		# radix.mx tcpip.mx upgrade.mx
}

EXTRA_DIST_DIR = Tests
