# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

MTSAFE

# the name (libmonetdb5) is also used in ../mal/mal_linker.mx
# if you change the name here, change it there as well
lib_monetdb5 = {
	VERSION = $(MONETDB5_VERSION)
	NAME = monetdb5
	SCRIPTS = mal
	DIR = libdir
	SOURCES = libmonetdb5.rc
	LIBS = ../mal/libmal ../modules/atoms/libatoms \
		../modules/kernel/libkernel ../modules/mal/libmal \
		../optimizer/liboptimizer ../scheduler/libscheduler \
		../../common/utils/libmsabaoth \
		../../common/utils/libmuuid \
		WIN32?../../common/utils/libstrptime \
		WIN32?../../gdk/libbat \
		WIN32&HAVE_MAPI?../../clients/mapilib/libmapi \
		WIN32?../../common/stream/libstream \
		WIN32?$(UUID_LIBS) \
		WIN32?$(MATH_LIBS) \
		WIN32?$(SOCKET_LIBS) \
		WIN32?$(MALLOC_LIBS) \
		WIN32?$(PTHREAD_LIBS) \
		WIN32?$(DL_LIBS) \
		WIN32?$(openssl_LIBS) \
		WIN32?$(pcre_LIBS) \
		WIN32?$(libxml2_LIBS)
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb5.pc.in
}

EXTRA_DIST_DIR = Tests
