# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

MTSAFE

# the name (libmonetdb5) is also used in ../mal/mal_linker.mx
# if you change the name here, change it there as well
lib_monetdb5 = {
	VERSION = $(MONETDB5_VERSION)
	NAME = monetdb5
	SCRIPTS = mal
	DIR = libdir
	SOURCES = libmonetdb5.rc
	LIBS = ../mal/libmal ../modules/atoms/libatoms \
		../modules/kernel/libkernel ../modules/mal/libmal \
		../optimizer/liboptimizer ../scheduler/libscheduler \
		../../gdk/libbat \
		../../clients/mapilib/libmapi \
		../../common/stream/libstream \
		../../common/utils/libmcrypt \
		../../common/utils/libmuuid \
		../../common/utils/libmsabaoth \
		$(UUID_LIBS) $(curl_LIBS) \
		$(MATH_LIBS) $(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) \
		$(DL_LIBS) $(READLINE_LIBS) $(openssl_LIBS) $(pcre_LIBS) \
		$(LTLIBICONV) $(zlib_LIBS) $(libxml2_LIBS) \
		$(libmicrohttpd_LIBS) $(liburiparser_LIBS)
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb5.pc.in
}

EXTRA_DIST_DIR = Tests
