# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE

# the name (libmonetdb5) is also used in ../mal/mal_linker.mx
# if you change the name here, change it there as well
lib_monetdb5 = {
	VERSION = $(MONETDB5_VERSION)
	NAME = monetdb5
	SCRIPTS = mal
	DIR = libdir
	SOURCES = libmonetdb5.rc
	LIBS = ../misc/libsabaoth ../mal/libmal ../modules/atoms/libatoms \
		../modules/kernel/libkernel ../modules/mal/libmal \
		../optimizer/liboptimizer ../scheduler/libscheduler \
		../../gdk/libbat \
		../../clients/mapilib/libmapi \
		../../common/stream/libstream \
		../../common/utils/libmcrypt \
		../../common/utils/libmuuid \
		$(UUID_LIBS) $(curl_LIBS) \
		$(MATH_LIBS) $(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) \
		$(DL_LIBS) $(READLINE_LIBS) $(openssl_LIBS) $(pcre_LIBS) \
		$(LTLIBICONV) $(zlib_LIBS) $(libxml2_LIBS)
}

EXTRA_DIST_DIR = Tests
