# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

## Process this file with automake to produce Makefile.in

MTSAFE

INCLUDES = $(zlib_CFLAGS) \
		   $(BZ_CFLAGS) \
		   $(liblzma_CFLAGS) \
		   $(openssl_CFLAGS) \
		   $(curl_CFLAGS)

lib_stream  =  {
	SOURCES = stream.c stream.h stream_socket.h
	VERSION = $(STREAM_VERSION)
	LIBS = $(SOCKET_LIBS) \
		   $(zlib_LIBS) \
		   $(BZ_LIBS) \
		   $(liblzma_LIBS) \
		   $(openssl_LIBS) \
		   $(curl_LIBS) \
		   $(LTLIBICONV)
}

headers_common = {
	DIR = includedir/monetdb
	HEADERS = h
	SOURCES = stream_socket.h stream.h
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb-stream.pc.in
}
