/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common/stream/mhapi.proto */

#ifndef PROTOBUF_C_common_2fstream_2fmhapi_2eproto__INCLUDED
#define PROTOBUF_C_common_2fstream_2fmhapi_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Mhapi__QueryResult Mhapi__QueryResult;
typedef struct _Mhapi__QueryResult__Column Mhapi__QueryResult__Column;
typedef struct _Mhapi__QueryResult__ColumnUnpacked Mhapi__QueryResult__ColumnUnpacked;


/* --- enums --- */


/* --- messages --- */

struct  _Mhapi__QueryResult__Column
{
  ProtobufCMessage base;
  size_t n_string_values;
  char **string_values;
  size_t n_int64_values;
  int64_t *int64_values;
  size_t n_int32_values;
  int32_t *int32_values;
  size_t n_double_values;
  double *double_values;
};
#define MHAPI__QUERY_RESULT__COLUMN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mhapi__query_result__column__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Mhapi__QueryResult__ColumnUnpacked
{
  ProtobufCMessage base;
  size_t n_string_values;
  char **string_values;
  size_t n_int64_values;
  int64_t *int64_values;
  size_t n_int32_values;
  int32_t *int32_values;
  size_t n_double_values;
  double *double_values;
};
#define MHAPI__QUERY_RESULT__COLUMN_UNPACKED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mhapi__query_result__column_unpacked__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Mhapi__QueryResult
{
  ProtobufCMessage base;
  /*
   *	required int32 result_id = 1;
   */
  /*
   *	required int64 col_count = 3;
   */
  int64_t row_count;
  size_t n_columns;
  Mhapi__QueryResult__Column **columns;
  size_t n_columns_unpacked;
  Mhapi__QueryResult__ColumnUnpacked **columns_unpacked;
};
#define MHAPI__QUERY_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mhapi__query_result__descriptor) \
    , 0, 0,NULL, 0,NULL }


/* Mhapi__QueryResult__Column methods */
extern void   mhapi__query_result__column__init
                     (Mhapi__QueryResult__Column         *message);
/* Mhapi__QueryResult__ColumnUnpacked methods */
extern void   mhapi__query_result__column_unpacked__init
                     (Mhapi__QueryResult__ColumnUnpacked         *message);
/* Mhapi__QueryResult methods */
extern void   mhapi__query_result__init
                     (Mhapi__QueryResult         *message);
extern size_t mhapi__query_result__get_packed_size
                     (const Mhapi__QueryResult   *message);
extern size_t mhapi__query_result__pack
                     (const Mhapi__QueryResult   *message,
                      uint8_t             *out);
extern size_t mhapi__query_result__pack_to_buffer
                     (const Mhapi__QueryResult   *message,
                      ProtobufCBuffer     *buffer);
extern Mhapi__QueryResult *
       mhapi__query_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
extern void   mhapi__query_result__free_unpacked
                     (Mhapi__QueryResult *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Mhapi__QueryResult__Column_Closure)
                 (const Mhapi__QueryResult__Column *message,
                  void *closure_data);
typedef void (*Mhapi__QueryResult__ColumnUnpacked_Closure)
                 (const Mhapi__QueryResult__ColumnUnpacked *message,
                  void *closure_data);
typedef void (*Mhapi__QueryResult_Closure)
                 (const Mhapi__QueryResult *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mhapi__query_result__descriptor;
extern const ProtobufCMessageDescriptor mhapi__query_result__column__descriptor;
extern const ProtobufCMessageDescriptor mhapi__query_result__column_unpacked__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_common_2fstream_2fmhapi_2eproto__INCLUDED */
