EXTRA_DIST = \
	conf-medusa conf-apps conf-aix conf-linux \
	config.guess config.sub \
	install-sh mkinstalldirs missing depcomp \
	ltmain.sh ltconfig    \
	stamp-h.in config.h.in

scripts_m4 = {
	DIR = pkgdatadir/conf
	SOURCES = monet.m4 conf.bash conf.csh
}

