#!/usr/bin/env bash

# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

#
# ! this file should be kept identical in                                               !
# ! MonetDB, MonetDB4, MonetDB5, clients, java, template, sql, geom, pathfinder, etc. !
#

if [ ! "`type -p Mbootstrap`" ] ; then
	cat <<- EOF >&2

	Mbootstrap not found.
	You need to install buildtools, first,
	and ensure that <[buildtools_]prefix>/bin is in your PATH.

EOF
	exit 1
fi

exec Mbootstrap
