
MTSAFE
INCLUDES = ../common ../gdk ../monet $(PTHREAD_INCS) 

CXXFLAGS = $(CFLAGS)

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONET_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = \
	../modules/plain/lib_kernel ../modules/plain/lib_arith \
	../modules/plain/lib_bat ../modules/plain/lib_algebra \
	../modules/plain/lib_sys ../modules/plain/lib_trans \
	../modules/plain/lib_str

smallTOC_SHARED_MODS =	\
	../mapi/lib_mapi	\
	../modules/calibrator/lib_calib	\
	../modules/plain/lib_aggr	\
	../modules/plain/lib_aggrX3	\
	../modules/plain/lib_alarm	\
	../modules/plain/lib_bat_arith	\
	../modules/plain/lib_bitset	\
	../modules/plain/lib_bitvector	\
	../modules/plain/lib_blob	\
	../modules/plain/lib_cluster	\
	../modules/plain/lib_ddbench	\
	../modules/plain/lib_decimal	\
	../modules/plain/lib_enum	\
	../modules/plain/lib_io	\
	../modules/plain/lib_lock	\
	../modules/plain/lib_malalgebra	\
	../modules/plain/lib_mmath	\
	../modules/plain/lib_monettime	\
	../modules/plain/lib_mprof	\
	../modules/plain/lib_oo7	\
	../modules/plain/lib_radix	\
	../modules/plain/lib_salgebra	\
	../modules/plain/lib_stats	\
	../modules/plain/lib_tcpip	\
	../modules/plain/lib_tpcd	\
	../modules/plain/lib_uchr	\
	../modules/plain/lib_unix	\
	../modules/plain/lib_url	\
	../modules/plain/lib_wisc	\
	../modules/plain/lib_xtables	\
	../modules/plain/lib_logger	\
	../modules/plain/lib_ascii_io	\
	../modules/plain/lib_streams	\
	\
	../modules/plain/lib_qt

largeTOC_SHARED_MODS =	\
	../modules/plain/lib_vector	\
	../modules/plain/lib_counters	\
	\
	../modules/plain/lib_iterator

CONFLICT_MODS =	\
	../modules/plain/lib_perfex

EXTRA_DIST = static_modules.mx 
#monet-config.mx.in monet-config.bat.in

bin_Mserver = {
	SOURCES = Mserver.mx initmodules.mx 
	LIBS = ../monet/libmonet STATIC_MODS @SHARED_LIBS@ ../gdk/libbat $(MONET_LIBS) ../common/libmutils
}

scripts_mcsh = {
	DIR = bindir
	SOURCES = monet-config.mx.in 
}

scripts_mcbat = {
	DIR = bindir
	SOURCES = monet-config.bat.in 
}

