
MTSAFE
INCLUDES = ../gdk ../monet $(PTHREAD_INCS) 

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONET_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS)
MAPI_LIBS = $(SOCKET_LIBS) $(GDK_LIBS)

STATIC_MODS = \
	../modules/plain/lib_kernel ../modules/plain/lib_arith \
	../modules/plain/lib_bat ../modules/plain/lib_algebra \
	../modules/plain/lib_sys ../modules/plain/lib_trans \
	../modules/plain/lib_str

EXTRA_DIST = static_modules.mx libMapi.def

lib_Mapi = {
	SOURCES = Mapi.mx
	LIBS = $(MAPI_LIBS)
	HEADERS = h
}

bin_Mserver = {
	SOURCES = Mserver.mx initmodules.mx
	LIBS = ../monet/libmonet STATIC_MODS ../gdk/libbat $(MONET_LIBS)
}

bin_Mload = {
	SOURCES = Mload.mx initmodules.mx
	LIBS = ../monet/libmonet STATIC_MODS ../gdk/libbat $(MONET_LIBS)
}

bin_Mdestroydb = bin_Mcreatedb
BINS = {
	SOURCES = Mcreatedb.mx Mdump.mx Mshutdown.mx \
	          Mrecover.mx Mcgi.mx Mclient.mx monet-config.mx.in
	LIBS = libMapi ../gdk/libbat $(MAPI_LIBS)
	Mclient_LIBS = ../gdk/libbat $(MAPI_LIBS) $(READLINE_LIBS) 
}
