MTSAFE
INCLUDES = ../gdk ../monet $(PTHREAD_INCS) ../mal

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONET_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS)

STATIC_MODS = 
#	../modules/plain/lib_kernel ../modules/plain/lib_arith \
#	../modules/plain/lib_bat ../modules/plain/lib_algebra \
#	../modules/plain/lib_sys ../modules/plain/lib_trans \
#	../modules/plain/lib_str

EXTRA_DIST = monet-config.mx.in

bin_Mserver = {
	SOURCES = Mserver.mx 
	LIBS = ../monet/libmonet STATIC_MODS ../gdk/libbat ../mal/libmal $(MONET_LIBS)
}

bin_Mdestroydb = bin_Mcreatedb
BINS = {
	SOURCES = Mcreatedb.mx 
	LIBS = ../gdk/libbat ../mal/libmal $(SOCKET_LIBS) $(GDK_LIBS)
}

bin_SCRIPTS = monet-config
