# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2014 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal \
		   ../atoms \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   $(HWCOUNTERS_INCS)

MTSAFE

lib_kernel = {
	NOINST
	SOURCES = \
		aggr.c \
		alarm.c alarm.h \
		algebra.c algebra.h \
		array.c array.h \
		bat5.c bat5.h \
		batcolor.c batcolor.h \
		batmmath.c batmmath.h \
		batstr.c \
		counters.c counters.h \
		group.c group.h \
		logger.c \
		microbenchmark.c microbenchmark.h \
		mmath.c mmath.h \
		status.c status.h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = bat5.mal algebra.mal status.mal \
		mmath.mal alarm.mal batstr.mal \
		batcolor.mal batmmath.mal \
		group.mal aggr.mal array.mal \
		counters.mal logger.mal microbenchmark.mal
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 00_aggr_hge.mal
}

EXTRA_DIST = alarm.mal counters.mal logger.mal microbenchmark.mal aggr.mal 00_aggr_hge.mal group.mal algebra.mal

EXTRA_DIST_DIR = Tests
