# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal \
		   ../atoms \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   $(HWCOUNTERS_INCS)

MTSAFE

lib_kernel = {
	NOINST
	SOURCES = \
		aggr_be_avg.mx \
		aggr_be_count.mx \
		aggr_be_minmax.mx \
		aggr_be_prod.mx \
		aggr_be_sum.mx \
		aggr_bge_avg.mx \
		aggr_bge_count.mx \
		aggr_bge_minmax.mx \
		aggr_bge_prod.mx \
		aggr_bge_sum.mx \
		aggr.mx \
		alarm.c \
		algebra.mx \
		array.mx \
		bat5.mx \
		batcalc.mx \
		batcast.mx \
		batcolor.mx \
		batifthen.mx \
		batmmath.mx \
		batmtime.mx \
		batstr.mx \
		calc.mx \
		counters.c \
		group.mx \
		lock.c \
		logger.c \
		microbenchmark.c \
		mmath.mx \
		sema.c \
		status.mx \
		unix.c
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = calc.mx bat5.mx algebra.mx status.mx unix.mal \
		mmath.mx lock.mal sema.mal alarm.mal batstr.mx batmtime.mx \
		batcolor.mx batifthen.mx batcast.mx batcalc.mx batmmath.mx \
		group.mx aggr.mx array.mx \
		counters.mal logger.mal microbenchmark.mal
}

EXTRA_DIST = aggr_ri.mx kprelude.mx alarm.mal alarm.h counters.mal counters.h lock.mal lock.h logger.mal microbenchmark.mal microbenchmark.h sema.mal unix.mal

EXTRA_DIST_DIR = Tests
