# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../monet ../../../common/options ../../../common/stream \
	../../../gdk $(HWCOUNTERS_INCS) 
MTSAFE

CFLAGS = $(CFLAGS_NO_OPT)

EXTRA_DIST = calib_analyse.c  calib_main.c  calib_print.c  calib_run.c \
	calib_common.c   calib_plot.c  calib_smp.c

LIBS = {
	DIR = libdir/monetdb4
	SEP = _
	SOURCES = calib.mx 
	#SCRIPTS = mil ""
	LIBS = ../../monet/libmonet ../../../gdk/libbat4 \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(MATH_LIBS)
}

BINS = {
	SOURCES = calibrator.c
	LIBS = $(MATH_LIBS)
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	SOURCES = calib.mx
}
