
INCLUDES = top_builddir/src/gdk top_builddir/src/monet \
	$(Z_CFLAGS) $(BZ_CFLAGS)
MTSAFE

# install these libs in the pkglib
LIBDIR = pkglib

LIBS = {
	SEP = _
#	SOURCES = bat.mx  algebra.mx system.mx startup.mx lock.mx
	SOURCES = startup.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
#scripts_mal = {
        #DIR = pkgdatadir
        #SOURCES = startup.mal
#}


EXTRA_DIST_DIR = Tests
