# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../misc \
		   ../../common/options \
		   ../../common/stream \
		   ../../common/utils \
		   ../../clients/mapilib \
		   ../../gdk \
		   $(READLINE_INCS)
MTSAFE

lib_mal = {
	NOINST
	SOURCES = \
		mal.c mal.h \
		mal_atom.mx \
		mal_authorize.c mal_authorize.h \
		mal_box.mx \
		mal_builder.c mal_builder.h \
		mal_client.mx \
		mal_debugger.mx \
		mal_errors.h \
		mal_exception.c mal_exception.h \
		mal_factory.c mal_factory.h \
		mal_function.c mal_function.h \
		mal_import.mx \
		mal_instruction.mx \
		mal_interpreter.mx \
		mal_linker.c mal_linker.h \
		mal_module.mx \
		mal_namespace.c mal_namespace.h \
		mal_parser.mx \
		mal_profiler.mx \
		mal_properties.c mal_properties.h \
		mal_readline.mx \
		mal_recycle.c mal_recycle.h \
		mal_resolve.mx \
		mal_sabaoth.c mal_sabaoth.h \
		mal_scenario.c mal_scenario.h \
		mal_session.c mal_session.h \
		mal_stack.c mal_stack.h \
		mal_type.c mal_type.h \
		mal_utils.c mal_utils.h \
		mal_xml.c mal_xml.h
}

EXTRA_DIST_DIR = Tests
