# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the Monet Database System.
# 
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.
# 
# Contributor(s):
# 		Martin Kersten <Martin.Kersten@cwi.nl>
# 		Peter Boncz <Peter.Boncz@cwi.nl>
# 		Niels Nes <Niels.Nes@cwi.nl>
# 		Stefan Manegold  <Stefan.Manegold@cwi.nl>

MTSAFE
# INCLUDES = ../../../../common ../../C $(PHP_INCS)

INCLUDES = -I../../C @PHP_INCS@
X_CFLAGS = -DCOMPILE_DL_MONETDB=1 -D_GNU_SOURCE

monetdb_la_LDFLAGS = -module

lib_monetdb = {
	PREFIX =
	NAME = monetdb
	SOURCES = php_monetdb.h php_monetdb.c
	LIBS = ../../C/libMapi $(MAPI_LIBS)
	DIR = @PHP_EXTENSIONDIR@
}

# scripts_php = {
# 	SOURCES = monetdb.php
# }
