all:
	   gcc -fpic -DCOMPILE_DL_MONETDB=1 `php-config --includes` `monet-config --cflags` -g -c -o monetdb.o php_monetdb.c
	   gcc -shared `monet-config --libs` -lMapi -rdynamic -g -o monetdb.so monetdb.o

install:
	cp monetdb.so `php-config --extension-dir`
	@echo "The module has been installed in `php-config --extension-dir`."
