
MTSAFE

INCLUDES = top_builddir/src/gdk top_builddir/src/monet \
	   top_builddir/src/modules/plain

mod_gis = {
	SOURCES = \
		geometry.mx baserelate.mx precision.mx reader.mx direction.mx \
		interval.mx point.mx box.mx segment.mx triangle.mx circle.mx \
		polystruct.mx polyline.mx polygon.mx cpolygon.mx multipoint.mx \
   		distance.mx overlap.mx inside.mx triangulate.mx \
		tri_construct.mx tri_misc.mx tri_monotone.mx tri_tri.mx \
   		varray.mx varlen.mx varheap.mx chull.mx minitree.mx point3d.mx \
		triangle3d.mx box3d.mx Array.mx Pqueue.mx Set.mx gis.mx
	HEADERS = h m
	SCRIPTS = mil
}

mod_opengis = {
	SOURCES = \
		writer.mx opengiswriter.mx Geometry.mx opengisreader.mx \
		MultiLineString.mx MultiPolygon.mx GeometryCollection.mx \
		Polygon.mx PointPoint.mx LineLine.mx PointLine.mx \
		LineStringLineString.mx PointLineString.mx \
		MultiPointMultiPoint.mx PointMultiPoint.mx MultiPointLine.mx \
		LineLineString.mx MultiPointLineString.mx PointPolygon.mx \
		MultiPointPolygon.mx PointMultiLineString.mx minirealm.mx \
		PolygonLineString.mx Reverse.mx opengis.mx
	HEADERS = h m
	SCRIPTS = mil
}

mod_gisbulk = {
	SOURCES = \
		split.mx rtree.mx rtree_box.mx rtree_point.mx \
		rtree_segment.mx rtree_polyline.mx rtree_polygon.mx \
		rtree_djoin.mx rtree_sjoin.mx interval_tree.mx octree.mx \
		gisbulk.mx
	HEADERS = h m
	SCRIPTS = mil
}

MODS = {
	SOURCES = blg.mx opengisbulk.mx gdkmem.mx
	HEADERS = h m
	SCRIPTS = mil
}
