CREATE FUNCTION k3m_build(id INTEGER, ra DOUBLE, decl DOUBLE) RETURNS TABLE(a BOOLEAN) EXTERNAL NAME k3m.build;
CREATE FUNCTION k3m_query(id INTEGER, ra DOUBLE, decl DOUBLE, dc DOUBLE) RETURNS TABLE(idc INTEGER, ids INTEGER, dist DOUBLE) EXTERNAL NAME k3m.query;
CREATE FUNCTION k3m_free() RETURNS TABLE(a BOOLEAN) EXTERNAL NAME k3m.free;
