
INCLUDES = top_builddir/src/gdk top_builddir/src/mal

YFLAGS = -d

MTSAFE

lib_monet = { 
	SOURCES = \
		monet.mx 
	HEADERS = h tab.h
	LIBS = ../gdk/libbat \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)

}

EXTRA_DIST = libmonet.def monet.eps
EXTRA_DIST_DIR = Tests
