
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

CC = $(C99)
INCLUDES = \
	../../runtime \
	../../compiler/include \
	../../../monetdb4/monet \
	../../../monetdb4/modules/plain \
	../../../monetdb4/modules/contrib \
	../../../monetdb4/modules \
	../../../monetdb4/modules/calibrator \
	../../../common/options \
	../../../common/stream \
	../../../gdk \
	$(libxml2_CFLAGS)
PF_LIBS = $(libxml2_LIBS) $(DL_LIBS)

lib__probxml = {
	DIR = libdir/monetdb4
	SOURCES = probxml.mx

	LIBS = \
		../../runtime/lib_pf_support \
		$(PF_LIBS) \
		../../../gdk/libbat4 \
		../../../common/stream/libstream4 \
		../../../monetdb4/monet/libmonet \
		../../../monetdb4/modules/plain/lib_streams \
		../../../monetdb4/modules/plain/lib_builtin \
		../../../monetdb4/modules/plain/lib_ascii_io \
		../../../monetdb4/modules/plain/lib_algebra \
		../../../monetdb4/modules/plain/lib_constant
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	SOURCES = probxml.mx
}

