
INCLUDES = $(MONETDB_INCS) \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		datacell.mx dc_compiler.mx dc_scheduler.mx \
		dc_receptor.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream
}
bin_streamSource = {
	SOURCES = streamSource.mx
	HEADERS = h 
	LIBS = $(MONETDB_LIBS) -lstream  
}
bin_streamSink = {
	SOURCES = streamSink.mx
	HEADERS = h 
	LIBS = $(MONETDB_LIBS) -lstream  
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = datacell.mx dc_compiler.mx dc_scheduler.mx \
		dc_receptor.mx
}

#EXTRA_DIST_DIR = Tests
