
INCLUDES = -I../../modules/atoms -I../../modules/kernel \
        -I../../mal $(MONETDB_INCS) \
        $(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS)

MTSAFE

lib_datacell = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		datacell.mx dc_compiler.mx dc_scheduler.mx \
		dc_receptor.mx dc_emitter.mx

	HEADERS = h 
	#SCRIPTS = mal mil ""
	LIBS = ../../optimizer/lib_optimizer ../../mal/libmal ../../modules/atoms/lib_mtime ../../modules/kernel/lib_bat ../../modules/mal/lib_tablet \
		$(MONETDB_LIBS) -lbat -lstream $(SOCKET_LIBS)
}
bin_dcsource = {
	SOURCES = dcsource.mx
	HEADERS = h 
	LIBS = $(MONETDB_LIBS) -lstream  $(SOCKET_LIBS)
}
bin_dcsink = {
	SOURCES = dcsink.mx
	HEADERS = h 
	LIBS = $(MONETDB_LIBS) -lbat -lstream   $(SOCKET_LIBS)
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = datacell.mx dc_compiler.mx dc_scheduler.mx \
		dc_receptor.mx dc_emitter.mx
}

#EXTRA_DIST_DIR = Tests
