START TRANSACTION;

CREATE SEQUENCE "mytest" AS int;
SELECT * FROM SEQUENCES;

SELECT NEXT VALUE FOR "mytest";
SELECT NEXT VALUE FOR "mytest";
SELECT * FROM SEQUENCES;

ALTER SEQUENCE "mytest" RESTART WITH 10;
SELECT * FROM SEQUENCES;

SELECT NEXT VALUE FOR "mytest";
SELECT NEXT VALUE FOR "mytest";
SELECT * FROM SEQUENCES;

DROP SEQUENCE "mytest";

ROLLBACK;
