#!/bin/bash
# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

# The JdbcClient program searches the latest Java .jar file
# and starts the program.
# Future versions might inspect a database of eligible servers
# to direct the interaction to the proper ports.


DBFARM=$MONET5_PREFIX/var/MonetDB5/dbfarm
DBSHARE=$MONET5_PREFIX/share/MonetDB/lib

# First perform a sanity checks
if [ -z "$MONET5_PREFIX"   ]
then
    echo "The MONET5_PREFIX environment variable has not been set"
    echo "It should point to where you have installed the build directory"
    exit
fi

CLIENT=`ls $DBSHARE/jdbcclient*.jar`
if [ ! -f "$CLIENT" ]
then
	echo "The JDBC client jar file is not accessible in the default location $DBSHARE"
	echo "Check your environment variable settings and installation"
	exit
fi

exec java -jar $CLIENT $*
