#!/bin/bash
# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

# The JdbcClient program searches the latest Java .jar file
# and starts the program.
# Future versions might inspect a database of eligible servers
# to direct the interaction to the proper ports.


# First perform a sanity checks
if [ -z "$MONET5_PREFIX" ];
then
	# Ok, life is not simple.  Let's try do do some voodoo and see if
	# we can figure the prefix out ourself...  First, we assume that the
	# installation we're in is sane; nothing has been moved after the
	# install.  Second, if the first is true, we're in a directory
	# called "bin", which is right after the PREFIX...
	if [ "`dirname $0`" == "." ];
	then
		dir="${PWD}"
	else
		dir="`dirname ${PWD}/$0`"
	fi
	if [ "`basename ${dir}`" == "bin" ];
	then
		# let's see if we have a share/MonetDB/lib...
		if [ -d "${dir}/../share/MonetDB/lib" ];
		then
			MONET5_PREFIX="${dir}/.."
		else 
			echo "The MONET5_PREFIX environment variable has not been set" >&2
			echo "It should point to where you have installed the build directory" >&2
			exit 1
		fi
	fi
fi


DBSHARE="$MONET5_PREFIX/share/MonetDB/lib"

# Find client jar, if more than one, take the most recent one
CLIENT=`ls $DBSHARE/jdbcclient*.jar | sort -r | head -n1`
if [ ! -f "$CLIENT" ]
then
	echo "The JDBC client jar file is not accessible in the default" >&2
	echo "location ($DBSHARE)" >&2
	echo "Check your environment variable settings and installation" >&2
	exit
fi

exec java -jar $CLIENT $*
