
MTSAFE
INCLUDES = ../common ../gdk ../mal $(PTHREAD_INCS) 

CXXFLAGS = $(CFLAGS)

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONET_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 


bin_Mserver = {
	SOURCES = Mserver.mx  
	LIBS = ../mal/libmal ../common/libmutils ../gdk/libbat \
		../sql/parser/libsql \
		$(MONET_LIBS) $(Z_LIBS) $(BZ_LIBS)
}

scripts_mcsh = {
	DIR = bindir
	SOURCES = monet-config.mx.in 
}

scripts_mcbat = {
	DIR = bindir
	SOURCES = monet-config.bat.in 
}

