# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.


MTSAFE
INCLUDES = -I../mal $(CLIENTS_INCS) $(MONETDB_INCS) $(OPENSSL_INCS) $(PCRE_CFLAGS)

bin_mserver5 = {
	SOURCES = mserver5.mx monet_version.h monet_version.c.in
	LIBS = ../mal/libmonetdb5 @SHARED_LIBS@ $(MONETDB_LIBS) \
                -lbat -lmutils -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
                $(PCRE_LIBS) $(OPENSSL_LIBS)
}

bin_stethoscope = {
	SOURCES = stethoscope.mx
	LIBS = @SHARED_LIBS@ -lbat -lmutils -lstream \
			$(MONETDB_LIBS) $(CLIENTS_LIBS) -lMapi \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

lib_embeddedmal = {
	SOURCES = embeddedclient.mx
	LIBS = ../mal/libmonetdb5 @SHARED_LIBS@ $(MONETDB_LIBS) -lbat -lmutils -lstream $(CLIENTS_LIBS) -lMapi \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

bin_Mbeddedmal = {
	SOURCES = prog.c
	LIBS = libembeddedmal ../mal/libmonetdb5 @SHARED_LIBS@ $(MONETDB_LIBS) -lbat -lmutils -lstream $(CLIENTS_LIBS) -lMapi \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}


scripts_sh = {
	COND = NOT_WIN32
	EXT = ""
	DIR = bindir
	SOURCES = mcheckpoint mrecover
}


EXTRA_DIST_DIR = Tests
