#!/bin/bash
# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

#See the MonetDB Version 5 documentation for details

function usage()
{
	echo "Usage: monetdb [command] [options] [script]"
	echo "Primary command:"
	echo "    --status        Show the server status [default]"
	echo "    --start         Server(s) is (are) started"
	echo "    --stop          Server(s) is (are) stopped"
	echo "    --databases     Show the known databases "
	echo "    --log           Show the server management log"
	echo ""
	echo "Secondary options:"
	echo "    --dbname=<database_name>"
	echo "    --dbfarm=<directory>"
	echo "    --dbinit=<stmt>           Server prepare statement"
	echo "    --config=<config_file>    Configuration file"
	echo "    --debug=<number>          Trace server actions[0]"
	echo "    --daemon=yes|no           Run in background [no]"
	echo "    --set <option>=<value>    Set environment value"
	echo "    --help                    This list of options"
}

DBFARM=$MONET5_PREFIX/var/MonetDB5/dbfarm
# First perform some sanity checks
if [ "$MONET5_PREFIX"  = "" ]
then
	echo "The MONET5_PREFIX environment variable has not been set"
	echo "It should point to where you have installed the build directory"
	exit
fi
if [ ! -d $DBFARM ]
then
	echo "Creation of missing database storage area '$DBFARM'"
	mkdir -p $DBFARM
fi
if [ ! -d $DBFARM ]
then
	echo "Database storage area '$DBFARM' is in accessible"
fi

ACTION="--status"

case "$1" in
 "--start" | "--stop" | "--status" ) 
		ACTION=$1;
		shift ;;
 "--databases" )
		ACTION=$1;
		shift ;;
 "--log" )
		cd $DBFARM
		more monetdb.log
		exit ;;
 "--help" )
	usage 
	exit ;;
 * ) 
	;;
esac

# massage the argument list to prepare for calling
ARGS=""
DBNAME=""
STARTUP=""
DELAY=""
while [ $# -gt 0 ]
do
	case "$1" in
	"--dbname="* )
		DBNAME="${1#--dbname=}"
		;;
	"--delay="*)
		DELAY="${1#--delay=}" 
		ARGS="$ARGS $1"
		;;
	"--dbinit="* )
		tail="${1#--dbinit=}"
		STARTUP=/tmp/mserver.startup$$
		echo $tail > $STARTUP
		;;
	* )
		ARGS="$ARGS $1"
		;;
	esac
	shift
done
#echo "ARGS $ARGS"

function getPID ()
{
	active=""
	if [ -f $1/.gdk_lock ]
	then
		pid=`sed -e "s/.*PID=//" -e "s/ .*//" -e 2q $1/.gdk_lock`
		if [ "$pid" != "" ]
		then
			active=`ps --no-heading --format pid -p $pid`
		fi
	fi
	echo $active
}

function getTIME ()
{
	if [ "$DELAY" = "" ]
	then
		echo `sed -e "s/.*TIME=//" -e "s/\@.*//" -e 2q $1/.gdk_lock`
	else
		echo 300
	fi
}

function start_mserver()
{
	# make sure the configuration file is in place
	if [ ! -f $1/.monetdb.conf ]
	then
			cp $MONET5_PREFIX/etc/MonetDB5.conf $1/.monetdb.conf
	fi
	pid=`getPID $1`
	#echo "start server $1 $pid"
	if [ "$pid" = "" ]
	then
		if [ "$STARTUP" != "" ]
		then
			cp "$STARTUP" $1/.mserver.dbinit
		fi
		if [ -f $1/.mserver.dbinit ]
		then
			STARTUP=$DBFARM/$1/.mserver.dbinit
		fi
		if [ "$ARGS" = "" ]
		then
			if [ -f $1/.mserver.args ]
			then
				ARGS=`cat $1/.mserver.args`
			else
				echo > $1/.mserver.args
			fi
		fi

		# use previous arguments if needed
		CONFIG="--config=$DBFARM/$1/.monetdb.conf"
		mserver --set daemon=yes --dbname=$1 $CONFIG $ARGS $STARTUP&
		sleep 1
		pid=`getPID $1`
		if [ "$pid" = "" ]
		then
			echo `date +"%F %T"` " FAILED $1 $ARGS" >>monetdb.log
		else
			echo `date +"%F %T"` " START $1 $ARGS" >>monetdb.log
		fi
		# start the guardian for this server as well
		if [ "$DELAY" != "" ]
		then
			echo $DELAY >$1/.mguardian.delay
		fi
		mguardian --start --dbname=$1
	else
		if [ "$DELAY" != "" ]
		then
			echo $DELAY >$1/.mguardian.delay
			if [ -f $i/.mguardian.sleep ]
			then
				#wakeup the mguardian process
				pid=`cat $i/.mguardian.sleep`
				kill -HUP $pid
			fi
			echo "mguardian delay for '$1' reset"
		else
			echo "mserver for '$1' already running"
		fi
	fi
}
function stop_mserver()
{
	pid=`getPID $1`
	if [ "$pid" != "" ]
	then
		echo "mserver for '$1' stopped"
		stopped=`expr $stopped + 1 `
		# disable the guardian first
		mguardian --stop $1
		kill -TERM $pid
		echo `date +"%F %T"` " STOP  $1" >>monetdb.log
	fi
}

function show_status_hdr()
{
	echo "DBNAME	SERVER	GUARD	DELAY	STARTED"
}
function show_status()
{
	if [ -f $1/.gdk_lock ]
	then
		pid=`getPID $1`
		if  [ "$pid" != "" ]
		then
			if [[ $header = 0 ]]
			then
				show_status_hdr
				header=1
			fi
			if [ -f $1/.mguardian.pid ]
			then
				guard=`cat $1/.mguardian.pid`
			else
				guard=missing
			fi
			if [ -f $1/.mserver.dbinit ]
			then
				dbinit=`cat $1/.mserver.dbinit`
			fi
			if [ -f $1/.mguardian.delay ]
			then
				delay=`cat $1/.mguardian.delay`
			else
				delay=unknown
			fi
			if [ "$delay" = "" ]
			then
				delay=`grep delay $1/.monetdb.conf |sed -e "s/\t.*//" -e "s/delay=//"`
			fi
			start=`getTIME $1`
			echo "$1	$pid	$guard	$delay	$start $dbinit"
		fi
	fi
}

# Initialization of the database directory should
# ideally involve copying a template
# Avoid creating database as a result from typos
function create_database ()
{
		read -p "Do you want to create database '$1' ? [yes/no]" answer
		if [ "$answer" = "yes" ]
		then
			mkdir $1
			cp $MONET5_PREFIX/etc/MonetDB5.conf $1/.monetdb.conf
			echo "Database $1 initialized"
		else
			exit
		fi
		read -p "Should the MAL listener be activated? [yes/no]" answer
		if [ "$answer" = "yes" ]
		then
			echo "mapi.listen();" >$1/.mserver.dbinit
		fi
		read -p "Should the SQL listener be activated ? [yes/no]" answer
		if [ "$answer" = "yes" ]
		then
			echo "include sql; sql.listen();" >>$1/.mserver.dbinit
		fi
}

# switch to dbfarm
cd $DBFARM
DBLIST=`ls`

# check for an overruling database name
tmp=`echo $* | sed -e "s/^.*--dbname=//" -e "s/ .*//"`
if [ "$DBNAME" != "" ]
then
	if [ ! -d $DBNAME ]
	then
		create_database $DBNAME
	fi
	DBLIST=$DBNAME
fi
#echo "DBLIST $DBLIST"

case "$ACTION" in
 "--databases" )
	for i in $DBLIST
	do
		echo $i
	done;;
 "--start" )
	started=0
	for i in $DBLIST
	do
		if [ -d $i ]
		then
			started=`expr $started + 1 `
			start_mserver  $i 
		fi
	done
	if [ $started = 0 ]
	then
		echo "No server started for $DBLIST"
	fi
	;;
 "--stop" )
	stopped=0
	for i in $DBLIST
	do
		if [ -d $i ]
		then
			stop_mserver  $i 
		fi
	done
	if [ $stopped = 0 ]
	then
		echo "No server running for $DBLIST"
	fi
	;;
 "--status" )
	header=0
	for i in $DBLIST
	do
		if [ -d $i ]
		then
			show_status  $i 
		fi
	done
	if [ $header = 0 ]
	then
		echo "No server running for $DBLIST"
	fi
	;;
 * ) ;;
esac

#remove any leftovers
rm -rf /tmp/.mserver.*
