start transaction;
create table pce (i int, s string);
commit;
start transaction;
prepare insert into pce (i,s) values (?,?); 
exec **(1,'test 1');
select * from pce;
commit;
start transaction;
exec **(2,'test 2');
select * from pce;
commit;
drop table pce;
