#!/bin/bash
# use the result of the command
# Mserver --dbinit="manual();"
# trim the header and last prompt to prepare the xml file


xsltproc manual.xsl manual.xml > manual.tex
if [ $? -eq 0 ]; then
	latex manual.tex
	makeindex manual.tex
	latex manual.tex
	rm -f manual.aux manual.log manual.idx
	rm -f manual.toc manual.ilg manual.idn
fi
# dvips manual.dvi -o x.ps
# cat x.ps|psnup -2 >manual.ps
# rm x.ps
