select name from ptables where name='doesnotexist';
select 1 from ptables where name='doesnotexist';
select 1 from ptables;
select 1 from ptables where 0=1;
select 1 from ptables where 1=1;
select 1 where 0=1;
select 1 where 1=1;
select 1, count(*) from ptables;
select name, count(*) from ptables;
rollback;
select 1, count(*) from ptables where 0=1;
select 1, count(*) where 0=1;
rollback;
