select name from _tables where name='doesnotexist';
select 1 from _tables where name='doesnotexist';
select 1 from _tables;
select 1 from _tables where 0=1;
select 1 from _tables where 1=1;
select 1 where 0=1;
select 1 where 1=1;
select 1, count(*) from _tables;
select name, count(*) from _tables;
select 1, count(*) from _tables where 0=1;
select 1, count(*) where 0=1;
