# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

INCLUDES = \
	../../../clients/mapilib \
	../../../common/options \
	../../../common/stream \
	../../modules/atoms \
	../../modules/mal \
	../../../gdk \
	../../mal \
	../../../sql/backends/monet5 \
	../../../sql/common \
	../../../sql/include \
	../../../sql/server \
	../../../sql/storage \
	$(libpy3_CFLAGS)
	

MTSAFE

lib__pyapi3 = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = pyapi.c pyapi.h unicode.c unicode.h pytypes.c pytypes.h type_conversion.c type_conversion.h  formatinput.c formatinput.h connection.c connection.h unspecified_evil.h
	XDEPS = $(libpy3_LIBDEP)
	LIBS = ../../tools/libmonetdb5 \
	       ../../../gdk/libbat \
	$(MALLOC_LIBS) $(libpy3_LIBS)
}

headers_pyapi3_mal = {
	COND = HAVE_LIBPY3
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = pyapi3.mal
}

headers_autoload = {
	COND = HAVE_LIBPY3
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 50_pyapi3.mal
}

EXTRA_DIST_DIR = Tests
