

CREATE TABLE GROUPS1
(EMPNUM INT, GRP INT);
CREATE TABLE NAMES1
(EMPNUM INT, NAME CHAR(5));
CREATE VIEW NAMGRP1 AS
SELECT * FROM NAMES1 NATURAL JOIN GROUPS1;

INSERT INTO GROUPS1 VALUES (0, 10);
INSERT INTO GROUPS1 VALUES (1, 20);
INSERT INTO GROUPS1 VALUES (2, 30);
INSERT INTO NAMES1 VALUES (5, 'HARRY');
INSERT INTO NAMES1 VALUES (1, 'MARY');
INSERT INTO NAMES1 VALUES (0, 'KERI');

select * from NAMGRP1 order by EMPNUM desc;
SELECT EMPNUM
FROM NAMGRP1
WHERE NAME = 'KERI'
AND GRP = 10;

drop view NAMGRP1;
drop table NAMES1;
drop table GROUPS1;
