# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../misc ../mal ../modules/atoms ../modules/mal ../modules/kernel \
	../../clients/mapilib \
	../../common/options \
	../../common/stream \
	../../gdk


MTSAFE

lib_optimizer = {
	NOINST
	SOURCES = \
		optimizer.mx \
		opt_accessmode.mx \
		opt_accumulators.mx \
		opt_aliases.mx \
		opt_cluster.mx \
		opt_coercion.mx \
		opt_commonTerms.mx \
		opt_compression.mx \
		opt_constants.mx \
		opt_costModel.mx \
		opt_crack.mx \
		opt_datacyclotron.mx \
		opt_datacell.mx \
		opt_dataflow.mx \
		opt_deadcode.mx \
		opt_derivepath.mx \
		opt_dictionary.mx \
		opt_emptySet.mx \
		opt_evaluate.mx \
		opt_factorize.mx \
		opt_garbageCollector.mx \
		opt_heuristics.mx \
		opt_history.mx \
		opt_inline.mx \
		opt_joinpath.mx \
		opt_joinselect.mx \
		opt_macro.mx \
		opt_mapreduce.mx \
		opt_mergetable.mx \
		opt_mitosis.mx \
		opt_multiplex.mx \
		opt_octopus.mx \
		opt_partitions.mx \
		opt_peephole.mx \
		opt_pipes.mx \
		opt_prejoin.mx \
		opt_prelude.mx \
		opt_pushranges.mx \
		opt_qep.mx \
		opt_recycler.mx \
		opt_reduce.mx \
		opt_remap.mx \
		opt_remoteQueries.mx \
		opt_reorder.mx \
		opt_selcrack.mx \
		opt_sidcrack.mx \
		opt_singleton.mx \
		opt_statistics.mx \
		opt_strengthReduction.mx \
		opt_support.mx \
		opt_tarantula.mx \
		opt_trace.mx
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_constants.mx opt_commonTerms.mx opt_datacyclotron.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_reorder.mx opt_prejoin.mx opt_compression.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx opt_derivepath.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx \
		opt_statistics.mx opt_trace.mx  opt_recycler.mx opt_dataflow.mx opt_datacell.mx \
		opt_cluster.mx opt_dictionary.mx opt_mapreduce.mx \
		opt_mitosis.mx opt_octopus.mx opt_tarantula.mx  opt_history.mx opt_selcrack.mx opt_sidcrack.mx
}

EXTRA_DIST = optimizerWrapper.mx

EXTRA_DIST_DIR = Tests
