# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../mal ../modules/atoms ../modules/mal ../modules/kernel \
	../../clients/mapilib \
	../../common/options \
	../../common/stream \
	../../common/utils \
	../../gdk


MTSAFE

lib_optimizer = {
	NOINST
	SOURCES = \
		optimizer.c optimizer.h optimizer_private.h \
		opt_aliases.c opt_aliases.h \
		opt_coercion.c opt_coercion.h \
		opt_commonTerms.c opt_commonTerms.h \
		opt_candidates.c opt_candidates.h \
		opt_constants.c opt_constants.h \
		opt_costModel.c opt_costModel.h \
		opt_dataflow.c opt_dataflow.h \
		opt_deadcode.c opt_deadcode.h \
		opt_evaluate.c opt_evaluate.h \
		opt_factorize.c opt_factorize.h \
		opt_garbageCollector.c opt_garbageCollector.h \
		opt_generator.c opt_generator.h \
		opt_querylog.c opt_querylog.h \
		opt_inline.c opt_inline.h \
		opt_joinpath.c opt_joinpath.h \
		opt_macro.c opt_macro.h \
		opt_matpack.c opt_matpack.h \
		opt_json.c opt_json.h \
		opt_mergetable.c opt_mergetable.h \
		opt_mitosis.c opt_mitosis.h \
		opt_multiplex.c opt_multiplex.h \
		opt_pipes.c opt_pipes.h \
		opt_prelude.c opt_prelude.h \
		opt_qep.c opt_qep.h \
		opt_recycler.c opt_recycler.h \
		opt_reduce.c opt_reduce.h \
		opt_remap.c opt_remap.h \
		opt_remoteQueries.c opt_remoteQueries.h \
		opt_reorder.c opt_reorder.h \
		opt_statistics.c opt_statistics.h \
		opt_support.c opt_support.h \
		opt_pushselect.c opt_pushselect.h \
		opt_profiler.c opt_profiler.h \
		opt_wrapper.c
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = optimizer.mal 
}

EXTRA_DIST_DIR = Tests
