# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

monetdb_var_dbfarmdir = $(localstatedir)/monetdb5/dbfarm
monetdb_var_dbfarm_DATA = .merovingian_properties
monetdb_etc_systemddir = $(prefix)/lib/systemd/system
monetdb_etc_systemd_DATA = monetdbd.service
monetdb_etc_logrotatedir = $(sysconfdir)/logrotate.d
monetdb_etc_logrotate_DATA = monetdbd

EXTRA_DIST = .merovingian_properties.in monetdbd.service.in monetdbd.in
