# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

SWIGFLAGS = -I../../mapilib
INCLUDES = -I../../mapilib $(MONETDB_CFLAGS) $(PERL_INCS)

# we need this flag to allow for a name that does not start with "lib"
MapiLib_la_LDFLAGS = -module

# with gcc we could use these
#X_CFLAGS = -Wno-unused-parameter -Wno-unused-function
# but we certainly have to override the default X_CFLAGS:
X_CFLAGS = -D_GNU_SOURCE

lib_MapiLib = {
	PREFIX =
	NAME = MapiLib
	SOURCES = MapiLib.pm.i
	LIBS = ../../mapilib/libMapi $(PERL_LIBS)
	DIR = $(prefix)/$(PERL_LIBDIR)
}

headers_pm = {
	HEADERS = pm
	SOURCES = MapiLib.pm.i
	TARGETS = MapiLib.pm
	DIR = $(prefix)/$(PERL_LIBDIR)
}

EXTRA_DIST = MapiLib.pm
