# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

SWIGFLAGS = -I../..
INCLUDES = -I../.. $(MONETDB_INCS) $(PERL_INCS)

# we need this flag to allow for a name that does not start with "lib"
MapiLib_la_LDFLAGS = -module

#  GNU's gcc does not like to compile swig-generated code
#  (at least not with our strict X_CFLAGS), complaining about
#  "warning: dereferencing type-punned pointer will break strict-aliasing rules",
#  "warning: unused variable '...'",
#  "warning: '...' defined but not used", and/or
#  'error: "..." is not defined'.
#  Hence, we use GCC_SWIG_CFLAGS to disable the respective warning
#  as locally as possbile via "-Wno-strict-aliasing -Wno-unused-variable -Wno-unused-function -Wno-undef".
#  Intel's icc does not like to compile swig-generated code
#  (at least not with our strict X_CFLAGS), complaining about
#  'error #869: parameter "..." was never referenced',
#  'error #177: function "..." was declared but never referenced', and/or
#  'error #310: old-style parameter list (anachronism)'.
#  Hence, we use ICC_SWIG_CFLAGS to disable the respective warning
#  as locally as possbile via "-wd869 -wd177 -wd310".
#  (See also buildtools/conf/MonetDB.m4.)
CFLAGS = $(GCC_SWIG_CFLAGS) $(ICC_SWIG_CFLAGS) -D_GNU_SOURCE

lib_MapiLib = {
	PREFIX =
	NAME = MapiLib
	SOURCES = MapiLib.pm.i
	LIBS = ../../mapilib/libMapi $(PERL_LIBS) $(MATH_LIBS)
	DIR = $(prefix)/$(PERL_LIBDIR)
}

headers_pm = {
	HEADERS = pm
	SOURCES = MapiLib.pm.i
	TARGETS = MapiLib.pm
	DIR = $(prefix)/$(PERL_LIBDIR)
}

EXTRA_DIST = MapiLib.pm
