# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

EXTRA_DIST = \
	abssyn.h \
	abssynprint.h \
	alg_cl_mnemonic.h \
	alg_dag.h \
	algebra_cse.h \
	opt_algebra_cse.h \
	algebra.h \
	algebra_mnemonic.h \
	algopt.h \
	array.h \
	bitset.h \
	builtins.h \
	child_mnemonic.h \
	compile.h \
	compile_interface.h \
	core2alg.h \
	core.h \
	core_mnemonic.h \
	coreopt.h \
	coreprint.h \
	env.h \
	fs.h \
	func_chk.h \
	functions.h \
	heuristic.h \
	import.h \
	intro_borders.h \
	la_proxy.h \
	la_thetajoin.h \
	logdebug.h \
	logical.h \
	logical_mnemonic.h \
	map_names.h \
	mem.h \
	mil_dce.h \
	milgen.h \
	mil.h \
	mil_mnemonic.h \
	mil_opt.h \
	milprint.h \
	milprint_summer.h \
	msa.h \
	msa_mnemonic.h \
	msaprint.h \
	normalize.h \
	ns.h \
	nsres.h \
	oops.h \
	options.h \
	ordering.h \
	parser.h \
	pathfinder.h \
	pfstrings.h \
	pf_ferry.h \
	pf_xq.h \
	physdebug.h \
	physical.h \
	physical_mnemonic.h \
	planner.h \
	plan_bundle.h \
	prettyp.h \
	properties.h \
	qname.h \
	scanner.h \
	scope.h \
	simplify.h \
	string_utils.h \
	subtyping.h \
	timer.h \
	typecheck.h \
	types.h \
	variable.h \
	varscope.h \
	xml2lalg.h \
	xml2lalg_converters.h \
	xml2lalg_xpath_utils.h \
	xquery_fo.h \
	sql.h \
	sql_opt.h \
	sql_mnemonic.h \
	lalg2sql.h \
	lalg2msa.h \
	sqlprint.h \
	load_stats.h
   
headers_pf_ferry = {
	HEADERS = h
	DIR = includedir
	SOURCES = pf_ferry.h
}

