# Copyright Notice:
# -----------------
# 
# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the ``Pathfinder'' system. The Initial
# Developer of the Original Code is the Database & Information
# Systems Group at the University of Konstanz, Germany. Portions
# created by U Konstanz are Copyright (C) 2000-2004 University
# of Konstanz. All Rights Reserved.
#
# Contributors:
#         Niels Nes <Niels.Nes@cwi.nl>
#

EXTRA_DIST = \
	abssyn.h         env.h        milprint.h   pathfinder.h  twig.h \
	abssynprint.h    fs.h         milty.h      pfstrings.h   typecheck.h \
	array.h          func_chk.h   miltype.h    prettyp.h     types.h \
	                 functions.h  normalize.h  qname.h       variable.h \
	core.h           import.h     ns.h         scope.h       varscope.h \
	core_mnemonic.h  mem.h        nsres.h      simplify.h    xquery_fo.h \
	coreprint.h      core2alg.h   oops.h       subtyping.h   algebra.h \
	                 mil.h        parser.h     timer.h       builtins.h \
	mil_mnemonic.h   milgen.h     algopt.h     algebra_cse.h coreopt.h \
	algebra_mnemonic.h milprint_summer.h hsk_parser.h
