INCLUDES = ../mal ../optimizer $(MONETDB_INCS)

#YFLAGS = -v -p mil -d

lib_xqry = {
	DIR = pkglibdir
	SEP = _
	NAME = xqry
	SOURCES = xqry_parser.mx xqry_scenario.mx xqry_gencode.mx xqry.mx \
		  xqry_keyword.mx xqry_mem.mx xqry_scanner.mx xqry_backend.mx

	HEADERS = h
	#SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../mal/libmal ../optimizer/lib_optimizer
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = xqry.mx 
}
