# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../../mal ../atoms ../kernel ../mosaic \
	../../../clients/mapilib \
   ../../../monetdb5/optimizer \
	../../../common/options \
	../../../common/stream \
	../../../common/utils \
	../../../gdk \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS) \
	$(openssl_CFLAGS)

MTSAFE

lib_mosaic = {
	NOINST
	SOURCES = \
		mosaic.c mosaic.h \
		mosaic_hdr.c mosaic_hdr.h \
		mosaic_literal.c mosaic_literal.h \
		mosaic_runlength.c mosaic_runlength.h \
		mosaic_dictionary.c mosaic_dictionary.h \
		mosaic_delta.c mosaic_delta.h \
		mosaic_linear.c mosaic_linear.h \
		mosaic_frame.c mosaic_frame.h \
		mosaic_calendar.c mosaic_calendar.h \
		mosaic_prefix.c mosaic_prefix.h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = mosaic.mal 
}

EXTRA_DIST_DIR = Tests
