# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../../mal ../atoms ../kernel ../mosaic \
	../../../clients/mapilib \
   ../../../monetdb5/optimizer \
	../../../common/options \
	../../../common/stream \
	../../../common/utils \
	../../../gdk \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS) \
	$(openssl_CFLAGS)

MTSAFE

lib_mosaic = {
	NOINST
	SOURCES = \
		mosaic.c mosaic.h mosaic_template.h \
		mosaic_utility.h \
		mosaic_hdr.c mosaic_hdr.h \
		mosaic_select_template.h \
		mosaic_projection_template.h \
		mosaic_join.h mosaic_join_templates.h \
		mosaic_raw.c mosaic_raw.h mosaic_raw_templates.h \
		mosaic_runlength.c mosaic_runlength.h mosaic_runlength_templates.h \
		mosaic_dict.c mosaic_dict.h \
		mosaic_dict256.c mosaic_dict256.h \
		mosaic_dictionary.h mosaic_dictionary_templates.h \
		mosaic_delta.c mosaic_delta.h mosaic_delta_templates.h \
		mosaic_linear.c mosaic_linear.h mosaic_linear_templates.h \
		mosaic_frame.c mosaic_frame.h mosaic_frame_templates.h \
		mosaic_prefix.c mosaic_prefix.h mosaic_prefix_templates.h \
		mosaic_private.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = mosaic.mal
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = mosaic_hge.mal
}

EXTRA_DIST_DIR = Tests
