
MTSAFE
INCLUDES =  -I../../common -I../../gdk -I../../mal \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS)


MAPI_LIBS = $(SOCKET_LIBS) $(PTHREAD_LIBS) $(MALLOC_LIBS)

lib_Mapi = {
	DIR = pkglibdir
	SOURCES = Mapi.mx 
	LIBS = $(MAPI_LIBS)
	HEADERS = h
}

BINS = {
#	SOURCES = Mshutdown.mx MapiClient.mx
	SOURCES = Mclient.mx
	LIBS = libMapi ../../gdk/libbat $(MAPI_LIBS) $(Z_LIBS) \
		$(BZ_LIBS)  $(READLINE_LIBS)
	Mclient_LIBS = libMapi ../../gdk/libbat $(MAPI_LIBS) \
		$(READLINE_LIBS) $(Z_LIBS) $(BZ_LIBS)

}
