connect to 'localhost' port port_num database 'mTests_sql_src_test_Connections_test1' as 'test_db' user 'monetdb' password 'monetdb' language 'sql';
select server, db, db_alias, language from connections;
disconnect 'test_db';
select server, db, db_alias, language from connections;
connect to 'localhost' port port_num database 'mTests_sql_src_test_Connections_test1' as 'test_db' user 'monetdb' password 'monetdb' language 'sql';
connect to 'localhost' port port_num5 database 'mTests_sql_src_test_Connections_test1' as 'test_db' user 'monetdb' password 'monetdb' language 'sql';
connect to 'localhost' port port_num database 'mTests_sql_src_test_Connections_test1' as 'test' user 'monetdb' password 'monetdb' language 'sql';
connect to 'localhost' port 4000 database 'dmo' as 'test_db' user 'monetdb' password 'monetdb' language 'sql';
select server, db, db_alias, language from connections;
disconnect 'test_db';
disconnect 'test_db';
connect to 'localhost' port port_num database 'mTests_sql_src_test_Connections_test1' as 'test_db' user 'monetdb' password 'monetdb' language 'sql';
select server, db, db_alias, language from connections;
disconnect ALL;
select server, db, db_alias, language from connections;
disconnect 'test_tb';
