#!/bin/sh

# if we have an older automake, patch our files a bit
case `automake --version | egrep "[0-9]\.[0-9](\.[0-9])?.*"` in
	*1.[56]*)
	mv configure.ac configure.ac.orig_bootstrap
	cp configure.ac.orig_bootstrap configure.ac
	patch << EOF
Index: configure.ac
===================================================================
RCS file: /cvsroot/monetdb/buildtools/burg/configure.ac,v
retrieving revision 1.2
diff -u -r1.2 configure.ac
--- configure.ac	13 Aug 2005 15:46:26 -0000	1.2
+++ configure.ac	27 Oct 2005 16:16:14 -0000
@@ -3,13 +3,12 @@

 AC_PREREQ(2.57)
 AC_INIT([burg], [1.0], [monet@cwi.nl])
-AM_INIT_AUTOMAKE
+AM_INIT_AUTOMAKE([burg], [1.0])
 AC_CONFIG_SRCDIR([burs.c])
-AC_CONFIG_HEADER([burg_config.h])
+AM_CONFIG_HEADER([burg_config.h])

 # Checks for programs.
 AC_PROG_CC
-AC_PROG_LEX
 AM_PROG_LEX()
 AC_PROG_YACC()

EOF
	;;
esac

aclocal || exit 1
autoheader || exit 1
autoconf || exit 1
automake --add-missing -c -f || exit 1

if [ -f configure.ac.orig_bootstrap ];
then
	mv configure.ac.orig_bootstrap configure.ac
fi

