# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

INCLUDES = -I../../atoms -I../../kernel \
        -I../../../mal $(CLIENTS_INCS) $(MONETDB_INCS) \
        $(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS) $(READLINE_INCS)

MTSAFE

lib_crackers = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = crackers.mx \
		crackers_AVL_index.mx crackers_AVL_tree.mx crackers_index.mx \
		crackers_core_ordered.mx crackers_core_unordered.mx crackers_validation.mx \
		crackers_joinselect_ops.mx crackers_select_ops.mx crackers_sideways.mx crackers_updates.mx
	LIBS = ../../../mal/libmal ../../kernel/lib_bat5 $(MONETDB_LIBS) -lbat -lstream ../../atoms/lib_mtime \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

headers_crackers = {
	DIR = includedir/MonetDB5/crackers
	SOURCES = crackers.mx \
		crackers_AVL_index.mx crackers_AVL_tree.mx crackers_index.mx \
		crackers_core_ordered.mx crackers_core_unordered.mx crackers_validation.mx \
		crackers_joinselect_ops.mx crackers_select_ops.mx crackers_sideways.mx crackers_updates.mx
	HEADERS = h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = crackers.mx
}

#EXTRA_DIST_DIR = Tests
