# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

SUBDIRS = buildtools common clients gdk \
	HAVE_MONETDB5?monetdb5 \
	HAVE_SQL?sql \
	HAVE_GEOM?geom \
	tools \
	HAVE_JAVA?java \
	HAVE_TESTING?testing \

EXTRA_DIST = bootstrap configure configure.ac configure.ag libversions \
			 MonetDB.spec rpm.mk.in COPYING README license.txt HowToStart.rst

EXTRA_DIST_DIR = NT debian template
