-- `<  ',  ` <  = ',  `>  ',  `>=   ', and`<>
SELECT INTERVAL '0-0' YEAR TO MONTH = INTERVAL  +'0-0' YEAR TO MONTH;
SELECT INTERVAL '0-0' YEAR TO MONTH = INTERVAL  -'0-0' YEAR TO MONTH;
SELECT INTERVAL '3-4' YEAR TO MONTH = INTERVAL  +'3-4' YEAR TO MONTH;
SELECT INTERVAL '3-4' YEAR TO MONTH = INTERVAL  '+3-4' YEAR TO MONTH;
SELECT INTERVAL '3-4' YEAR TO MONTH = INTERVAL +'+3-4' YEAR TO MONTH;
SELECT INTERVAL '3-4' YEAR TO MONTH = INTERVAL -'-3-4' YEAR TO MONTH;
SELECT INTERVAL '3-4' YEAR TO MONTH = INTERVAL   '3-4' YEAR TO MONTH;

SELECT INTERVAL '3-7' YEAR TO MONTH = INTERVAL '43' MONTH;
SELECT INTERVAL '3-7' YEAR TO MONTH = INTERVAL '23' DAY;  -- err: incomparable

SELECT INTERVAL '3' DAY + INTERVAL '4' DAY = INTERVAL '7' DAY;
SELECT INTERVAL '3' DAY + INTERVAL '4' HOUR = INTERVAL '3 4' DAY TO HOUR;
SELECT INTERVAL '3' DAY + INTERVAL '8 4' DAY TO HOUR = INTERVAL '11 4' DAY TO HOUR;
SELECT INTERVAL '3' DAY - INTERVAL '4' DAY = INTERVAL -'1' DAY;
SELECT INTERVAL '3' DAY - INTERVAL -'8 4' DAY TO HOUR = INTERVAL '11 4' DAY TO HOUR;
-- SELECT ( DATE '1997-01-01' - DATE '1996-01-01') DAY = INTERVAL '366' DAY; -- fixme
-- SELECT ( DATE '1997-01-01' - DATE '1996-01-01') YEAR TO MONTH = INTERVAL '1-0' YEAR TO MONTH; -- fixme
SELECT INTERVAL '4' DAY * 3 = INTERVAL '12' DAY;
SELECT 3 * INTERVAL '4' DAY = INTERVAL '12' DAY;
SELECT INTERVAL '12:30' HOUR TO MINUTE * 3 = INTERVAL '37:30' HOUR TO MINUTE;
SELECT INTERVAL '4' DAY / 2 = INTERVAL '2' DAY;
-- SELECT 2 / INTERVAL '4' DAY; -- err: not permitted
SELECT - INTERVAL '4' DAY = INTERVAL -'4' DAY;
SELECT + INTERVAL '4' DAY = INTERVAL '4' DAY;
