import os, sys


def main():
    clcmd = str(os.getenv('SQL_CLIENT'))
    clcmd1 = str(os.getenv('SQL_CLIENT')) + "-uskyserver -Pskyserver"
    sys.stdout.write('Create User\n')
    clt = os.popen(clcmd + "<%s" % ('%s/../create_user.sql' % os.getenv('RELSRCDIR')), 'w')
    clt.close()
    sys.stdout.write('tables\n')
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../../../sql/math.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../../../sql/cache.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../../../sql/ms_functions.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_tables.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_constraints.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    sys.stdout.write('views\n')
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_views.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    sys.stdout.write('functions\n')
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_functions.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    sys.stdout.write('Cleanup\n')
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropFunctions.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropMs_functions.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropMath.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropCache.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropViews.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropConstraints.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    clt1 = os.popen(clcmd1 + "<%s" % ('%s/../Skyserver_dropTables.sql' % os.getenv('RELSRCDIR')), 'w')
    clt1.close()
    sys.stdout.write('Remove User\n')
    clt = os.popen(clcmd + "<%s" % ('%s/../drop_user.sql' % os.getenv('RELSRCDIR')), 'w')
    clt.close()

main()
