#
# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the ``Pathfinder'' system. The Initial
# Developer of the Original Code is the Database & Information
# Systems Group at the University of Konstanz, Germany. Portions
# created by U Konstanz are Copyright (C) 2000-2005 University
# of Konstanz. All Rights Reserved.
#
# Contributors:
#         Torsten Grust <torsten.grust@uni-konstanz.de>
#         Maurice van Keulen <M.van.Keulen@bigfoot.com>
#         Jens Teubner <jens.teubner@uni-konstanz.de>
#

SUBDIRS = schema debug mem parser semantics core algebra mil include

INCLUDES = include $(MONETDB_INCS) $(LIBGC_CFLAGS)

LDFLAGS = $(LIBGC_LIBS) $(SOCKET_LIBS) $(LIBXML2_LIBS)

lib_compiler1 = {
	NOINST
	DIR = libdir
	SOURCES = \
	     compile.c
}
lib_compiler2 = {
	NOINST
	DIR = libdir
	SOURCES = \
	     env.c \
	     oops.c \
	     pfstrings.c \
	     qname.c \
	     scope.c \
	     timer.c \
	     variable.c
}
bin_pf = {
	LIBS = \
		libcompiler1 \
		schema/libschema \
		debug/libdebug \
		mem/libmem \
		parser/libparser \
		semantics/libsemantics \
		core/libcore \
		algebra/libalgebra \
		mil/libmil \
                algebra/hskparser/libhskparser \
		libcompiler2 \
		$(LIBGC_LDADD) $(LIBXML2_LDADD)
		
	SOURCES = \
	     main.c
}
