# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

MTSAFE
INCLUDES = $(MONETDB4_INCS) $(CLIENTS_INCS) $(MONETDB_INCS)

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
EXTRA_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = $(MONETDB4_MODS) \
	-l_builtin -l_arith -l_bat -l_algebra -l_sys -l_trans -l_str -l_constant

smallTOC_SHARED_MODS =	\
	-l_mapi	\
	\
	-l_aggr	\
	-l_aggrX3	\
	-l_alarm	\
	-l_ascii_io	\
	-l_bat_arith	\
	-l_blob	\
	-l_enum	\
	-l_lock	\
	-l_logger	\
	-l_mkey	\
	-l_mmath	\
	-l_monettime	\
	-l_pcre	\
	-l_pqueue	\
	-l_streams	\
	-l_unix	\
	-l_url	\
	-l_xtables	\
	\
	-l_malalgebra	\
	-l_txtsim	\
	\
	../../runtime/lib_pf_support \
	../../runtime/lib_pathfinder \
	../../runtime/lib_pf_standoff \
	../../runtime/lib_xrpc_client	\
	../../runtime/lib_xrpc_server	\
	@HAVE_PFTIJAH_TRUE@ ../../modules/pftijah/lib_pftijah

EXTRA_DIST = static_modules.mx

lib_initmodules = {
	NOINST
	SOURCES = initmodules.mx
}

bin_Mserver = {
	COND = LINK_STATIC
	SOURCES = Mserver.mx
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet
}

lib_embeddedxq = {
	SOURCES = embeddedclient.mx
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(CLIENTS_LIBS) -lMapi
}

bin_Mbeddedxq = {
	SOURCES = prog.c
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		libembeddedxq \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(CLIENTS_LIBS) -lMapi
}

EXTRA_DIST_DIR = Tests
