# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

MTSAFE
INCLUDES = \
	../../../MonetDB4/src/monet \
	../../../MonetDB4/src/modules/plain \
	../../../MonetDB4/src/modules/contrib \
	../../../MonetDB4/src \
	../../../MonetDB4/src/modules/calibrator \
	../../../clients/src/mapilib \
	../../../common/options \
	../../../common/stream \
	../../../gdk

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
EXTRA_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = \
	../../../MonetDB4/src/modules/plain/lib_builtin \
	../../../MonetDB4/src/modules/plain/lib_arith \
	../../../MonetDB4/src/modules/plain/lib_bat \
	../../../MonetDB4/src/modules/plain/lib_algebra \
	../../../MonetDB4/src/modules/plain/lib_sys \
	../../../MonetDB4/src/modules/plain/lib_trans \
	../../../MonetDB4/src/modules/plain/lib_str \
	../../../MonetDB4/src/modules/plain/lib_constant

smallTOC_SHARED_MODS =	\
	../../../MonetDB4/src/mapi/lib_mapi	\
	\
	../../../MonetDB4/src/modules/plain/lib_aggr	\
	../../../MonetDB4/src/modules/plain/lib_aggrX3	\
	../../../MonetDB4/src/modules/plain/lib_alarm	\
	../../../MonetDB4/src/modules/plain/lib_ascii_io	\
	../../../MonetDB4/src/modules/plain/lib_bat_arith	\
	../../../MonetDB4/src/modules/plain/lib_blob	\
	../../../MonetDB4/src/modules/plain/lib_enum	\
	../../../MonetDB4/src/modules/plain/lib_lock	\
	../../../MonetDB4/src/modules/plain/lib_logger	\
	../../../MonetDB4/src/modules/plain/lib_mkey	\
	../../../MonetDB4/src/modules/plain/lib_mmath	\
	../../../MonetDB4/src/modules/plain/lib_monettime	\
	../../../MonetDB4/src/modules/plain/lib_pcre	\
	../../../MonetDB4/src/modules/plain/lib_pqueue	\
	../../../MonetDB4/src/modules/plain/lib_streams	\
	../../../MonetDB4/src/modules/plain/lib_unix	\
	../../../MonetDB4/src/modules/plain/lib_url	\
	../../../MonetDB4/src/modules/plain/lib_xtables	\
	\
	../../../MonetDB4/src/modules/plain/lib_malalgebra	\
	../../../MonetDB4/src/modules/plain/lib_txtsim	\
	\
	../../runtime/lib_pf_support \
	../../runtime/lib_pathfinder \
	../../runtime/lib_pf_standoff \
	../../runtime/lib_xrpc_client	\
	../../runtime/lib_xrpc_server	\
	@HAVE_PFTIJAH_TRUE@ ../../modules/pftijah/lib_pftijah

EXTRA_DIST = static_modules.mx

lib_initmodules = {
	NOINST
	SOURCES = initmodules.mx
}

bin_Mserver = {
	COND = LINK_STATIC
	SOURCES = Mserver.mx
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		../../../gdk/libbat \
		../../../common/options/libmoptions \
		../../../common/stream/libstream \
		../../../MonetDB4/src/monet/libmonet
}

lib_embeddedxq = {
	SOURCES = embeddedclient.c.in
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		../../../gdk/libbat \
		../../../common/options/libmoptions \
		../../../common/stream/libstream \
		../../../MonetDB4/src/monet/libmonet \
		../../../clients/src/mapilib/libmapi
}

bin_Mbeddedxq = {
	SOURCES = prog.c
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		libembeddedxq \
		../../../gdk/libbat \
		../../../common/options/libmoptions \
		../../../common/stream/libstream \
		../../../MonetDB4/src/monet/libmonet \
		../../../clients/src/mapilib/libmapi
}

EXTRA_DIST = embeddedclient.h static_modules.mx
EXTRA_DIST_DIR = Tests
