## Process this file with automake to produce Makefile.in

INCLUDES = $(MONET_INCS) ../include

lib_debug = {
	NOINST
	DIR = libdir
	SOURCES = \
		abssynprint.c \
		coreprint.c \
		mildebug.c \
		prettyp.c 
}

