
INCLUDES = \
	../include \
	../../client \
	$(MONET_INCS)

DEFS = @DEFS@
ODBCLIBS = odbc32.lib odbccp32.lib version.lib shlwapi.lib user32.lib

lib_MonetODBCs = {
	SOURCES = setup.c setup.rc
	LIBS = $(ODBCLIBS)
}

bin_install = {
	SOURCES = install.c
	LIBS = $(ODBCLIBS)
}
