#!/bin/bash

pf -s2 <<'EOT'
declare xmlspace preserve;
declare xmlspace strip;
declare namespace foo = "http://www.foo.bar";
declare namespace bar = "http://www.bar.foo";
declare variable $a := 42;
42
EOT
echo $?
