#!/usr/bin/env sh

# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

# bootstrap sub-targets
( cd Mx && ./bootstrap ) || exit 1
( cd mel && ./bootstrap ) || exit 1
( cd burg && ./bootstrap ) || exit 1

# bootstrap ourself
aclocal -I .
if [ "`type -t glibtoolize`" = "file" ] ; then
	glibtoolize --copy --force --automake
else
	libtoolize --copy --force --automake
fi
aclocal -I .
autoconf
autoheader
automake --add-missing --copy --foreign
