# Meta-Makefile.msc for buildtools

all:
	cd autogen && python setup.py install
	cd Mx && $(MAKE) /nologo /f Makefile.msc
	cd mel && $(MAKE) /nologo /f Makefile.msc

clean:
	cd autogen && del /q build
	cd Mx && $(MAKE) /nologo /f Makefile.msc clean
	cd mel && $(MAKE) /nologo /f Makefile.msc clean
