# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

MTSAFE
INCLUDES = -I$(MONETDB_INCLUDEDIR)/C $(MONETDB_INCS) $(PTHREAD_INCS)

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONETDB_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = -L$(MONETDB_PREFIX)/lib/MonetDB \
	-l_builtin -l_arith -l_bat -l_algebra -l_sys -l_trans -l_str

smallTOC_SHARED_MODS =	\
	-l_mapi	\
	\
	-l_aggr	\
	-l_aggrX3	\
	-l_alarm	\
	-l_ascii_io	\
	-l_bat_arith	\
	-l_blob	\
	-l_enum	\
	-l_mkey	\
	-l_mmath	\
	-l_monettime	\
	-l_pcre	\
	-l_pqueue	\
	-l_streams	\
	-l_unix	\
	-l_xtables	\
	\
	-l_txtsim	\
	\
	../backends/$(SQL_BACKEND)/lib_sql_server

EXTRA_DIST = static_modules.mx mysqldump2bulkload.py

lib_initmodules = {
	NOINST
	SOURCES = initmodules.mx
}

bin_Mserver = {
	COND = LINK_STATIC
	SOURCES = Mserver.mx
	LIBS = -L$(MONETDB_PREFIX)/lib -linitmodules -lmonet STATIC_MODS @SHARED_LIBS@ -lbat $(MONETDB_LIBS) -lmutils -lstream
}

lib_embeddedsql = {
	SOURCES = embeddedclient.mx
}

bin_Mbeddedsql = {
	SOURCES = prog.c
	LIBS = -L$(MONETDB_PREFIX)/lib -lembeddedsql -linitmodules -lMapi -lmonet STATIC_MODS @SHARED_LIBS@ -lbat $(MONETDB_LIBS) -lmutils -lstream
}
