# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

MTSAFE

SWIGFLAGS = $(MONETDB_INCS) $(MONETDBCLIENTS_INCS)
INCLUDES = $(MONETDB_INCS) $(MONETDBCLIENTS_INCS) $(MONETDB4_INCS) $(PYTHON_INCS)

# with gcc we could use these
#X_CFLAGS = -Wno-unused-parameter -Wno-unused-function
# but we certainly have to override the default X_CFLAGS:
X_CFLAGS =

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
EXTRA_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = $(MONETDB4_MODS) \
	-l_builtin -l_arith -l_bat -l_algebra -l_sys -l_trans -l_str -l_constant

smallTOC_SHARED_MODS =	\
	-l_mapi	\
	\
	-l_aggr	\
	-l_aggrX3	\
	-l_alarm	\
	-l_ascii_io	\
	-l_bat_arith	\
	-l_blob	\
	-l_enum	\
	-l_mkey	\
	-l_mmath	\
	-l_monettime	\
	-l_pcre	\
	-l_pqueue	\
	-l_streams	\
	-l_logger	\
	-l_unix	\
	-l_xtables	\
	\
	-l_txtsim	\
	\
	../backends/$(SQL_BACKEND)/lib_sql_server

EXTRA_DIST = static_modules.mx mysqldump2bulkload.py

lib_initmodules = {
	NOINST
	SOURCES = initmodules.mx
}

bin_Mserver = {
	COND = LINK_STATIC
	SOURCES = Mserver.mx
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet
}

lib_embeddedsql = {
	SOURCES = embeddedclient.mx
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(MONETDBCLIENTS_LIBS) -lMapi
}

bin_Mbeddedsql = {
	SOURCES = prog.c
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		libembeddedsql \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(MONETDBCLIENTS_LIBS) -lMapi
}

bin_embeddedExample = {
	SOURCES = embeddedExample.c
	DIR = pkglibdir/Tests
	LIBS = libinitmodules STATIC_MODS @SHARED_LIBS@ $(EXTRA_LIBS) \
		libembeddedsql \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(MONETDBCLIENTS_LIBS) -lMapi
}

scripts_h = {
	EXT = h
	DIR = includedir
	SOURCES = embeddedclient.mx
}

lib_monetdb = {
	COND = HAVE_PYTHON_SWIG
	PREFIX =
	NAME = _monetdb
	SOURCES = monetdb.py.i
	LIBS = libembeddedsql $(PYTHON_LIBS) $(MONETDB_LIBS) -lmutils -lstream $(MONETDBCLIENTS_LIBS) -lMapi
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}

scripts_py = {
	COND = HAVE_PYTHON_SWIG
        EXT = py
        SOURCES = monetdb.py.i
        TARGETS = monetdb.py
        DIR = $(prefix)/$(PYTHON_LIBDIR)
}
