
MTSAFE
INCLUDES = -I$(MONET_PREFIX)/include -I$(MONET_PREFIX)/include/gdk -I$(MONET_PREFIX)/include/monet $(PTHREAD_INCS) 

CXXFLAGS = $(CFLAGS)

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
MONET_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS)

STATIC_MODS = -L$(MONET_PREFIX)/lib/Monet \
	-l_kernel -l_arith \
	-l_bat -l_algebra \
	-l_sys -l_trans \
	-l_str

smallTOC_SHARED_MODS =	\
	-l_mapi	\
	-l_aggr	\
	-l_aggrX3	\
	-l_alarm	\
	-l_bat_arith	\
	-l_blob	\
	-l_ddbench	\
	-l_enum	\
	-l_io	\
	-l_monettime	\
	-l_unix	\
	-l_xtables	\
	-l_ascii_io	\
	-l_streams	\
	-l_uchr	\
	\
	../server/lib_sqlserver

nonSQL_MODS = \
	-l_bitset	\
	-l_bitvector	\
	-l_cluster	\
	-l_decimal	\
	-l_lock	\
	-l_malalgebra	\
	-l_mmath	\
	-l_mprof	\
	-l_oo7	\
	-l_radix	\
	-l_salgebra	\
	-l_stats	\
	-l_tcpip	\
	-l_tpcd	\
	-l_url	\
	-l_wisc	\
	-l_logger	\
	-l_qt

largeTOC_SHARED_MODS =	\
	-l_vector	\
	-l_counters	\
	-l_iterator

CONFLICT_MODS =	\
	-l_perfex

EXTRA_DIST = static_modules.mx

bin_Mserver = {
	SOURCES = Mserver.mx initmodules.mx 
	LIBS = -L$(MONET_PREFIX)/lib -lmonet STATIC_MODS @SHARED_LIBS@ -lbat $(MONET_LIBS)
}

