SELECT * FROM (
	SELECT 'a' AS TABLE_CAT
	UNION ALL
	SELECT 'a' AS TABLE_CAT
	UNION ALL
	SELECT 'a' AS TABLE_CAT
	UNION ALL
	SELECT 'a' AS TABLE_CAT
	UNION ALL
	SELECT 'a' AS TABLE_CAT
) AS tables WHERE 1=1;
