
INCLUDES = -I../../common -I../../gdk \
	../../../include/atoms \
	-I../../mal $(HWCOUNTERS_INCS) $(PCL_FLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = calc.mx bat.mx algebra.mx system.mx unix.mx \
		mapi.mx kernel_init.mx mmath.mx lock.mx alarm.mx \
		batcalc.mx group.mx mkey.mx aggrX3.mx pcl.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = ../common/libmutils ../common/libstream ../../gdk/libbat \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
	LDFLAGS = -lm
}
scripts_mal = {
	DIR = pkglibdir/kernel
	SOURCES = calc.mx bat.mx algebra.mx system.mx unix.mx \
		mapi.mx kernel_init.mx mmath.mx lock.mx alarm.mx \
		batcalc.mx group.mx mkey.mx aggrX3.mx pcl.mx
}


EXTRA_DIST_DIR = Tests
