# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

INCLUDES = \
	-I../atoms -I../../mal \
	$(MONETDB_INCS)  \
	$(HWCOUNTERS_INCS) $(PCL_FLAGS) $(ICONV_CFLAGS)

MTSAFE

LIBS = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = \
		calc.mx bat5.mx algebra.mx status.mx unix.mx \
		mmath.mx lock.mx sema.mx alarm.mx  batifthen.mx \
		batcast.mx batcalc.mx batmath.mx aggr.mx counters.mx \
		pqueue.mx mkey.mx microbenchmark.mx 

	#SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream $(MATH_LIBS) \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}

lib__batstr = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = batstr.mx 
	#SCRIPTS = mil ""
	LIBS = ../atoms/lib_str $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}
lib__batmtime = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = batmtime.mx
	#SCRIPTS = mil ""
	LIBS = ../atoms/lib_str ../atoms/lib_mtime ../../mal/libmal $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

lib__batcolor = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = batcolor.mx
	#SCRIPTS = mil ""
	LIBS = ../atoms/lib_color $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}

lib__group = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = group.mx
	#SCRIPTS = mil ""
	LIBS = ./lib_algebra $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}

lib__array = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = array.mx
	#SCRIPTS = mil ""
	LIBS = ./lib_algebra $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}

lib__logger = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = logger.mx
	#SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
		../../mal/libmal ./lib_bat5
		
}

headers_h = {
	DIR = includedir/MonetDB5/kernel
	SOURCES = \
		calc.mx bat5.mx algebra.mx status.mx unix.mx \
		mmath.mx lock.mx sema.mx alarm.mx  batifthen.mx \
		batcast.mx batcalc.mx batmath.mx aggr.mx counters.mx \
		pqueue.mx mkey.mx microbenchmark.mx \
		batstr.mx batmtime.mx batcolor.mx group.mx array.mx logger.mx
	HEADERS = h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = calc.mx bat5.mx algebra.mx status.mx unix.mx \
		mmath.mx lock.mx sema.mx alarm.mx batstr.mx batmtime.mx \
		batcolor.mx batifthen.mx batcast.mx batcalc.mx batmath.mx \
		group.mx aggr.mx array.mx \
		counters.mx logger.mx pqueue.mx mkey.mx microbenchmark.mx
}

EXTRA_DIST_DIR = Tests
