INCLUDES = $(MONETDB_INCS)

MTSAFE

lib_mal = {
	NAME = mal
	SOURCES = \
	mal.mx mal_utils.mx mal_type.mx mal_instruction.mx mal_box.mx mal_scope.mx \
	mal_stack.mx mal_import.mx mal_session.mx mal_interpreter.mx \
	mal_exception.mx mal_resolve.mx mal_function.mx mal_xml.mx \
	mal_parser.mx mal_linker.mx mal_debugger.mx mal_atom.mx  \
	mal_client.mx mal_profiler.mx mal_scenario.mx mal_factory.mx \
	mal_namespace.mx mal_properties.mx mal_optimizer.mx scenario_init.mx \
	mal_syntax.mx mal_macro.mx mal_compiler.mx mal_costmodel.mx \
	mal_builder.mx

	HEADERS = h 
	SCRIPTS = mal
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
#doc_ml = {
#	DIR = pkgdatadir/docs/mal
#	SOURCES = \
#	mal.mx mal_utils.mx mal_type.mx mal_instruction.mx mal_box.mx mal_scope.mx \
#	mal_stack.mx mal_import.mx mal_session.mx mal_interpreter.mx \
#	mal_exception.mx mal_resolve.mx mal_function.mx mal_xml.mx \
#	mal_parser.mx mal_linker.mx mal_debugger.mx mal_atom.mx  \
#	mal_client.mx mal_profiler.mx mal_scenario.mx mal_factory.mx \
#	mal_namespace.mx mal_properties.mx mal_optimizer.mx scenario_init.mx \
#	mal_syntax.mx mal_macro.mx mal_compiler.mx mal_costmodel.mx \
# 	mal_builder.mx
#}
scripts_mal = {
	DIR = pkglibdir
	SOURCES = mal_scenario.mal
}
