# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

#INCLUDES = -I../optimizer -I../scheduler -I../modules/kernel \

INCLUDES = $(MONETDB_INCS) $(READLINE_INCS) $(OPENSSL_INCS)
MTSAFE

lib_mal = {
	NOINST
	SOURCES = \
		mal.mx \
		mal_atom.mx \
		mal_authorize.mx \
		mal_box.mx \
		mal_builder.mx \
		mal_client.mx \
		mal_debugger.mx \
		mal_errors.mx \
		mal_exception.mx \
		mal_factory.mx \
		mal_function.mx \
		mal_import.mx \
		mal_instruction.mx \
		mal_interpreter.mx \
		mal_linker.mx \
		mal_module.mx \
		mal_namespace.mx \
		mal_parser.mx \
		mal_profiler.mx \
		mal_properties.mx \
		mal_readline.mx \
		mal_recycle.mx \
		mal_resolve.mx \
		mal_sabaoth.mx \
		mal_scenario.mx \
		mal_session.mx \
		mal_stack.mx \
		mal_type.mx \
		mal_utils.mx \
		mal_xml.mx
}

headers_mal = {
	DIR = includedir/MonetDB5/mal
	SOURCES = \
		mal.mx \
		mal_atom.mx \
		mal_authorize.mx \
		mal_box.mx \
		mal_builder.mx \
		mal_client.mx \
		mal_debugger.mx \
		mal_errors.mx \
		mal_exception.mx \
		mal_factory.mx \
		mal_function.mx \
		mal_import.mx \
		mal_instruction.mx \
		mal_interpreter.mx \
		mal_linker.mx \
		mal_module.mx \
		mal_namespace.mx \
		mal_parser.mx \
		mal_profiler.mx \
		mal_properties.mx \
		mal_readline.mx \
		mal_recycle.mx \
		mal_resolve.mx \
		mal_sabaoth.mx \
		mal_scenario.mx \
		mal_session.mx \
		mal_stack.mx \
		mal_type.mx \
		mal_utils.mx \
		mal_xml.mx

	HEADERS = h 
}

EXTRA_DIST_DIR = Tests
