title: "[GENERAL] "
body:
  - type: textarea
    id: question
    attributes:
      label: What is the topic ?
      description: Straight to the point. Be succinct.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots here.
  - type: markdown
    attributes:
      value: "Identity Disclosure"
  - type: input
    attributes:
      label: "Full Name:"
      placeholder: e.g., Jane Doe
    validations:
      required: true
  - type: input
    attributes:
      label: "Affiliation:"
      placeholder: e.g., FooBar Corp
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If we find the above answers questionable and it is not obvious from your GitHub profile page,
        we reserve the right to close your discussion without further review. Please refer to the
        [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.
