
CFLAGS = -DUNIX -DMX_CXX_SUFFIX=\"cc\"

EXTRA_DIST = warning.gif epstogif

bin_Mx = {
	SOURCES = \
		Mx.c Index.c Def.c Form.c Tok.c Code.c Display.c Print.c Io.c \
		Sys.c disclaimer.c  Tex2Html.c Mx.h MxFcnDef.h  
}


#bin_prefixMxFile = {
#	SOURCES = prefixMxFile.c disclaimer.c disclaimer.h
#}
#
#BINS = {
#	SOURCES = idxmx.c epsffit.c 
#}

EXTRA_DIST = prefixMxFile.c disclaimer.c disclaimer.h idxmx.c epsffit.c 
