# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.

# With the IBM compiler (xlc) and optimization enabled, 
# Mx behaves "strangely" on sara's solo:
# /tmp/StM/_BUILD_MONET_ntv_64_d_--enable-optimize_/src/utils/Mx/Mx -n -x c /san/stst/nielsnes/StM/MonetDB/src/common/stream.mxMx:Unresolved reference::stream_readVal[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:1980].
# Mx:Unresolved reference::stream_readVal[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:1988].
# Mx:Unresolved reference::stream_readVal[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:1996].
# Mx:Unresolved reference::stream_readArray[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:2022].
# Mx:Unresolved reference::stream_readArray[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:2030].
# Mx:Unresolved reference::stream_readArray[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:2038].
# Mx:Unresolved reference::stream_printf_va_vsnprintf[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:2059].
# Mx:Unresolved reference::stream_printf_va_vsnprintf[/san/stst/nielsnes/StM/MonetDB/src/common/stream.mx:2073].
# /san/stst/nielsnes/StM/MonetDB/src/common/stream.mx: ./stream.c - created
# Hence, we "mis-use" the NO_INLINE_CFLAGS (cf. conf/monet.m4) to disable
# optimization in this case (and maybe disable inlining in same other cases,
# but that does not matter for Mx).

CFLAGS = -DUNIX -DMX_CXX_SUFFIX=$(CXXEXT) $(NO_INLINE_CFLAGS)

bin_Mx = {
	SOURCES = \
		Mx.c Index.c Def.c Form.c Tok.c Code.c Display.c Print.c Io.c \
		Sys.c disclaimer.c  Tex2Html.c Mx.h MxFcnDef.h  
}


bin_prefixMxFile = {
	SOURCES = prefixMxFile.c disclaimer.c disclaimer.h
}

BINS = {
	SOURCES = idxmx.c epsffit.c 
}

EXTRA_DIST = warning.gif epstogif.in getopt.c mygetopt.h
