# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = \
	../../../common/options \
	../../../common/stream \
	../../../gdk \
	../../mal \
	../../modules/kernel \
	../../modules/atoms \
	../../modules/mal \	
	../../../sql/common \
	../../../sql/include \
	../../../sql/server \
	../../../sql/storage \
	../../../sql/backends/monet5 \
	$(libr_CFLAGS)

MTSAFE

# R include files contain redundant declarations
rapi_CFLAGS = -Wno-redundant-decls

lib__rapi = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = rapi.c rapi.h converters.c.h
	XDEPS = $(libr_LIBDEP)
	LIBS = NATIVE_WIN32?../../tools/libmonetdb5 \
	       NATIVE_WIN32?../../../gdk/libbat \
	       $(MALLOC_LIBS) $(libr_LIBS)
}

headers_rapi_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = rapi.mal
}

headers_rapi_R = {
	HEADERS = R
	DIR = libdir/monetdb5
	SOURCES = rapi.R
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 50_rapi.mal
}

EXTRA_DIST_DIR = Tests
