# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2013 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal ../atoms ../kernel \
	../../../clients/mapilib \
	../../../common/options \
	../../../common/stream \
	../../../common/utils \
	../../../gdk \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS)

MTSAFE

lib_mal = {
	NOINST
	SOURCES = \
		batExtensions.c batExtensions.h \
		bbp.c bbp.h \
		box.c box.h \
		clients.c clients.h \
		cluster.c cluster.h \
		const.c  const.h \
		constraints.c constraints.h \
		factories.c factories.h \
		groupby.c groupby.h \
		groups.c groups.h \
		inspect.c inspect.h \
		iterator.c  iterator.h \
		joinpath.c  joinpath.h \
		language.c language.h \
		mal_io.c mal_io.h \
		mal_mapi.c mal_mapi.h \
		manual.c manual.h \
		mat.c mat.h \
		mdb.c mdb.h \
		mkey.c mkey.h \
		pcre.c \
		pqueue.c pqueue.h \
		profiler.c profiler.h \
		querylog.c querylog.h \
		recycle.c recycle.h \
		remote.c remote.h \
		sabaoth.c sabaoth.h \
		sysmon.c sysmon.h \
		tablet.c tablet.h \
		tokenizer.c tokenizer.h \
		trader.c trader.h \
		transaction.c \
		txtsim.c txtsim.h \
		urlbox.c urlbox.h \
		zorder.c zorder.h \
		sample.c sample.h \
		json_util.c json_util.h \
		calc.c batcalc.c
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = language.mal constraints.mal mal_init.mal box.mal bbp.mal \
		profiler.mal const.mal batExtensions.mal \
		inspect.mal manual.mal mal_io.mal pqueue.mal mkey.mal \
		iterator.mal clients.mal \
		factories.mal groupby.mal mdb.mal pcre.mal mat.mal \
		urlbox.mal transaction.mal \
		mal_mapi.mal sabaoth.mal remote.mal  \
		txtsim.mal recycle.mal \
		cluster.mal trader.mal \
		tokenizer.mal zorder.mal sample.mal json_util.mal \
		calc.mal batcalc.mal batmtime.mal querylog.mal sysmon.mal
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 00_calc_hge.mal 00_batcalc_hge.mal \
		00_cluster_hge.mal 00_iterator_hge.mal 00_language_hge.mal \
		00_mal_mapi_hge.mal 00_mkey_hge.mal 00_pqueue_hge.mal
}

EXTRA_DIST = batExtensions.mal iterator.mal constraints.mal \
	groupby.mal mal_init.mal manual.mal mkey.mal pcre.mal \
	profiler.mal recycle.mal remote.mal sabaoth.mal trader.mal \
	transaction.mal txtsim.mal tablet.mal tablet.h sample.mal json_util.mal \
	mal_mapi.mal mat.mal tokenizer.mal pqueue.mal calc.mal \
	batcalc.mal batmtime.mal querylog.mal sysmon.mal \
	00_calc_hge.mal 00_batcalc_hge.mal \
	00_cluster_hge.mal 00_iterator_hge.mal 00_language_hge.mal \
	00_mal_mapi_hge.mal 00_mkey_hge.mal 00_pqueue_hge.mal

EXTRA_DIST_DIR = Tests
