# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../misc ../../mal ../atoms ../kernel \
	../../../clients/mapilib \
	../../../common/options \
	../../../common/stream \
	../../../common/utils \
	../../../gdk \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS)

MTSAFE

lib_mal = {
	NOINST
	SOURCES = \
		algebraExtensions.mx \
		attach.mx \
		batExtensions.mx \
		bbp.mx \
		box.mx \
		bpm.mx \
		chopper.mx \
		clients.mx \
		cluster.mx \
		const.mx \
		constraints.mx \
		factories.mx \
		groupby.mx \
		histogram.mx \
		inspect.mx \
		language.mx \
		mal_io.mx \
		mal_mapi.mx \
		manual.mx \
		mat.mx \
		mdb.mx \
		mkey.mx \
		pcre.mx \
		pma.mx \
		pqueue.mx \
		profiler.mx \
		recycle.mx \
		remote.mx \
		sabaoth.mx \
		statistics.mx \
		tablet.mx \
		tablet_sql.mx \
		tokenizer.mx \
		trader.mx \
		transaction.mx \
		txtsim.mx \
		urlbox.mx \
		zorder.mx
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = language.mx constraints.mx mal_init.mx box.mx bbp.mx \
		profiler.mx const.mx attach.mx batExtensions.mx algebraExtensions.mx \
		inspect.mx manual.mx mal_io.mx pqueue.mx mkey.mx \
		chopper.mx clients.mx \
		factories.mx groupby.mx mdb.mx pcre.mx  tablet.mx mat.mx histogram.mx \
		urlbox.mx statistics.mx transaction.mx \
		mal_mapi.mx sabaoth.mx remote.mx  \
		bpm.mx txtsim.mx recycle.mx \
		cluster.mx trader.mx pma.mx \
		tokenizer.mx zorder.mx
}

EXTRA_DIST = prelude.mx

EXTRA_DIST_DIR = Tests
