# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2012 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal ../atoms ../kernel \
	../../../clients/mapilib \
	../../../common/options \
	../../../common/stream \
	../../../common/utils \
	../../../gdk \
	$(pcre_CFLAGS) $(zlib_CFLAGS) $(BZIP_INCS) $(MSGCONTROL_FLAGS)

MTSAFE

lib_mal = {
	NOINST
	SOURCES = \
		algebraExtensions.c algebraExtensions.h \
		attach.c attach.h \
		batExtensions.c \
		bbp.c bbp.h \
		box.c box.h \
		chopper.c \
		clients.c clients.h \
		cluster.mx \
		const.c  const.h \
		constraints.c constraints.h \
		factories.c factories.h \
		groupby.c groupby.h \
		histogram.h \
		inspect.c inspect.h \
		language.mx \
		mal_io.c mal_io.h \
		mal_mapi.c mal_mapi.h \
		manual.c manual.h \
		mat.mx \
		mdb.c mdb.h \
		mkey.c mkey.h \
		pcre.c \
		pqueue.mx \
		profiler.c profiler.h \
		recycle.c recycle.h \
		remote.c remote.h \
		sabaoth.c sabaoth.h \
		tablet.c tablet.h \
		tablet_sql.c \
		tokenizer.mx \
		trader.c trader.h \
		transaction.c \
		txtsim.c txtsim.h \
		urlbox.c urlbox.h \
		zorder.c zorder.h \
		sample.c sample.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = language.mx constraints.mal mal_init.mal box.mal bbp.mal \
		profiler.mal const.mal attach.mal batExtensions.mal algebraExtensions.mal \
		inspect.mal manual.mal mal_io.mal pqueue.mx mkey.mal \
		chopper.mal clients.mal \
		factories.mal groupby.mal mdb.mal pcre.mal tablet.mal mat.mx \
		urlbox.mal transaction.mal \
		mal_mapi.mal sabaoth.mal remote.mal  \
		txtsim.mal recycle.mal \
		cluster.mx trader.mal \
		tokenizer.mx zorder.mal sample.mal
}

EXTRA_DIST = prelude.mx algebraExtensions.mal attach.mal batExtensions.mal chopper.mal constraints.mal groupby.mal histogram.mal mal_init.mal manual.mal mkey.mal pcre.mal profiler.mal recycle.mal remote.mal sabaoth.mal trader.mal transaction.mal txtsim.mal tablet.mal tablet.h sample.mal mal_mapi.mal

EXTRA_DIST_DIR = Tests
