START TRANSACTION;

CREATE TABLE IF NOT EXISTS json_data (id INT, jdata JSON);

COPY 4 RECORDS INTO json_data FROM STDIN DELIMITERS E',',E'\n';
1,"\\""
2,"\\\\"
3,NULL
4,"\\n"

COPY 4 RECORDS INTO json_data FROM STDIN DELIMITERS E',',E'\n' NO ESCAPE;
5,"\""
6,"\\"
7,NULL
8,"\n"

SELECT * FROM json_data;
ROLLBACK;

START TRANSACTION;
CREATE TABLE IF NOT EXISTS str_data (id INT, bdata TEXT);

COPY 5 RECORDS INTO str_data FROM STDIN DELIMITERS E',',E'\n';
1,
2,NULL
3,A12B
4,\\
5,a\nb

COPY 5 RECORDS INTO str_data FROM STDIN DELIMITERS E',',E'\n' NO ESCAPE;
6,
7,NULL
8,A12B
9,\\
10,a\nb

SELECT * FROM str_data;
ROLLBACK;
