# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

MTSAFE

SUBDIRS = MonetDB-CLI-MapiPP MonetDB-CLI DBD Tests

headers_perl = {
	HEADERS = pm
	DIR = $(prefix)/$(PERL_LIBDIR)
	SOURCES = Mapi.pm 
}
