DROP TABLE t;
CREATE TABLE t (i INT, j INT);
INSERT INTO t VALUES (10, 20);

START TRANSACTION;
SAVEPOINT sp;
UPDATE t SET i = 42 WHERE j = 20;
RELEASE SAVEPOINT sp;
COMMIT;

SELECT * FROM t;
DROP TABLE t;

