# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2014 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../common/options ../common/stream ../common/utils $(valgrind_CFLAGS)

lib_gdk = {
	VERSION = $(GDK_VERSION)
	NAME = bat
	SOURCES = \
		gdk.h gdk_atomic.h gdk_batop.c \
		gdk_select.c gdk_select_legacy.c \
		gdk_search.c gdk_search.h gdk_tm.c \
		gdk_align.c gdk_bbp.c gdk_bbp.h \
		gdk_heap.c gdk_setop.c gdk_utils.c gdk_utils.h \
		gdk_atoms.c gdk_atoms.h \
		gdk_qsort.c gdk_qsort_impl.h gdk_ssort.c gdk_ssort_impl.h \
		gdk_storage.c gdk_bat.c \
		gdk_delta.c gdk_cross.c gdk_system.c gdk_value.c \
		gdk_posix.c gdk_logger.c gdk_sample.c \
		gdk_private.h gdk_delta.h gdk_logger.h gdk_posix.h \
		gdk_system.h gdk_tm.h gdk_storage.h \
		gdk_calc.c gdk_calc.h gdk_calc_compare.h gdk_calc_private.h \
		gdk_aggr.c gdk_group.c gdk_mapreduce.c gdk_mapreduce.h \
		gdk_imprints.c gdk_imprints.h \
		gdk_join.c gdk_join_legacy.c \
		bat.feps bat1.feps bat2.feps \
		libbat.rc
	LIBS = ../common/options/libmoptions \
		../common/stream/libstream \
		../common/utils/libmutils \
		$(MATH_LIBS) $(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(PSAPILIB) $(KVM_LIBS)
}

headers_h = {
	DIR = includedir/monetdb
	HEADERS = h
	SOURCES = \
		gdk.h \
		gdk_atomic.h \
		gdk_atoms.h \
		gdk_bbp.h \
		gdk_calc.h \
		gdk_delta.h \
		gdk_posix.h \
		gdk_search.h \
		gdk_system.h \
		gdk_utils.h
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb-gdk.pc.in
}
