# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2020 MonetDB B.V.

MTSAFE

INCLUDES = ../common/options ../common/stream ../common/utils $(valgrind_CFLAGS)

lib_gdk = {
	VERSION = $(GDK_VERSION)
	NAME = bat
	SOURCES = \
		gdk_calc.c gdk_calc.h gdk_calc_compare.h gdk_calc_private.h \
		gdk_select.c \
		gdk_analytic_bounds.c gdk_analytic.h \
		gdk_qsort.c gdk_qsort_impl.h \
		gdk_ssort.c gdk_ssort_impl.h \
		gdk_aggr.c \
		gdk_analytic_func.c \
		gdk_bbp.c gdk_bbp.h \
		gdk_group.c \
		gdk_join.c \
		gdk_firstn.c \
		gdk_logger.c gdk_logger.h \
		gdk_batop.c \
		gdk_bat.c \
		gdk_hash.c gdk_hash.h \
		gdk_utils.c gdk_utils.h \
		gdk_imprints.c gdk_imprints.h \
		gdk_atoms.c gdk_atoms.h \
		gdk_project.c \
		gdk_string.c \
		gdk_orderidx.c \
		gdk_search.c \
		gdk_heap.c \
		gdk_storage.c gdk_storage.h \
		gdk_time.c gdk_time.h \
		gdk_cand.c gdk_cand.h \
		gdk_unique.c \
		gdk_posix.c gdk_posix.h \
		gdk_system.c gdk_system.h gdk_system_private.h \
		gdk_tracer.c gdk_tracer.h \
		gdk_align.c \
		gdk_interprocess.c gdk_interprocess.h \
		gdk_sample.c \
		gdk_tm.c gdk_tm.h \
		gdk_value.c \
		gdk_delta.c gdk_delta.h \
		gdk_cross.c \
		gdk.h gdk_private.h \
		xoshiro256starstar.h \
		libbat.rc
	LIBS = ../common/options/libmoptions \
		../common/utils/libmutils \
		WIN32?../common/stream/libstream \
		WIN32?$(MATH_LIBS) \
		WIN32?$(SOCKET_LIBS) \
		WIN32?$(MALLOC_LIBS) \
		WIN32?$(PTHREAD_LIBS) \
		WIN32?$(DL_LIBS) \
		WIN32?$(PSAPILIB) \
		WIN32?$(KVM_LIBS)
}

headers_h = {
	DIR = includedir/monetdb
	HEADERS = h
	SOURCES = \
		gdk.h \
		gdk_analytic.h \
		gdk_atoms.h \
		gdk_bbp.h \
		gdk_calc.h \
		gdk_cand.h \
		gdk_delta.h \
		gdk_posix.h \
		gdk_hash.h \
		gdk_system.h \
		gdk_tracer.h \
		gdk_utils.h
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb-gdk.pc.in
}
