# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../common/options ../common/stream ../common/utils $(valgrind_CFLAGS)

gdk_scanselect_CFLAGS = $(NO_INLINE_CFLAGS)
# gdk_relop.mx

EXTRA_DIST = gdk_scanselect_defs.mx gdk_private.h

lib_gdk = { 
	VERSION = $(GDK_VERSION)
	NAME = bat
	SOURCES = \
		gdk_scanselect_defs_chr.mx \
		gdk_scanselect_defs_bte.mx \
		gdk_scanselect_defs_sht.mx \
		gdk_scanselect_defs_int.mx \
		gdk_scanselect_defs_flt.mx \
		gdk_scanselect_defs_dbl.mx \
		gdk_scanselect_defs_lng.mx \
		gdk_scanselect_defs_str.mx \
		gdk_scanselect_defs_fix.mx \
		gdk_scanselect_defs_var.mx \
		gdk_scanselect.mx gdk.mx gdk_batop.mx \
		gdk_search.mx gdk_tm.mx gdk_align.mx gdk_bbp.mx \
		gdk_heap.mx gdk_setop.mx gdk_utils.mx gdk_atoms.mx \
		gdk_qsort.mx gdk_ssort.mx gdk_storage.mx gdk_bat.mx \
		gdk_delta.mx gdk_relop.mx gdk_system.mx gdk_value.mx \
		gdk_rangejoin.mx \
		gdk_posix.mx gdk_logger.mx bat.feps bat1.feps bat2.feps \
		libbat.rc
	LIBS = ../common/options/libmoptions \
		../common/stream/libstream \
		../common/utils/libmutils \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
