
INCLUDES = \
        -I$(srcdir)/../include -I. \
	-I$(top_srcdir)/include \
	-I$(top_srcdir)/src/parser \
	-I$(MONETDIST)/include/plain \
	-I$(MONETDIST)/include/stream \
	-I$(top_builddir)/ \
	$(ODBC_INCS)

DEFS = -DUNIXODBC @DEFS@

EXTRA_DIST = \
	driver.h \
	driverextras.h 

lib_MonetODBC = {
	SOURCES = \
	SQLAllocConnect.c \
	SQLAllocEnv.c \
	SQLAllocHandle.c \
	SQLAllocStmt.c \
	SQLBindCol.c \
	SQLBindParameter.c \
	SQLBrowseConnect.c \
	SQLBulkOperations.c \
	SQLCancel.c \
	SQLCloseCursor.c \
	SQLColAttribute.c \
	SQLColAttributes.c \
	SQLColumnPrivileges.c \
	SQLColumns.c \
	SQLConnect.c \
	SQLCopyDesc.c \
	SQLDescribeCol.c \
	SQLDescribeParam.c \
	SQLDisconnect.c \
	SQLDriverConnect.c \
	SQLEndTran.c \
	SQLError.c \
	SQLExecDirect.c \
	SQLExecute.c \
	SQLExtendedFetch.c \
	SQLFetch.c \
	SQLFetchScroll.c \
	SQLForeignKeys.c \
	SQLFreeConnect.c \
	SQLFreeEnv.c \
	SQLFreeHandle.c \
	SQLFreeStmt.c \
	SQLGetConnectAttr.c \
	SQLGetConnectOption.c \
	SQLGetCursorName.c \
	SQLGetData.c \
	SQLGetDescField.c \
	SQLGetDescRec.c \
	SQLGetDiagField.c \
	SQLGetDiagRec.c \
	SQLGetEnvAttr.c \
	SQLGetInfo.c \
	SQLGetStmtAttr.c \
	SQLGetStmtOption.c \
	SQLGetTypeInfo.c \
	SQLMoreResults.c \
	SQLNativeSql.c \
	SQLNumParams.c \
	SQLNumResultCols.c \
	SQLParamData.c \
	SQLParamOptions.c \
	SQLPrepare.c \
	SQLPrimaryKeys.c \
	SQLProcedureColumns.c \
	SQLProcedures.c \
	SQLPutData.c \
	SQLRowCount.c \
	SQLSetConnectOption.c \
	SQLSetCursorName.c \
	SQLSetDescField.c \
	SQLSetDescRec.c \
	SQLSetEnvAttr.c \
	SQLSetParam.c \
	SQLSetPos.c \
	SQLSetScrollOptions.c \
	SQLSetStmtAttr.c \
	SQLSetStmtOption.c \
	SQLSpecialColumns.c \
	SQLStatistics.c \
	SQLTablePrivileges.c \
	SQLTables.c \
	SQLTransact.c \
	_FreeDbc.c \
	_FreeStmt.c \
	_FreeDbcList.c \
	_FreeStmtList.c \
	_FreeResults.c \
	_GetData.c \
	_NativeToSQLColumnHeader.c \
	_NativeToSQLType.c \
	_NativeTypeDesc.c \
	_NativeTypeLength.c \
	_NativeTypePrecision.c \
	catalog-client.c \
	statement_dump.c \
	comm.c comm.h \
	gdk.c 
	LIBS = \
	${top_builddir}/src/parser/libsql.la \
	-L$(MONETDIST)/lib/Monet -lstream  -lm
}
