\input texinfo
@c %**start of header
@setfilename MonetDB
@c %**end of header

@c environment
@set VERSION 4.4
@set UPDATED 21/11/2004

@copying
     This file documents the MonetDB Version @value{VERSION} 
    Kernel Implementation Notes
     
Last updated: @value{UPDATED}

     Copyright (C) 2000-2004 CWI
     
     Permission is granted to make and distribute verbatim
     copies of this manual provided the copyright notice and
     this permission notice are preserved on all copies.
     
@end copying

@titlepage
@title MonetDB Kernel Implementation Notes
@subtitle Version @value{VERSION}
@author @emph{The MonetDB Development Team}
@page
@vskip 0pt plus 1fill
@c the following start the copy right page
@insertcopying
@end titlepage

@contents

@ifnottex
@page
@node Top, About this manual, (dir), (dir)
@top MonetDB

@include Assets/General_information
@menu
* About this manual::
* Introduction V5::
@end menu
@end ifnottex

@node Introduction V5, ,About this manual, Top
@include Assets/About_this_manual

@include gdk.bdy.texi
@include gdk_align.bdy.texi
@include gdk_atoms.bdy.texi
@include gdk_bat.bdy.texi
@include gdk_batop.bdy.texi
@include gdk_bbp.bdy.texi
@include gdk_delta.bdy.texi
@include gdk_desc.bdy.texi
@include gdk_heap.bdy.texi
@include gdk_posix.bdy.texi
@include gdk_relop.bdy.texi
@include gdk_scanselect.bdy.texi
@include gdk_setop.bdy.texi
@include gdk_qsort.bdy.texi
@include gdk_search.bdy.texi
@include gdk_storage.bdy.texi
@include gdk_system.bdy.texi
@include gdk_tm.bdy.texi
@include gdk_utils.bdy.texi
@include gdk_value.bdy.texi


@bye
