\input texinfo
@c %**start of header
@setfilename MonetDB
@c %**end of header

@c environment
@set VERSION 5.0
@set UPDATED Sept 9, 2005

@copying
     This file documents the MonetDB Version @value{VERSION} Reference Manual
     
Last updated: @value{UPDATED}

     Copyright (C) 2000-2005 CWI
     
     Permission is granted to make and distribute verbatim
     copies of this manual provided the copyright notice and
     this permission notice are preserved on all copies.
     
@end copying

@titlepage
@title MonetDB Reference Manual
@subtitle Version @value{VERSION}
@author @emph{The MonetDB Development Team}
@page
@vskip 0pt plus 1fill
@c the following start the copy right page
@insertcopying
@end titlepage

@iftex
@contents
@end iftex

@ifnottex

@page
@node Top, TOC,  , 
@top MonetDB Reference Manual
@include Assets/General-information.texi

@node TOC, About this manual, Top,(Dir)
Table of contents
@menu
* TOC::
* About this manual::
@menu
* Intended audience::
* Features and Limitations::
@menu
* When to consider MonetDB::
* When not to consider MonetDB::
@end menu
* The History of MonetDB::
* Manual Generation::
* Conventions and notation::
@end menu

* Download and Installation::
@menu
* Binary Distributions::
* Source Distributions::
@end menu

* MonetDB overview ::
@menu
* Architecture overview:: 
* Design considerations:: 
* MAL synopsis:: 
* Backward compatibility:: 
* Scenario management::
@menu
* Client administration::
* Session scenarios::
* MAL execution:: 
@end menu
@end menu

* SQL ::
@menu
* Getting Started with SQL::
* The VOC Tutorial::
* SQL Feature Overview::
@menu
* SQL Feature List::
* SET Statement::
* EXPLAIN Statement::
* DEBUG Statement::
@end menu
* Optimizer Control::
* SQL Implementation Roadmap::
@end menu

* XQuery ::

* MapiClient and Interfaces::
* MonetDB Assembler Language::
@menu
* MAL instructions::
* Flow of control::
* Function definitions::
@menu
* Function Clones::
* Commands and Patterns::
@end menu
* Factory definitions::
* Modules::
* Type resolution::
@menu
* Atomary types::
@end menu
* Boxed variables::
* Property management::
@end menu

* MAL interpreter::

* Optimizer landscape::
@menu
* What optimizers to consider?::
* Optimization Dependencies::
* Optimizer Building Blocks::
* Query Optimizer Framework::
@end menu

* Optimizer toolkit::
@menu
* Alias Removal::
* Dead Code Removal::
* Accumulator Evaluations::
* Heuristic Rewrite Rules::
* Common Sub-Expression Removal::
* Empty Set Reduction::
* Singleton Set Replacement::
* Peephole Optimization::
* Multiplex Compiler::
* Garbage Collector::
* Code Factorization::
* Partitioned Database Optimizer::
* Strength Reduction::
* Costmodels::
* Variable Stack Reduction::
* Query Execution Plans::
@end menu
* Program Debugging::
@menu
* The MAL Debugger::
* Handling Breakpoints::
* Runtime Inspection::
@end menu
* Execution Profiling::
@menu
* Event Filtering ::
* Event Caching::
@end menu

* MonetDB Extension Modules ::
* MonetDB BAT Kernel ::
* Advanced Topics::
* Appendices::
@menu
* MAL Syntax ::
* MAL Instruction Overview::
* MAL Instruction Help::
@end menu
@end menu

@end ifnottex

@node About this manual, Features and Limitations, TOC , TOC
@include Assets/About-this-manual.texi

@include Assets/Features.texi
@include Assets/History.texi
@include Assets/Conventions.texi

@node Download and Installation, Binary Distributions, Conventions and notation, TOC
@section Downloads and Installation
@include Assets/Downloadintro.texi

@node MonetDB overview, Design considerations, Source Distributions, TOC

@include mal.bdy.texi

@node Session scenarios , Scenario management , Backward compatibility, MonetDB overview
@include mal_scenario.bdy.texi


@node Client administration, SQL, Scenario management, MonetDB overview
@include mal_client.bdy.texi

@node SQL, Getting Started with SQL, Client administration, TOC
@include Assets/SQLoverview.texi
@node XQuery, MapiClient and Interfaces, SQL Implementation Roadmap, TOC
@include Assets/XQueryOverview.texi

@node MapiClient and Interfaces, MonetDB Assembler Language, XQuery, TOC
@chapter MapiClient and Interfaces
@section Console Interface
@include mal_readline.bdy.texi
@section MapiClient
@section Application Programming Interfaces
Give a brief introduction to Mapi, JDBC, ODBC,Perl....
@subsection PHP
@subsection JDBC
@subsection ODBC
@subsection Perl

@node MonetDB Assembler Language, MAL instructions, MapiClient and Interfaces , TOC
@include mal_instruction.bdy.texi

@node Function definitions, Function Clones ,Flow of control , MonetDB Assembler Language
@include mal_function.bdy.texi

@node Factory definitions, Type resolution , Commands and Patterns, MonetDB Assembler Language
@include mal_factory.bdy.texi

@node Type resolution, Atomary types, Factory definitions, MonetDB Assembler Language
@include mal_resolve.bdy.texi
@node Atomary types, Boxed variables, Type resolution, MonetDB Assembler Language
@include mal_atom.bdy.texi

@node Boxed variables, Property management , Atomary types, MonetDB Assembler Language
@include mal_box.bdy.texi

@node Property management,  Modules, Boxed variables, MonetDB Assembler Language
@include mal_properties.bdy.texi

@node Modules , MAL interpreter , Property management, TOC
@include mal_import.bdy.texi

@node MAL interpreter, Optimizer landscape, Modules, TOC
@include mal_interpreter.bdy.texi
@include mal_linker.bdy.texi
@include mal_stack.bdy.texi

@node Optimizer landscape, What optimizers to consider?, MAL interpreter, TOC
@include mal_optimizer.bdy.texi
@include mal_commonExpressions.bdy.texi
@include mal_emptyset.bdy.texi
@include mal_singleton.bdy.texi
@include mal_peephole.bdy.texi
@include mal_multiplex.bdy.texi
@include mal_garbageCollector.bdy.texi
@include mal_factorize.bdy.texi
@include mal_partitionedQuery.bdy.texi
@include mal_strengthReduction.bdy.texi
@include mal_costmodel.bdy.texi
@include mal_reduce.bdy.texi
@node Query Execution Plans, Program Debugging, Variable Stack Reduction,  Optimizer toolkit
@include mal_qep.bdy.texi

@node Program Debugging, The MAL Debugger, Query Execution Plans, TOC
@include mal_debugger.bdy.texi

@node Execution Profiling, Event Filtering, Runtime Inspection, TOC
@include mal_profiler.bdy.texi

@node MonetDB Extension Modules , MonetDB BAT Kernel, Event Caching, TOC
@node MonetDB BAT Kernel , Advanced Topics, MonetDB Extension Modules , TOC
@node Advanced Topics , Appendices, MonetDB BAT Kernel , TOC
This is the place to describe Membedded, distribution stuff...

@node Appendices, MAL Syntax , Advanced Topics, TOC
@menu
* MAL Syntax ::
* MAL Instruction Overview:: 
* MAL Instruction Help:: 
@end menu

@node MAL Syntax, MAL Instruction Overview, Appendices, Appendices
@ifnottex
@include mal_syntax.bdy.texi
@end ifnottex

@node MAL Instruction Overview, MAL Instruction Help, MAL Syntax, Appendices
@appendix MAL Instruction Overview
@include Assets/MALinstructions.texi

@node MAL Instruction Help, , MAL Instruction Overview, Appendices
@appendix MAL Instruction Help
@include Assets/MALhelp.texi

@appendix Conversion of MIL programs
@bye
