\input texinfo
@c %**start of header
@setfilename MonetDB
@c %**end of header

@c environment
@set VERSION 5.0
@set UPDATED 21/11/2004

@copying
     This file documents the MonetDB Version @value{VERSION} Reference Manual
     
Last updated: @value{UPDATED}

     Copyright (C) 2000-2004 CWI
     
     Permission is granted to make and distribute verbatim
     copies of this manual provided the copyright notice and
     this permission notice are preserved on all copies.
     
@end copying

@titlepage
@title MonetDB Reference Manual
@subtitle Version @value{VERSION}
@author @emph{The MonetDB Development Team}
@page
@vskip 0pt plus 1fill
@c the following start the copy right page
@insertcopying
@end titlepage

@iftex
@contents
@end iftex

@ifnottex

@page
@node Top, TOC,  , 
@top MonetDB Reference Manual
@include Assets/General_information

@node TOC, About this manual, Top,(Dir)
Table of contents
@menu
* TOC::
* About this manual::
@menu
* Intended audience::
* Manual Generation::
* Conventions and notation::
@end menu

* Installation ::

* MonetDB overview ::
@menu
* The history of MonetDB::
* Architecture overview:: 
* Design considerations:: 
* Backward compatibility:: 
* MAL synopsis:: 
* Session management::
@menu
* Client administration::
* Session scenarios::
* MAL execution:: 
@end menu
@end menu



--- The SQL front-end ---

--- The Xquery front-end ---

* The application interfaces ::

* MonetDB Assembler Language::
@menu
* MAL constants::
* MAL variables::
* MAL instructions::
* Flow of control::
* Instruction Records::
* Before-after calls::
* The parser::
* Reverse programming::
* Function definitions::
* Factory definitions::
* Bootstrap::
* Modules::
* MAL interpreter::
* Atom types::
* Type resolution::
* Boxed variables::
* Optimizer framework::
* Property management::
* Name space management::
* MAL syntax::
@end menu

* XML interface::
* The MAL debugger::
* The MAL profiler::

--- The BAT kernel ---

--- Extension modules ---
@end menu

@end ifnottex

@node About this manual, Installation , TOC , TOC
@include Assets/About_this_manual

@node Installation , MonetDB overview, About this manual , TOC
@include Assets/Features
@node MonetDB overview, MonetDB Assembler Language, Installation, TOC
@include mal.bdy.texi
@include mal_scenario.bdy.texi
@include mal_client.bdy.texi
@include mal_session.bdy.texi
@include Assets/History

@node MonetDB Assembler Language , XML interface, MonetDB overview , TOC
@include mal_instruction.bdy.texi
@include mal_parser.bdy.texi

@node Function definitions, Factory definitions , , TOC
@include mal_function.bdy.texi

@node Factory definitions, Bootstrap , Function definitions, TOC
@include mal_factory.bdy.texi

@node Bootstrap , Modules ,Factory definitions, TOC
@include mal_linker.bdy.texi

@node Modules , MAL interpreter ,Bootstrap, TOC
@include mal_import.bdy.texi

@node MAL interpreter, Atom types, Modules, TOC
@include mal_interpreter.bdy.texi
@include mal_stack.bdy.texi

@node Atom types, Type resolution,MAL interpreter, TOC
@include mal_atom.bdy.texi

@node Type resolution, Boxed variables, Atom types, TOC
@include mal_type.bdy.texi
@include mal_resolve.bdy.texi

@node Boxed variables, Optimizer framework , Type resolution, TOC
@include mal_box.bdy.texi

@node Optimizer framework, Property management , Boxed variables, TOC
@include mal_optimizer.bdy.texi

@node Property management, Name space management , Optimizer framework, TOC
@include mal_properties.bdy.texi

@node Name space management, , Property management, TOC
@include mal_namespace.bdy.texi
@include mal_scope.bdy.texi

@node XML interface, The MAL debugger, MonetDB Assembler Language, TOC
@include mal_xml.bdy.texi

@node The MAL debugger, The MAL profiler , XML interface, TOC
@include mal_debugger.bdy.texi

@node The MAL profiler, MAL syntax , The MAL debugger, TOC
@include mal_profiler.bdy.texi

@node MAL syntax,, The MAL profiler, TOC
@ifnottex
@include mal_syntax.bdy.texi
@end ifnottex

@include Assets/ApplicationInterfaces


@bye
