#!/bin/bash

echo "create bdy files"

if [ -z "$1" ] ||  [ -z "$2" ];
then
	echo "usage $0 m5prefix m4prefix" > /dev/stderr
	exit -1
fi

# extract the texi files from the source trees
# leave them behind in a temporary directory

dir=$1
m4dir=$2

mkdir ${dir}/doc/share/tmp
cd ${dir}/src/mal
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp

cd ${dir}/src/optimizer
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp

cd ${m4dir}/src/gdk
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp
cp *pdf ${dir}/doc/share/tmp
cp *feps *pdf ${dir}/doc/share/tmp
sed -i -e "/@t/,/@contents/d" ${dir}/doc/share/tmp/gdk.bdy.texi

cd ${m4dir}/src/mapi/clients/C
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp

cd ${dir}/src/modules/mal
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		cp $b.bdy.texi ${dir}/doc/share/tmp/$b.bdy.texi.bak
		cp $b.bdy.texi $b.2.bdy.texi
		ex $b.bdy.texi <<!EOF
		/^@example/s/.*/ @table @code/
/^@end example/s//@end table/
		g/^command/s//@item command
		g/^pattern/s//@item pattern
		g/^function/s//@item function
		g/^address/d
		g/^comment "/s///
		g/^comment/s///
		g/{unsafe}/s//\\\\{unsafe\\\\}/
		g/";/s///
		/^@example/,/^@end example/d
		/^@example/,/^module/-1d
		/@table/+1s/module \(.*\);/ @noindent module @code{\1};/
/@tabl/m/@tabl/+1
		0i
@page
.
		f
		w!
!EOF
		ex $b.2.bdy.texi <<!EOF2
		g/{unsafe}/s//@verb{ { }unsafe@verb{ } }/
		w!
!EOF2
		mv $b.2.bdy.texi $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp
cd ${dir}/src/mil
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp
cd ${dir}/src/modules/atoms
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
cp *gif *eps *pdf ${dir}/doc/share/tmp
cd ${dir}/src/modules/kernel
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
		mv $b.bdy.texi  ${dir}/doc/share/tmp
done
