#!/bin/bash

echo "create bdy files"

mkdir ${MONET5_PREFIX}/share/MonetDB5
cd ${MONET5_PREFIX}/../src/mal
ls
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
cd ${MONET5_PREFIX}/../src/optimizer
ls
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done

cd ${MONETDB_PREFIX}/../src/gdk
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
cp *png ${MONET5_PREFIX}/share/MonetDB5
cp *feps ${MONET5_PREFIX}/share/MonetDB5
sed -i -e "/@t/,/@contents/d" ${MONET5_PREFIX}/share/MonetDB5/gdk.bdy.texi

cd ${MONETDB_PREFIX}/../src/mapi/clients/C
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done

cd ${MONET5_PREFIX}/../src/modules/mal
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
cd ${MONET5_PREFIX}/../src/mil
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
cd ${MONET5_PREFIX}/../src/modules/atoms
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
cd ${MONET5_PREFIX}/../src/modules/kernel
ls *mx
for f in  `ls *.mx`
do
	b=`basename $f .mx`
	echo "---->" $f $b.bdy.texi 
        Mx -i -B -H1 $f
        mv $b.bdy.texi ${MONET5_PREFIX}/share/MonetDB5
done
