#!/bin/bash

xsltproc manual.xsl manual.xml > manual.tex
if [ $? -eq 0 ]; then
	latex manual.tex
	makeindex manual.tex
	latex manual.tex
	rm -f manual.aux manual.log manual.idx
	rm -f manual.toc manual.ilg manual.idn
fi
