\input texinfo
@c %**start of header
@setfilename MonetDB
@c %**end of header

@c environment
@set VERSION 5.0
@set UPDATED 18/12/2004

@copying
     This file documents the MonetDB Version @value{VERSION} 
    Module Implementation Notes
     
Last updated: @value{UPDATED}

     Copyright (C) 2000-2005 CWI
     
     Permission is granted to make and distribute verbatim
     copies of this manual provided the copyright notice and
     this permission notice are preserved on all copies.
     
@end copying

@titlepage
@title MonetDB Modules Implementation Notes
@subtitle Version @value{VERSION}
@author @emph{The MonetDB Development Team}
@page
@vskip 0pt plus 1fill
@c the following start the copy right page
@insertcopying
@end titlepage

@contents

@ifnottex
@page
@node Top, About this manual, (dir), (dir)
@top MonetDB

@include Assets/General_information
@menu
* About this manual::
* Introduction V5::
* Atom definitions ::
* BAT buffer pool::
* Box definition::
* Client management::
* Constant support box::
* Cracker index ::
* Enumerated types ::
* Factory management::
* Cracker index ::
* Inspection ::
* IO module::
* MAL language support::
* MIL support box::
* Multiplexed operations::
* Optimizer support::
* Profiler::
* Stream module::
* Tablet display::
* Thread management::
* Transaction management::
* Simple aggregations::
* BAT module::
* BAT algebra module::
* Basic arithmetic::
* Math operations::
* BAT calculations::
* Group operations::
* Locks and semaphores::
* Time and interupts::
* Unix features::
* Status information::
* MAPI information::
@end menu
@end ifnottex

@node Introduction V5, BAT buffer pool ,About this manual, Top
@include Assets/About_this_manual_gdk

@ @node Atom definitions , BAT buffer pool, Introduction V5 ,  Top
@ @include atoms.bdy.texi

@node BAT buffer pool , Box definition , Introduction V5 ,  Top
@include bbp.bdy.texi

@node Box definition, Client management, BAT buffer pool ,  Top
@include box.bdy.texi

@node Client management, Constant support box , Box definition ,  Top
@include clients.bdy.texi

@node Constant support box , Cracker index , Client management ,  Top
@include const.bdy.texi

@node Cracker index , Enumerated types , Constant support box ,  Top
@include crackers.bdy.texi

@node Enumerated types , Factory management , Cracker index ,  Top
@include enum.bdy.texi

@node Factory management , Inspection , Enumerated types ,  Top
@include factory.bdy.texi

@node Inspection , IO module , Factory management ,  Top
@include inspect.bdy.texi

@node IO module, MAL language support , Inspection ,  Top
@include io.bdy.texi

@node MAL language support, MIL support box , IO module ,  Top
@include language.bdy.texi

@node MIL support box , Multiplexed operations, MAL language support ,  Top
@include mil.bdy.texi

@node Multiplexed operations , Optimizer support , MIL support box ,  Top
@include multiplex.bdy.texi

@node Optimizer support , Profiler , Multiplexed operations ,  Top
@include optimizer.bdy.texi

@node Profiler , Stream module , Optimizer support ,  Top
@include profiler.bdy.texi

@node Stream module , Tablet display , Profiler ,  Top
@include streams.bdy.texi

@node Tablet display, Thread management, Stream module ,  Top
@include tablet.bdy.texi

@node Thread management, Transaction management, Tablet display,  Top
@include thread.bdy.texi

@node Transaction management, BAT module , Thread management ,  Top
@include transaction.bdy.texi

@node BAT module, BAT algebra module, Transaction management,  Top
@include bat.bdy.texi

@node BAT algebra module, Basic arithmethic, BAT module,  Top
@include algebra.bdy.texi

@node Basic arithmetic, Simple aggregations , Basic arithmethic ,  Top
@include calc.bdy.texi

@node Simple aggregations , Math operations ,Calculation module, Top
@include aggrX3.bdy.texi

@node Math operations, Time and interupts , Simple aggregations ,Top
@include mmath.bdy.texi

@node BAT calculations, Group operations , Math operations ,Top
@include batcalc.bdy.texi

@node Group operations, Locks and semaphores , BAT calculations ,Top
@include group.bdy.texi

@node Locks and semaphores, Time and interupts , Group operations,Top
@include lock.bdy.texi

@node Timers and interupts , Unix features, Locks and semaphores , Top
@include alarm.bdy.texi

@node Unix features, Status information,Timers and interupts , Top
@include unix.bdy.texi

@node Status information, MAPI ,Unix features , Top
@include status.bdy.texi

@node MAPI , ,Status information , Top
@include status.bdy.texi

@bye
