\input texinfo
@c %**start of header
@c this file is meant for the SQL line

@setfilename MonetDB
@setcontentsaftertitlepage
@settitle MonetDB/XQuery Reference Manual
@c %**end of header

@c environment
@set VERSION 5.0
@set UPDATED July 30, 2006

@copying
     This file documents the MonetDB Version @value{VERSION} Reference Manual
     
Last updated: @value{UPDATED}

     Copyright (C) 2000-2006 CWI
     
     Permission is granted to make and distribute verbatim
     copies of this manual provided the copyright notice and
     this permission notice are preserved on all copies.
@ifhtml
The latest documentation can be downloaded as a single file for printing
@url{http://monetdb.cwi.nl/projects/monetdb/Assets/xqmanual.pdf,single page manual} or
@url{http://monetdb.cwi.nl/projects/monetdb/Assets/xqmanual-2x1.pdf,double page manual}.
@end ifhtml
     
@emph{Disclaimer} The reference manual and underlying source
code base are still under development.
This may lead to incomplete and inconsistencies descriptions,
for which we apologize in advance. You can help improving the manual
using the 
@url{mailto:monetdb-users@@lists.sourceforge.net,MonetDB mailing list}.

@end copying

@titlepage
@title MonetDB/XQuery Reference Manual
@subtitle Version @value{VERSION}
@author @emph{The MonetDB Development Team}
@page
@vskip 0pt plus 1fill
@c the following start the copy right page
@insertcopying
@end titlepage

@iftex
@c output the table of contents
@contents
@c make sure you run pdftex twice 
@end iftex

@ifnottex
@node Top
@top MonetDB/XQuery Reference Manual
@insertcopying
@end ifnottex

@menu
* General Introduction::
* Client Interfaces::
* XQuery Introduction::
* Development Roadmap::
* Programming Interfaces::
* Embedded MonetDB::
* Appendices::
@end menu

@set XQmanual
@set mclient @code{MapiClient}
@set mjclient @code{MapiClient}
@set bookname MonetDB/Xquery

@node General Introduction, Intended audience, Top , Top
@include xquery/warning.texi
@include Assets/About-this-manual.texi

@node Features and Limitations, MonetDB Pro's, How to read this manual, General Introduction
@include Assets/Features.texi

@node A Brief History , Manual Generation, Size Limitations, General Introduction
@include Assets/History.texi

@node Manual Generation, Conventions , A Brief History , General Introduction
@include Assets/Conventions.texi

@node Download and Installation, Standard Distribution , Additional Resources, General Introduction
@include Assets/Downloadintro.texi

@node Source Distribution, Linux Installation, Software Versions , Download and Installation
@include Assets/Setup.texi

@node Start and Stop the Server, Database Configuration ,Daily Builds, General Introduction
@include Assets/StartStop.texi

@node Database Configuration , Checkpoint and Recovery, Start and Stop the Server, General Introduction
@include Assets/DatabaseConfiguration.texi

@node Checkpoint and Recovery, Database Dumps, Database Configuration, General Introduction
@include Assets/Checkpoints.texi

@node Database Dumps, Client Interfaces, Checkpoint and Recovery, General Introduction
@include Assets/Databasedump.texi

@node Client Interfaces, MAPI Client, Database Dumps, Top
@include mal_client.bdy.texi
@menu
* MAPI Client::
* JDBC Client::
* Console Interface::
* Apache Configuration::
@end menu
@node MAPI Client, JDBC Client, Client Interfaces, Client Interfaces
@include Assets/MapiClient.texi
@include xquery/MapiClient.texi

@node JDBC Client, Console Interface, MAPI Client, Client Interfaces
@include Assets/JdbcClient.texi
@include xquery/JDBC-XQ.texi
@include xquery/XML-DB.texi

@node Console Interface, Apache Configuration, JDBC Client, Client Interfaces
@subsection Console Interface
@include mal_readline.bdy.texi

@node Apache Configuration, Development Roadmap, Console Interface, Client Interfaces
@include xquery/Apache.texi
@include xquery/Security.texi

@node Development Roadmap, XQuery Roadmap, Apache Configuration, Top
@include Assets/Roadmap.texi
@menu
* XQuery Roadmap ::
* Server Roadmap ::
@end menu

@node XQuery Roadmap, Server Roadmap, Development Roadmap, Development Roadmap

@node Server Roadmap, XQuery Introduction, XQuery Roadmap, Development Roadmap
@include Assets/ServerRoadmap.texi

@c The XQuery specific part

@node XQuery Introduction, XQuery QuickTours, Server Roadmap , Top
@include xquery/warning.texi
@menu
* XQuery QuickTours::
* Supported Features ::
* Document Management::
* Prepared Queries::
* StandOff Extensions::
@end menu
@include xquery/intro.texi
@include xquery/Xpath.texi
@include xquery/Xquery.texi
@include xquery/Language.texi

@node XQuery QuickTours, Supported Features, XQuery Introduction , XQuery Introduction
@include xquery/warning.texi

@node Supported Features, Document Management , XQuery QuickTours , XQuery Introduction
@section Supported Features
@include xquery/warning.texi
@include xquery/Functions.texi

@node Document Management, Document Collection, Supported Features,XQuery Introduction
@menu
* Document Collection::
* Add Document::
* Remove Document::
* Cache Policy::
* Miscellaneous::
@end menu
@include xquery/warning.texi
@include xquery/DocMgmt.texi

@node Document Collection , Add Document, Document Management, Document Management
@include xquery/ListDoc.texi
@node Add Document, Remove Document, Document Collection, Document Management
@include xquery/AddDoc.texi
@node Remove Document, Cache Policy, Add Document, Document Management
@include xquery/DelDoc.texi
@node Cache Policy, Miscellaneous, Remove Document, Document Management
@include xquery/Cache.texi
@node Miscellaneous, Prepared Queries, Cache Policy, Document Management
@include xquery/DocOther.texi

@node Prepared Queries, StandOff Extensions , Miscellaneous ,XQuery Introduction
@include xquery/PreparedQueries.texi

@node StandOff Extensions, Extended XPath Steps ,Prepared Queries ,XQuery Introduction
@section StandOff Extensions
@include xquery/Standoff.texi

@node Programming Interfaces, The JDBC Library, Why StandOff Extensions?, Top
@menu
* The Mapi Library ::
* The Perl Library::
* The PHP Library::
* The Python Library::
* The JDBC Library::
* The ODBC Library::
@end menu
@c @include xquery/API.texi

@c End of XQuery specific part

@node The JDBC Library, Appendices , Programming Interfaces, Programming Interfaces
@include xquery/jdbcmanual.texi

@node Appendices, XQuery Functions, The JDBC Library, Top
@menu
* XQuery Functions::
* Troubleshooting::
* VOC History::
@end menu

@node XQuery Functions, XQuery Aggregation  , Appendices, Appendices
@include xquery/FunctionsList.texi

@node Troubleshooting, VOC History, XQuery Date/Time, Appendices
@include xquery/trouble.texi
@node VOC History,  , Troubleshooting, Appendices
@include Assets/VOChistory.texi

@bye
