# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

SUBDIRS = NOT_WIN32?merovingian

INCLUDES = ../../include ../../common ../../storage ../../server \
	$(MONETDB5_INCS) $(CLIENTS_INCS) $(MONETDB_INCS) $(READLINE_INCS)

lib__sql = {
	DIR = libdir/MonetDB5
	SOURCES = \
		sql.mx \
		sql_user.mx \
		sql_scenario.mx \
		sql_gencode.mx \
		sql_optimizer.mx \
		sql_result.mx \
		sql_readline.mx \
		sql_emptyset.mx \
		sql_bpm.mx
	LIBS = ../../server/libsqlserver ../../storage/libstore ../../storage/bat/libbatstore ../../storage/restrict/librestrictstore ../../storage/bpm/libbpmstore ../../common/libsqlcommon \
		$(MONETDB5_MODS) -l_bbp -l_replication -l_mkey -l_str -l_blob -l_logger -l_mtime -l_bat5 -l_optimizer -l_tablet -l_cluster -l_bpm -l_remote -l_run_octopus -l_algebra \
		$(MONETDB5_RDF_LIB) $(MONETDB5_LIBS) -lmonetdb5 -l_mal_mapi \
		$(MONETDB_LIBS) -lbat -lstream $(READLINE_LIBS) $(PTHREAD_LIBS) 
}


lib_embeddedsql5 = {
	SOURCES = embeddedclient.c.in
	LIBS = ../../server/libsqlserver ../../storage/libstore ../../storage/bat/libbatstore ../../storage/restrict/librestrictstore ../../storage/bpm/libbpmstore ../../common/libsqlcommon \
		$(MONETDB5_MODS) -l_logger -l_bat5 -l_tablet -l_cluster -l_bpm $(MONETDB5_LIBS) -lmonetdb5 \
		$(CLIENTS_LIBS) $(MONETDB_LIBS) -lbat -lMapi -lmutils -lstream $(READLINE_LIBS) $(PTHREAD_LIBS)
}

bin_Mbeddedsql5 = {
	SOURCES = prog.c
	LIBS = libembeddedsql5 ../../server/libsqlserver ../../storage/libstore ../../storage/bat/libbatstore ../../storage/restrict/librestrictstore ../../storage/bpm/libbpmstore ../../common/libsqlcommon \
		$(MONETDB5_MODS) -l_logger -l_bat5 -l_tablet -l_cluster -l_bpm $(MONETDB5_LIBS) -lmonetdb5 \
		$(CLIENTS_LIBS) $(MONETDB_LIBS) -lbat -lMapi -lmutils -lstream $(READLINE_LIBS) $(PTHREAD_LIBS)
}

headers_h = {
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = embeddedclient.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = sql.mx sql_bpm.mx sql_emptyset.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 40_sql.mal
}

EXTRA_DIST = 40_sql.mal
EXTRA_DIST_DIR = Tests
