# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.

INCLUDES = ../../common ../../server $(MONET5_INCS) $(MONETDB_INCS)

lib__sql = {
	DIR = libdir/MonetDB5
	SOURCES = \
		sql.mx \
		sql_scenario.mx \
		sql_gencode.mx \
                sql_optimizer.mx \
		sql_server.mx
	WINLIBS = -lbat -lmonet -lstream -l_streams -l_bat -l_kernel -l_ascii_io
	LIBS = ../../server/libsqlserver $(MONETDB_LIBS) -lbat -lmal -lstream $(MONET5_LIBS)
}

scripts_mal = {
	DIR = libdir/MonetDB5
	SOURCES = sql.mx sql_scenario.mx sql_server.mx
}
