# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

INCLUDES = ../../include ../../common ../../storage ../../server \
	-I$(MONETDB_INCLUDEDIR)/C $(MONET5_INCS) $(MONETDB_INCS)

lib__sql = {
	DIR = libdir/MonetDB5
	SOURCES = \
		sql.mx \
		sql_user.mx \
		sql_scenario.mx \
		sql_gencode.mx \
		sql_optimizer.mx \
		sql_cache.mx \
		sql_result.mx \
		sql_readline.mx
	LIBS = ../../server/libsqlserver ../../storage/bat/libbatstore ../../common/libsqlcommon \
		$(MONET5_MODS) -l_mtime -l_bat5 $(MONET5_LIBS) -loptimizer -lmal \
		$(MONETDB_LIBS) -lbat -lstream $(PTHREAD_LIBS)
}


lib_embeddedsql5 = {
	SOURCES = embeddedclient.mx
	LIBS = ../../server/libsqlserver ../../storage/bat/libbatstore ../../common/libsqlcommon \
		$(MONET5_MODS) -l_bat5 $(MONET5_LIBS) -lmal \
		$(MONETDB_LIBS) -lbat -lMapi -lmutils -lstream $(PTHREAD_LIBS)
}

bin_Mbeddedsql5 = {
	SOURCES = prog.c
	LIBS = libembeddedsql5 ../../server/libsqlserver ../../storage/bat/libbatstore ../../common/libsqlcommon \
		$(MONET5_MODS) -l_bat5 $(MONET5_LIBS) -lmal \
		$(MONETDB_LIBS) -lbat -lMapi -lmutils -lstream $(PTHREAD_LIBS)
}

lib__sql_cache = {
	DIR = libdir/MonetDB5
	SOURCES = dummy.c
}

scripts_mal = {
	DIR = libdir/MonetDB5
	SOURCES = sql.mx sql_cache.mx
}
