# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2013 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../gdk \
		   $(libxml2_CFLAGS) $(curl_CFLAGS)
MTSAFE

lib_atoms = {
	NOINST
	SOURCES = \
		batxml.c \
		blob.c blob.h \
		color.c color.h \
		identifier.c identifier.h \
		inet.c inet.h \
		mtime.c mtime.h \
		streams.c streams.h \
		str.c str.h \
		url.c url.h \
		json_atom.c json_atom.h \
		mcurl.c \
		xml.c xml.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = \
		batxml.mal \
		blob.mal \
		color.mal \
		identifier.mal \
		inet.mal \
		streams.mal \
		str.mal \
		url.mal \
		json_atom.mal \
		xml.mal \
        mcurl.mal \
		mtime.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = blob.mal color.mal identifier.mal inet.mal xml.mal xml.sql batxml.sql str.mal batxml.mal url.mal json_atom.mal streams.mal mtime.mal mcurl.mal
