# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   $(libxml2_CFLAGS)
MTSAFE

lib_atoms = {
	NOINST
	SOURCES = \
		batxml.mx \
		blob.c \
		color.c \
		identifier.c \
		inet.c \
		mtime.mx \
		streams.mx \
		str.mx \
		url.mx \
		xml.c
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = \
		batxml.mx \
		blob.mal \
		color.mal \
		identifier.mal \
		inet.mal \
		mtime.mx \
		streams.mx \
		str.mx \
		url.mx \
		xml.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = blob.mal blob.h color.mal color.h identifier.mal identifier.h inet.mal inet.h xml.mal xml.h xml.sql
