# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = ../../mal \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../gdk \
		   $(libxml2_CFLAGS) $(curl_CFLAGS) $(openssl_CFLAGS)
MTSAFE

lib_atoms = {
	NOINST
	SOURCES = \
		batxml.c \
		blob.c blob.h \
		color.c color.h \
		identifier.c \
		inet.c \
		json.c json.h \
		mcurl.c \
		mtime.c mtime.h \
		str.c str.h \
		streams.c streams.h \
		url.c url.h \
		uuid.c \
		xml.c xml.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = \
		batxml.mal \
		blob.mal \
		color.mal \
		identifier.mal \
		inet.mal \
		json.mal \
		mcurl.mal \
		mtime.mal \
		streams.mal \
		str.mal \
		url.mal \
		uuid.mal \
		xml.mal
}

headers_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = \
		00_json_hge.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = xml.sql batxml.sql
