CREATE TABLE tab2(col0 INTEGER, col1 INTEGER, col2 INTEGER);
INSERT INTO tab2 VALUES (64,77,40), (75,67,58), (46,51,23);
SELECT * FROM tab2 WHERE col2 NOT IN ( - + col1, col2 * + col1, + - col0 * + + 36, + + col2, 84 * + + col0 ) AND NOT NULL IS NULL;
SELECT CAST ( SUM ( DISTINCT 23 ) * - COUNT ( DISTINCT + - col1 ) AS BIGINT ) FROM tab2 AS cor0 WHERE NOT NULL; --NULL
SELECT CAST ( SUM ( DISTINCT 23 ) * - COUNT ( DISTINCT + - col1 ) AS BIGINT ) FROM tab2 AS cor0 WHERE NULL; --NULL
SELECT DISTINCT CAST ( SUM ( DISTINCT 23 ) * - COUNT ( DISTINCT + - col1 ) AS BIGINT ) FROM tab2 AS cor0 WHERE NOT ( NULL ) IS NULL; --NULL
SELECT ALL + + MIN ( DISTINCT - - 14 ) AS col1, CAST ( - SUM ( DISTINCT 74 ) AS BIGINT ) col0 FROM tab2 AS cor0 
WHERE NULL BETWEEN col0 AND NULL; --NULL, NULL
DROP TABLE tab2;
