SELECT ALL + 62 * + - CAST( ( CASE WHEN NULL NOT IN ( CAST ( CAST ( - 77 AS INTEGER ) AS INTEGER ) )
THEN NULL WHEN ( NULL ) NOT IN ( 94 * COUNT ( * ) ) THEN + ( NULLIF ( 45, 80 + 90 ) ) - COUNT ( * )
ELSE NULL END ) AS BIGINT) AS col2;
