# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

INCLUDES = \
	../include \
	../driver \
	-I$(MONETDB_INCLUDEDIR) \
	$(ODBC_INCS)

DEFS = @DEFS@
ODBCLIBS = -lodbc32 -lodbccp32 -lversion -lshlwapi -luser32

lib_MonetODBCs = {
	SOURCES = setup.c setup.rc setup.syms resource.h
	LIBS = -lodbccp32 -luser32
}

bin_odbcinstall = {
	SOURCES = install.c
	LIBS = -lodbc32 -lodbccp32 -lversion -lshlwapi -luser32
}

EXTRA_DIST = banner.bmp
