# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE
INCLUDES = ../../../common/options ../../../common/stream \
	../../../MonetDB/src/gdk \
	../../../MonetDB4/src/monet \
	../../../MonetDB4/src/modules/plain \
	../../../MonetDB4/src/modules/contrib \
	../../../MonetDB4/src/mapi \
	../../../MonetDB4/src/modules/calibrator \
	$(GEOS_INCS) -I../lib

lib__geom = {
	DIR = libdir/MonetDB4
	SOURCES = geom.mx
	LIBS = ../../../MonetDB/src/gdk/libbat \
	       ../../../common/stream/libstream \
	       ../../../MonetDB4/src/monet/libmonet \
	       $(GEOS_LIBS) ../lib/libgeom
}

scripts_mil = {
	DIR = libdir/MonetDB4
	SOURCES = geom.mx
}
