CREATE stream TABLE testing (a int);

CREATE TABLE results (b int);

CREATE CONTINUOUS PROCEDURE stressing() BEGIN INSERT INTO results SELECT a FROM testing; END;

START CONTINUOUS PROCEDURE;
STOP CONTINUOUS PROCEDURE;
