START TRANSACTION;

CREATE TABLE rapi16(a INTEGER, b DOUBLE);
INSERT INTO rapi16 VALUES (1,1.2), (1,2.2), (2,2.5), (2,0.9);


CREATE FUNCTION rapi16(a INTEGER, b DOUBLE) RETURNS TABLE (c INTEGER, d DOUBLE) LANGUAGE R {
data.frame(c=a,d=b)};

SELECT * FROM rapi16((SELECT A, B FROM rapi16 AS X));

CREATE VIEW rapi16v AS SELECT * FROM rapi16((SELECT A, B FROM rapi16 AS X));
SELECT * FROM rapi16v;

DROP VIEW rapi16v;
DROP FUNCTION rapi16;
DROP TABLE rapi16;

ROLLBACK;
