# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

MTSAFE

# We compile against the standard interface, so no classpath needed
CLASSPATH = ""

java_Test_Cautocommit = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Cautocommit.java
}

java_Test_Csavepoints = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Csavepoints.java
}

java_Test_PStimedate = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_PStimedate.java
}

java_Test_PStimezone = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_PStimezone.java
}

java_Test_Rbooleans = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Rbooleans.java
}

java_Test_Rpositioning = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Rpositioning.java
}

java_Test_Rtimedate = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Rtimedate.java
}

java_Test_Sbatching = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Sbatching.java
}

java_Test_Rmetadata = {
	DIR = pkgdatadir/Tests
	SOURCES = Test_Rmetadata.java
}

EXTRA_DIST_DIR = Tests
