# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = -I../../mal $(monetdbcommon_CFLAGS) $(libxml2_CFLAGS)
MTSAFE

lib__xml = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = xml.mx 

	#SCRIPTS = mal
	LIBS = ../../tools/libmonetdb5 $(monetdbcommon_LIBS) $(MALLOC_LIBS) \
		$(libxml2_LIBS)
}

headers_xml_autoload = {
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 05_xml.mal
}

headers_xml_h = {
	DIR = includedir/MonetDB5/atoms
	SOURCES = xml.mx
	HEADERS = h 
}

headers_xml_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = xml.mx
}

lib_batxml = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = batxml.mx
	LIBS = lib_xml ../../tools/libmonetdb5 $(monetdbcommon_LIBS) $(MATH_LIBS) \
                $(MALLOC_LIBS) $(libxml2_LIBS)
}

headers_batxml_h = {
	DIR = includedir/MonetDB5/mal
	SOURCES = batxml.mx
	HEADERS = h 
}

headers_batxml_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = batxml.mx
}

EXTRA_DIST_DIR = Tests
