INCLUDES = -I../../mal $(MONETDB_INCS) \
	 $(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS)
MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = blob.mx url.mx mtime.mx streams.mx inet.mx color.mx

	HEADERS = h 
	#SCRIPTS = mal
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) ../../mal/libmal
}

lib__str = {
	DIR = pkglibdir
	SEP = _
	SOURCES = str.mx 

	HEADERS = h 
	#SCRIPTS = mal
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
		$(ICONV_LIBS) ../../mal/libmal
}


scripts_mal = {
	DIR = pkglibdir
	SOURCES = str.mx blob.mx url.mx mtime.mx streams.mx inet.mx color.mx
}

#EXTRA_DIST_DIR = Tests
