
INCLUDES = -I../../common -I../../gdk -I../../mal \
	 $(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS)
MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = atoms_init.mx str.mx blob.mx url.mx mtime.mx \
		uchr.mx 

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = ../../common/libstream ../../gdk/libbat \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
scripts_mal = {
	DIR = pkglibdir/atoms
	SOURCES = atoms_init.mx str.mx blob.mx url.mx mtime.mx \
		uchr.mx 
}

EXTRA_DIST_DIR = Tests
