#!/bin/sh

set $1				# no quotes!

dir="$1"; shift			# first arg is directory

for f
do
    if fgrep "$dir/$f" > /dev/null 2>&1 <<\EOF
MonetDB/bootstrap
MonetDB/de-bootstrap
MonetDB/rules.mk
MonetDB/conf/conf.bash
template/bootstrap
template/de-bootstrap
template/rules.mk
template/conf/conf.bash
sql/bootstrap
sql/de-bootstrap
sql/rules.mk
sql/conf/conf.bash
xml/bootstrap
xml/de-bootstrap
xml/rules.mk
xml/conf/conf.bash
pathfinder/bootstrap
pathfinder/de-bootstrap
pathfinder/rules.mk
pathfinder/conf/conf.bash
buildtools/conf/conf.bash
EOF
    then
	cat <<EOF

WARNING:

The file "$dir/$f" should be kept identical in
MonetDB, template, sql, pathfinder,  xml, pruning, monet5, amdb!

(If necessary, please contact Stefan.Manegold@cwi.nl for details.)

EOF
    fi
done
