#!/bin/sh

set $1				# no quotes!

dir="$1"; shift			# first arg is directory

for f
do
    if fgrep "$dir/$f" > /dev/null 2>&1 <<\EOF
MonetDB/bootstrap
MonetDB/de-bootstrap
MonetDB4/bootstrap
MonetDB4/de-bootstrap
MonetDB5/bootstrap
MonetDB5/de-bootstrap
clients/bootstrap
clients/de-bootstrap
template/bootstrap
template/de-bootstrap
sql/bootstrap
sql/de-bootstrap
pathfinder/bootstrap
pathfinder/de-bootstrap
xml/bootstrap
xml/de-bootstrap
geom/bootstrap
geom/de-bootstrap
EOF
    then
	cat <<EOF

WARNING:

The file "$dir/$f" should be kept identical in
MonetDB, MonetDB4, MonetDB5, clients, template, sql, pathfinder, xml, geom, amdb, datacell, pruning !

(If necessary, please contact Stefan.Manegold@cwi.nl for details.)

EOF
    fi
done
