#!/bin/sh

set $1				# no quotes!

dir="$1"; shift			# first arg is directory

for f
do
    if fgrep "$dir/$f" > /dev/null 2>&1 <<\EOF
MonetDB/bootstrap
MonetDB/rules.mk
MonetDB/conf/conf.bash
sql/bootstrap
sql/rules.mk
sql/conf/conf.bash
template/bootstrap
template/rules.mk
template/conf/conf.bash
EOF
    then
	cat <<EOF
WARNING:

The file "$dir/$f" should be kept identical in
MonetDB, monet5, sql, xml, acoi, gis, template, playpen, misq, times100, pruning!
EOF
    fi
done
