# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the Monet Database System.
# 
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.
# 
# Contributor(s):
# 		Martin Kersten <Martin.Kersten@cwi.nl>
# 		Peter Boncz <Peter.Boncz@cwi.nl>
# 		Niels Nes <Niels.Nes@cwi.nl>
# 		Stefan Manegold  <Stefan.Manegold@cwi.nl>

MTSAFE

VPATH = $(srcdir):$(srcdir)/example

EXTRA_DIST = manifest

jar_MonetJDBC = {
	DIR = libdir/MonetDB/java
	SOURCES = nl/cwi/monetdb/jdbc/MonetConnection.java \
	          nl/cwi/monetdb/jdbc/MonetDatabaseMetaData.java \
	          nl/cwi/monetdb/jdbc/MonetDriver.java.in \
	          nl/cwi/monetdb/jdbc/MonetResultSet.java \
	          nl/cwi/monetdb/jdbc/MonetSavepoint.java \
	          nl/cwi/monetdb/jdbc/MonetSocket.java \
	          nl/cwi/monetdb/jdbc/MonetStatement.java \
	          JdbcClient.java
	EXTRA = MaskingThread.class PasswordField.class QueryPart.class SQLStack.class
	MANIFEST = $(srcdir)/manifest
}

