# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MT_SAFE

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = \
		createdb.mx \
		cache.sql octopus.sql parts.sql \
		replication.sql temporal.sql vacuum.sql
}

headers_rdf = {
	COND = HAVE_RAPTOR
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = rdf.sql
}

EXTRA_DIST = clients.sql cluster.sql compress.sql date.sql \
	dependency_functions.sql dictionary.sql history.sql inet.sql \
	math.sql mtime.sql skyserver.sql system.sql times.sql \
	tracelog.sql url.sql zorder.sql
