# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MT_SAFE

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 10_math.sql 11_times.sql 12_url.sql 13_date.sql 14_inet.sql 15_history.sql 16_tracelog.sql 17_compress.sql 18_dictionary.sql 19_cluster.sql 20_vacuum.sql 21_dependency_functions.sql 22_clients.sql 23_skyserver.sql 24_zorder.sql 25_debug.sql 99_system.sql
}

headers_moresql = {
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = \
		cache.sql octopus.sql parts.sql \
		temporal.sql
}

headers_rdf = {
	COND = HAVE_RAPTOR
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 30_rdf.sql
}
