# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../../common/options ../../common/stream \
		   $(openssl_CFLAGS) $(MSGCONTROL_FLAGS)

lib_mapi = {
	VERSION = $(MAPI_VERSION)
	SOURCES = mapi.mx mapi.rc
	LIBS = $(SOCKET_LIBS) ../../common/stream/libstream \
		../../common/options/libmoptions $(openssl_LIBS)
}

lib_mapi4 = {
	VERSION = $(MAPI_VERSION)
	COND = HAVE_MONETDB4
	SOURCES = mapi.mx mapi.rc
	LIBS = $(SOCKET_LIBS) ../../common/stream/libstream4 \
		../../common/options/libmoptions $(openssl_LIBS)
}

headers_mapi = {
	DIR = includedir/monetdb
	HEADERS = h
	SOURCES = mapi.mx
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb-mapi.pc.in
}
