# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

MTSAFE

INCLUDES = ../../common/options ../../common/stream ../../common/utils \
		   $(MSGCONTROL_FLAGS)

lib_mapi = {
	VERSION = $(MAPI_VERSION)
	SOURCES = mapi.c mapi.rc
	LIBS = $(SOCKET_LIBS) ../../common/stream/libstream \
		../../common/options/libmoptions \
		../../common/utils/libmcrypt $(openssl_LIBS)
}

headers_mapi = {
	DIR = includedir/monetdb
	HEADERS = h
	SOURCES = mapi.h
}

headers_pc = {
	COND = NOT_WIN32
	HEADERS = pc
	DIR = libdir/pkgconfig
	SOURCES = monetdb-mapi.pc.in
}
