## Process this file with automake to produce Makefile.in

EXTRA_DIST = sqlserver.mil

INCLUDES = ../common ../client $(MONET_INCS)

lib__sqlserver = {
	DIR = libdir/MonetDB
	SOURCES = sqlserver.mx mvc.mx bm.mx logger.mx privileges.mx \
		catalog_module.c statement_exec.c 
	LIBS = ../common/libsql $(MONET_LIBS)
	LDFLAGS = -module
}

scripts_mil = {
	DIR = datadir/MonetDB
	SOURCES = sqlserver.mil
}
