# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

## Process this file with automake to produce Makefile.in

INCLUDES = ../include ../common ../storage $(MONETDB_INCS)

YFLAGS = -d -p sql -v

lib_sqlserver = {
	NOINST
	DIR = libdir
	SOURCES = \
		sql_atom.mx \
		sql_datetime.mx \
		sql_string.mx \
		sql_decimal.mx \
		sql_scope.mx \
		sql_statement.mx \
		sql_trans.mx \
		sql_schema.mx \
		sql_updates.mx \
		sql_select.mx \
		sql_semantic.mx \
		sql_optimize.mx \ 
		sql_rel2bin.mx \
		sql_qc.mx \
		sql_sym.mx \
		sql_symbol.mx \
		sql_scan.mx \   
		sql_parser.mx \  
		sql_mvc.mx \    
		sql_env.mx \    
		sql_sequence.mx \    
		sql_privileges.mx \  
		sql_query.mx \
		sql_list.mx \
		sql_mem.mx

	WINLIBS = ../storage/bat/libbatstore ../common/libsqlcommon -lbat -lmonet -lstream -l_streams -l_bat -l_kernel -l_ascii_io -l_algebra 
	LIBS = $(MONETDB_LIBS)
}

