## Process this file with automake to produce Makefile.in

INCLUDES = $(MONET_INCS)

YFLAGS = -d -p sql -v

lib_sqlserver = {
	NOINST
	DIR = libdir
	SOURCES = \
		sql_atom.mx \
		sql_datetime.mx \
		sql_string.mx \
		sql_decimal.mx \
		sql_scope.mx \
		sql_types.mx \
		sql_statement.mx \
		sql_semantic.mx \
		sql_optimize.mx \ 
		sql_rel2bin.mx \
		sql_qc.mx \
		sql_sym.mx \
		sql_symbol.mx \
		sql_scan.mx \   
		sql_parser.mx \  
		sql_bm.mx \ 
		sql_logger.mx \      
		sql_mvc.mx \    
		sql_privileges.mx \  
		sql_backend.mx \
		sql_query.mx \
		sql_list.mx \
		sql_mem.mx

	WINLIBS = -lbat -lmonet -lstream -l_streams -l_kernel -l_ascii_io -l_algebra 
	LIBS = $(MONET_LIBS)
}

