# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

SUBDIRS = UDF ENABLE_DATACELL?datacell

# force sql.o to not depend on .../rdf/rdf.h since it only optionally created
RDF_INC = -I../../../monetdb5/extras/rdf

INCLUDES = ../../include ../../common ../../storage ../../server \
		   ../../../monetdb5/misc \
		   ../../../monetdb5/modules/atoms \
		   ../../../monetdb5/modules/kernel \
		   ../../../monetdb5/mal \
		   ../../../monetdb5/modules/mal \
		   ../../../monetdb5/optimizer \
		   ../../../monetdb5/scheduler \
		   ../../../clients/mapilib \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   $(RDF_INC) \
		   $(READLINE_INCS)

lib__sql = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = \
		sql.mx \
		sql_user.c sql_user.h \
		sql_scenario.c sql_scenario.h \
		sql_gencode.c sql_gencode.h \
		sql_optimizer.c sql_optimizer.h \
		sql_result.mx \
		sql_readline.c sql_readline.h \
		sql_emptyset.c sql_emptyset.h
	LIBS = ../../server/libsqlserver \
		   ../../storage/libstore \
		   ../../storage/bat/libbatstore \
		   ../../storage/restrict/librestrictstore \
		   ../../common/libsqlcommon \
		   HAVE_RAPTOR?../../../monetdb5/extras/rdf/librdf \
		   ../../../monetdb5/tools/libmonetdb5 \
		   ../../../gdk/libbat \
		   ../../../common/stream/libstream \
		   $(READLINE_LIBS) $(PTHREAD_LIBS) \
		   $(raptor_LIBS)
}


# embedded is disabled, but keep building instructions for the moment we
# like to revive this or someone whould like to build this for some reason
#
#lib_embeddedsql5 = {
#	SOURCES = embeddedclient.c.in
#	LIBS = ../../server/libsqlserver \
#		   ../../storage/libstore \
#		   ../../storage/bat/libbatstore \
#		   ../../storage/restrict/librestrictstore \
#		   ../../common/libsqlcommon \
#		   ../../../monetdb5/tools/libmonetdb5 \
#		   ../../../gdk/libbat \
#		   ../../../clients/mapilib/libmapi \
#		   ../../../common/stream/libstream \
#		   $(READLINE_LIBS) $(PTHREAD_LIBS)
#}
#
#bin_mbeddedsql5 = {
#	SOURCES = prog.c
#	LIBS = libembeddedsql5 \
#		   ../../server/libsqlserver \
#		   ../../storage/libstore \
#		   ../../storage/bat/libbatstore \
#		   ../../storage/restrict/librestrictstore \
#		   ../../common/libsqlcommon \
#		   ../../../monetdb5/tools/libmonetdb5 \
#		   ../../../gdk/libbat \
#		   ../../../clients/mapilib/libmapi \
#		   ../../../common/stream/libstream \
#		   $(READLINE_LIBS) $(PTHREAD_LIBS) $(curl_LIBS)
#}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = sql.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 40_sql.mal
}

EXTRA_DIST = 40_sql.mal
EXTRA_DIST_DIR = Tests
