# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

SUBDIRS = NOT_WIN32?vaults UDF LSST HAVE_GSL?gsl generator

INCLUDES = ../../include ../../common ../../storage ../../server \
		   ../../../monetdb5/modules/atoms \
		   ../../../monetdb5/modules/kernel \
		   ../../../monetdb5/mal \
		   ../../../monetdb5/modules/mal \
		   ../../../monetdb5/optimizer \
		   ../../../monetdb5/scheduler \
		   ../../../monetdb5/extras/rapi \
		   ../../../clients/mapilib \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../gdk \
		   $(READLINE_INCS)

lib__sql = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = \
		sql.c sql.h \
		mal_backend.c mal_backend.h \
		sql_user.c sql_user.h \
		sql_scenario.c sql_scenario.h \
		sql_execute.c sql_execute.h \
		sql_assert.c sql_assert.h \
		sql_upgrades.c sql_upgrades.h \
		rel_bin.c rel_bin.h \
		sql_statement.c sql_statement.h \
		sql_statistics.c sql_statistics.h \
		sql_gencode.c sql_gencode.h \
		sql_optimizer.c sql_optimizer.h \
		sql_result.c sql_result.h \
		sql_readline.c sql_readline.h \
		sql_cast.c sql_cast.h \
		sql_cast_impl_down_from_flt.h \
		sql_cast_impl_down_from_int.h \
		sql_cast_impl_up_to_flt.h \
		sql_cast_impl_up_to_int.h \
		sql_round.c sql_round_impl.h sql_bat2time.c \
		sql_fround.c sql_fround_impl.h \
		sql_rank.c sql_rank.h
	LIBS = ../../server/libsqlserver \
		   ../../storage/libstore \
		   ../../storage/bat/libbatstore \
		   ../../common/libsqlcommon \
 		   ../../../monetdb5/tools/libmonetdb5 \
		   ../../../gdk/libbat \
		   ../../../common/stream/libstream \
		   ../../../common/utils/libmcrypt \
		   $(READLINE_LIBS) $(PTHREAD_LIBS) \
		   $(openssl_LIBS) $(MATH_LIBS)
}


# embedded is disabled, but keep building instructions for the moment we
# like to revive this or someone whould like to build this for some reason
#
#lib_embeddedsql5 = {
#	SOURCES = embeddedclient.c.in
#	LIBS = ../../server/libsqlserver \
#		   ../../storage/libstore \
#		   ../../storage/bat/libbatstore \
#		   ../../common/libsqlcommon \
#		   ../../../monetdb5/tools/libmonetdb5 \
#		   ../../../gdk/libbat \
#		   ../../../clients/mapilib/libmapi \
#		   ../../../common/stream/libstream \
#		   $(READLINE_LIBS) $(PTHREAD_LIBS)
#}
#
#bin_mbeddedsql5 = {
#	SOURCES = prog.c
#	LIBS = libembeddedsql5 \
#		   ../../server/libsqlserver \
#		   ../../storage/libstore \
#		   ../../storage/bat/libbatstore \
#		   ../../common/libsqlcommon \
#		   ../../../monetdb5/tools/libmonetdb5 \
#		   ../../../gdk/libbat \
#		   ../../../clients/mapilib/libmapi \
#		   ../../../common/stream/libstream \
#		   $(READLINE_LIBS) $(PTHREAD_LIBS) $(curl_LIBS)
#}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = sql_aggr_bte.mal  sql_aggr_flt.mal sql_aggr_dbl.mal  sql_aggr_int.mal  sql_aggr_lng.mal \
		sql_aggr_sht.mal  sql_aggr_wrd.mal  sql_decimal.mal  sql_inspect.mal \
		sql_rank.mal sql.mal 
}

headers_mal_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = sql_hge.mal sql_aggr_hge.mal sql_decimal_hge.mal
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 40_sql.mal
}

headers_autoload_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 41_sql_hge.mal
}

EXTRA_DIST = 40_sql.mal \
	41_sql_hge.mal sql_hge.mal sql_aggr_hge.mal sql_decimal_hge.mal \
	sql_aggr_bte.mal  sql_aggr_flt.mal  sql_aggr_int.mal  sql_aggr_lng.mal \
	sql_aggr_sht.mal  sql_aggr_wrd.mal  sql_decimal.mal  sql_inspect.mal \
	sql_rank.mal sql.mal 

EXTRA_DIST_DIR = Tests
