# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

## Process this file with automake to produce Makefile.in

INCLUDES = ../include ../common ../storage \
		   ../../monetdb5/mal \
		   ../../monetdb5/extras/rapi \
		   ../../clients/mapilib \
		   ../../common/options \
		   ../../common/stream \
		   ../../gdk

AM_YFLAGS = -d -p sql

lib_sqlserver = {
	NOINST
	DIR = libdir
	SOURCES = \
		sql_atom.c \
		sql_datetime.c \
		sql_decimal.c \
		sql_semantic.c \
		sql_qc.c \
		sql_symbol.c \
		sql_scan.c \
		sql_parser.y \
		sql_mvc.c \
		sql_env.c \
		sql_privileges.c \
		rel_semantic.c \
		rel_select.c \
		rel_updates.c \
		rel_trans.c \
		rel_schema.c \
		rel_sequence.c \
		rel_prop.c \
		rel_exp.c \
		rel_optimizer.c \
		rel_planner.c rel_planner.h \
		rel_distribute.c \
		rel_remote.c rel_remote.h \
		rel_psm.c \
		rel_xml.c \
		rel_dump.c \
		rel_dump.h rel_exp.h \
		rel_optimizer.h rel_distribute.h rel_prop.h rel_schema.h rel_select.h \
		rel_semantic.h rel_sequence.h rel_trans.h \
		rel_updates.h rel_psm.h rel_xml.h sql_atom.h sql_datetime.h \
		sql_decimal.h sql_env.h sql_mvc.h sql_parser.h \
		sql_privileges.h sql_qc.h sql_scan.h \
		sql_semantic.h sql_symbol.h
}
