# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

# In some cases, there is a (possibly) uninitialized variable in
# bison.simple ... |-(
# However, gcc-2.9-aix51-020209 on SARA's solo seems to ignore
# "-Wno-uninitialized"; hence, we switch-off "-Werror" by disabling X_CFLAGS
# locally in src/monet/Makefile.ag:
# @NO_X_CFLAGS@ with NO_X_CFLAGS='X_CFLAGS' generates "X_CFLAGS =" in the
# generated Makefile.

@NO_X_CFLAGS@

INCLUDES = $(MONETDB_CFLAGS)

YFLAGS = -d

MTSAFE

lib_monet = { 
	SOURCES = \
		monet.mx monet_interpreter.mx monet_queue.mx yytree.mx \
		monet_client.mx monet_multiplex.mx monet_tbl.mx \
		monet_context.mx monet_parse.mx monet_deparse.mx \
		monet_process.mx monet.feps
	HEADERS = h tab.h
	LIBS = $(MONETDB_LIBS) -lmutils -lstream -lbat \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)

}

EXTRA_DIST = monet_tem.mx 
EXTRA_DIST_DIR = Tests
