#!/bin/sh
./gcol elapuser 
awk -f column  <o >o1
./gcol elapsys 
awk -f column  <o >o2
./gcol inblock
awk -f column  <o >o3
./gcol oublock
awk -f column  <o >o4
./gcol majflt
awk -f column  <o >o5
./gcol ninvcsw
awk -f column  <o >o6
./gcol elapsed
awk -f column  <o >o7

pr -mt o1 o2 o3 o4 o5 o6 o7>s
rm -f o o[12345678]
echo '#~BeginVariableOutput~#'
cat s
## StM: replaced "ex" by "cat"
#ex - s <<!EOF
#f
#g/'/s///g
#g/\]/s// /g
#g/\[/s// /g
#g/^$/d
#1,$p
#w
#q
#!EOF
#echo ''
echo '#~EndVariableOutput~#'
