# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

INCLUDES = -I../../monet -I../plain \
	$(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS) \
	$(NETCDF_CFLAGS)
MTSAFE

LIB_mnetcdf = {
	DIR = libdir/MonetDB4
	SEP = _
	COND = HAVE_NETCDF
	SOURCES = mnetcdf.mx 
	HEADERS = h proto.h m
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet ../plain/lib_algebra \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
		$(NETCDF_LIBS) $(MATH_LIBS)
}

HEADERS_mnetcdf = {
	DIR = includedir/MonetDB4/mnetcdf
	COND = HAVE_NETCDF
	SOURCES = mnetcdf.mx 
	HEADERS = h proto.h m
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/MonetDB4
	COND = HAVE_NETCDF
	SOURCES = mnetcdf.mx 
}

EXTRA_DIST_DIR = Tests
