# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

man_MANS = monetdbd.1

monetdb_var_logdir = $(logdir)
monetdb_var_log_DATA = 
monetdb_var_rundir = $(rundir)
monetdb_var_run_DATA = 
monetdb_var_dbfarmdir = $(localstatedir)/monetdb5/dbfarm
monetdb_var_dbfarm_DATA = .merovingian_properties
monetdb_etc_systemddir = $(prefix)/lib/systemd/system
monetdb_etc_systemd_DATA = monetdbd.service

INCLUDES = .. \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../common/options \
		   ../../../clients/mapilib \
		   ../../../gdk \
		   ../../../monetdb5/mal \
		   $(MSGCONTROL_FLAGS)

EXTRA_DIST = monetdbd.1.in .merovingian_properties.in monetdbd.service.in

bin_monetdbd = {
	SOURCES = \
			  merovingian.c merovingian.h \
			  argvcmds.c argvcmds.h \
			  client.c client.h \
			  connections.c connections.h \
			  controlrunner.c controlrunner.h \
			  discoveryrunner.c discoveryrunner.h \
			  forkmserver.c forkmserver.h \
			  handlers.c handlers.h \
			  multiplex-funnel.c multiplex-funnel.h \
			  proxy.c proxy.h
	LIBS = ../utils/libmeroutil \
		   ../../../common/stream/libstream \
		   ../../../clients/mapilib/libmapi \
		   ../../../common/utils/libmcrypt \
		   ../../../common/utils/libmsabaoth \
		   ../../../common/utils/libmuuid \
		   ../../../common/utils/libmutils \
		   ../../../monetdb5/tools/libmonetdb5 \
		   ../../../gdk/libbat \
		   $(UUID_LIBS) \
		   $(openssl_LIBS) \
		   $(curl_LIBS) \
		   $(SOCKET_LIBS) \
		   $(MALLOC_LIBS) \
		   $(PTHREAD_LIBS)
}
