# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

man_MANS = monetdbd.1

monetdb_var_logdir = $(logdir)
monetdb_var_log_DATA = 
monetdb_var_rundir = $(rundir)
monetdb_var_run_DATA = 
monetdb_var_dbfarmdir = $(localstatedir)/monetdb5/dbfarm
monetdb_var_dbfarm_DATA = .merovingian_properties

# MONETDB5: Sabaoth
INCLUDES = .. \
		   ../../../monetdb5/misc \
		   ../../../common/stream \
		   ../../../common/utils \
		   ../../../clients/mapilib \
		   $(MSGCONTROL_FLAGS)

EXTRA_DIST = $(man_MANS) .merovingian_properties

bin_monetdbd = {
	# hack: include monetdbd.1.in and .merovingian_properties.in here to
	#       get them expanded
	SOURCES = monetdbd.1.in .merovingian_properties.in \
			  merovingian.c merovingian.h \
			  argvcmds.c argvcmds.h \
			  client.c client.h \
			  connections.c connections.h \
			  controlrunner.c controlrunner.h \
			  discoveryrunner.c discoveryrunner.h \
			  forkmserver.c forkmserver.h \
			  handlers.c handlers.h \
			  multiplex-funnel.c multiplex-funnel.h \
			  peering.c peering.h \
			  proxy.c proxy.h
	LIBS = ../utils/libmeroutil \
		   ../../../monetdb5/misc/libsabaoth \
		   ../../../common/stream/libstream \
		   ../../../clients/mapilib/libmapi \
		   ../../../common/utils/libmutils \
		   $(UUID_LIBS) \
		   $(curl_LIBS) \
		   $(SOCKET_LIBS) \
		   $(MALLOC_LIBS) \
		   $(PTHREAD_LIBS)
}
