# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

man_MANS = monetdb5.conf.5

EXTRA_DIST = monetdb5.conf.in $(man_MANS)

INCLUDES = ../../gdk

lib_sabaoth = {
	NOINST
	SOURCES = msabaoth.h msabaoth.c
}

headers_conf = {
	HEADERS = conf
	DIR = sysconfdir
	SOURCES = monetdb5.conf
}

monetdb_var_logdir = $(localstatedir)/log/monetdb
monetdb_var_log_DATA = 
monetdb_var_rundir = $(localstatedir)/run/monetdb
monetdb_var_run_DATA = 
monetdb_var_dbfarmdir = $(localstatedir)/monetdb5/dbfarm
monetdb_var_dbfarm_DATA = 
