# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

EXTRA_DIST = Mtest.py.in Mtest.py.bat Mlog.in Mlog.bat Mfilter.py.in \
	     MkillUsers.in testing_getopt.c

bin_Mdiff = {
	SOURCES = difflib.c helpers.c Mdiff.c difflib.h  helpers.h
	LIBS = $(MALLOC_LIBS)
}

bin_Mtimeout = {
	SOURCES = Mtimeout.c
	COND = NOT_WIN32
}

bin_Mapprove.py = bin_Mtest.py
bin_Mapprove.py.bat = NATIVE_WIN32?bin_Mtest.py.bat

scripts_bat = {
	COND = NATIVE_WIN32
	DIR = bindir
	SOURCES = Mlog.bat Mtest.py.bat
}

scripts_py = {
	DIR = bindir
	SOURCES = Mtest.py Mfilter.py 
}

headers_python = {
	HEADERS = py
	DIR = $(prefix)/$(PYTHON_LIBDIR)/MonetDBtesting
	SOURCES = trace.py process.py monet_options.py.in __init__.py subprocess26.py
}

scripts_sh = {
	COND = NOT_WIN32
	EXT = ""
	DIR = bindir
	SOURCES = Mlog MkillUsers
}
