create sequence seq as int;
select get_value_for('sys','seq');
select get_value_for('sys','seq');
select next_value_for('sys','seq');
select next_value_for('sys','seq');
select get_value_for('sys','seq');
select get_value_for('sys','seq');
select next_value_for('sys','seq');
select get_value_for('sys','seq');
SELECT NEXT VALUE FOR sys.seq;
select get_value_for('sys','seq');
drop sequence seq;

start transaction;
create sequence seq as int;
select get_value_for('sys','seq');
select get_value_for('sys','seq');
select next_value_for('sys','seq');
select next_value_for('sys','seq');
select get_value_for('sys','seq');
select get_value_for('sys','seq');
select next_value_for('sys','seq');
select get_value_for('sys','seq');
SELECT NEXT VALUE FOR sys.seq;
select get_value_for('sys','seq');
rollback;
