
INCLUDES = -I$(MONET_BUILD)/src/gdk -I$(MONET_BUILD)/src/monet \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS)
MTSAFE

# install these libs in the pkglib
LIBDIR = pkglib

LIBS = {
	SEP = _
	SOURCES = \
		aggr.mx alarm.mx algebra.mx arith.mx bat.mx bitset.mx \
		bitvector.mx blob.mx cluster.mx  ddbench.mx \
		decimal.mx enum.mx io.mx iterator.mx kernel.mx lock.mx \
		malalgebra.mx mmath.mx monettime.mx mprof.mx oo7.mx \
		perfex.mx qt.mx radix.mx salgebra.mx stats.mx str.mx \
		sys.mx tcpip.mx  tpcd.mx trans.mx uchr.mx \
		unix.mx url.mx vector.mx wisc.mx xtables.mx logger.mx
	HEADERS = h proto.h m
	SCRIPTS = mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)

}

lib_stream  =  {
	SOURCES = stream.mx
	HEADERS = h
	LIBS = \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS)
}

lib__streams = {
	SOURCES = streams.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet ./libstream \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

lib__ascii_io = {
	SOURCES = ascii_io.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet ./libstream ./lib_streams
}

lib__counters = {
	SOURCES = counters.mx
	HEADERS = h proto.h m
	SCRIPTS = mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(HWCOUNTERS_LIBS)
}


EXTRA_DIST_DIR = Tests
