
INCLUDES = top_builddir/src/gdk top_builddir/src/monet
MTSAFE

MODS = {
	SOURCES = \
		aggr.mx alarm.mx algebra.mx arith.mx bat.mx bitset.mx \
		bitvector.mx blob.mx cluster.mx counters.mx ddbench.mx \
		decimal.mx enum.mx io.mx iterator.mx kernel.mx lock.mx \
		malalgebra.mx mmath.mx monettime.mx mprof.mx oo7.mx \
		perfex.mx qt.mx radix.mx salgebra.mx stats.mx str.mx \
		sys.mx tcpip.mx temporal.mx tpcd.mx trans.mx uchr.mx \
		unix.mx url.mx vector.mx wisc.mx xtables.mx
	HEADERS = h m
	SCRIPTS = mil
}
