# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.

INCLUDES = -I../../common -I../../gdk -I../../monet \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS) $(PCRE_CFLAGS)
MTSAFE

lib__streams = {
	DIR = pkglibdir
	SOURCES = streams.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
}

lib__str = {
	DIR = pkglibdir
	SEP = _
	SOURCES = str.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
	LIBS	= $(ICONV_LIBS)
}

#doc__str = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = str.mx
#}

lib__xtables = {
	DIR = pkglibdir
	SEP = _
	SOURCES = xtables.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet ./lib_algebra \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

#doc_xtables = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = xtables.mx
#}

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		algebra.mx arith.mx bat.mx kernel.mx sys.mx trans.mx \
		mkey.mx profiler.mx \
		aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx blob.mx \
		decimal.mx enum.mx lock.mx mmath.mx monettime.mx \
		radix.mx stats.mx tcpip.mx unix.mx url.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
	LDFLAGS = -lm
}

#doc_libs = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = \
#		algebra.mx arith.mx bat.mx kernel.mx sys.mx trans.mx \
#		mkey.mx profiler.mx \
#		aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx blob.mx \
#		decimal.mx enum.mx lock.mx mmath.mx monettime.mx \
#		radix.mx stats.mx tcpip.mx unix.mx url.mx
#}

lib__counters = {
	DIR = pkglibdir
	SOURCES = counters.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
	LIBS = $(HWCOUNTERS_LIBS)
}

#doc__counters = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = counters.mx
#}

lib__pcl = {
	DIR = pkglibdir
	SOURCES = pcl.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
	LIBS = $(PCL_LIBS)
}

#doc__pcl = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = pcl.mx
#}

lib__pcre = {
	DIR = pkglibdir
	SOURCES = pcre.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
	LIBS = $(PCRE_LIBS)
}

#doc__pcre = {
#	DIR = pkgdatadir/docs/plain/
#	SOURCES = pcre.mx
#}

scripts_mil = {
	DIR = pkglibdir
	SOURCES = streams.mx str.mx xtables.mx \
         	algebra.mx arith.mx bat.mx kernel.mx sys.mx trans.mx \
                mkey.mx profiler.mx \
                aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx \
		blob.mx decimal.mx enum.mx lock.mx mmath.mx \
		monettime.mx radix.mx stats.mx tcpip.mx \
		unix.mx url.mx counters.mx pcl.mx pcre.mx
}

EXTRA_DIST_DIR = Tests
