#!/bin/bash

#Warning experimental code, only works for me :-)

echo "MCC compiler called for" $1
base=`basename $1 .c`
echo "Result available as " $base

gcc -DHAVE_CONFIG_H -c $1 -I. \
     -I../.. -I/ufs/mk/monet5/src/mal \
     -I/ufs/mk/monet5/Linux/src/modules/mal \
     -I/ufs/mk/monet5/Linux/src/modules/kernel \
     -I/ufs/mk/monet5/Linux/src/modules/atoms \
    -I/ufs/mk/monet5/Linux/include/MonetDB5/mal \
    -I/ufs/mk/monet5/Linux/lib/MonetDB5/ \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/common \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/gdk \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/monet \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/plain \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/contrib \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/mapi \
    -I/ufs/mk/opensource/MonetDB/Linux/include/MonetDB/C \
    -g -O2 -DHWCOUNTERS -DHW_Linux -DHW_i686 \
    -D_REENTRANT -fPIC -DPIC 
    # -g -O2 -std=c99 -Wall -W -DHWCOUNTERS -DHW_Linux -DHW_i686 \
    # -Wno-sign-compare -D_REENTRANT -fPIC -DPIC 
    # -Werror-implicit-function-declaration -Werror -Wno-format \
    #-Wno-unused-function -Wno-unused-label -Wno-strict-aliasing \

echo "Program is ready to be linked"
