#!/bin/bash

DBFARM=$PWD/dbfarm
DBNAME=test
MSERVER="Mtimeout -timeout 123 mserver --dbfarm=$DBFARM --dbname=$DBNAME -c All.conf --set monet_prompt= --trace"

echo "Initialize database"
rm -rf $DBFARM/$DBNAME
echo 'quit();' | $MSERVER

mkdir -p test_out_err
for f in  `ls tst*.mal`
do
	b=`basename $f .mal`
	s=$b.stable
	t=test_out_err/$b.test
	echo "---->" $f $b $s $t
	echo "stdout of test '$b\` in directory 'src/mal\` itself:" > $t.out
	echo "stderr of test '$b\` in directory 'src/mal\` itself:" > $t.err
	$MSERVER $f </dev/null >> $t.out 2>> $t.err
	diff -I'^# [Cc]ompiled for ' -I'^# config:' -I'^# dbfarm:' -I'^# dbname:' $t.out $s.out
	diff -I'^# [Cc]ompiled for ' -I'^# config:' -I'^# dbfarm:' -I'^# dbname:' $t.err $s.err
done
