#!/bin/bash

#DBFARM=$PWD/dbfarm
DBFARM=/ufs/mk/monet5/Linux/var/MonetDB/dbfarm
DBNAME=test
#MSERVER="Mtimeout -timeout 123 mserver --dbfarm=$DBFARM --dbname=$DBNAME -c All.conf --set monet_prompt= --trace"
MSERVER="valgrind  --leak-check=full --show-reachable=yes --num-callers=20 mserver5 --dbfarm=$DBFARM --dbname=$DBNAME --set monet_prompt= --trace"

echo "Initialize database"
rm -rf $DBFARM/$DBNAME
echo 'clients.quit();' | $MSERVER

mkdir -p test_out_err
for f in  `ls tst*.mal`
do
	b=`basename $f .mal`
	s=$b.stable
	t=test_out_err/$b.test
	echo "---->" $f $b $s $t
	echo "stdout of test '$b\` in directory 'src/mal\` itself:" > $t.out
	echo "stderr of test '$b\` in directory 'src/mal\` itself:" > $t.err
	echo $MSERVER $f
	$MSERVER $f </dev/null >> $t.valgrind.out 2>> $t.valgrind.err |tee $t.valgrind.out 
	#diff -I'^# [Cc]ompiled for ' -I'^# config:' -I'^# dbfarm:' -I'^# dbname:' $t.out $s.out
	#diff -I'^# [Cc]ompiled for ' -I'^# config:' -I'^# dbfarm:' -I'^# dbname:' $t.err $s.err
done
