#!/bin/bash
echo "Initialize database"
rm -rf /usr/mk/Linux/var/MonetDB/demo/*

for f in  `ls tst???.mal tst1???.mal tst2???.mal tst3???.mal`
do
	echo "---->" $f
	Mserver -c tst.conf $f </dev/null > `basename $f .mal`.output 
	diff `basename $f .mal`.output `basename $f .mal`.stable
done
