#!/bin/bash
echo "Initialize database"
rm -rf /usr/mk/Linux/var/dbfarm/demo/*

for f in  `ls tst??? tst1??? tst2??? tst3???`
do
	echo "---->" $f
	valgrind Mserver -c tst.conf $f </dev/null > $f.valgrind.output
	diff $f.output $f.stable
done
