#!/bin/bash

DBFARM=$PWD/dbfarm
DBNAME=test
MSERVER="Mserver --dbfarm=$DBFARM --dbname=$DBNAME -c All.conf --set monet_prompt= --trace"

echo "Initialize database"
rm -rf $DBFARM/$DBNAME
echo 'quit();' | $MSERVER

mkdir -p test_out_err
for f in  `ls tst*.mal`
do
	b=`basename $f .mal`
	s=$b.stable
	t=test_out_err/$b.valgrind
	echo "---->" $f $b $s $t
	echo "stdout of test '$b\` in directory 'src/mal\` itself:" > $b.test.out
	echo "stderr of test '$b\` in directory 'src/mal\` itself:" > $b.test.err
	valgrind $MSERVER $f </dev/null >> $t.out 2>> $t.err
	diff $t.out $s.out
	diff $t.err $s.err
done
