# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

MTSAFE

SWIGFLAGS = -I../../mapilib
INCLUDES = ../../mapilib $(MONETDB_CFLAGS) @PHP_INCS@

# we need this flag to allow for a name that does not start with "lib"
monetdb_la_LDFLAGS = -module

# with gcc we could use these
#X_CFLAGS = -Wno-unused-parameter -Wno-unused-function
# but we certainly have to override the default X_CFLAGS:
X_CFLAGS = -DCOMPILE_DL_MONETDB=1 -D_GNU_SOURCE

SUBDIRS = HAVE_PEAR?DB examples 

lib_monetdb = {
	PREFIX =
	NAME = monetdb
	SOURCES = php_monetdb.h php_monetdb.c
	LIBS = ../../mapilib/libMapi $(MAPI_LIBS) $(PHP_LIBS)
	DIR = $(prefix)/$(PHP_EXTENSIONDIR)
}
