#!/bin/sh

pwd=`pwd`

if [ $# -lt 1 ]; then
	echo "sql file missing"
	echo "usage: Msql file.sql"
	exit 1
fi

f=$1;

if [ ! -f "/$f" ]; then
	if [ ! -f "$pwd/$f" ]; then
		echo "/$f and $pwd/$f not found"
		exit 1
	else
		f="$pwd/$f"
	fi
fi

MapiClient <<EOF
sql("$f", "/tmp/$USER-sql.mil", 0);
EOF
echo "commit();" >> /tmp/$USER-sql.mil

MapiClient <<EOF
source("/tmp/$USER-sql.mil");
EOF

#rm -f /tmp/$USER-sql.mil
