# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../../include \
		   ../../../common \
		   ../../../storage \
		   ../../../server .. \
		   ../../../../monetdb5/modules/atoms \
		   ../../../../monetdb5/modules/kernel \
		   ../../../../monetdb5/mal \
		   ../../../../monetdb5/modules/mal \
		   ../../../../monetdb5/optimizer \
		   ../../../../monetdb5/scheduler \
		   ../../../../clients/mapilib \
		   ../../../../common/options \
		   ../../../../common/stream \
		   ../../../../common/utils \
		   ../../../../gdk \
		   $(READLINE_INCS) $(MSEED_CFLAGS) $(cfitsio_CFLAGS) $(curl_CFLAGS)

lib__vault = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = vault.mx
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		   ../../../../gdk/libbat $(curl_LIBS)
}

lib__mseed = {
	MODULE
	COND = HAVE_MSEED
	DIR = libdir/monetdb5
	SOURCES = mseed.mx
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		   ../../../../gdk/libbat \
		   $(MSEED_LIBS) 
}

lib__fits = {
	MODULE
	COND = HAVE_CFITSIO
	DIR = libdir/monetdb5
	SOURCES = fits.mx
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		   $(cfitsio_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = vault.mx
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = vault.mx
}

headers_mseedmal = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = mseed.mx
}

headers_fitsmal = {
	COND = HAVE_CFITSIO
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = fits.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 70_vault.mal
}

headers_mseedautoload = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 71_mseed.mal
}

headers_fitsautoload = {
    COND = HAVE_CFITSIO
    HEADERS = mal
    DIR = libdir/monetdb5/autoload
    SOURCES = 72_fits.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 70_vault.mal 71_mseed.mal 72_fits.mal
