# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

SUBDIRS = HAVE_SAMTOOLS?bam HAVE_FITS?fits HAVE_LIDAR?lidar HAVE_NETCDF?netcdf HAVE_SHP?shp

INCLUDES = ../../../include \
	   ../../../common \
	   ../../../storage \
	   ../../../server .. \
	   ../../../../monetdb5/modules/atoms \
	   ../../../../monetdb5/modules/kernel \
	   ../../../../monetdb5/mal \
	   ../../../../monetdb5/modules/mal \
	   ../../../../monetdb5/optimizer \
	   ../../../../monetdb5/scheduler \
	   ../../../../common/options \
	   ../../../../common/stream \
	   ../../../../common/utils \
	   ../../../../gdk

lib__vault = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = vault.c vault.h
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
	       ../../../../gdk/libbat $(curl_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = vault.mal
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = vault.sql
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 70_vault.mal
}

EXTRA_DIST_DIR = Tests
