# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

## Process this file with automake to produce Makefile.in

INCLUDES = .. ../include ../storage \
		   ../../common/options \
		   ../../common/stream \
		   ../../monetdb5/mal \
		   ../../gdk

lib_sqlcommon = {
	NOINST
	DIR = libdir
	SOURCES = \
		sql_mem.c sql_list.c sql_hash.c sql_stack.c sql_backend.c \
		sql_keyword.c sql_changeset.c sql_types.c sql_string.c \
		sql_backend.h sql_string.h sql_types.h
}
