# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

## Process this file with automake to produce Makefile.in

INCLUDES = .. ../include ../storage \
		   ../../common/options \
		   ../../common/stream \
		   ../../gdk

lib_sqlcommon = {
	NOINST
	DIR = libdir
	SOURCES = \
		sql_mem.c sql_list.c sql_stack.c sql_backend.c \
		sql_keyword.c sql_changeset.c sql_types.c sql_string.c \
		sql_backend.h sql_string.h sql_types.h
}
