# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

MTSAFE
INCLUDES = ../../mapilib ../../../common/options $(READLINE_INCS)

MAPI_LIBS = $(SOCKET_LIBS) 

BINS = {
	CONDINST = HAVE_TESTING
	DIR = bindir
	SOURCES = sample0.c sample1.c sample4.c \
		smack00.c smack01.c
	LIBS = $(MAPI_LIBS) ../../mapilib/libmapi \
		$(curl_LIBS)
}
