# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE
INCLUDES = ../../mapilib ../../../common/options $(READLINE_INCS)

MAPI_LIBS = $(SOCKET_LIBS) 

BINS = {
	CONDINST = HAVE_TESTING
	DIR = bindir
	SOURCES = sample0.c sample1.c sample2.c sample3.c sample4.c \
		smack00.c smack01.c
	LIBS = $(MAPI_LIBS) ../../mapilib/libmapi \
		$(curl_LIBS)
}
