-- use the [size] shortcut for integer type dimensions
CREATE ARRAY ary(x TINYINT DIMENSION[4], y BIGINT DIMENSION[-5], v FLOAT DEFAULT 3.7);
SELECT * FROM ary;

CREATE ARRAY ary1(x TINYINT DIMENSION, y BIGINT DIMENSION, v FLOAT DEFAULT 3.7);
SELECT * FROM ary1;

CREATE ARRAY ary2(x TINYINT DIMENSION[4], y BIGINT DIMENSION, z BIGINT DIMENSION[-5], v FLOAT DEFAULT 3.7);
SELECT * FROM ary2;

SELECT * FROM _tables WHERE type = 7 OR fixed_array = TRUE;

DROP ARRAY ary;
DROP ARRAY ary1;
DROP ARRAY ary2;

