CREATE ARRAY matrix (x INT DIMENSION[4], y INT DIMENSION[4], v FLOAT DEFAULT 0.0);
CREATE ARRAY stripes (x INT DIMENSION[4], y INT DIMENSION[4] CHECK(MOD(y,2) = 1), v FLOAT DEFAULT 0.0);
SELECT * FROM matrix;
SELECT * FROM stripes;
INSERT INTO matrix(v) SELECT v FROM stripes;
SELECT * FROM matrix;
DROP ARRAY matrix;
DROP ARRAY stripes;

