CREATE ARRAY matrix_0403 (x INT DIMENSION[4], y INT DIMENSION[4], v FLOAT DEFAULT 0.0);
CREATE ARRAY stripes (x INT DIMENSION[4], y INT DIMENSION[4] CHECK(MOD(y,2) = 1), v FLOAT DEFAULT 6.6);
SELECT * FROM matrix_0403;
SELECT * FROM stripes;
INSERT INTO matrix_0403(v) SELECT v FROM stripes;
SELECT * FROM matrix_0403;
DROP ARRAY matrix_0403;
DROP ARRAY stripes;

