create array a (x int dimension[4], y int dimension[4], v tinyint);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;
create array a (x int dimension[4], y int dimension[4], v smallint);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;
create array a (x int dimension[4], y int dimension[4], v integer);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;
create array a (x int dimension[4], y int dimension[4], v bigint);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;
create array a (x int dimension[4], y int dimension[4], v real);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;
create array a (x int dimension[4], y int dimension[4], v double);
insert into a select x, y, x * 4 + y from a;
select * from a;
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[x-1:x+2][*];
select x, y, sum(v), avg(v), min(v), max(v), count(v), sum(v), v from a group by a[*][y-2:y+1];
drop array a;

create array aa (x int dimension[4], y int dimension[4], v1 tinyint, v2 tinyint);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;
create array aa (x int dimension[4], y int dimension[4], v1 smallint, v2 smallint);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;
create array aa (x int dimension[4], y int dimension[4], v1 integer, v2 integer);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;
create array aa (x int dimension[4], y int dimension[4], v1 bigint, v2 bigint);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;
create array aa (x int dimension[4], y int dimension[4], v1 real, v2 real);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;
create array aa (x int dimension[4], y int dimension[4], v1 double, v2 double);
insert into aa select x, y, x * 4 + y, y * 4 + x from aa;
select * from aa;
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[x-1:x+2][*];
select x, y, sum(v1), avg(v1), min(v1), max(v1), count(v1), v1, sum(v2), avg(v2), min(v2), max(v2), count(v2), v2 from aa group by aa[*][y-2:y+1];
drop array aa;

