CREATE ARRAY vmatrix (
  x INTEGER DIMENSION[-1:4],
  y INTEGER DIMENSION[-1:4],
  w FLOAT DEFAULT 0) AS SELECT y, x, v FROM matrix; 

CREATE ARRAY vector (
  x INTEGER DIMENSION[-1:4],
  w FLOAT DEFAULT 0);
SELECT (A.v+B.v)/2 FROM vector AS A JOIN
  (SELECT x+1 AS x, w FROM vector) AS B ON A.x = B.x;

CREATE ARRAY vmatrix (  x INTEGER DIMENSION[-1:4], 
  y INTEGER DIMENSION[-1:4],
  w FLOAT DEFAULT 0) AS
SELECT x-1, y, v FROM matrix WHERE x > 2
UNION SELECT x, y, 0 FROM matrix WHERE x =3;
