all: HowToRelease.html windowsbuild.html

HowToRelease.html: HowToRelease.rst
	rst2html.py HowToRelease.rst > HowToRelease.html

windowsbuild.html: windowsbuild.rst
	rst2html.py windowsbuild.rst > windowsbuild.html
