MTSAFE
INCLUDES = $(MONETDB_INCS) \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS)

LIBS = {
        DIR = pkglibdir
        SEP = _
        SOURCES = mil.mx mil_algebra_procs.mx mil_system_procs.mx \
				mil_insert.mx 

        HEADERS = h 
        SCRIPTS = mal mil ""
}


#doc_mal = {
#	DIR = pkgdatadir/docs/modules/mil
#	SOURCES = mil_schema.mx mil_algebra_procs.mx mil_system_procs.mx
#}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mil.mx mil_algebra_procs.mx mil_system_procs.mx \
		mil_insert.mx 
}

#EXTRA_DIST_DIR = Tests
