MTSAFE
INCLUDES = -I../atoms ../kernel \
        -I../../mal $(MONETDB_INCS) \
        $(Z_CFLAGS) $(BZ_CFLAGS)

#LIBS = {
#        DIR = pkglibdir
#        SEP = _
#        SOURCES = mil_algebra_procs.mx mil_system_procs.mx

#        HEADERS = h 
#        #SCRIPTS = mal mil ""
#}

lib__mil_utils = {
	DIR = pkglibdir
	SOURCES = mil_utils.mx

	HEADERS = h 
	#SCRIPTS = mal mil ""
	LIBS = ../kernel/lib_bat ../../mal/libmal $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

#lib__mil_insert = {
#	DIR = pkglibdir
#	SOURCES = mil_insert.mx

#	HEADERS = h 
#	#SCRIPTS = mal mil ""
#	LIBS = ../kernel/lib_bat ../../mal/libmal $(MONETDB_LIBS) -lbat -lstream \
#                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
#                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
#}


#doc_mal = {
#	DIR = pkgdatadir/docs/modules/mil
#	SOURCES = mil_schema.mx mil_algebra_procs.mx mil_system_procs.mx
#}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mil_utils.mx mil_algebra_procs.mx mil_system_procs.mx 
#		mil_insert.mx 
}

#EXTRA_DIST_DIR = Tests
