# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2014 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../../../monetdb5/mal \
	   ../../../../common/options \
	   ../../../../common/stream \
	   ../../../../common/utils \
	   ../../../../gdk

lib__gsl = {
	MODULE
	COND = HAVE_GSL
	DIR = libdir/monetdb5
	SOURCES = gsl.c
	LIBS = $(gsl_LIBS)
}

headers_gslmal = {
	COND = HAVE_GSL
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = gsl.mal
}

headers_gslautoload = {
    COND = HAVE_GSL
    HEADERS = mal
    DIR = libdir/monetdb5/autoload
    SOURCES = 73_gsl.mal
}

headers_gsl = {
	COND = HAVE_GSL
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 46_gsl.sql
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 73_gsl.mal gsl.mal
