# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = ../../../../monetdb5/mal \
	   ../../../../common/options \
	   ../../../../common/stream \
	   ../../../../common/utils \
	   ../../../../gdk

lib__gsl = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = gsl.c
	LIBS = $(gsl_LIBS)
}

headers_gslmal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = gsl.mal
}

headers_gslautoload = {
    HEADERS = mal
    DIR = libdir/monetdb5/autoload
    SOURCES = 73_gsl.mal
}

headers_gsl = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 46_gsl.sql
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 73_gsl.mal gsl.mal
