#!/bin/sh

NAME="$1"
PRELUDE="$2 $3"

Mlog   "echo 'debugmask(2);' > d2.mil"
        echo 'debugmask(2);' > d2.mil
Mlog   "$MSERVER --dbname=$TSTDB d2.mil Arjen_02.mal"
eval    $MSERVER --dbname=$TSTDB d2.mil Arjen_02.mal
