START TRANSACTION;

DROP VIEW SpecObj ;
DROP VIEW SpecLine ;
DROP VIEW SpecPhoto ;
DROP VIEW Tile ;
DROP VIEW TilingBoundary ;
DROP VIEW TilingMask ;
DROP VIEW TiledTarget ;
DROP VIEW Columns ;
DROP VIEW Run ;
DROP VIEW PhotoSecondary ;
DROP VIEW PhotoFamily ;
DROP VIEW PhotoObj ;
DROP VIEW PhotoAux ;
DROP VIEW PhotoStatus ;
DROP VIEW PrimTarget ;
DROP VIEW SecTarget ;
DROP VIEW InsideMask ;
DROP VIEW SpecZWarning ;
DROP VIEW ImageMask ;
DROP VIEW TiMask ;
DROP VIEW PhotoMode ;
DROP VIEW PhotoType ;
DROP VIEW MaskType ;
DROP VIEW FieldQuality ;
DROP VIEW PspStatus ;
DROP VIEW FramesStatus ;
DROP VIEW SpecClass ;
DROP VIEW SpecLineNames ;
DROP VIEW SpecZStatus ;
DROP VIEW HoleType ;
DROP VIEW ObjType ;
DROP VIEW ProgramType ;
DROP VIEW CoordType ;
DROP VIEW FieldMask ;
DROP VIEW PhotoFlags ;
DROP VIEW Star ;
DROP VIEW Galaxy ;
DROP VIEW Sky ;
DROP VIEW Unknown ;
DROP VIEW PhotoPrimary ;

COMMIT;
