DROP VIEW CoordType;
DROP VIEW FieldMask;
DROP VIEW FieldQuality;
DROP VIEW FramesStatus;
DROP VIEW GalaxyTag;
DROP VIEW HoleType;
DROP VIEW ImageMask;
DROP VIEW InsideMask;
DROP VIEW MaskType;
DROP VIEW ObjType;
DROP VIEW PhotoAux;
DROP VIEW PhotoAuxAll;
DROP VIEW PhotoFamily;
DROP VIEW PhotoFlags;
DROP VIEW PhotoMode;
DROP VIEW PhotoObj;
DROP VIEW Galaxy;
DROP VIEW PhotoSecondary;
DROP VIEW PhotoStatus;
DROP VIEW PhotoType;
DROP VIEW PrimTarget;
DROP VIEW ProgramType;
DROP VIEW PspStatus;
DROP VIEW QsoCatalog;
DROP VIEW QsoConcordance;
DROP VIEW RegionConvex;
DROP VIEW Run;
DROP VIEW SecTarget;
DROP VIEW Sky;
DROP VIEW spbsParams;
DROP VIEW SpecClass;
DROP VIEW SpecLine ;
DROP VIEW SpecLineNames;
DROP VIEW SpecObj ;
DROP VIEW SpecPhoto ;
DROP VIEW SpecZStatus;
DROP VIEW SpecZWarning;
DROP VIEW Star;
DROP VIEW StarTag;
DROP VIEW TargPhotoObj;
DROP VIEW TargPhotoPrimary ;
DROP VIEW TargPhotoSecondary;
DROP VIEW Tile;
DROP VIEW TiledTarget;
DROP VIEW TilingBoundary;
DROP VIEW TilingMask;
DROP VIEW TiMask;
DROP VIEW UberCalibStatus;
DROP VIEW Unknown;
DROP VIEW PhotoPrimary ;
DROP VIEW PhotoTag;
