#!/bin/sh

# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

./gcol elapuser 
awk -f column  <o >o1
./gcol elapsys 
awk -f column  <o >o2
./gcol inblock
awk -f column  <o >o3
./gcol oublock
awk -f column  <o >o4
./gcol majflt
awk -f column  <o >o5
./gcol ninvcsw
awk -f column  <o >o6
./gcol elapsed
awk -f column  <o >o7

pr -mt o1 o2 o3 o4 o5 o6 o7>s
rm -f o o[12345678]
echo '#~BeginVariableOutput~#'
cat s
## StM: replaced "ex" by "cat"
#ex - s <<!EOF
#f
#g/'/s///g
#g/\]/s// /g
#g/\[/s// /g
#g/^$/d
#1,$p
#w
#q
#!EOF
#echo ''
echo '#~EndVariableOutput~#'
