#!/bin/sh

NAME="$1"
PRELUDE="$2 $3"

Mlog   "$MSERVER --dbname=$TSTDB         < $NAME.1.mil"
eval    $MSERVER --dbname=$TSTDB         < $NAME.1.mil
Mlog   "$MSERVER --dbname=$TSTDB         < $NAME.2.mil"
eval    $MSERVER --dbname=$TSTDB         < $NAME.2.mil

