#!/bin/bash

pf -s6 <<'EOT'
(: fn:concat is special in that it allows an arbitrary number
   of arguments. It's thus treated explicitly in functions.c :)
declare function concat($x)
{
    42
};
42
EOT
echo $?
