START TRANSACTION;

CREATE TABLE aap (x int, y int);
INSERT INTO aap VALUES (5,7), (6,9), (11,13), (15,17);

CREATE TABLE test AS SELECT ALL x, y FROM aap ORDER BY x DESC LIMIT 3 WITH DATA;

SELECT * FROM test;

ROLLBACK;
