# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

INCLUDES = ../ \
       ../../ \
       ../../../../include \
	   ../../../../common \
	   ../../../../storage \
	   ../../../../server \
	   ../../../../../monetdb5/modules/atoms \
	   ../../../../../monetdb5/modules/kernel \
	   ../../../../../monetdb5/mal \
	   ../../../../../monetdb5/modules/mal \
	   ../../../../../monetdb5/optimizer \
	   ../../../../../monetdb5/scheduler \
	   ../../../../../clients/mapilib \
	   ../../../../../common/options \
	   ../../../../../common/stream \
	   ../../../../../common/utils \
	   ../../../../../gdk \
	   $(READLINE_INCS) \
	   $(netcdf_CFLAGS)

lib__netcdf = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = netcdf.c
	LIBS = ../../../../../monetdb5/tools/libmonetdb5 \
	       $(netcdf_LIBS)
}

headers_netcdfmal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = netcdf.mal
}

headers_netcdfsql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 74_netcdf.sql
}

headers_netcdfautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 74_netcdf.mal
}

EXTRA_DIST = 74_netcdf.mal netcdf.mal 74_netcdf.sql netcdf_vault.h
