# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

SUBDIRS = HAVE_JAVAJDBC?tests

EXTRA_DIST = build.xml build.properties release.txt

EXTRA_DIST_DIR = src \
		 example

JAVA_HOME = @JAVA_HOME@

ant_distjdbc = {
	COND = HAVE_JAVAJDBC
	DIR = datadir/monetdb/lib
	FILES = monetdb-1.6-mcl.jar monetdb-1.19-jdbc.jar jdbcclient.jar
}

ant_distmerocontrol = {
	COND = HAVE_JAVAMEROCONTROL
	DIR = datadir/monetdb/lib
	FILES = merocontrol.jar
}

# vim: ft=automake :
