# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

SUBDIRS = HAVE_JAVAJDBC?tests

EXTRA_DIST = build.xml build.properties release.txt

EXTRA_DIST_DIR = src \
		 example

JAVA_HOME = @JAVA_HOME@

ant_distjdbc = {
	COND = HAVE_JAVAJDBC
	DIR = datadir/monetdb/lib
	FILES = monetdb-mcl-1.13.jar monetdb-jdbc-2.18.jar jdbcclient.jar
}

ant_distmerocontrol = {
	COND = HAVE_JAVAMEROCONTROL
	DIR = datadir/monetdb/lib
	FILES = merocontrol.jar
}

# vim: ft=automake :
