# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

SUBDIRS = conf HAVE_JAVAJDBC?tests HAVE_JAVAJDBC?scripts

EXTRA_DIST = configure.ag rpm.mk.in \
		MonetDB-java.spec MonetDB-java.spec.in \
		RunMtest.in RunMtest.bat.in \
		RunMapprove.in \
		build.xml build.properties release.txt

EXTRA_DIST_DIR = NT \
		 src \
		 lib \
		 example

ant_distjdbc = {
	COND = HAVE_JAVAJDBC
	DIR = datadir/MonetDB/lib
	FILES = monetdb-1.2-mcl.jar monetdb-1.7-jdbc.jar jdbcclient.jar
}

ant_distxrpc = {
	COND = HAVE_JAVAXRPC
	DIR = datadir/MonetDB/lib
	FILES = xrpcapi.jar xrpcwrapper.jar xrpcclient.jar
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
