## Process this file with automake to produce Makefile.in

INCLUDES = $(MONET_INCS) ../include

# locally disable "-Werror"
X_CFLAGS =

lib_core = {
	NOINST
	DIR = libdir
	SOURCES = \
		fs.mt \
		core.c \
		simplify.c 
}

EXTRA_DIST = simpl_impl.c  fs_impl.c.m4  fs_impl.c fs.mt.m4
