## Process this file with automake to produce Makefile.in

INCLUDES = $(MONET_INCS) ../include

# locally disable "-Werror"
X_CFLAGS =

lib_core = {
	NOINST
	DIR = libdir
	SOURCES = \
		fs.mt.sed \
		core.c \
		simplify.mt \
		fs_impl.h.sed
}

EXTRA_DIST = simpl_impl.c 
