# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE
INCLUDES = ../lib \
		   ../../common/options \
		   ../../common/stream \
		   ../../gdk \
		   ../../monetdb5/modules/atoms \
		   ../../monetdb5/modules/kernel \
		   ../../monetdb5/mal \
		   ../../monetdb5/modules/mal \
		   ../../monetdb5/optimizer \
		   ../../monetdb5/scheduler \
		   $(GEOS_INCS)

lib__geom = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = geom.mx
	LIBS = ../lib/libgeom \
		   ../../gdk/libbat \
	       ../../common/stream/libstream \
	       ../../monetdb5/tools/libmonetdb5 \
	       $(GEOS_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = geom.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 30_geom.mal
}

EXTRA_DIST = 30_geom.mal
