# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

MTSAFE
X_CFLAGS = -fopenmp
GPU_LIBS = $(MONETDB_SRC)/geom/gspatial/apps/gpu/pnpoly/cuda/lib/x86_64/linux/release/g_pnpoly.o -lcuda -lcudart -lm -lstdc++ 
INCLUDES = ../lib \
           ../../gdk \
           ../../common/stream \
           ../../common/options \
           ../../monetdb5/mal \
           ../gspatial/apps/gpu/pnpoly/cuda/include/x86_64/linux/release \
           /usr/local/cuda-8.0/include \
           $(GEOS_INCS) $(PROJ_INCS) \
           $(SFCGAL_INCS) ${GPU_INCS}

lib__geom = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = geom.h geom.c geomBulk.c geom_upgrade.c geom_geojson.c geom_x3d.c geom_clean.c
	LIBS = ../lib/libgeom \
		   ../../gdk/libbat \
	       ../../common/stream/libstream \
	       ../../monetdb5/tools/libmonetdb5 \
	       $(GEOS_LIBS) $(PROJ_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = geom.mal
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 30_geom.mal
}

lib__sfcgal = {
	COND = HAVE_SFCGAL
	MODULE
	DIR = libdir/monetdb5
	SOURCES = sfcgal.h sfcgal.c sfcgalBulk.c
	LIBS = ../lib/libgeom \
		   ../../gdk/libbat \
	       ../../common/stream/libstream \
	       ../../monetdb5/tools/libmonetdb5 \
	       $(SFCGAL_LIBS)
}

headers_mal_sfcgal = {
	COND = HAVE_SFCGAL
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = sfcgal.mal
}

headers_autoload_sfcgal = {
	COND = HAVE_SFCGAL
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 31_sfcgal.mal
}

lib__gpu = {
	COND = HAVE_GPUSPATIAL
	MODULE
	DIR = libdir/monetdb5
	SOURCES = gpu.h gpu.c
	LIBS = ../lib/libgeom \
		   ../../gdk/libbat \
	       ../../common/stream/libstream \
	       ../../monetdb5/tools/libmonetdb5 \
	       $(GPU_LIBS)
}

headers_mal_gpu = {
	COND = HAVE_GPUSPATIAL
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = gpu.mal
}

headers_autoload_gpu = {
	COND = HAVE_GPUSPATIAL
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 32_gpu.mal
}

EXTRA_DIST = 30_geom.mal 31_sfcgal.mal 32_gpu.mal geom.mal sfcgal.mal gpu.mal
