# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

man_MANS = monetdbd.1

# MONETDB5: Sabaoth
# MONETDB:  GDKmalloc, stream
INCLUDES = \
	../../../../../../MonetDB5/src/modules/atoms \
	../../../../../../MonetDB5/src/compiler \
	../../../../../../MonetDB5/src/modules/kernel \
	../../../../../../MonetDB5/src/mal \
	../../../../../../MonetDB5/src/modules/mal \
	../../../../../../MonetDB5/src/optimizer \
	../../../../../../MonetDB5/src/scheduler \
	../../../../../../MonetDB/src/common \
	../../../../../../MonetDB/src/gdk \
	../../../../../../clients/src/mapilib \
	../../../../../../common/stream \
	..

EXTRA_DIST = $(man_MANS) \
	merovingian.h \
	client.h \
	connections.h \
	controlrunner.h \
	discoveryrunner.h \
	forkmserver.h \
	handlers.h \
	multiplex-funnel.h \
	peering.h \
	proxy.h

bin_monetdbd = {
	# hack: include merovingian.1.in here to get it expanded
	SOURCES = monetdbd.1.in \
		merovingian.c \
		client.c \
		connections.c \
		controlrunner.c \
		discoveryrunner.c \
		forkmserver.c \
		handlers.c \
		multiplex-funnel.c \
		peering.c \
		proxy.c
	LIBS = \
		../utils/libmeroutil \
		$(UUID_LIBS) \
		../../../../../../MonetDB5/src/tools/libmonetdb5 \
		../../../../../../MonetDB/src/gdk/libbat \
		../../../../../../clients/src/mapilib/libMapi \
		../../../../../../common/stream/libstream \
		$(curl_LIBS) \
		$(CLIENTS_LIBS) -lMapi \
		$(SOCKET_LIBS) \
		$(MALLOC_LIBS) \
		$(PTHREAD_LIBS)
}
