# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

## Process this file with automake to produce Makefile.in

INCLUDES = .. ../../include ../../common ../bat \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk

lib_restrictstore = {
	NOINST
	DIR = libdir
	SOURCES = \
		restrict_table.c restrict_storage.c restrict_logger.c \
		restrict_logger.h restrict_storage.h restrict_table.h
}
