## Process this file with automake to produce Makefile.in
#
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Initial Developer of the Original Code is the Database &
# Information Systems Group at the University of Konstanz, Germany.
# Portions created by the University of Konstanz are Copyright (C)
# 2000-2006 University of Konstanz.  All Rights Reserved.
#


SUBDIRS = 

INCLUDES = ../../include $(MONETDB_INCS)

lib_prop = {
	NOINST
	DIR = libdir
	SOURCES = \
		prop_card.c \
		prop_const.c \
		prop_dom.c \
		prop_icol.c \
		prop_key.c \
		prop_ocol.c \
		prop_reqval.c \
		prop_ori_names.c \
		prop_unq_names.c
}
