
CREATE TABLE x ( a DOUBLE , b DOUBLE );
INSERT INTO x VALUES (1.0,2.0);
INSERT INTO x VALUES (2.0,3.0);
SELECT * FROM x;

SELECT CORR( a , b ) FROM x;
SELECT CORR( a , CAST( b AS INTEGER ) ) FROM x;
SELECT CORR( CAST( a AS INTEGER ) , b ) FROM x;

drop table x;
