CREATE SCHEMA banana;
SET SCHEMA banana;

CREATE MERGE TABLE t  ( num DECIMAL(8,2) DEFAULT NULL );
CREATE       TABLE t0 ( num DECIMAL(8,2) DEFAULT NULL );
ALTER TABLE t ADD TABLE t0;

SELECT * FROM t;

CREATE FUNCTION foo ()
RETURNS TABLE (i DECIMAL(8,2))
BEGIN
    RETURN SELECT * FROM t;
END;

-- this fails unexpectedly
SELECT * FROM foo();

SET SCHEMA sys;
DROP SCHEMA banana;
