CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
SELECT col2 FROM tab0 AS cor0 WHERE + col4 NOT IN ( + 0 + + col1 );
DROP TABLE tab0;
