CREATE TABLE tab0(col0 INTEGER, col1 INTEGER, col2 INTEGER);
SELECT - col0 AS col1 FROM tab0 AS cor0 WHERE NOT + col0 IS NOT NULL GROUP BY col1, col0 HAVING NOT - col1 + + AVG ( DISTINCT col0 ) IS NULL;
DROP TABLE tab0;
