CREATE TABLE tab0(pk INTEGER PRIMARY KEY, col0 INTEGER, col1 FLOAT, col2 TEXT, col3 INTEGER, col4 FLOAT, col5 TEXT);
SELECT - col4 col0 FROM tab0 WHERE NOT NULL IS NULL;
SELECT - ( + 13 ) col0 FROM tab0 WHERE NOT NULL IS NULL;
SELECT + col3 * 82 col3 FROM tab0 AS cor0 WHERE NULL IS NULL;
SELECT DISTINCT + MAX ( DISTINCT - col1 ) col2 FROM tab0 WHERE - col3 + + 72 IS NULL;
DROP TABLE tab0;
