CREATE TABLE tab2(col0 INTEGER, col1 INTEGER, col2 INTEGER);
SELECT ALL - 89 FROM tab2 GROUP BY col1, col1 HAVING - CAST ( NULL AS INTEGER ) * + - 17 + + - COUNT ( * ) NOT IN ( + MAX ( 44 ) );
DROP TABLE tab2;
