
EXTRA_DIST =  Mtest.py.in Mlog.in Mlog.bat Mfilter.py.in MkillUsers.in Mlimit.c

bin_Mdiff = {
	SOURCES = difflib.c helpers.c Mdiff.c difflib.h  helpers.h
}

bin_Mtimeout = {
	SOURCES = Mtimeout.c
}

bin_SCRIPTS = Mtest.py Mlog Mfilter.py MkillUsers

scripts_bat = {
	DIR = bindir
	SOURCES = Mlog.bat
}
