
EXTRA_DIST =  Mtest.in Mlog.in Mfilter.in MkillUsers.in Mlimit.c

bin_Mdiff = {
	SOURCES = difflib.c helpers.c Mdiff.c difflib.h  helpers.h
}

bin_Mtimeout = {
	SOURCES = Mtimeout.c
}

bin_SCRIPTS = Mtest Mlog Mfilter MkillUsers
bin_Mapprove = bin_Mtest
