#!/bin/sh

NAME="$1"
PRELUDE="$2 $3"

for i in README awkscript column format gcol summary test100k init.mil tst100.mil load.mil; do
    if [ ! -f $i ]; then
        /bin/rm -f $i
        ln -s $RELSRCDIR/../$i .
    fi
done

TSTDB=${TSTDB}_${NAME}

if [ -d $GDK_DBFARM/$TSTDB ] ; then
	rm -rf $GDK_DBFARM/$TSTDB
fi
Mlog -x mkdir -p $GDK_DBFARM/$TSTDB
#Mlog -x $MLOAD test100k -db $TSTDB -oid 30000000 -s 100000 -f format
Mlog   "$MSERVER --dbname=$TSTDB         < load.mil"
eval    $MSERVER --dbname=$TSTDB         < load.mil
Mlog   "$MSERVER --dbname=$TSTDB         < init.mil"
eval    $MSERVER --dbname=$TSTDB         < init.mil
Mlog   "$MSERVER --dbname=$TSTDB         < $NAME.mil | tee output"
eval    $MSERVER --dbname=$TSTDB         < $NAME.mil | tee output
PATH=/bin:$PATH ; export PATH
Mlog -x sh summary
#Mlog -x rm -rf $GDK_DBFARM/$TSTDB

