
# temporary disable "-Werror" to get modules compiled
X_CFLAGS =
X_CXXFLAGS =

INCLUDES = -I$(MONET_BUILD)/src/gdk -I$(MONET_BUILD)/src/monet \
	$(Z_CFLAGS) $(BZ_CFLAGS)
MTSAFE

LIBDIR = pkglib

lib_stream  =  {
	SOURCES = stream.mx
	HEADERS = h
	LIBS = \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) 
}

