
INCLUDES = -I$(MONETDB_BUILD)/src/gdk -I$(MONETDB_BUILD)/src/monet \
	$(Z_CFLAGS) $(BZ_CFLAGS)
MTSAFE

LIBDIR = pkglib

#lib_stream  =  {
#	SOURCES = stream.mx
#	HEADERS = h
#	LIBS = \
#		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) 
#}

