debian/tmp/usr/lib/x86_64-linux-gnu/libbat.so usr/lib/x86_64-linux-gnu
debian/tmp/usr/include/monetdb/gdk*.h usr/include/monetdb
debian/tmp/usr/include/monetdb/matomic.h usr/include/monetdb
debian/tmp/usr/include/monetdb/mstring.h usr/include/monetdb
# usr/include/monetdb/monetdb*.h EXCEPT: monetdbe.h
debian/tmp/usr/include/monetdb/monet_*.h usr/include/monetdb
debian/tmp/usr/include/monetdb/monetdb_*.h usr/include/monetdb
debian/tmp/usr/lib/x86_64-linux-gnu/pkgconfig/monetdb-gdk.pc usr/lib/x86_64-linux-gnu/pkgconfig
