## Process this file with automake to produce Makefile.in

MTSAFE

INCLUDES = srcdir

EXTRA_DIST = monet_getopt.h getopt.c getopt1.c memcmp.c monet_options.py.in

lib_mutils = { 
	NAME = mutils
	SOURCES = monet_utils.mx monet_options.mx.in @LIBOBJS@ monet_getopt.h
	HEADERS = h
	LIBS = @LIBOBJS@
}
