# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

## Process this file with automake to produce Makefile.in

MTSAFE

EXTRA_DIST = monet_getopt.h getopt.c getopt1.c memcmp.c
EXTRA_HEADERS = stream_socket.h

lib_mutils = { 
	NAME = mutils
	SOURCES = monet_utils.mx monet_options.mx monet_getopt.h
	HEADERS = h
}

INCLUDES = $(Z_CFLAGS) $(BZ_CFLAGS) $(OPENSSL_INCS) $(CURL_INCS)

lib_stream  =  {
	SOURCES = stream.mx dummy_gdk_utils.mx
	HEADERS = h
	LIBS = libmutils $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) $(OPENSSL_LIBS) $(CURL_LIBS)
}

scripts_py = {
	DIR = pkgdatadir/python
	SOURCES = monet_options.py.in
}

