# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2014 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../modules/atoms ../../modules/mal ../../mal \
		   ../../modules/kernel \
		   ../../../clients/mapilib \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   $(raptor_CFLAGS)

MTSAFE

lib_rdf = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = rdf.h rdf_shredder.c rdfalgebra.c

	LIBS = ../../tools/libmonetdb5 \
		   ../../../gdk/libbat \
		   $(MALLOC_LIBS) $(raptor_LIBS)
}

headers_rdf_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = rdfalgebra.mal
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 30_rdf.mal
}

#EXTRA_DIST_DIR = Tests
EXTRA_DIST = 30_rdf.mal rdfalgebra.mal
