#!/bin/sh
#=========================================================================#
#== Creation Script for the Monet Source Code Web                       ==#
#=========================================================================#
#== o get the source distribution of Monet, compile it, and set the     ==#
#==   environment variables MONETHOME and PREFIX to correct values.     ==#
#== o make sure a Monet database 'index' exists, and occurs in the      ==#
#==   $MONETHOME/homes file.                                            ==#
#== o make sure that the WWWidx WWWlink and Mx utilities are made       ==#
#== o make sure the 'blob', 'io', and 'str' modules are installed.      ==#
#== o this script is activated with at most 5 parameters:               ==#
#==   0) 'mkdirs'                                                       ==#
#==      The scripts assume the necessary directories to be present     ==#
#==      without checking. You must make them once with thgis option.   ==#
#==   1) 'index'                                                        ==#
#==      The source files are first indexed and the results put in the  ==#
#==      WWW hierarchy under *.mx.mx names. The found definitions are   ==#
#==      entered in the 'index' database.                               ==#
#==   2) 'link'                                                         ==#
#==      Link finding is then performed.                                ==#
#==      - gdk_* files are matched with themselves                      ==#
#==      - monet_* files are matched with themselves and the gdk group  ==#
#==      - tool files are matched with the gdk group                    ==#
#==   3) 'extract'                                                      ==#
#==      Mx code is extracted to HTML, and directories are created.     ==#
#==   4) 'dbgen'                                                        ==#
#==      for each definition, a separate HTML page has to be created.   ==#
#==      as well as an overall index for each group (gdk, monet tools)  ==#  
#==      This task is performed by running the wwwmake.monet MIL        ==#
#==      script to the Mserver -db index.                               ==#
#==                                                                     ==#
#==   So, a total remake of the tree is done with:                      ==#
#==      wwwmake mkdirs index link extract dbgen 	                ==#
#==                                                                     ==#
#==  "wwwmake empty" generates an empty database to start over.         ==#
#==  "wwwmake clean" also deletes all files, and may take long.         ==#
#==                                                                     ==#
#=========================================================================#

WWWSCW=www/scw

WWWDIR=..
#MANDIR=http://www.cs.ubc.ca/man/solaris2.1
DBDIR=$MONETHOME/dbfarm/index
DBPRT=50080

WWWIDX=WWWidx
WWWLINK=WWWlink
MX=Mx

do_index()
{
    echo "#=================================================================#"
    echo "#== index phase                                                 ==#"
    echo "#=================================================================#"
    for j in gdk monet 
    do
      cd $MONETHOME/src/$j
      for i in *.mx
      do
        echo WWWidx $i -G$j ">" $WWWSCW/$j/$i.idx
        $WWWIDX $i -G$j > ../../$WWWSCW/$j/$i.idx
      done
      cd $MONETHOME
    done

    cd src/tools
    for i in M*.mx
    do
      echo WWWidx $i -G$j ">" $WWWSCW/tools/$i.idx
      $WWWIDX $i -Gtools > ../../$WWWSCW/tools/$i.idx
    done
    cd $MONETHOME

      cd modules/plain/
      for j in *.mx
      do
        m=`echo $j | awk -F".mx" '{ printf "%s\n", $1  }'`
        echo WWWidx $j -Gmodules ">" $WWWSCW/modules/$j.idx
        $WWWIDX $j -Gmodules > ../../$WWWSCW/modules/$j.idx
      done
      cd $MONETHOME
}
    
do_link()
{   echo
    echo "#=================================================================#"
    echo "#== link matching phase                                         ==#"
    echo "#=================================================================#"
    cd $MONETHOME
    cd src/gdk
    for i in *.mx
    do
      echo WWWlink $WWWSCW/gdk/$i.idx -Rgdk ">" $WWWSCW/gdk/$i
      $WWWLINK ../../$WWWSCW/gdk/$i.idx -W$WWWDIR -Rgdk > ../../$WWWSCW/gdk/$i
    done
    cd $MONETHOME
    
    cd src/monet
    for i in *.mx
    do
      echo WWWlink $WWWSCW/monet/$i.idx -Rgdk -Rmonet ">" $WWWSCW/monet/$i 
      $WWWLINK ../../$WWWSCW/monet/$i.idx -W$WWWDIR -Rgdk -Rmonet\
		> ../../$WWWSCW/monet/$i
    done
    cd $MONETHOME
    
    cd src/tools
    for i in *.mx
    do
      echo WWWlink $WWWSCW/tools/$i.idx -Rtools -Rgdk -Rmonet ">" $WWWSCW/tools/$i
      $WWWLINK ../../$WWWSCW/tools/$i.idx -W$WWWDIR -Rtools -Rgdk -Rmonet > ../../$WWWSCW/tools/$i
    done
    cd $MONETHOME

      cd modules/plain 
      for j in *.mx
      do
        m=`echo $j | awk -F".mx" '{ printf "%s\n", $1  }'`
        echo WWWlink $WWWSCW/modules/$j.idx -Rmodules -Rgdk -Rmonet ">" $WWWSCW/modules/$j
        $WWWLINK ../../$WWWSCW/modules/$j.idx -W$WWWDIR -Rmodules -Rgdk -Rmonet \
		 > ../../$WWWSCW/modules/$j
      done
      cd $MONETHOME
}
    
do_extract()
{   echo
    echo "#=================================================================#"
    echo "#== HTML: extraction phase                                      ==#"
    echo "#=================================================================#"
    for j in monet gdk tools
    do
      cd $MONETHOME/$WWWSCW/$j
      for i in *.mx
      do
        echo Mx -w $i
        cd $MONETHOME/src/$j
        $MX -w -R$MONETHOME/$WWWSCW/$j $MONETHOME/$WWWSCW/$j/$i
      done
      cd $MONETHOME
    done

      cd modules/plain 
      for i in *.mx
      do
        m=`echo $i | awk -F".mx" '{ printf "%s\n", $1  }'`
        echo Mx -w $i
        $MX -w -R$MONETHOME/$WWWSCW/modules/ $MONETHOME/$WWWSCW/modules/$i
      done
      cd $MONETHOME
}


do_dbgen()
{   echo
    echo "#=================================================================#"
    echo "#== Definition Page Generation                                  ==#"
    echo "#=================================================================#"
    echo "GEN_ALL;" | Mserver -db index 
}


do_mkdirs()
{
    cd $MONETHOME
    for j in monet gdk tools
    do
      # make empty subdirectories
      cd src/$j
      for i in *.mx
      do
        # make empty definition directory
        DIR=`echo $j/$i | awk -F".mx" '{ printf "%s\n", $1  }'`
        if [ -d ../../$WWWSCW/$DIR ]; then 
    	  touch ../../$WWWSCW/$DIR;
        else 
    	  mkdir -p ../../$WWWSCW/$DIR;
        fi
        # make empty subdirectories
        for k in 1 2 3 4 5 6 7 8 9
        do
    	if [ -d ../../$WWWSCW/$DIR/$k ]; then 
    	    touch ../../$WWWSCW/$DIR/$k;
    	else
    	    mkdir -p ../../$WWWSCW/$DIR/$k;
    	fi
        done
      done
      cd $MONETHOME
    done

      cd modules/plain
      for i in *.mx
      do
        echo `pwd` i=$i j=$j
        m=`echo $i | awk -F".mx" '{ printf "%s\n", $1  }'`
        DIR=modules/$m
        if [ -d ../../$WWWSCW/$DIR ]; then 
    	  touch ../../$WWWSCW/$DIR;
        else 
    	  mkdir -p ../../$WWWSCW/$DIR;
        fi
        # make empty subdirectories
        for k in 1 2 3 4 5 6 7 8 9
        do
    	if [ -d ../../$WWWSCW/$DIR/$k ]; then 
    	    touch ../../../$WWWSCW/$DIR/$k;
    	else
    	    mkdir -p ../../$WWWSCW/$DIR/$k;
    	fi
        done
      done
      cd $MONETHOME
}


do_empty()
{
    if [ -d $DBDIR ]; then 
	rm $DBDIR/core $DBDIR/.gdk_lock 2>/dev/null
    else
	mkdir -p $DBDIR
    fi
    if [ -d $DBDIR/bat ]; then 
        rm $DBDIR/bat/*.buns
        rm $DBDIR/bat/*.Z
        rm $DBDIR/bat/*.hheap
        rm $DBDIR/bat/*.theap
        rm $DBDIR/bat/*.hacc
        rm $DBDIR/bat/*.tacc
        rm $DBDIR/bat/BBP.dir
    else 
	mkdir -p $DBDIR/bat
    fi
    if [ -d $DBDIR/users ]; then 
	touch $DBDIR/users
    else
	mkdir -p $DBDIR/users
    fi
    if [ -d $DBDIR/users/adm ]; then 
	touch $DBDIR/users/adm
    else 
	mkdir -p $DBDIR/users/adm
    fi
    rm $DBDIR/users/adm/prelude.mil 
    ln -s $MONETHOME/scripts/wwwmake.mil $DBDIR/users/adm/prelude.mil
}

do_clean()
{
    do_empty()
    do_mkdirs()
    for i in $WWWSCW/gdk $WWWSCW/tools $WWWSCW/monet
    do
      find $i \( \( -name '*.mx*' -o -name '*.html' \)  ! -name index.html \) -exec rm {} \;
      for k in $i/*/ 
      do
        for j in $k/*_pseudo.html
        do
          rm -f $j 2>/dev/null 
        done
        for l in 1 2 3 4 5 6 7 8 9
        do
          for j in  $k/$l/*_index.html
          do
            rm -f $j 2>/dev/null 
          done
        done
        for l in 1 2 3 4 5 6 7 8 9
        do
          for j in  $k/$l/*_pseudo.html
          do
            rm -f $j 2>/dev/null 
          done
        done
      done
    done
}

case $* in
*empty*) do_empty;;
esac
case $* in
*mkdirs*) do_mkdirs;;
esac
case $* in
*clean*) do_clean;;
esac
case $* in
*index*) do_index;;
esac
case $* in
*link*) do_link;;
esac
case $* in
*extract*) do_extract;;
esac
case $* in
*dbgen*) do_dbgen;;
esac
