SELECT INTERVAL '3' YEAR;
SELECT INTERVAL '7' MONTH;
SELECT INTERVAL '3-7' YEAR TO MONTH;
SELECT INTERVAL -'3-7' YEAR TO MONTH;
SELECT INTERVAL +'0-0' YEAR TO MONTH;
SELECT INTERVAL -'0-0' YEAR TO MONTH;
SELECT INTERVAL '1 23:45:12' DAY TO SECOND;
