# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

INCLUDES = .. \
	../../../../common \
	../../../../monetdb5/modules/atoms \
	../../../../monetdb5/mal \
	../../../../monetdb5/modules/mal \
        ../../../../common/options \
        ../../../../common/stream \
	../../../../common/utils \
	../../../../clients/mapilib \
	../../../../sql/server \
	../../../../sql/include \
	../../../../sql/storage \
	../../../../sql/common \
	../../../../sql/backends/monet5 \
	../../../../gdk \
	$(liburiparser_CFLAGS)

lib__jsonstore = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = rest_jsonstore.c rest_jsonstore.h \ 
		rest_jsonstore_handle_get.c rest_jsonstore_handle_get.h
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
	     ../../../../sql/server/libsqlserver \
	     ../../../../sql/common/libsqlcommon \
	     ../../../../sql/storage/libstore \
	     #../../../../sql/backends/monet5/lib_sql \
	     ../../../../gdk/libbat \
	     $(liburiparser_LIBS) \
	     $(openssl_LIBS)
}

headers_jsonstoremal = {
	COND = HAVE_JSONSTORE
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = jsonstore.mal
}

headers_restautoload = {
	COND = HAVE_JSONSTORE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 73_jsonstore.mal
}

EXTRA_DIST = 73_jsonstore.mal jsonstore.mal rest_jsonstore.h
EXTRA_DIST_DIR = Tests
