# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2013 MonetDB B.V.
# All Rights Reserved.

INCLUDES = .. \
	../../../../common \
	../../../../monetdb5/modules/atoms \
	../../../../monetdb5/mal \
	../../../../monetdb5/modules/mal \
        ../../../../common/options \
        ../../../../common/stream \
	../../../../common/utils \
	../../../../clients/mapilib \
	../../../../sql/server \
	../../../../sql/include \
	../../../../sql/storage \
	../../../../sql/common \
	../../../../sql/backends/monet5 \
	../../../../gdk

lib__jsonstore = {
	MODULE
	#SEP = _
	DIR = libdir/monetdb5
	#COND = HAVE_URIPARSER
	SOURCES = rest_jsonstore.c rest_jsonstore.h \ 
		rest_jsonstore_handle_get.c rest_jsonstore_handle_get.h
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
	     ../../../../sql/server/libsqlserver \
	     ../../../../sql/common/libsqlcommon \
	     ../../../../sql/storage/libstore \
	     #../../../../sql/backends/monet5/lib_sql \
	     ../../../../gdk/libbat \
	     $(uriparser_LIBS)
}

headers_jsonstoremal = {
	COND = HAVE_JSONSTORE
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = jsonstore.mal
}

headers_restautoload = {
	COND = HAVE_JSONSTORE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 73_jsonstore.mal
}

EXTRA_DIST = 73_jsonstore.mal jsonstore.mal rest_jsonstore.h
