SELECT * FROM (SELECT 1 as c) a LEFT OUTER JOIN (SELECT 1 as c) b ON 1 = 1;
SELECT * FROM (SELECT 1 as c) a LEFT OUTER JOIN (SELECT 1 as c) b ON 1 = 0;
SELECT * FROM (SELECT 1 as c) a RIGHT OUTER JOIN (SELECT 1 as c) b ON 1 = 1;
SELECT * FROM (SELECT 1 as c) a RIGHT OUTER JOIN (SELECT 1 as c) b ON 1 = 0;
SELECT * FROM (SELECT 1 as c) a FULL OUTER JOIN (SELECT 1 as c) b ON 1 = 1;
SELECT * FROM (SELECT 1 as c) a FULL OUTER JOIN (SELECT 1 as c) b ON 1 = 0;
