# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

man_MANS = monetdb.1

INCLUDES = ../../../common/stream \
		   ../../../common/utils \
		   ../utils

EXTRA_DIST = $(man_MANS)

bin_monetdb = {
	SOURCES = monetdb.c
	LIBS = ../utils/libmeroutil \
		   ../../../common/utils/libmcrypt \
		   ../../../common/utils/libmsabaoth \
		   ../../../common/utils/libmuuid \
		   ../../../common/utils/libmutils \
		   ../../../common/stream/libstream \
		   $(UUID_LIBS) \
		   $(openssl_LIBS) \
		   $(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) $(snappy_LIBS) $(lz4_LIBS) $(liblzma_LIBS) $(curl_LIBS) $(LTLIBICONV)
}
