# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2014 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../../include \
		   ../../../common \
		   ../../../storage \
		   ../../../server ../.. \
		   ../../../../monetdb5/modules/atoms \
		   ../../../../monetdb5/modules/kernel \
		   ../../../../monetdb5/mal \
		   ../../../../monetdb5/modules/mal \
		   ../../../../monetdb5/optimizer \
		   ../../../../monetdb5/scheduler \
		   ../../../../clients/mapilib \
		   ../../../../common/options \
		   ../../../../common/stream \
		   ../../../../common/utils \
		   ../../../../gdk \
		   $(READLINE_INCS) $(MSEED_CFLAGS) $(curl_CFLAGS)

lib__generator = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = generator.c 
	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		   ../../../../gdk/libbat $(curl_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = generator.mal
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 90_generator.sql
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 90_generator.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 90_generator.mal 90_generator.sql generator.mal
