# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = ../../../include \
		   ../../../common \
		   ../../../storage \
		   ../../../server \
		   ../../../../monetdb5/modules/atoms \
		   ../../../../monetdb5/modules/kernel \
		   ../../../../monetdb5/mal \
		   ../../../../monetdb5/modules/mal \
		   ../../../../monetdb5/optimizer \
		   ../../../../monetdb5/scheduler \
		   ../../../../common/options \
		   ../../../../common/stream \
		   ../../../../common/utils \
		   ../../../../gdk

lib__generator = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = generator.c  generator.h
	LIBS = WIN32?../../../../monetdb5/tools/libmonetdb5 \
	       WIN32?../../../../gdk/libbat
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = generator.mal
}

headers_mal_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = generator_hge.mal
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 90_generator.sql
}

headers_sql_hge = {
	COND = HAVE_HGE
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 90_generator_hge.sql
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 90_generator.mal
}

headers_autoload_hge = {
	COND = HAVE_HGE
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 90_generator_hge.mal
}

EXTRA_DIST_DIR = Tests
