START TRANSACTION;

CREATE TABLE foo (a INT);

SELECT 1
FROM (SELECT a FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo
      UNION ALL
      SELECT 0 FROM foo) AS t;

INSERT INTO foo VALUES (3), (6), (7);

SELECT DISTINCT a
FROM (
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo) t;

SELECT DISTINCT a
FROM (
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT a FROM foo UNION ALL
SELECT 0 FROM foo) t;

DROP TABLE foo;

ROLLBACK;
