CREATE TABLE test1 (t int);
INSERT INTO test1 VALUES (1),(2),(3);
CREATE TRIGGER trtest
 BEFORE DELETE ON test1 REFERENCING OLD ROW AS oldrow
 FOR EACH ROW INSERT INTO test2 SELECT * FROM oldrow; --error. table test2 doesn't exist

CREATE TABLE test2 (t int);
CREATE TRIGGER trtest
 BEFORE DELETE ON test1 REFERENCING OLD ROW AS oldrow
 FOR EACH ROW INSERT INTO test2 SELECT * FROM oldrow; 

DELETE FROM test1 WHERE t=1;
SELECT * FROM test1;
SELECT * FROM test2;

DROP TRIGGER trtest;
DROP TABLE test1;
DROP TABLE test2;
