create table ints (id int);
insert into ints values (24), (42);
create table t (i bigint, j bigint);
insert into t(i) select id from ints;
insert into t(j) select id from ints;
insert into t(i, j) select id, id from ints;
insert into t(i, j) select cast(id as bigint), id from ints;
insert into t(i, j) select id, cast(id as bigint) from ints;
drop table t;
drop table ints;
