
EXTRA_DIST =  Mtest.py.in Mtest.py.bat Mlog.in Mlog.bat Mfilter.py.in MkillUsers.in Mlimit.c \
		prof.py Mprofile-commands.lst

INCLUDES = ../common

bin_Mdiff = {
	SOURCES = difflib.c helpers.c Mdiff.c difflib.h  helpers.h
	LIBS = ../common/libmutils
}

bin_Mtimeout = {
	SOURCES = Mtimeout.c
}

bin_Mapprove.py = bin_Mtest.py
bin_Mapprove.py.bat = bin_Mtest.py.bat
bin_Mprofile.py = bin_Mtest.py
bin_Mprofile.py.bat = bin_Mtest.py.bat

scripts_bat = {
	DIR = bindir
	SOURCES = Mlog.bat Mtest.py.bat
}

scripts_py = {
	DIR = bindir
	SOURCES = prof.py
}

scripts_lst = {
	DIR = pkgdatadir
	SOURCES = Mprofile-commands.lst
}

scripts_sh = {
	DIR = bindir
	SOURCES = Mtest.py Mlog Mfilter.py MkillUsers
}
