#!/bin/sh

# if we have an older automake, patch our files a bit
case `automake --version | egrep "[0-9]\.[0-9](\.[0-9])?.*"` in
	*1.[56]*)
	mv configure.ac configure.ac.orig_bootstrap
	cp configure.ac.orig_bootstrap configure.ac
	patch << EOF
Index: configure.ac
===================================================================
RCS file: /cvsroot/monetdb/buildtools/Mx/configure.ac,v
retrieving revision 1.4
diff -u -r1.4 configure.ac
--- configure.ac-       Fri Nov 25 10:40:24 2005
+++ configure.ac        Fri Nov 25 10:42:27 2005
@@ -3,9 +3,9 @@
 
 AC_PREREQ(2.57)
 AC_INIT([Mx], [1.0], [monet@cwi.nl])
-AM_INIT_AUTOMAKE
+AM_INIT_AUTOMAKE([Mx], [1.0])
 AC_CONFIG_SRCDIR([Mx.c])
-AC_CONFIG_HEADER([mx_config.h])
+AM_CONFIG_HEADER([mx_config.h])
 
 # Checks for programs.
 AC_PROG_CC
EOF
	;;
esac

aclocal || exit 1
autoheader || exit 1
autoconf || exit 1
automake --add-missing || exit 1

if [ -e configure.ac.orig_bootstrap ];
then
	mv configure.ac.orig_bootstrap configure.ac
fi
