@chapter General Introduction
The @value{bookname}
 reference manual serves as the primary entry
point to locate information on its functionality,
system architecture, services, and best practices on using its components.

@ifset M5manual
The manual is focussed on the features available in Version 5.
Users of previous versions may benefit from the sections
on e.g. SQL and the Inner Core of the system, because these
components are shared with Version 4.
@end ifset

The manual is produced from a Texinfo framework file, which collects
and organizes bits-and-pieces of information scattered around the many
source components comprising the MonetDB software family.
The Texinfo file is turned into a HTML browse-able version using
@emph{makeinfo} program.
The PDF version can be produced using @emph{pdflatex}.
Alternative formats, e.g. XML and DocBook format, can be
readily obtained from the Texinfo file.

The copyright(2007) on the MonetDB software, documentation,
and logo is owned by CWI.
Other trademarks and copyrights referred to in this manual are
the property of their respective owners.
@menu
* Intended audience::
* How to read this manual::
* Features and Limitations::
* A Brief History ::
* Manual Generation::
* Download and Installation::
* Start and Stop the Server::
* Database Configuration::
* Checkpoint and Recovery::
* Database Dumps::
@end menu

@node Intended audience, How to read this manual, General Introduction, General Introduction
@section Intended Audience
The MonetDB reference manual is aimed at application developers and
researchers with an intermediate level exposure to database technology,
its embedding in host environments, such as C, Perl, Python, PHP,
or middleware solutions based on JDBC and ODBC.

The route towards becoming a database application expert is long
and tedious. It requires building experiences from small toy examples
towards large business critical application.
The reference manual is not designed for this purpose,
but in combination with the abundance of tutorial articles on SQL-based
systems, it should be possible to quickly create your first
working MonetDB/SQL application.

@ifset M5manual
The bulk of the MonetDB reference manual deals with the techniques
deployed in the back-end for the expert user and researcher.
Judicious use of the programming interfaces and database kernel modules for
domain specific tasks lead to high-performance solutions.
The grand challenge for the MonetDB development team
is to assemble a sufficient and orthogonal set of partial solutions
to accomodate a wide variety of front-ends. 
@end ifset

Feedback on the functionality provided is highly
appreciated, especially when you embark on a complex programming
project. If the envisioned missing functionality is generally 
applicable it makes sense to contribute it to the community.
Share your comments and thoughts through the
@url{mailto:monetdb-users@@lists.sourceforge.net,MonetDB mailing list}
held at SourceForge.

@node How to read this manual, Features and Limitations, Intended audience, General Introduction
@section How to read this manual
@ifset M5manual
The reference manual covers a lot of ground, which at first reading
may be slightly confusing. 
The material is presented in a top-down fashion.
Starting at installing the system components,
SQL \& XQuery and the application interface layer, 
it discusses the MAL software stack at length.
Forward references are included frequently to point into the right
direction for additional information.

If you are interested in technical details
of the MonetDB system, you should start reading @ref{MonetDB Overview}.
Two reading  tracks are possible. The @ref{MAL Introduction } language
and subsequent sections describe the abstract machine and MAL
optimizers to improve execution speed.
It is relevant for a better understanding of the query processing
behavior and provides an entry point to built new languages on top
of the database kernel. The tutorial on SQL to MAL compilation
provides a basis for developing your own language front-end.

The second track, The Inner Core describes the datastructures
and operations exploited in the abstract machine layer. This part
is essential for developers to aid in bug fixing and to
extend the kernel with new functionality. 
For most readers, however, it can be skipped without causing
problems to develop efficient applications.
@end ifset

@ifset SQLmanual
First time SQL users of MonetDB should read @ref{Download
and Installation} and @ref{SQL Introduction}. 
It prepares the ground to develop applications.
Advanced topics for application builders are covered in @ref{Programming
Interfaces}.
If you are interested in technical details
about the system, you should start reading the MonetDB 
reference manual.
@end ifset

@ifset XQRYmanual
The query language XQuery is intended for users
living at the edge of technology. It provides a functional
complete implementation of the XQuery and XUpdate standard.
Unfortunately, the XQuery compiler is currently only
available for MonetDB Version 4.
@end ifset
