@chapter About this manual
This is the MonetDB reference manual, which serves as the primary entry
point to locate information on its functionality,
system architecture, services, and
best practices on using its components.

The manual is produced from a Texinfo framework file, which collects
and organizes bits-and-pieces of information scattered around the many
source components comprising the MonetDB software family. 
The Texinfo file is turned into a HTML browse-able version using 
@emph{makeinfo} program. It can also be used to produce
a Postscript version using @emph{tex2dvi} followed by 
@emph{dvips}. The PDF version can be produced from the Postscript
using @emph{ps2pdf}.
Alternative formats, e.g. XML and DocBook format, can be
readily obtained from the Texinfo file.

The copyright(2005) and the MonetDB logo are owned by CWI.
Other trademarks and copyrights referred to in this manual are
the property of their respective owners.

@emph{Disclaimer} The reference manual is still under development,
much like the underlying source code base. This may lead to 
incomplete and inconsistencies descriptions,
for which we apologize in advance. You can help improving the manual
using the user commentary system included in the website.
@menu
* Intended audience::
* Features and Limitations::
@menu
* When to consider MonetDB::
* When not to consider MonetDB::
@end menu
* The History of MonetDB::
* Manual Generation::
* Conventions and notation::
@end menu

@node Intended audience, Manual Generation,,About this manual
@section Intended Audience
The MonetDB reference manual is aimed at programmers and application
developers with an intermediate level exposure to database technology,
its embedding in host environments such as C, Perl, Python, PHP,
or middleware solutions based on JDBC and ODBC.

The route towards becoming a database application expert is long
and difficult. It requires building experiences from small toy examples
towards large business critical application.
The MonetDB reference manual is not designed for this purpose,
but in combination with the abundance of articles and papers on the web
it should be possible to create your first MonetDB/SQL application
without much difficulty.

Users interested in building applications on top of the MonetDB
product suite are advised to read @ref{Download and Installation} and @ref{SQL}.

The bulk of the MonetDB reference manual deals with the techniques
available in the back-end for the expert user. Judicious use
of the programming interfaces and database kernel modules for
domain specific tasks lead to high-performance solutions. 
The grand challenge for the MonetDB development team
is to assemble a sufficient and orthogonal set of partial solutions. 
Feedback on the current set is highly
appreciated, especially before you embark on a complex programming
project. If the envisioned functionality is generally applicable it makes
sense to contribute it to the community.

The preferred channel to share your comments is through the
@c share your comments: share your thoughts, post your comments??
@url{mailto:monetdb-users@lists.sourceforge.net,MonetDB mailing list}
held at SourceForge.
