@section Manual Generation
The MonetDB code base is a large collection of files, scattered
over the system modules. Each source file is written in a
literal programming style, which physically binds documentation with 
the relevant code sections. The utility program Mx processes the
files marked *.mx to extract the code sections for system
compilation or to prepare for a pretty printed listing.

The reference manual is based on @emph{Texinfo} formatted
documentation to simplify generation for different rendering
platforms.
The components for the reference manual are extracted by
@example
Mx -i -B -H1 <filename>.mx
@end example
which generates the file <filename>.bdy.texi.
These pieces are collected and
glued together in a manual framework, running @emph{makeinfo} to produce
the desired output format.
The @emph{Texinfo} information is currently limited
to the documentation, it could also be extended to process the code.

A printable version of an *.mx file can be produced using the commands:
@example
Mx  <filename>.mx
pdflatex <filename>.tex
@end example

@menu
* Conventions ::
* Additional Resources::
@end menu
@node Conventions, Additional Resources, Manual Generation, Manual Generation
@subsection Conventions and Notation
The  typographical conventions used in this manual are straightforward.
@sc{Monospaced} text is used to designate names in the code base
and examples. 
@emph{Italics} is used in explanations to indicate where a user
supplied value should be substituted.

Snippets of code are illustrated in verbatim font. 
The interaction with textual client interfaces uses the default 
prompt-setting of the underlying operating system. 

Keywords in the MonetDB interface languages are case sensitive;
SQL keywords are not case sensitive. No distinction is made
in this manual.

@node Additional Resources, Download and Installation, Conventions, Manual Generation
@subsection Additional Resources
Although this reference manual aims to be complete for developing
applications with MonetDB, it also depends on
additional resources for a full understanding.

This reference manual relies on external documentation for the basics of its
query languages SQL, XQuery, its application interfaces, PHP, Perl,
Pyhton, and its middleware support, JDBC and ODBC.
Examples are used to illustrate their behaviour in the context of
MonetDB only.
The resource locations identified below may at times proof valuable.

@multitable {example}{and the remainder is long}
@item Perl DBI
@tab @url{http://www.perl.org/,http://www.perl.org/}
@item PHP5
@tab @url{http://www.php.net/,http://www.php.net/}
@item Python
@tab @url{http://www.python.org/,http://www.python.org/}
@item XQuery
@tab @url{http://wwww.w3c.org/TR/xquery/,http://wwww.w3c.org/TR/xquery/}
@end multitable

The primary source for additional information is the MonetDB website,
@url{http://monetdb.cwi.nl/,http://monetdb.cwi.nl/}, and the code base
itself.  Information on the background of its architecture can be found
in the library of scientific publications.

