Using MonetDB for experimentation and application development
requires installation of the back-end server Mserver, a front-end compiler for 
SQL or XQuery, the APIs, and a (graphical) user interface.
These components are packaged conveniently for several platforms in
the @url{"http://sourceforge.net/project/showfiles.php?group_id=56967",download} section at SourceForge.

Most people prefer a version `officially' declared as stable. Stable
means that special care has been taken to assure that all errors reported
during the nightly builds have been solved on the platforms of interest.
Major bug fixes are also applied to the latest stable version, while functional
enhancements are kept for the next release.

Before you embark upon application development, take a quick look at
the tutorial section. It illustrates a small, but concrete application
scenario geared at querying a historical database with trading trips of the
world-famous East-Indian Trading Corp (1602-1795).

If you encounter errors during the installation, please have a look at the
@url{"http://monetdb.cwi.nl/GetGoing/Trouble/FAQ/index.html",FAQ}
for common errors and some advice on how to proceed.

@menu
* Binary Distributions::Intended for end-users.
* Source Distributions::Intended for system developers.
@end menu

@node Binary Distributions, Source Distributions, Download and Installation, Download and Installation
@section Binary Distributions
@subsection Linux platforms
@subsection Windows distributions

@node Source Distributions, MonetDB overview ,Binary Distributions, Download and Installation
@section Source Distributions
@subsection Linux platforms
@subsection Windows distributions

