@chapter SQL
MonetDB/SQL is a full-fledged SQL implementation which closely follows 
the SQL-99 standards where possible.
It is realized as a separate compiler, which translates SQL statements into MAL.
In this process common optimization heuristics, specific to relational algebra
are performed.

The MonetDB/SQL compiler can be downloaded from the
@url{"http://sourceforge.net/project/showfiles.php?group_id=56967",download} 
section at SourceForge. It is already included in the Windows installers.

There are bindings for MonetDB/SQL with for example JDBC, ODBC, PHP and C, 
(see @ref{Application Interfaces} to integrate seemlessly in existing 
developments environments.
Client utilities like Aqua Data Studio and iSQL will work flawlessly 
with MonetDB/SQL to make your experience with MonetDB/SQL even better! 

@menu
* The VOC Tutorial::
* SQL Feature Overview::
@menu
* SQL Feature List::
* SQL Session Variables::
* SQL EXPLAIN Statement::
* SQL DEBUG Statement::
@end menu
* SQL Planned Features::
@end menu

@node The VOC Tutorial, SQL Feature Overview, SQL, TOC
@section The VOC tutorial

@node SQL Feature Overview, SQL Feature List, The VOC Tutorial, SQL
@section SQL Features 
The MonetDB/SQL implementation is based on the SQL-99 standard. 
It is built incrementally over time to cope with the effort
required to realize all features. Priority is given to those
features relevant to our research and upon request from our major
clients.

The plethora of SQL implementations also show that the standard
alone is hardly sufficient. All database systems have extended
or twisted the language structure to satisfy the needs of their
customer, support legacy, and to better tap into the functionality
offered by their kernels. 
MonetDB/SQL is bound to follow this path too. The kernel imposes
limitations on the features that can and cannot be realized.

In the context of programming support, we provide a few
primitives to simplify debugging of SQL programs.

@node SQL Feature List, SQL Session Variables, SQL Feature Overview, SQL
@subsection SQL-99 Feature list
In this section we give an itemized list of the SQL-99 features
supported in the current release.

@node SQL Session Variables, SQL EXPLAIN Statement, SQL Feature List, SQL
@subsection SQL Session Variables
MonetDB/SQL provides a rudimentary scheme to introduce and deal with
session variables.

@node SQL EXPLAIN Statement, SQL DEBUG Statement, SQL Session Variables, SQL
@subsection SQL EXPLAIN Statement
The results of the MonetDB/SQL compiler can be made visible using
the @code{explain} statement modifier.

@example
@end example

@node SQL DEBUG Statement, SQL Planned Features, SQL EXPLAIN Statement, SQL
@subsection SQL DEBUG Statement

The default execution engine for SQL statements is 
the MAL interpreter, which comes with a debugger (See @ref{The MAL Debugger})

@example
@end example

@node SQL Planned Features, XQuery, SQL DEBUG Statement,  SQL
@section Planned Features
In this section we summarize the SQL features scheduled for implementation
and those that won;t be supported in the foreseeable future.
