#!/bin/sh

NAME="$1"
PRELUDE="$2 $3"

Mlog   "$MSERVER --dbname=$TSTDB         < $NAME.1.mil"
eval    $MSERVER --dbname=$TSTDB         < $NAME.1.mil
echo " restart gives correct refcnt b from 0 to 1 "
echo " since b is part of a and persistent expected refcnt should be 2 "
Mlog   "$MSERVER --dbname=$TSTDB         < $NAME.2.mil"
eval    $MSERVER --dbname=$TSTDB         < $NAME.2.mil

