# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

MTSAFE
INCLUDES = ../mapilib ../../common/options ../../common/stream ../R/MonetDB.R/src $(READLINE_INCS)

lib_mcutil = {
	NOINST
	SOURCES = dump.c prompt.c dotmonetdb.c eventparser.c eventparser.h
}

bin_mclient = {
	SOURCES = mclient.c ReadlineTools.c ReadlineTools.h mapisplit-dummy.c profiler-dummy.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(READLINE_LIBS) \
		$(curl_LIBS) $(LTLIBICONV) $(PTHREAD_LIBS) $(MATH_LIBS) $(SOCKET_LIBS)
}

bin_msqldump = {
	SOURCES = msqldump.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS)
}

bin_stethoscope = {
	SOURCES = stethoscope.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(SOCKET_LIBS)
}

bin_tachograph = {
	SOURCES = tachograph.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(SOCKET_LIBS)
}

bin_tomograph = {
	SOURCES = tomograph.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(SOCKET_LIBS)
}

# disabled: it's not really a tool for users, more to debug mapi
# problems, or measure performance
#bin_mnc = {
#	SOURCES = mnc.c
#	LIBS = ../../common/stream/libstream \
#		../mapilib/libmapi \
#		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(SOCKET_LIBS)
#}

man_MANS = mclient.1 msqldump.1

EXTRA_DIST = msqldump.h mprompt.h dotmonetdb.h $(man_MANS)

EXTRA_DIST_DIR = Tests
