# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE
INCLUDES = ../mapilib ../../common/options ../../common/stream $(READLINE_INCS)

lib_mcutil = {
	NOINST
	SOURCES = dump.c prompt.c
}

bin_mclient = {
	SOURCES = mclient.c ReadlineTools.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(READLINE_LIBS) \
		$(curl_LIBS) $(LTLIBICONV)
}

bin_msqldump = {
	SOURCES = msqldump.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS)
}

bin_stethoscope = {
	SOURCES = stethoscope.c
	LIBS = libmcutil ../mapilib/libmapi \
		../../common/stream/libstream \
		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS)
}

bin_mnc = {
	NOINST
	SOURCES = mnc.c
	LIBS = ../../common/stream/libstream \
		../mapilib/libmapi \
		$(curl_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(SOCKET_LIBS)
}

man_MANS = mclient.1 msqldump.1

EXTRA_DIST = msqldump.h mprompt.h ReadlineTools.h $(man_MANS)

EXTRA_DIST_DIR = Tests
