.TH MSQLDUMP 1 MonetDB
.SH NAME
msqldump \- dump a MonetDB/SQL database
.SH SYNOPSIS
.B msqldump
[
.I options
] [
.I dbname
]
.SH DESCRIPTION
MonetDB is a database management system that is developed from a
main-memory perspective with use of a fully decomposed storage model,
automatic index management, extensibility of data types and search
accelerators, SQL- and XML- frontends.
.PP
.I Msqldump
is the program to dump an MonetDB/SQL database.
The dump can be used to populate a new MonetDB/SQL database.
.PP
Before
.I msqldump
starts parsing command line options, it reads a
.I .monetdb
file.
If the environment variable
.B DOTMONETDBFILE
is set, it reads the file pointed to by that variable instead.
When unset,
.I msqldump
searches for a
.I .monetdb
file in the current working directory, and if that doesn't exist, in the
current user's home directory.
This file can contain defaults for the flags
.BR user
and
.BR password .
To disable reading the
.I .monetdb
file, set the variable
.B DOTMONETDBFILE
to the empty string in the environment.
.SH OPTIONS
.TP
\fB\-\-help\fP (\fB\-?\fP)
Print usage information and exit.
.TP
\fB\-\-database=\fP\fIdatabase\fP (\fB\-d\fP \fIdatabase\fP)
Specify the name of the database to connect to.
The
.B \-d
can be omitted if it is the last option.
.TP
\fB\-\-host=\fP\fIhostname\fP (\fB\-h\fP \fIhostname\fP)
Specify the name of the host on which the server runs (default:
localhost).
.TP
\fB\-\-port=\fP\fIportnr\fP (\fB\-p\fP \fIportnr\fP)
Specify the portnumber of the server (default: 50000).
.TP
\fB\-\-user\fP\fB=\fP\fIuser\fP (\fB\-u\fP \fIuser\fP)
Specify the user to connect as.
If this flag is absent, the client will ask for a user name.
.TP
\fB\-\-describe\fP (\fB\-D\fP)
Only dump the database schema.
.TP
\fB\-\-inserts\fP (\fB\-N\fP)
When dumping the table data, use INSERT INTO statements, rather than
COPY INTO + CSV values.
INSERT INTO statements are more portable, and necessary when the
load of the dump is processed by e.g. a JDBC application.
.TP
\fB\-\-functions\fP (\fB\-f\fP)
Only dump functions definitions.
.TP
\fB\-\-table=\fP\fItable\fP (\fB\-t\fP \fItable\fP)
Only dump the specified \fItable\fP.
.TP
\fB\-\-quiet\fP (\fB\-q\fP)
Don't print the welcome message.
.TP
\fB\-\-Xdebug\fP (\fB\-X\fP)
Trace network interaction between
.I mclient
and the server.
.SH SEE ALSO
.IR mclient (1),
.IR mserver5 (1)
