# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

SWIGFLAGS = -DHAVE_LONG_LONG $(INCLUDES)
INCLUDES = ../include $(PYTHON_INCS) 

X_CFLAGS =

lib_odbc = {
	PREFIX =
	NAME = _odbc
	SOURCES = odbc.py.i
	LIBS = ../driver/libMonetODBC $(PYTHON_LIBS)
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}

headers_py = {
	HEADERS = py
	SOURCES = odbc.py.i
	TARGETS = odbc.py
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}

EXTRA_DIST = odbc.py
