# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

MTSAFE

SUBDIRS = tests scripts

EXTRA_DIST = build.xml build.properties release.txt
EXTRA_DIST_DIR = src \
		 lib \
		 example

ant_jar_mcl = {
	DIR = datadir/MonetDB/lib
	FILES = monetdb-1.0-mcl.jar
}

ant_jar_jdbc = {
	DIR = datadir/MonetDB/lib
	FILES = monetdb-1.6-jdbc.jar
}

ant_jar_jdbcclient = {
	DIR = datadir/MonetDB/lib
	FILES = jdbcclient.jar
}

ant_jar_xrpcwrapper = {
	DIR = datadir/MonetDB/lib
	FILES = xrpcwrapper-0.1.jar
}

ant_create_mjclient = {
	COND = NOT_WIN32
	DIR = bindir
	FILES = mjclient
}

ant_create_mjclient_bat = {
	COND = NATIVE_WIN32
	DIR = bindir
	FILES = mjclient.bat
}
