
CREATE TABLE FEAT16 (
EMPNUM INT PRIMARY KEY,
PNUM INT UNIQUE);

INSERT INTO FEAT16 VALUES (3, NULL);
INSERT INTO FEAT16 VALUES (4, NULL);

select * from feat16;

drop table FEAT16;

CREATE TABLE FEAT16 (
PNUM INT);

INSERT INTO FEAT16 VALUES (NULL);
INSERT INTO FEAT16 VALUES (NULL);

ALTER TABLE FEAT16 ADD UNIQUE(PNUM);
INSERT INTO FEAT16 VALUES (NULL);
INSERT INTO FEAT16 VALUES (2);
INSERT INTO FEAT16 VALUES (2);

select * from feat16;

drop table FEAT16;

--- test with multi-columns
CREATE TABLE FEAT16 (
Age int,
PNUM INT);

INSERT INTO FEAT16 VALUES (NULL, NULL);
INSERT INTO FEAT16(age) VALUES (NULL);

ALTER TABLE FEAT16 ADD UNIQUE(PNUM);
INSERT INTO FEAT16 VALUES (NULL, NULL);
INSERT INTO FEAT16 VALUES (2, NULL);
INSERT INTO FEAT16 VALUES (2, NULL);
INSERT INTO FEAT16 VALUES (NULL, 2);
INSERT INTO FEAT16 VALUES (NULL, 2);

select * from feat16;

drop table FEAT16;
CREATE TABLE FEAT16 (
Age int,
PNUM INT);

INSERT INTO FEAT16 VALUES (NULL, NULL);
INSERT INTO FEAT16 VALUES (NULL, NULL);
--INSERT INTO FEAT16(age) VALUES (NULL);

--select * from FEAT16;

ALTER TABLE FEAT16 ADD UNIQUE(AGE,PNUM);
INSERT INTO FEAT16 VALUES (NULL, NULL);
INSERT INTO FEAT16 VALUES (2, NULL);
INSERT INTO FEAT16 VALUES (2, NULL);
INSERT INTO FEAT16 VALUES (NULL, 2);
INSERT INTO FEAT16 VALUES (NULL, 2);
INSERT INTO FEAT16 VALUES (2, 2);
INSERT INTO FEAT16 VALUES (2, 2);

select * from feat16;

drop table FEAT16;

---- insert multiple values

create table t1 (id int);
insert into t1 values(1);
insert into t1 values(1);
insert into t1 values(1);
insert into t1 values(1);


create table t2 (id int unique);
insert into t2 select * from t1;

select * from t2;

drop table t1;
drop table t2;
