
CREATE TABLE FEAT16 (
EMPNUM INT PRIMARY KEY,
PNUM INT UNIQUE);

INSERT INTO FEAT16 VALUES (3, NULL);
INSERT INTO FEAT16 VALUES (4, NULL);

select * from feat16;

drop table FEAT16;

CREATE TABLE FEAT16 (
PNUM INT);

INSERT INTO FEAT16 VALUES (NULL);
INSERT INTO FEAT16 VALUES (NULL);

ALTER TABLE FEAT16 ADD UNIQUE(PNUM);
INSERT INTO FEAT16 VALUES (NULL);
INSERT INTO FEAT16 VALUES (2);
INSERT INTO FEAT16 VALUES (2);

select * from feat16;

drop table FEAT16;
