#! /bin/sh

# helps bootstrapping NDK, when checked out from CVS
# requires GNU autoconf and GNU automake
# this is not meant to go into the distributions

#~/autogen/autogen.py
test -f conf/ltmain.sh || libtoolize -c -f; perl -i -p -e  's/link \| relink\)/link \| relink\)\n    CC=\$arg/g' conf/ltmain.sh
aclocal -I .
autoheader
automake -a -c

# dirty hack, needed because automake 1.4 generates the wrong dependency
echo "mel_tab.h: mel_tab.cc" >> src/mel/Makefile.in

autoupdate
autoconf

exit 0

