#!/bin/bash

# helps bootstrapping Monet, when checked out from CVS
# requires GNU autoconf, automake and libtool
# this is not meant to go into the distributions

find . -name .cache\* \-exec rm {} \;
src/utils/autogen/autogen.py `pwd`
cat configure.ag > configure.in
echo "AC_OUTPUT(" >> configure.in
cat acout.in  >> configure.in
echo ")" >> configure.in

test -f conf/ltmain.sh || libtoolize -c -f; 
#if [ ! "`grep \"CC=\$arg\" conf/ltmain.sh 2>/dev/null`" ]; then
#  perl -i.bak -p -e  's/link \| relink\)/link \| relink\)\n    CC=\$arg/g' conf/ltmain.sh

#fi
# default deplibs_check_method (pass all libs)
# needed since deplibs is switched off in libtool 1.3c (we cannot wait for 1.4)
perl -i.bak -p -e  's/&& deplibs_check_method=unknown/&& deplibs_check_method=pass_all/g' conf/ltconfig
aclocal -I . -I conf
# patch aclocal.m4 to call the linker with "-IPA" on IRIX (medusa)
# (just adding -IPA to LDFLAGS somehow doesn't help ...)
perl -i.bak -p -e 's|(LD-ld. )|$1-IPA |g' aclocal.m4
autoheader
automake -a -c

# dirty hack, needed because automake 1.4 generates the wrong dependency
#echo "mel_tab.h: mel_tab.cc" >> src/mel/Makefile.in
perl -i.bak -p -e  's/tab\.hh/tab.h/g' src/mel/Makefile.in

#autoupdate
autoconf

# patch configure to cope with Intel's C/C++ compiler for Linux ("icc")
cat << "EOF" | patch configure
--- configure~	Wed May 23 20:46:51 2001
+++ configure	Wed May 23 20:49:57 2001
@@ -1075,7 +1075,7 @@
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   echo 'void f(){}' > conftest.c
-if test -z "`${CC-cc} -g -c conftest.c 2>&1`"; then
+if test -z "`${CC-cc} -g -c conftest.c 2>&1 | egrep -v '^conftest.c:$|^icc: NOTE: The evaluation period for this product ends on .* UTC.$'`"; then
   ac_cv_prog_cc_g=yes
 else
   ac_cv_prog_cc_g=no
@@ -1218,7 +1218,7 @@
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   echo 'void f(){}' > conftest.cc
-if test -z "`${CXX-g++} -g -c conftest.cc 2>&1`"; then
+if test -z "`${CXX-g++} -g -c conftest.cc 2>&1 | egrep -v '^conftest.cc:$|^icc: NOTE: The evaluation period for this product ends on .* UTC.$'`"; then
   ac_cv_prog_cxx_g=yes
 else
   ac_cv_prog_cxx_g=no
EOF

exit 0

