
SUBDIRS = src conf doc scripts tests 

EXTRA_DIST = rules.mk bootstrap lady.gif configure.ag RunMtest.in RunMtest.bat.in
EXTRA_DIST_DIR = NT

EXTRA_HEADERS = config.h

scripts_gif = {
	DIR = pkgdatadir
	SOURCES = lady.gif
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
