# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

## Process this file with automake to produce Makefile.in

#EXTRA_HEADERS = sql_storage.h

SUBDIRS = bat 

INCLUDES = ../include ../common \
		   ../../common/options \
		   ../../common/stream \
		   ../../gdk

lib_store = {
	NOINST
	DIR = libdir
	SOURCES = \
		store_dependency.c store_sequence.c \
		store.c sql_catalog.c \
		sql_storage.h store_dependency.h \
		store_sequence.h
}
