gem_monetdb = {
	FILES = ruby-monetdb-sql-0.1.gemspec
	# activerecord-monetdb-adapter-0.1.gemspec
	DIR = $(prefix)/$(RUBY_DIR)
}

EXTRA_DIST = Changelog README TODO ruby-monetdb-sql-0.1.gemspec activerecord-monetdb-adapter-0.1.gemspec
EXTRA_DIST_DIR = examples lib adapter
