## Process this file with automake to produce Makefile.in

YFLAGS = -d -p sql

INCLUDES = \
	-I../../common -I../../gdk  \
	-I../modules/atoms \
	-I../../mal $(Z_CFLAGS) $(BZ_CFLAGS)


lib_sql = {
	SOURCES = \
		sqlparser.y sqlscan.c sqlscan.h sqlexecute.c sqlexecute.h \
		sql.c sql.h optimize.h optimize.c \
		catalog.c catalog.h types.c types.h \
		list.c list.h symbol.c symbol.h sym.h \
		statement.c statement.h \
		atom.c atom.h mem.h string.c \
		datetime.c datetime.h var.h scope.c scope.h context.h
	WINLIBS = $(MONET_LIBS) -lbat
	HEADERS = h tab.h
}
