# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

## Process this file with automake to produce Makefile.in

INCLUDES = .. ../../include ../../common \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk \
		   ../../../monetdb5/modules/atoms \
		   ../../../monetdb5/modules/kernel \
		   ../../../monetdb5/mal \
		   ../../../monetdb5/modules/mal \
		   ../../../monetdb5/optimizer \
		   ../../../monetdb5/scheduler

lib_batstore = {
	NOINST
	DIR = libdir
	SOURCES = \
		bat_table.c bat_storage.c bat_logger.c bat_utils.c \
		res_table.c 
}

EXTRA_DIST = bat_logger.h bat_storage.h bat_table.h bat_utils.h res_table.h
