# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = .. \
       ../.. \
       ../../../../include \
	   ../../../../common \
	   ../../../../storage \
	   ../../../../server \
	   ../../../../../monetdb5/modules/atoms \
	   ../../../../../monetdb5/modules/kernel \
	   ../../../../../monetdb5/mal \
	   ../../../../../monetdb5/modules/mal \
	   ../../../../../monetdb5/optimizer \
	   ../../../../../monetdb5/scheduler \
	   ../../../../../common/options \
	   ../../../../../common/stream \
	   ../../../../../common/utils \
	   ../../../../../gdk \
	   ../../../../../geom/lib \
	   ../../../../../geom/monetdb5 \
	   $(GDAL_CFLAGS)

lib__shp = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = shp.c shp.h
	LIBS = NATIVE_WIN32?../../../../../monetdb5/tools/libmonetdb5 \
	       $(GDAL_LIBS)
}

headers_shpmal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = shp.mal
}

headers_shpsql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 75_shp.sql
}

headers_shpautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 75_shp.mal
}
