# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../misc ../mal ../optimizer \
		   ../modules/atoms ../modules/mal ../modules/kernel \
		   ../../clients/mapilib \
		   ../../common/options \
		   ../../common/stream \
		   ../../gdk

MTSAFE

lib_scheduler = {
	NOINST
	SOURCES = \
		run_adder.c run_adder.h \
		run_isolate.c run_isolate.h \
		run_memo.c run_memo.h \
		run_octopus.c run_octopus.h \
		run_pipeline.mx 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = run_adder.mal run_isolate.mal run_pipeline.mx run_memo.mal run_octopus.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = run_adder.mal run_centipede.mal run_centipede.h run_isolate.mal run_memo.mal run_octopus.mal
