# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2017 MonetDB B.V.

INCLUDES = ../mal ../optimizer \
		   ../modules/atoms ../modules/mal ../modules/kernel \
		   ../../clients/mapilib \
		   ../../common/options \
		   ../../common/stream \
		   ../../common/utils \
		   ../../gdk

MTSAFE

lib_scheduler = {
	NOINST
	SOURCES = \
		run_adder.c run_adder.h \
		run_isolate.c run_isolate.h \
		run_memo.c run_memo.h \
		srvpool.c srvpool.h \
		run_pipeline.c run_pipeline.h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = run_adder.mal run_isolate.mal run_memo.mal srvpool.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = run_adder.mal run_isolate.mal run_memo.mal srvpool.mal
