@echo off

set PATH=%CLIENTS_PREFIX%\lib\MonetDB\Tests;%PATH%

set PYTHONPATH=%MONETDB_PREFIX%\%PYTHON_LIBDIR%;%PYTHONPATH%
set PYTHONPATH=%CLIENTS_PREFIX%\%PYTHON_LIBDIR%;%CLIENTS_PREFIX%\%PYTHON_LIBDIR%\MonetDB;%PYTHONPATH%
set PYTHONPATH=%SQL_PREFIX%\%PYTHON_LIBDIR%;%SQL_PREFIX%\%PYTHON_LIBDIR%\MonetDB;%PYTHONPATH%

set PYTHONPATH=%TSTBLDBASE%\NT\src\backends\python\monet5;%PYTHONPATH%

prompt # $t $g  
echo on

sqlsample.py "%GDK_DBFARM%" "%TSTDB%" 5
