INCLUDES = -I../mal -I../modules/mal $(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(PCL_FLAGS) $(PCRE_CFLAGS)


MTSAFE

lib_optimizer = {
	DIR = pkglibdir
	SEP = _
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_commonTerms.mx opt_iterators.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx

	HEADERS = h 
	#SCRIPTS = mal
	LIBS = ../mal/libmal $(MONETDB_LIBS) -lbat -lstream $(MATH_LIBS) \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_commonTerms.mx opt_iterators.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx
}

EXTRA_DIST_DIR = Tests
