# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

INCLUDES = -I../mal -I../modules/atoms -I../modules/mal -I../modules/kernel $(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS)


MTSAFE

lib_optimizer = {
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_constants.mx opt_commonTerms.mx opt_datacyclotron.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_datacell.mx opt_reorder.mx opt_prejoin.mx opt_compression.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx opt_derivepath.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx \
		opt_statistics.mx opt_trace.mx  opt_recycler.mx opt_dataflow.mx \
		opt_cluster.mx  opt_replication.mx opt_dictionary.mx opt_mapreduce.mx \
		opt_mitosis.mx opt_octopus.mx  opt_history.mx opt_selcrack.mx opt_sidcrack.mx

	#SCRIPTS = mal
	LIBS = ../modules/atoms/lib_mtime ../mal/libmonetdb5 \
		../modules/mal/lib_bpm ../modules/mal/lib_remote ../modules/kernel/lib_algebra \
		../modules/kernel/lib_group \
		$(MONETDB_LIBS) -lbat -lstream $(MATH_LIBS) \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
}

headers_optimizer = {
	DIR = includedir/MonetDB5/optimizer
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_constants.mx opt_commonTerms.mx opt_datacyclotron.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_datacell.mx opt_reorder.mx opt_prejoin.mx opt_compression.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx opt_derivepath.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx \
		opt_statistics.mx opt_trace.mx  opt_recycler.mx opt_dataflow.mx \
		opt_cluster.mx  opt_replication.mx opt_dictionary.mx opt_mapreduce.mx \
		opt_mitosis.mx opt_octopus.mx  opt_history.mx opt_selcrack.mx opt_sidcrack.mx

	HEADERS = h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES =  opt_prelude.mx \
		opt_support.mx  opt_crack.mx optimizer.mx  opt_factorize.mx \
		opt_deadcode.mx opt_garbageCollector.mx opt_strengthReduction.mx \
		opt_aliases.mx opt_constants.mx opt_commonTerms.mx opt_datacyclotron.mx \
		opt_coercion.mx opt_emptySet.mx opt_peephole.mx opt_multiplex.mx \
		opt_singleton.mx opt_costModel.mx opt_reduce.mx opt_macro.mx \
		opt_accumulators.mx opt_qep.mx opt_mergetable.mx \
		opt_remoteQueries.mx opt_joinselect.mx opt_partitions.mx \
		opt_datacell.mx opt_reorder.mx opt_prejoin.mx opt_compression.mx \
		opt_evaluate.mx opt_inline.mx opt_pushranges.mx opt_derivepath.mx \
		opt_accessmode.mx opt_joinpath.mx opt_heuristics.mx opt_remap.mx \
		opt_statistics.mx opt_trace.mx  opt_recycler.mx opt_dataflow.mx \
		opt_cluster.mx  opt_replication.mx opt_dictionary.mx opt_mapreduce.mx \
		opt_mitosis.mx opt_octopus.mx  opt_history.mx opt_selcrack.mx opt_sidcrack.mx
}

EXTRA_DIST_DIR = Tests
