# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

MTSAFE

# FIXME: libMonetODBC is actually a module, once cannot link against
# that on Darwin.  We need to properly link against (unix)ODBC and use
# it's drivermanager which correctly dlopens the MonetODBC module.  This
# requires a odbc.ini file, and testing to be aware of it as well.
#BINS = {
#	CONDINST = HAVE_TESTING
#	DIR = libdir/monetdb/tests
#	SOURCES = odbcsample1.c testgetinfo.c
#	LIBS = ../driver/libMonetODBC ../../mapilib/libmapi $(curl_LIBS)
#}

bin_odbctest = {
	COND = NATIVE_WIN32
	SOURCES = odbcsample1.c
	LIBS = -lodbc32
}
