#!/bin/bash

# helps bootstrapping Monet, when checked out from CVS
# requires GNU autoconf, automake and libtool
# this is not meant to go into the distributions

find . -name .cache* \-exec rm {} \;
src/utils/autogen/autogen.py `pwd`
cat configure.ag > configure.in
echo "AC_OUTPUT(" >> configure.in
cat acout.in  >> configure.in
echo ")" >> configure.in

test -f conf/ltmain.sh || libtoolize -c -f; 
#if [ ! "`grep \"CC=\$arg\" conf/ltmain.sh 2>/dev/null`" ]; then
#  perl -i.bak -p -e  's/link \| relink\)/link \| relink\)\n    CC=\$arg/g' conf/ltmain.sh

#fi
# default deplibs_check_method (pass all libs)
# needed since deplibs is switched off in libtool 1.3c (we cannot wait for 1.4)
perl -i.bak -p -e  's/&& deplibs_check_method=unknown/&& deplibs_check_method=pass_all/g' conf/ltconfig
aclocal -I .
autoheader
automake -a -c

#autoupdate
autoconf

exit 0

