SUBDIRS = src conf #scripts 

EXTRA_DIST = rules.mk bootstrap lady.gif configure.ag RunMtest.in RunMtest.bat.in \
	 RunMapprove.in RunMapprove.bat.in sysdefs.h.in
EXTRA_DIST_DIR = NT

EXTRA_HEADERS = config.h sysdefs.h

scripts_gif = {
	DIR = pkgdatadir
	SOURCES = lady.gif
}
TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)

