# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

# mal, modules, optimizer, scheduler: the main libmonetdb5 body
# tools: builds libmonetdb5 from mal, modules, optimizer, scheduler
# extras: builds optional/separate libraries that require libmonetdb5
SUBDIRS = mal modules optimizer scheduler tools extras NATIVE_WIN32?NT
