#!/bin/bash

# Once you have checked out MonetDB_5 from /ufs/monet/repository/monet5,
# run this script to checkout from cvs.sourceforge.net:/cvsroot/monetdb
# those directories that MonetDB_5 shares with MonetDB_4-3.

SharedDirs="conf src/common src/gdk src/testing src/utils src/mapi/clients src/mapi/examples src/mapi/Tests"

if [ ! "$1" ] ; then
	echo ''
	echo 'Usage: $0 <SF-username>'
	echo ' <SF-username>: your username at SourceForge.net,'
	echo '                or "anonymous", in case you are not a'
	echo '                registered user at SourceForge.net.'
	echo ''
	exit 1
fi

SFuser="$1"
if [ "$SFuser" = "anonymous" ] ; then
	SFuser="pserver:$SFuser"
  else
	SFuser="ext:$SFuser"
fi
SFsource="-d:$SFuser@cvs.monetdb.sourceforge.net:/cvsroot/monetdb"

echo "pruning empty directories..."
cvs -q update -d -P
echo "pruning empty directories... done."

echo "checking-out directories shared with MonetDB_4-3:"
for d0 in $SharedDirs ; do
	echo "$d0:"
	if [ "${d0%/*}" = "$d0" ] ; then
		d1="."
		d2="$d0"
	  else
		d1="${d0%/*}"
		d2="${d0##*/}"
	fi
	( cd $d1 && (
		Entries="yes"
		if [ ! -d "$d2" ] ; then
			cvs -q $SFsource checkout -P -d $d2 MonetDB/$d0
		  else
			x="`cat $d2/CVS/Root 2>/dev/null`/`cat $d2/CVS/Repository 2>/dev/null`"
			y="${SFsource#*@}/MonetDB/$d0"
			if [ "${x%$y}" = "$x" ] ; then
				echo "Warning: Directory $d0 does already exist,"
				echo "         but is not a checkout of $y !"
				Entries=""
			fi
		fi
		if [ "$Entries"  -a  ! "`grep "^D/$d2////$" CVS/Entries`" ] ; then
			echo "D/$d2////" >> CVS/Entries
		fi
	))
	echo "$d0: done."
done
echo "checking-out directories shared with MonetDB_4-3: done."

