# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = \
	../../mapilib \
	../../../common/options \
	$(ODBC_INCS)

DEFS = @DEFS@

lib_MonetODBC = {
	MODULE
	SOURCES = \
	ODBCConvert.c \
	ODBCDbc.c \
	ODBCDbc.h \
	ODBCDesc.c \
	ODBCDesc.h \
	ODBCEnv.c \
	ODBCEnv.h \
	ODBCError.c \
	ODBCError.h \
	ODBCGlobal.h \
	ODBCStmt.c \
	ODBCStmt.h \
	ODBCUtil.c \
	ODBCUtil.h \
	SQLAllocConnect.c \
	SQLAllocEnv.c \
	SQLAllocHandle.c \
	SQLAllocStmt.c \
	SQLBindCol.c \
	SQLBindParameter.c \
	SQLBrowseConnect.c \
	SQLBulkOperations.c \
	SQLCancel.c \
	SQLCloseCursor.c \
	SQLColAttribute.c \
	SQLColAttributes.c \
	SQLColumnPrivileges.c \
	SQLColumns.c \
	SQLConnect.c \
	SQLCopyDesc.c \
	SQLDataSources.c \
	SQLDescribeCol.c \
	SQLDescribeParam.c \
	SQLDisconnect.c \
	SQLDriverConnect.c \
	SQLDrivers.c \
	SQLEndTran.c \
	SQLError.c \
	SQLExecDirect.c \
	SQLExecute.c \
	SQLExtendedFetch.c \
	SQLFetch.c \
	SQLFetchScroll.c \
	SQLForeignKeys.c \
	SQLFreeConnect.c \
	SQLFreeEnv.c \
	SQLFreeHandle.c \
	SQLFreeStmt.c \
	SQLGetConnectAttr.c \
	SQLGetConnectOption.c \
	SQLGetCursorName.c \
	SQLGetData.c \
	SQLGetDescField.c \
	SQLGetDescRec.c \
	SQLGetDiagField.c \
	SQLGetDiagRec.c \
	SQLGetEnvAttr.c \
	SQLGetFunctions.c \
	SQLGetInfo.c \
	SQLGetStmtAttr.c \
	SQLGetStmtOption.c \
	SQLGetTypeInfo.c \
	SQLMoreResults.c \
	SQLNativeSql.c \
	SQLNumParams.c \
	SQLNumResultCols.c \
	SQLParamData.c \
	SQLParamOptions.c \
	SQLPrepare.c \
	SQLPrimaryKeys.c \
	SQLProcedureColumns.c \
	SQLProcedures.c \
	SQLPutData.c \
	SQLRowCount.c \
	SQLSetConnectAttr.c \
	SQLSetConnectOption.c \
	SQLSetCursorName.c \
	SQLSetDescField.c \
	SQLSetDescRec.c \
	SQLSetEnvAttr.c \
	SQLSetParam.c \
	SQLSetPos.c \
	SQLSetScrollOptions.c \
	SQLSetStmtAttr.c \
	SQLSetStmtOption.c \
	SQLSpecialColumns.c \
	SQLStatistics.c \
	SQLTablePrivileges.c \
	SQLTables.c \
	SQLTransact.c \
	driver.rc \
	ODBC.syms
	LIBS = ../../mapilib/libmapi $(LTLIBICONV) $(ODBC_LIBS) $(SOCKET_LIBS)
}

