
INCLUDES = $(MONETDB_INCS) \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS) $(PCL_FLAGS) $(PCRE_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		chopper.mx language.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx const.mx bbp.mx io.mx \
		enum.mx inspect.mx crackers.mx \
		thread.mx clients.mx tablet.mx \
		transaction.mx factory.mx mdb.mx  \
		statistics.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) 
}

lib__pcre = {
	DIR = pkglibdir
	SOURCES = pcre.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	WINLIBS = ../../common/libstream ../../gdk/libbat \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
	LIBS = $(PCRE_LIBS)
}

#doc_mal = {
#	DIR = pkgdatadir/docs/modules/mal
#	SOURCES = \
#		startup.mx mal_init.mx language.mx box.mx multiplex.mx  \
#		atoms.mx profiler.mx const.mx bbp.mx io.mx \
#		enum.mx inspect.mx crackers.mx \
#		chopper.mx thread.mx clients.mx tablet.mx \
#		transaction.mx factory.mx mdb.mx 
#}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = language.mx mal_init.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx const.mx bbp.mx  \
		enum.mx inspect.mx crackers.mx io.mal \
		chopper.mx thread.mx clients.mx tablet.mx \
		transaction.mx factory.mx mdb.mx pcre.mx \
		statistics.mx
}

#EXTRA_DIST_DIR = Tests
