
INCLUDES = $(MONETDB_INCS) \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		chopper.mx language.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx const.mx mil.mx bbp.mx io.mx \
		enum.mx streams.mx inspect.mx crackers.mx \
		thread.mx optimizer.mx clients.mx tablet.mx \
		transaction.mx reference.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
doc_mal = {
	DIR = pkgdatadir/docs/modules/mal
	SOURCES = \
		startup.mx mal_init.mx language.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx const.mx mil.mx bbp.mx io.mx \
		enum.mx streams.mx inspect.mx crackers.mx \
		chopper.mx thread.mx optimizer.mx clients.mx tablet.mx \
		transaction.mx reference.mx
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = language.mx mal_init.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx const.mx mil.mx bbp.mx  \
		enum.mx streams.mx inspect.mx crackers.mx io.mal \
		chopper.mx thread.mx optimizer.mx clients.mx tablet.mx \
		transaction.mx reference.mx
}

#EXTRA_DIST_DIR = Tests
