
INCLUDES = $(MONETDB_INCS) \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		chopper.mx language.mx box.mx \
		profiler.mx const.mx bbp.mx io.mx \
		inspect.mx crackers.mx \
		thread.mx clients.mx tablet.mx \
		transaction.mx factory.mx mdb.mx  \
		statistics.mx rsbox.mx partitions.mx 
		#datacell.mx 

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream
}

lib__pcre = {
	DIR = pkglibdir
	SOURCES = pcre.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream $(PCRE_LIBS) 
}

#doc_mal = {
#	DIR = pkgdatadir/docs/modules/mal
#	SOURCES = \
#		mal_init.mx language.mx box.mx \
#		profiler.mx const.mx bbp.mx io.mx \
#		inspect.mx crackers.mx \
#		chopper.mx thread.mx clients.mx tablet.mx \
#		transaction.mx factory.mx mdb.mx 
#}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = language.mx mal_init.mx box.mx \
		profiler.mx const.mx bbp.mx  \
		inspect.mx crackers.mx io.mal \
		chopper.mx thread.mx clients.mx tablet.mx \
		transaction.mx factory.mx mdb.mx pcre.mx \
		statistics.mx rsbox.mx partitions.mx 
	#datacell.mx 
}

#EXTRA_DIST_DIR = Tests
