# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

EXTRA_DIST_DIR = Tests

MTSAFE
INCLUDES = $(MONETDB5_INCS) $(MONETDB_INCS)

lib__example = {
	MODULE
	DIR = libdir/MonetDB5
	SOURCES = example.c
	LIBS = $(MONETDB5_MODS) 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = example.mal
}
EXTRA_DIST = example.mal example.h
