# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = .. \
	../../../include \
	../../../common \
	../../../storage \
	../../../server \
	../../../../monetdb5/modules/atoms \
	../../../../monetdb5/modules/kernel \
	../../../../monetdb5/mal \
	../../../../monetdb5/modules/mal \
	../../../../monetdb5/optimizer \
	../../../../common/options \
	../../../../common/stream \
	../../../../gdk

lib__lsst = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = lsst.c lsst.h
	LIBS = NATIVE_WIN32?../../../../monetdb5/tools/libmonetdb5 \
		NATIVE_WIN32?../../../../gdk/libbat
}

headers_lsstmal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = lsst.mal
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5
	SOURCES = lsst.sql
}

headers_lsstautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 80_lsst.mal
}

EXTRA_DIST_DIR = Tests
