# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

## Process this file with automake to produce Makefile.in

INCLUDES = .. \
	../../../include \
	../../../common \
	../../../storage \
	../../../server \
	../../../../monetdb5/modules/atoms \
	../../../../monetdb5/modules/kernel \
	../../../../monetdb5/mal \
	../../../../monetdb5/modules/mal \
	../../../../monetdb5/optimizer \
	../../../../clients/mapilib \
	../../../../common/options \
	../../../../common/stream \
	../../../../gdk

lib__datacell = {
	MODULE
	DIR = libdir/monetdb5
	SEP = _
	SOURCES = basket.c \
		  dcsocket.c \
		  receptor.c \
		  petrinet.c \
		  dcoperator.c \
		  opt_datacell.c \
		  datacell.c \
		  emitter.c 

	LIBS = ../../../../monetdb5/tools/libmonetdb5 \
		../../../../gdk/libbat 
}

bin_actuator = {
	SOURCES = actuator.c dcsocket.c
	LIBS = ../../../../common/stream/libstream \
		   ../../../../common/options/libmoptions \
		   ../../../../gdk/libbat \
		   ../../../../monetdb5/tools/libmonetdb5
		
}

bin_sensor = {
	SOURCES = sensor.c dcsocket.c
	LIBS = ../../../../common/stream/libstream \
		   ../../../../common/options/libmoptions \
		   ../../../../gdk/libbat \
		   ../../../../monetdb5/tools/libmonetdb5
}

scripts_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = basket.mal \
		  receptor.mal \
		  emitter.mal \
		  petrinet.mal \
		  datacell.mal \
		  opt_datacell.mal \
		  dcoperator.mal
}

scripts_sql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 50_datacell.sql 
}

headers_datacellautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 50_datacell.mal
}

EXTRA_DIST = 50_datacell.mal 50_datacell.sql basket.mal basket.h datacell.mal datacell.h dcoperator.mal dcoperator.h dcsocket.h emitter.mal emitter.h opt_datacell.mal opt_datacell.h petrinet.mal petrinet.h receptor.mal receptor.h
