# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

INCLUDES = ../../include ../../common ../../storage ../../server \
	$(MONETDB_INCS)

lib__sql_server = {
	DIR = libdir/MonetDB
	SOURCES = \
		sql_server.mx \
		sql_session.mx \
		sql_gencode.mx \
		sql_result.mx
	LIBS = ../../server/libsqlserver ../../storage/bat/libbatstore ../../common/libsqlcommon $(MONETDB_LIBS) -lbat -lmonet -lstream -l_streams -l_bat -l_builtin -l_ascii_io -l_algebra -l_str -l_monettime
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = sql_server.mx 
}

EXTRA_DIST_DIR = Tests
