
INCLUDES = ../../common ../../server $(MONET_INCS)

lib__sql_server = {
	DIR = libdir/MonetDB
	SOURCES = \
		sql_server.mx \
		sql_session.mx \
		sql_gencode.mx 
	WINLIBS = -lbat -lmonet -lstream -l_streams -l_bat -l_kernel -l_ascii_io -l_algebra -l_str -l_monettime
	LIBS = ../../server/libsqlserver $(MONET_LIBS)
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = sql_server.mx 
}
