
MTSAFE

INCLUDES = $(PTHREAD_INCS)

NO_INLINE_FILES = gdk_scanselect.mx gdk_relop.mx

lib_gdk = { 
	NAME = bat
	SOURCES = \
		gdk.mx gdk_batop.mx gdk_desc.mx gdk_search.mx gdk_tm.mx \
		gdk_align.mx gdk_bbp.mx gdk_heap.mx gdk_setop.mx gdk_utils.mx \
		gdk_atoms.mx gdk_compress.mx gdk_qsort.mx gdk_storage.mx \
		gdk_bat.mx gdk_delta.mx gdk_relop.mx gdk_system.mx \
		gdk_value.mx gdk_posix.mx \
		gdk_scanselect.mx bat.feps bat1.feps bat2.feps
	HEADERS = h
	LIBS = $(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS)
}

EXTRA_DIST = index.html 
EXTRA_DIST_DIR = Tests
