# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at 
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the Monet Database System.
# 
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2002 CWI.  
# All Rights Reserved.
# 
# Contributor(s):
# 		Martin Kersten <Martin.Kersten@cwi.nl>
# 		Peter Boncz <Peter.Boncz@cwi.nl>
# 		Niels Nes <Niels.Nes@cwi.nl>
# 		Stefan Manegold  <Stefan.Manegold@cwi.nl>


MTSAFE

INCLUDES = -I../common $(PTHREAD_INCS)

NO_INLINE_FILES = gdk_scanselect.mx gdk_relop.mx

lib_gdk = { 
	NAME = bat
	SOURCES = \
		gdk.mx gdk_batop.mx gdk_desc.mx gdk_search.mx gdk_tm.mx \
		gdk_align.mx gdk_bbp.mx gdk_heap.mx gdk_setop.mx gdk_utils.mx \
		gdk_atoms.mx gdk_compress.mx gdk_qsort.mx gdk_storage.mx \
		gdk_bat.mx gdk_delta.mx gdk_relop.mx gdk_system.mx \
		gdk_value.mx gdk_posix.mx \
		gdk_scanselect.mx bat.feps bat1.feps bat2.feps
	HEADERS = h
	LIBS = $(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS)
}

EXTRA_DIST = index.html 
EXTRA_DIST_DIR = Tests
