# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

EXTRA_DIST = \
		Test_Cautocommit.java \
		Test_Csavepoints.java \
		Test_Ctransaction.java \
		Test_PStimedate.java \
		Test_Rbooleans.java \
		Test_Rpositioning.java \
		Test_Rtimedate.java \
		Test_Sbatching.java \
		Test_Rmetadata.java \
		Test_Cmanycon.java \
		build.xml build.properties

ant_compile = {
	DIR = pkgdatadir/Tests
	FILES = \
		Test_Cautocommit.class \
		Test_Csavepoints.class \
		Test_Ctransaction.class \
		Test_PStimedate.class \
		Test_Rbooleans.class \
		Test_Rpositioning.class \
		Test_Rtimedate.class \
		Test_Sbatching.class \
		Test_Rmetadata.class \
		Test_Cmanycon.class
}
