MTSAFE
LIBS = {
        DIR = pkglibdir
        SEP = _
        SOURCES = mil_schema.mx mil_algebra_procs.mx mil_system_procs.mx

        HEADERS = h 
        SCRIPTS = mal mil ""
}


doc_mal = {
	DIR = pkgdatadir/docs/modules/mil
	SOURCES = mil_schema.mx mil_algebra_procs.mx mil_system_procs.mx
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mil_schema.mx  mil_algebra_procs.mx mil_system_procs.mx
}

#EXTRA_DIST_DIR = Tests
