# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

#
# Contributor(s):
#		Martin Kersten <Martin.Kersten@cwi.nl>
#		Peter Boncz <Peter.Boncz@cwi.nl>
#		Niels Nes <Niels.Nes@cwi.nl>
#		Stefan Manegold  <Stefan.Manegold@cwi.nl>

EXTRA_DIST_DIR = Tests

MTSAFE
INCLUDES = $(MONETDB_INCS)

lib__example = {
	DIR = libdir/MonetDB
	SOURCES = example.mx
	HEADERS = h
	LIBS = $(MONETDB_LIBS) 
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = example.mx
}
