
MTSAFE
INCLUDES = $(MONET_INCS)

lib__example = {
	DIR = libdir/MonetDB
	SOURCES = example.mx
	HEADERS = h
	LIBS = $(MONET_LIBS) 
	LDFLAGS = -module
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = example.mx
}
