 [
  [ N 14,	I 774,	I (-1),	I _doc,	S "auction.xml",	 I 2 ]
 ,[ N 15,	I 773,	I 0,	I _elem,	S "site",	I 2 ]
 ,[ N 16,	I 347,	I 1,	I _elem,	S "regions",	I 2 ]
 ,[ N 17,	I 51,	I 2,	I _elem,	S "africa",	I 2 ]
 ,[ N 18,	I 50,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 19,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 20,	I 0,	I 5,	I _text,	S "item0",	I 2 ]
 ,[ N 21,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 22,	I 0,	I 5,	I _text,	S "United States",	I 2 ]
 ,[ N 23,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 24,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 25,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 26,	I 0,	I 5,	I _text,	S "duteous nine eighteen ",	I 2 ]
 ,[ N 27,	I 1,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 28,	I 0,	I 5,	I _text,	S "Creditcard",	I 2 ]
 ,[ N 29,	I 9,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 30,	I 8,	I 5,	I _elem,	S "parlist",	I 2 ]
 ,[ N 31,	I 4,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 32,	I 3,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 33,	I 0,	I 8,	I _text,	S "\012page rous lady idle authority capt professes stabs monster petition heave humbly removes rescue runs shady peace most piteous worser oak assembly holes patience but malice whoreson mirrors master tenants smocks yielded ",	I 2 ]
 ,[ N 34,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 35,	I 0,	I 9,	I _text,	S " officer embrace such fears distinction attires ",	I 2 ]
 ,[ N 36,	I 2,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 37,	I 1,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 38,	I 0,	I 8,	I _text,	S "\012shepherd noble supposed dotage humble servilius bitch theirs venus dismal wounds gum merely raise red breaks earth god folds closet captain dying reek \012",	I 2 ]
 ,[ N 39,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 40,	I 0,	I 5,	I _text,	S "Will ship internationally, See description for charges",	I 2 ]
 ,[ N 41,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 42,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 43,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 44,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 45,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 46,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 47,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 48,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 49,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 50,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 51,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 52,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 53,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 54,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 55,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 56,	I 12,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 57,	I 11,	I 5,	I _elem,	S "mail",	I 2 ]
 ,[ N 58,	I 1,	I 6,	I _elem,	S "from",	I 2 ]
 ,[ N 59,	I 0,	I 7,	I _text,	S "Dominic Takano mailto:Takano@yahoo.com",	I 2 ]
 ,[ N 60,	I 1,	I 6,	I _elem,	S "to",	I 2 ]
 ,[ N 61,	I 0,	I 7,	I _text,	S "Mechthild Renear mailto:Renear@acm.org",	I 2 ]
 ,[ N 62,	I 1,	I 6,	I _elem,	S "date",	I 2 ]
 ,[ N 63,	I 0,	I 7,	I _text,	S "10/12/1999",	I 2 ]
 ,[ N 64,	I 4,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 65,	I 0,	I 7,	I _text,	S "\012asses scruple learned crowns preventions half whisper logotype weapons doors factious already pestilent sacks dram atwain girdles deserts flood park lest graves discomfort sinful conceiv therewithal motion stained preventions greatly suit observe sinews enforcement ",	I 2 ]
 ,[ N 66,	I 1,	I 7,	I _elem,	S "emph",	I 2 ]
 ,[ N 67,	I 0,	I 8,	I _text,	S " armed ",	I 2 ]
 ,[ N 68,	I 0,	I 7,	I _text,	S " gold gazing set almost catesby turned servilius cook doublet preventions shrunk \012",	I 2 ]
 ,[ N 69,	I 61,	I 2,	I _elem,	S "asia",	I 2 ]
 ,[ N 70,	I 60,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 71,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 72,	I 0,	I 5,	I _text,	S "item1",	I 2 ]
 ,[ N 73,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 74,	I 0,	I 5,	I _text,	S "United States",	I 2 ]
 ,[ N 75,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 76,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 77,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 78,	I 0,	I 5,	I _text,	S "great ",	I 2 ]
 ,[ N 79,	I 1,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 80,	I 0,	I 5,	I _text,	S "Money order, Cash",	I 2 ]
 ,[ N 81,	I 5,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 82,	I 4,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 83,	I 0,	I 6,	I _text,	S "\012print deceit arming ros apes unjustly oregon spring hamlet containing leaves italian turn ",	I 2 ]
 ,[ N 84,	I 1,	I 6,	I _elem,	S "bold",	I 2 ]
 ,[ N 85,	I 0,	I 7,	I _text,	S " spirit model favour disposition ",	I 2 ]
 ,[ N 86,	I 0,	I 6,	I _text,	S " approach charg gold promotions despair flow assured terror assembly marry concluded author debase get bourn openly gonzago wisest bane continue cries \012",	I 2 ]
 ,[ N 87,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 88,	I 0,	I 5,	I _text,	S "Will ship internationally",	I 2 ]
 ,[ N 89,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 90,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 91,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 92,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 93,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 94,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 95,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 96,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 97,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 98,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 99,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 100,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 101,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 102,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 103,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 104,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 105,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 106,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 107,	I 23,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 108,	I 10,	I 5,	I _elem,	S "mail",	I 2 ]
 ,[ N 109,	I 1,	I 6,	I _elem,	S "from",	I 2 ]
 ,[ N 110,	I 0,	I 7,	I _text,	S "Fumitaka Cenzer mailto:Cenzer@savera.com",	I 2 ]
 ,[ N 111,	I 1,	I 6,	I _elem,	S "to",	I 2 ]
 ,[ N 112,	I 0,	I 7,	I _text,	S "Lanju Takano mailto:Takano@itc.it",	I 2 ]
 ,[ N 113,	I 1,	I 6,	I _elem,	S "date",	I 2 ]
 ,[ N 114,	I 0,	I 7,	I _text,	S "02/24/2000",	I 2 ]
 ,[ N 115,	I 3,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 116,	I 0,	I 7,	I _text,	S "\012entreaty hath fowl prescience bounds roof fiend intellect boughs caught add jests feelingly doubt trojans wisdom greatness tune worship doors fields reads canst france pay progeny wisdom stir mov impious promis clothes hangman trebonius choose men fits preparation ",	I 2 ]
 ,[ N 117,	I 1,	I 7,	I _elem,	S "keyword",	I 2 ]
 ,[ N 118,	I 0,	I 8,	I _text,	S " benefit since eclipse gates ",	I 2 ]
 ,[ N 119,	I 11,	I 5,	I _elem,	S "mail",	I 2 ]
 ,[ N 120,	I 1,	I 6,	I _elem,	S "from",	I 2 ]
 ,[ N 121,	I 0,	I 7,	I _text,	S "Papa Godskesen mailto:Godskesen@uwindsor.ca",	I 2 ]
 ,[ N 122,	I 1,	I 6,	I _elem,	S "to",	I 2 ]
 ,[ N 123,	I 0,	I 7,	I _text,	S "Ioana Blumberg mailto:Blumberg@conclusivestrategies.com",	I 2 ]
 ,[ N 124,	I 1,	I 6,	I _elem,	S "date",	I 2 ]
 ,[ N 125,	I 0,	I 7,	I _text,	S "08/02/2001",	I 2 ]
 ,[ N 126,	I 4,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 127,	I 0,	I 7,	I _text,	S "\012jealousy back greg folded gauntlets conduct hardness across sickness peter enough royal herb embrace piteous die servilius avoid ",	I 2 ]
 ,[ N 128,	I 1,	I 7,	I _elem,	S "keyword",	I 2 ]
 ,[ N 129,	I 0,	I 8,	I _text,	S " laying chance dungeons pleasant thyself fellow purse steward heaven ambassador terrible doubtfully ",	I 2 ]
 ,[ N 130,	I 0,	I 7,	I _text,	S " milk sky clouds unbraced put sacrifices seas childish longer flout heavy pitch rosalind orderly music delivery appease \012",	I 2 ]
 ,[ N 131,	I 88,	I 2,	I _elem,	S "australia",	I 2 ]
 ,[ N 132,	I 87,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 133,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 134,	I 0,	I 5,	I _text,	S "item2",	I 2 ]
 ,[ N 135,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 136,	I 0,	I 5,	I _text,	S "United States",	I 2 ]
 ,[ N 137,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 138,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 139,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 140,	I 0,	I 5,	I _text,	S "scarce brook ",	I 2 ]
 ,[ N 141,	I 0,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 142,	I 59,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 143,	I 58,	I 5,	I _elem,	S "parlist",	I 2 ]
 ,[ N 144,	I 4,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 145,	I 3,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 146,	I 0,	I 8,	I _text,	S "\012senses concave valiant star further instruments bankrupts countrymen horrid costard youth necessity tend curiously waken witness navy there honest interest perceive defendant chief traffic where nuptial descent travel prepare agreed voices swears remember peerless doing ",	I 2 ]
 ,[ N 147,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 148,	I 0,	I 9,	I _text,	S " preparation rejoice ",	I 2 ]
 ,[ N 149,	I 8,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 150,	I 7,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 151,	I 0,	I 8,	I _text,	S "\012swear canker barbarian parching coxcomb excess conspiring nobles sounded consider sayings fishified prime may spirit ",	I 2 ]
 ,[ N 152,	I 1,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 153,	I 0,	I 9,	I _text,	S " untruths misgives choughs mew here garments tenfold ",	I 2 ]
 ,[ N 154,	I 0,	I 8,	I _text,	S " error discontent hung beatrice straight muse shame deep twice mann maecenas any conveyance fingers whereupon child case ",	I 2 ]
 ,[ N 155,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 156,	I 0,	I 9,	I _text,	S " season presently victory women beating ",	I 2 ]
 ,[ N 157,	I 0,	I 8,	I _text,	S " deprive almost wed dreams slew reveal \012",	I 2 ]
 ,[ N 158,	I 5,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 159,	I 4,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 160,	I 0,	I 8,	I _text,	S "\012spotted attend burden camillo field enlarge stead corporal ground tormenting ",	I 2 ]
 ,[ N 161,	I 1,	I 8,	I _elem,	S "bold",	I 2 ]
 ,[ N 162,	I 0,	I 9,	I _text,	S " naturally sanctuary riddle exile coming awake senseless chance famous albans ",	I 2 ]
 ,[ N 163,	I 0,	I 8,	I _text,	S " service cricket limb from clouds amongst shore penker defend quantity dumb churlish uncover swung eros figur sulphur sky birth stare negligent unction shield instance ambition gate injury fort put infants find slavish hugh see afterwards slanders chides eyes minds alb loved endure combating voyage \012",	I 2 ]
 ,[ N 164,	I 15,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 165,	I 14,	I 7,	I _elem,	S "parlist",	I 2 ]
 ,[ N 166,	I 2,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 167,	I 1,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 168,	I 0,	I 10,	I _text,	S "\012maintained peril rivall suddenly finds studies weary truth indulgence anatomy assisted imminent may excepted yonder aches regal \012",	I 2 ]
 ,[ N 169,	I 4,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 170,	I 3,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 171,	I 1,	I 10,	I _elem,	S "bold",	I 2 ]
 ,[ N 172,	I 0,	I 11,	I _text,	S " friar prophetess ",	I 2 ]
 ,[ N 173,	I 0,	I 10,	I _text,	S " spirits delays turning cassio finding unpractis steel sweets promises credulity err nym complete star greatly mope sorry experience virtues been offending bed drives faction learnt hurl eleven huge \012",	I 2 ]
 ,[ N 174,	I 5,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 175,	I 4,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 176,	I 0,	I 10,	I _text,	S "\012piece hours cruelly april league winged ",	I 2 ]
 ,[ N 177,	I 1,	I 10,	I _elem,	S "keyword",	I 2 ]
 ,[ N 178,	I 0,	I 11,	I _text,	S " tract element sails course placed fouler four plac joint ",	I 2 ]
 ,[ N 179,	I 0,	I 10,	I _text,	S " words blessing fortified loving forfeit doctor valiant crying wife county planet charge haughty precious alexander longboat bells lewd kingdoms knife giver frantic raz commend sit sovereignty engaged perceive its art alliance forge bestow perforce complete roof fie confident raging possible cassio teen crave park reign lords sounded our requite fourth confidence high \012",	I 2 ]
 ,[ N 180,	I 21,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 181,	I 20,	I 7,	I _elem,	S "parlist",	I 2 ]
 ,[ N 182,	I 14,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 183,	I 13,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 184,	I 0,	I 10,	I _text,	S "\012sent fled bids oswald help answer artillery jealous hugh fingers gladly mows our craving ",	I 2 ]
 ,[ N 185,	I 1,	I 10,	I _elem,	S "emph",	I 2 ]
 ,[ N 186,	I 0,	I 11,	I _text,	S " preventions spurr edmund drunk how faction quickly bolingbroke painfully ",	I 2 ]
 ,[ N 187,	I 0,	I 10,	I _text,	S " valorous line clasp cheek patchery encompassed honest after auspicious home engaged prompt mortimer bird dread jephthah prithee unfold deeds fifty goose either herald temperance coctus took sought fail each ado checking funeral thinks linger advantage bag ridiculous along accomplishment flower glittering school disguis portia beloved crown sheets garish rather forestall vaults doublet embassy ecstasy crimson rheum befall sin devout pedro little exquisite mote messenger lancaster hideous object arrows smites gently skins bora parting desdemona longing third throng character hat sov quit mounts true house field nearest lucrece tidings fought logotype eaten commanding treason censur ripe praises windsor temperate jealous made sleeve scorn throats fits uncape tended science preventions preventions high pipes reprieves ",	I 2 ]
 ,[ N 188,	I 1,	I 10,	I _elem,	S "bold",	I 2 ]
 ,[ N 189,	I 0,	I 11,	I _text,	S " sold ",	I 2 ]
 ,[ N 190,	I 0,	I 10,	I _text,	S " marriage sampson safety distrust witch christianlike plague doubling visited with bleed offenders catching attendants ",	I 2 ]
 ,[ N 191,	I 1,	I 10,	I _elem,	S "emph",	I 2 ]
 ,[ N 192,	I 0,	I 11,	I _text,	S " cars livery stand ",	I 2 ]
 ,[ N 193,	I 0,	I 10,	I _text,	S " denay ",	I 2 ]
 ,[ N 194,	I 1,	I 10,	I _elem,	S "keyword",	I 2 ]
 ,[ N 195,	I 0,	I 11,	I _text,	S " cimber paper admittance tread character ",	I 2 ]
 ,[ N 196,	I 0,	I 10,	I _text,	S " battlements seen dun irish throw redeem afflicts suspicion \012",	I 2 ]
 ,[ N 197,	I 4,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 198,	I 3,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 199,	I 0,	I 10,	I _text,	S "\012traduc barks twenty secure pursuit believing necessities longs mental lack further observancy uncleanly understanding vault athens lucius sleeps nor safety evidence repay whensoever senses proudest restraint love mouths slaves water athenian willingly hot grieves delphos pavilion sword indeed lepidus taking disguised proffer salt before educational streets things osw rey stern lap studies finger doomsday pots bounty famous manhood observe hopes unless languish ",	I 2 ]
 ,[ N 200,	I 1,	I 10,	I _elem,	S "keyword",	I 2 ]
 ,[ N 201,	I 0,	I 11,	I _text,	S " transformed nourish breeds north ",	I 2 ]
 ,[ N 202,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 203,	I 0,	I 5,	I _text,	S "Will ship internationally",	I 2 ]
 ,[ N 204,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 205,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 206,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 207,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 208,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 209,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 210,	I 9,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 211,	I 8,	I 5,	I _elem,	S "mail",	I 2 ]
 ,[ N 212,	I 1,	I 6,	I _elem,	S "from",	I 2 ]
 ,[ N 213,	I 0,	I 7,	I _text,	S "Aspi L'Ecuyer mailto:L'Ecuyer@intersys.com",	I 2 ]
 ,[ N 214,	I 1,	I 6,	I _elem,	S "to",	I 2 ]
 ,[ N 215,	I 0,	I 7,	I _text,	S "Lesley Jeris mailto:Jeris@zambeel.com",	I 2 ]
 ,[ N 216,	I 1,	I 6,	I _elem,	S "date",	I 2 ]
 ,[ N 217,	I 0,	I 7,	I _text,	S "10/09/1998",	I 2 ]
 ,[ N 218,	I 1,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 219,	I 0,	I 7,	I _text,	S "\012necessities chains rosencrantz house heed course lawn diest unvirtuous supposed sees chough swor numbers game roman soundest wrestler sky lodovico beast shivers desolate norfolk forgot paulina wars george while beggar sheath thursday capable presently his protector father orchard enemies believe drains tokens prison charge cloud stab york mild scene true devotion confidence hundred those guiltless pricks sort himself mutiny officers directive wholesome edge acts dion ride draw brings custom chapless beside sex dowry casca goods priam blasphemy prick octavia brain curer thinkest idiot inward missing conspiracy tents scab inundation caesar officer dramatis \012",	I 2 ]
 ,[ N 220,	I 57,	I 2,	I _elem,	S "europe",	I 2 ]
 ,[ N 221,	I 56,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 222,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 223,	I 0,	I 5,	I _text,	S "item3",	I 2 ]
 ,[ N 224,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 225,	I 0,	I 5,	I _text,	S "Uzbekistan",	I 2 ]
 ,[ N 226,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 227,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 228,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 229,	I 0,	I 5,	I _text,	S "abhorr execution beckon rue ",	I 2 ]
 ,[ N 230,	I 1,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 231,	I 0,	I 5,	I _text,	S "Money order, Creditcard, Cash",	I 2 ]
 ,[ N 232,	I 18,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 233,	I 17,	I 5,	I _elem,	S "parlist",	I 2 ]
 ,[ N 234,	I 4,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 235,	I 3,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 236,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 237,	I 0,	I 9,	I _text,	S " perjur kills insanie unfortunate conjuration deeper confounded belied first guard ",	I 2 ]
 ,[ N 238,	I 0,	I 8,	I _text,	S " pale profits height desir ashore france strength kept entrench poisons worth fought ignorance moody poniards speaks jack egg offspring victory food double emperor round jewel abbey apparel untainted lass protest start wings acquit lake lady battles further low thief try brook cake mounted officers dean shrunk lowness dew sandy prologue armies suspicion eighty advance thankfulness albany ended experience halt doubted wert kingdom fiend directed pair perhaps \012",	I 2 ]
 ,[ N 239,	I 11,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 240,	I 10,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 241,	I 0,	I 8,	I _text,	S "\012prayer odds rend condemn conrade swearing dispos losses boar little from thought different couch respected human robe dictynna later pays edward babe distemper bards damned mayst sustain while self alcibiades listen weak soil ",	I 2 ]
 ,[ N 242,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 243,	I 0,	I 9,	I _text,	S " view presume loggets feed ",	I 2 ]
 ,[ N 244,	I 0,	I 8,	I _text,	S " afoot yields erection balthasar fathers datchet thankless lear cause evil cheerfully instance tarried because cough ancient testimony tarquin cousin reported porter beastly jade bark sex slack lear devil devoured amiable mason moss shoulders labour meanest feign eggs encount forbid enobarbus halters nam emilia fiends bearing food inheritor wiser ",	I 2 ]
 ,[ N 245,	I 1,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 246,	I 0,	I 9,	I _text,	S " hedge ",	I 2 ]
 ,[ N 247,	I 0,	I 8,	I _text,	S " functions there capital greasy dark crush your sequest between devout thou strikes demand dost reverent conference least told ado modena jealousy nunnery mistrust nightly worthy closes tall proudly fierce receive nearness safer jacks shut dire mates wind unfortunate monsieur parcels sauced extremities throat dog empty treasury etc detested stand taxations edges mourner sue knavery unlook perseus diadem heartily peer tut compounded art reconcile study thought cockatrice money pity intend thing claud edmund throws torments ropes contrive story slain advise lecher ardea relics keeping treads buckingham defences lag neighbour ourself marshal disordered moderate venus afeard article rot hazards craft crowns ",	I 2 ]
 ,[ N 248,	I 1,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 249,	I 0,	I 9,	I _text,	S " plainness patient ",	I 2 ]
 ,[ N 250,	I 0,	I 8,	I _text,	S " lying knowledge diseases meritorious medicine instead lid happy without them bands answer \012",	I 2 ]
 ,[ N 251,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 252,	I 0,	I 5,	I _text,	S "Will ship only within country",	I 2 ]
 ,[ N 253,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 254,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 255,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 256,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 257,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 258,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 259,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 260,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 261,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 262,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 263,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 264,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 265,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 266,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 267,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 268,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 269,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 270,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 271,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 272,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 273,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 274,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 275,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 276,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 277,	I 0,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 278,	I 49,	I 2,	I _elem,	S "namerica",	I 2 ]
 ,[ N 279,	I 48,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 280,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 281,	I 0,	I 5,	I _text,	S "item4",	I 2 ]
 ,[ N 282,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 283,	I 0,	I 5,	I _text,	S "United States",	I 2 ]
 ,[ N 284,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 285,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 286,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 287,	I 0,	I 5,	I _text,	S "unsur brutish ",	I 2 ]
 ,[ N 288,	I 1,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 289,	I 0,	I 5,	I _text,	S "Money order, Creditcard",	I 2 ]
 ,[ N 290,	I 16,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 291,	I 15,	I 5,	I _elem,	S "parlist",	I 2 ]
 ,[ N 292,	I 8,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 293,	I 7,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 294,	I 0,	I 8,	I _text,	S "\012prepar likelihood eagle body walk borachio month writing left speed patents coach through protectorship congruent confusion favours following populous garden henceforth shoots function fourscore mangled favorably slain secretly vice distinguish bardolph content hence boy worse bring usurers stew beard longed creep hid pursuivant beholders senators son mercutio woo bestow trumpet excess muffler pick ugly felt causes remove adding tear often rounds underbearing tree purer kibes endless women benefit throw ",	I 2 ]
 ,[ N 295,	I 4,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 296,	I 0,	I 9,	I _text,	S " claim firmness ",	I 2 ]
 ,[ N 297,	I 1,	I 9,	I _elem,	S "keyword",	I 2 ]
 ,[ N 298,	I 0,	I 10,	I _text,	S " arrived sees wrestled multitude repent preventions infamy reproof shalt hearted prais knave doubtless ",	I 2 ]
 ,[ N 299,	I 0,	I 9,	I _text,	S " deny ",	I 2 ]
 ,[ N 300,	I 0,	I 8,	I _text,	S " merely grave voluble late loath digest horn slave hunger stronger amazed salt killing ross cry dry tongue kiss yields auspicious quietness perpetual ways \012",	I 2 ]
 ,[ N 301,	I 5,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 302,	I 4,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 303,	I 0,	I 8,	I _text,	S "\012court mean returning brook creatures appointed paunches henry sights west prunes flutes regiment seems bed musicians slumber post friendship prevention abreast wouldst words vexation builds unfelt holly walk inform moods deck bulk begin action school nobles antique people unkennel stomach into petitions jack assail yongrey ages betimes golden sink droop kernel hoppedance perfection weight ",	I 2 ]
 ,[ N 304,	I 1,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 305,	I 0,	I 9,	I _text,	S " whining safe english rod other featur ",	I 2 ]
 ,[ N 306,	I 0,	I 8,	I _text,	S " betwixt orator across amiss mine guests guard yon willing remit longing goneril visitation honey \012",	I 2 ]
 ,[ N 307,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 308,	I 0,	I 5,	I _text,	S "Will ship only within country, Buyer pays fixed shipping charges, See description for charges",	I 2 ]
 ,[ N 309,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 310,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 311,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 312,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 313,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 314,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 315,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 316,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 317,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 318,	I 9,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 319,	I 8,	I 5,	I _elem,	S "mail",	I 2 ]
 ,[ N 320,	I 1,	I 6,	I _elem,	S "from",	I 2 ]
 ,[ N 321,	I 0,	I 7,	I _text,	S "Honari Castan mailto:Castan@uni-muenchen.de",	I 2 ]
 ,[ N 322,	I 1,	I 6,	I _elem,	S "to",	I 2 ]
 ,[ N 323,	I 0,	I 7,	I _text,	S "Maz Lucky mailto:Lucky@washington.edu",	I 2 ]
 ,[ N 324,	I 1,	I 6,	I _elem,	S "date",	I 2 ]
 ,[ N 325,	I 0,	I 7,	I _text,	S "01/24/1998",	I 2 ]
 ,[ N 326,	I 1,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 327,	I 0,	I 7,	I _text,	S "\012scene disposition substance prick counsel start temples \012",	I 2 ]
 ,[ N 328,	I 35,	I 2,	I _elem,	S "samerica",	I 2 ]
 ,[ N 329,	I 34,	I 3,	I _elem,	S "item",	I 2 ]
 ,[ N 330,	I 1,	I 4,	I _elem,	S "id",	I 2 ]
 ,[ N 331,	I 0,	I 5,	I _text,	S "item5",	I 2 ]
 ,[ N 332,	I 1,	I 4,	I _elem,	S "location",	I 2 ]
 ,[ N 333,	I 0,	I 5,	I _text,	S "United States",	I 2 ]
 ,[ N 334,	I 1,	I 4,	I _elem,	S "quantity",	I 2 ]
 ,[ N 335,	I 0,	I 5,	I _text,	S "1",	I 2 ]
 ,[ N 336,	I 1,	I 4,	I _elem,	S "name",	I 2 ]
 ,[ N 337,	I 0,	I 5,	I _text,	S "nakedness ",	I 2 ]
 ,[ N 338,	I 1,	I 4,	I _elem,	S "payment",	I 2 ]
 ,[ N 339,	I 0,	I 5,	I _text,	S "Creditcard, Personal Check, Cash",	I 2 ]
 ,[ N 340,	I 8,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 341,	I 7,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 342,	I 0,	I 6,	I _text,	S "\012music sift kissing design airy office dismantled hope reconcil combat wert quite translate overcome unthrifty ",	I 2 ]
 ,[ N 343,	I 4,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 344,	I 0,	I 7,	I _text,	S " fell othello ",	I 2 ]
 ,[ N 345,	I 1,	I 7,	I _elem,	S "bold",	I 2 ]
 ,[ N 346,	I 0,	I 8,	I _text,	S " wolf entreat audaciously down sands sports pilgrimage duellist league holiday cheek that tables merrily knot selves ionia impure ",	I 2 ]
 ,[ N 347,	I 0,	I 7,	I _text,	S " prophet draw throwing solemn yonder ",	I 2 ]
 ,[ N 348,	I 0,	I 6,	I _text,	S " rightful foam worthless polack veronesa antony beget thereby carry untread hales \012",	I 2 ]
 ,[ N 349,	I 1,	I 4,	I _elem,	S "shipping",	I 2 ]
 ,[ N 350,	I 0,	I 5,	I _text,	S "Will ship only within country, Will ship internationally",	I 2 ]
 ,[ N 351,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 352,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 353,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 354,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 355,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 356,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 357,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 358,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 359,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 360,	I 2,	I 4,	I _elem,	S "incategory",	I 2 ]
 ,[ N 361,	I 1,	I 5,	I _elem,	S "category",	I 2 ]
 ,[ N 362,	I 0,	I 6,	I _text,	S "category0",	I 2 ]
 ,[ N 363,	I 0,	I 4,	I _elem,	S "mailbox",	I 2 ]
 ,[ N 364,	I 27,	I 1,	I _elem,	S "categories",	I 2 ]
 ,[ N 365,	I 26,	I 2,	I _elem,	S "category",	I 2 ]
 ,[ N 366,	I 1,	I 3,	I _elem,	S "id",	I 2 ]
 ,[ N 367,	I 0,	I 4,	I _text,	S "category0",	I 2 ]
 ,[ N 368,	I 1,	I 3,	I _elem,	S "name",	I 2 ]
 ,[ N 369,	I 0,	I 4,	I _text,	S "dispatch reported dotard holofernes ",	I 2 ]
 ,[ N 370,	I 21,	I 3,	I _elem,	S "description",	I 2 ]
 ,[ N 371,	I 20,	I 4,	I _elem,	S "parlist",	I 2 ]
 ,[ N 372,	I 2,	I 5,	I _elem,	S "listitem",	I 2 ]
 ,[ N 373,	I 1,	I 6,	I _elem,	S "text",	I 2 ]
 ,[ N 374,	I 0,	I 7,	I _text,	S "\012shift carrion doubtful strangle sounding crowned troubled naked yesterday overthrow owe silent recount waters derive sans four \012",	I 2 ]
 ,[ N 375,	I 16,	I 5,	I _elem,	S "listitem",	I 2 ]
 ,[ N 376,	I 15,	I 6,	I _elem,	S "parlist",	I 2 ]
 ,[ N 377,	I 2,	I 7,	I _elem,	S "listitem",	I 2 ]
 ,[ N 378,	I 1,	I 8,	I _elem,	S "text",	I 2 ]
 ,[ N 379,	I 0,	I 9,	I _text,	S "\012fragment pamper arthur thrive wound fouler streets preventions obey vow bawds myrtle said infinite montague fierce sense ride souls commended gainsay profession labour intents persuade alter \012",	I 2 ]
 ,[ N 380,	I 2,	I 7,	I _elem,	S "listitem",	I 2 ]
 ,[ N 381,	I 1,	I 8,	I _elem,	S "text",	I 2 ]
 ,[ N 382,	I 0,	I 9,	I _text,	S "\012ord villain wore thunder congeal pawned alack customary deny faithful top office spoken please neighbour office afternoon drum embowell touch sue lifeless leapt called weary congregation yield \012",	I 2 ]
 ,[ N 383,	I 8,	I 7,	I _elem,	S "listitem",	I 2 ]
 ,[ N 384,	I 7,	I 8,	I _elem,	S "text",	I 2 ]
 ,[ N 385,	I 0,	I 9,	I _text,	S "\012mental fatal hard ancient stands cor dishes therein gramercy discipline farewell dire tricks protest cut horatio brother speech sleeping adultress pitch cave liv nurse drink state plants combating desired requir rebellion afraid repented tree scald stopp wine advise undermine norfolk vilely whet scars companions hanging foolish scene musty fruitful unburthen teacher garments betimes sight now for oaths vouchsafe particulars globe laertes afflictions rouse once news humanity buck destroy military lucius lap ",	I 2 ]
 ,[ N 386,	I 1,	I 9,	I _elem,	S "keyword",	I 2 ]
 ,[ N 387,	I 0,	I 10,	I _text,	S " considered forc mourning verona ",	I 2 ]
 ,[ N 388,	I 0,	I 9,	I _text,	S " waters triumphing officer hastily ",	I 2 ]
 ,[ N 389,	I 1,	I 9,	I _elem,	S "emph",	I 2 ]
 ,[ N 390,	I 0,	I 10,	I _text,	S " resign subject figure hay thwart written signs gout bred distance period glove players change folly ",	I 2 ]
 ,[ N 391,	I 0,	I 9,	I _text,	S " going wat lost song hautboys pick business crocodile leading cave twice frenzy sprightly dislike invite forbids morn devour ambassador seldom speak tickling rejoice triumphant ascanius forward \012",	I 2 ]
 ,[ N 392,	I 5,	I 1,	I _elem,	S "catgraph",	I 2 ]
 ,[ N 393,	I 4,	I 2,	I _elem,	S "edge",	I 2 ]
 ,[ N 394,	I 1,	I 3,	I _elem,	S "from",	I 2 ]
 ,[ N 395,	I 0,	I 4,	I _text,	S "category0",	I 2 ]
 ,[ N 396,	I 1,	I 3,	I _elem,	S "to",	I 2 ]
 ,[ N 397,	I 0,	I 4,	I _text,	S "category0",	I 2 ]
 ,[ N 398,	I 17,	I 1,	I _elem,	S "people",	I 2 ]
 ,[ N 399,	I 16,	I 2,	I _elem,	S "person",	I 2 ]
 ,[ N 400,	I 1,	I 3,	I _elem,	S "id",	I 2 ]
 ,[ N 401,	I 0,	I 4,	I _text,	S "person0",	I 2 ]
 ,[ N 402,	I 1,	I 3,	I _elem,	S "name",	I 2 ]
 ,[ N 403,	I 0,	I 4,	I _text,	S "Jaak Tempesti",	I 2 ]
 ,[ N 404,	I 1,	I 3,	I _elem,	S "emailaddress",	I 2 ]
 ,[ N 405,	I 0,	I 4,	I _text,	S "mailto:Tempesti@labs.com",	I 2 ]
 ,[ N 406,	I 1,	I 3,	I _elem,	S "phone",	I 2 ]
 ,[ N 407,	I 0,	I 4,	I _text,	S "+0 (873) 14873867",	I 2 ]
 ,[ N 408,	I 1,	I 3,	I _elem,	S "homepage",	I 2 ]
 ,[ N 409,	I 0,	I 4,	I _text,	S "http://www.labs.com/~Tempesti",	I 2 ]
 ,[ N 410,	I 1,	I 3,	I _elem,	S "creditcard",	I 2 ]
 ,[ N 411,	I 0,	I 4,	I _text,	S "5048 5813 2703 8253",	I 2 ]
 ,[ N 412,	I 3,	I 3,	I _elem,	S "watches",	I 2 ]
 ,[ N 413,	I 2,	I 4,	I _elem,	S "watch",	I 2 ]
 ,[ N 414,	I 1,	I 5,	I _elem,	S "open_auction",	I 2 ]
 ,[ N 415,	I 0,	I 6,	I _text,	S "open_auction0",	I 2 ]
 ,[ N 416,	I 198,	I 1,	I _elem,	S "open_auctions",	I 2 ]
 ,[ N 417,	I 197,	I 2,	I _elem,	S "open_auction",	I 2 ]
 ,[ N 418,	I 1,	I 3,	I _elem,	S "id",	I 2 ]
 ,[ N 419,	I 0,	I 4,	I _text,	S "open_auction0",	I 2 ]
 ,[ N 420,	I 1,	I 3,	I _elem,	S "initial",	I 2 ]
 ,[ N 421,	I 0,	I 4,	I _text,	S "13.56",	I 2 ]
 ,[ N 422,	I 1,	I 3,	I _elem,	S "reserve",	I 2 ]
 ,[ N 423,	I 0,	I 4,	I _text,	S "33.78",	I 2 ]
 ,[ N 424,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 425,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 426,	I 0,	I 5,	I _text,	S "10/22/2001",	I 2 ]
 ,[ N 427,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 428,	I 0,	I 5,	I _text,	S "10:21:43",	I 2 ]
 ,[ N 429,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 430,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 431,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 432,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 433,	I 0,	I 5,	I _text,	S "55.50",	I 2 ]
 ,[ N 434,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 435,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 436,	I 0,	I 5,	I _text,	S "07/27/2001",	I 2 ]
 ,[ N 437,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 438,	I 0,	I 5,	I _text,	S "12:36:50",	I 2 ]
 ,[ N 439,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 440,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 441,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 442,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 443,	I 0,	I 5,	I _text,	S "19.50",	I 2 ]
 ,[ N 444,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 445,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 446,	I 0,	I 5,	I _text,	S "02/14/2000",	I 2 ]
 ,[ N 447,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 448,	I 0,	I 5,	I _text,	S "16:40:16",	I 2 ]
 ,[ N 449,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 450,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 451,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 452,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 453,	I 0,	I 5,	I _text,	S "19.50",	I 2 ]
 ,[ N 454,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 455,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 456,	I 0,	I 5,	I _text,	S "05/09/2001",	I 2 ]
 ,[ N 457,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 458,	I 0,	I 5,	I _text,	S "11:39:57",	I 2 ]
 ,[ N 459,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 460,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 461,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 462,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 463,	I 0,	I 5,	I _text,	S "30.00",	I 2 ]
 ,[ N 464,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 465,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 466,	I 0,	I 5,	I _text,	S "07/12/1999",	I 2 ]
 ,[ N 467,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 468,	I 0,	I 5,	I _text,	S "23:20:27",	I 2 ]
 ,[ N 469,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 470,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 471,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 472,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 473,	I 0,	I 5,	I _text,	S "13.50",	I 2 ]
 ,[ N 474,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 475,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 476,	I 0,	I 5,	I _text,	S "10/21/2001",	I 2 ]
 ,[ N 477,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 478,	I 0,	I 5,	I _text,	S "01:19:47",	I 2 ]
 ,[ N 479,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 480,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 481,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 482,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 483,	I 0,	I 5,	I _text,	S "3.00",	I 2 ]
 ,[ N 484,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 485,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 486,	I 0,	I 5,	I _text,	S "09/28/2001",	I 2 ]
 ,[ N 487,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 488,	I 0,	I 5,	I _text,	S "17:03:24",	I 2 ]
 ,[ N 489,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 490,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 491,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 492,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 493,	I 0,	I 5,	I _text,	S "6.00",	I 2 ]
 ,[ N 494,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 495,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 496,	I 0,	I 5,	I _text,	S "11/15/1999",	I 2 ]
 ,[ N 497,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 498,	I 0,	I 5,	I _text,	S "14:23:15",	I 2 ]
 ,[ N 499,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 500,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 501,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 502,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 503,	I 0,	I 5,	I _text,	S "9.00",	I 2 ]
 ,[ N 504,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 505,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 506,	I 0,	I 5,	I _text,	S "01/02/1998",	I 2 ]
 ,[ N 507,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 508,	I 0,	I 5,	I _text,	S "22:18:07",	I 2 ]
 ,[ N 509,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 510,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 511,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 512,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 513,	I 0,	I 5,	I _text,	S "1.50",	I 2 ]
 ,[ N 514,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 515,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 516,	I 0,	I 5,	I _text,	S "12/24/2001",	I 2 ]
 ,[ N 517,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 518,	I 0,	I 5,	I _text,	S "16:46:32",	I 2 ]
 ,[ N 519,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 520,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 521,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 522,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 523,	I 0,	I 5,	I _text,	S "13.50",	I 2 ]
 ,[ N 524,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 525,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 526,	I 0,	I 5,	I _text,	S "08/12/2000",	I 2 ]
 ,[ N 527,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 528,	I 0,	I 5,	I _text,	S "11:41:54",	I 2 ]
 ,[ N 529,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 530,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 531,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 532,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 533,	I 0,	I 5,	I _text,	S "3.00",	I 2 ]
 ,[ N 534,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 535,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 536,	I 0,	I 5,	I _text,	S "11/15/2000",	I 2 ]
 ,[ N 537,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 538,	I 0,	I 5,	I _text,	S "15:53:40",	I 2 ]
 ,[ N 539,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 540,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 541,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 542,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 543,	I 0,	I 5,	I _text,	S "6.00",	I 2 ]
 ,[ N 544,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 545,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 546,	I 0,	I 5,	I _text,	S "03/04/2000",	I 2 ]
 ,[ N 547,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 548,	I 0,	I 5,	I _text,	S "20:46:15",	I 2 ]
 ,[ N 549,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 550,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 551,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 552,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 553,	I 0,	I 5,	I _text,	S "16.50",	I 2 ]
 ,[ N 554,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 555,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 556,	I 0,	I 5,	I _text,	S "07/22/1998",	I 2 ]
 ,[ N 557,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 558,	I 0,	I 5,	I _text,	S "10:34:11",	I 2 ]
 ,[ N 559,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 560,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 561,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 562,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 563,	I 0,	I 5,	I _text,	S "25.50",	I 2 ]
 ,[ N 564,	I 9,	I 3,	I _elem,	S "bidder",	I 2 ]
 ,[ N 565,	I 1,	I 4,	I _elem,	S "date",	I 2 ]
 ,[ N 566,	I 0,	I 5,	I _text,	S "04/01/1998",	I 2 ]
 ,[ N 567,	I 1,	I 4,	I _elem,	S "time",	I 2 ]
 ,[ N 568,	I 0,	I 5,	I _text,	S "10:44:22",	I 2 ]
 ,[ N 569,	I 2,	I 4,	I _elem,	S "personref",	I 2 ]
 ,[ N 570,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 571,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 572,	I 1,	I 4,	I _elem,	S "increase",	I 2 ]
 ,[ N 573,	I 0,	I 5,	I _text,	S "7.50",	I 2 ]
 ,[ N 574,	I 1,	I 3,	I _elem,	S "current",	I 2 ]
 ,[ N 575,	I 0,	I 4,	I _text,	S "243.06",	I 2 ]
 ,[ N 576,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 577,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 578,	I 0,	I 5,	I _text,	S "item0",	I 2 ]
 ,[ N 579,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 580,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 581,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 582,	I 23,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 583,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 584,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 585,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 586,	I 17,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 587,	I 16,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 588,	I 0,	I 6,	I _text,	S "\012debauch corpse canons domain night forsake yea satisfy between fume were monsters ear players moreover ungentleness sorrows prouder tonight favours rome bastard unshown excellence journey loves swearing proceeds stone buck battle breathless kindness prophesy entomb urging rogues hector conquer provoke nothing raw wight places needy feasted romeo rivers worser occupation brook stoops brooch plucks level samp tent windsor rubs whereof beam signior built suff heavy dull husbands roman favour urge spear gone wolf cheeks execute resolv such horrid drives provide twice spoke trade friar taking pheasant sentenc scarf corrections brothers charge spur ass agamemnon truepenny saves roots practis impatient diest didest starv seeing beneath interpose gods home black forgot snuff dress dozen napkins ",	I 2 ]
 ,[ N 589,	I 1,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 590,	I 0,	I 7,	I _text,	S " countess northumberland headlong needless angry pleading ",	I 2 ]
 ,[ N 591,	I 0,	I 6,	I _text,	S " better joy ",	I 2 ]
 ,[ N 592,	I 1,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 593,	I 0,	I 7,	I _text,	S " meagre ",	I 2 ]
 ,[ N 594,	I 0,	I 6,	I _text,	S " reap enquire crab wales died violent rear past liberty ",	I 2 ]
 ,[ N 595,	I 1,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 596,	I 0,	I 7,	I _text,	S " braggart armour infer bankrupt winds teeth ",	I 2 ]
 ,[ N 597,	I 0,	I 6,	I _text,	S " case wore pouch crows cognition ",	I 2 ]
 ,[ N 598,	I 1,	I 6,	I _elem,	S "keyword",	I 2 ]
 ,[ N 599,	I 0,	I 7,	I _text,	S " reports expedition free chief cressida hearsed ",	I 2 ]
 ,[ N 600,	I 0,	I 6,	I _text,	S " loath monuments silent congregation soon farm doct ross susan ready empty dedicate shilling whole soul foot beseech higher lifeless hay postmaster distress disposition ",	I 2 ]
 ,[ N 601,	I 1,	I 6,	I _elem,	S "bold",	I 2 ]
 ,[ N 602,	I 0,	I 7,	I _text,	S " inherits ",	I 2 ]
 ,[ N 603,	I 0,	I 6,	I _text,	S " marcus betters pitch betray beam corse player quality ros conduct thersites greediness boast pilgrims startles contented belch hung thus captain early blood par brook jul gain needs above ensign grapes revelling glean thank \012",	I 2 ]
 ,[ N 604,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 605,	I 0,	I 5,	I _text,	S "6",	I 2 ]
 ,[ N 606,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 607,	I 0,	I 4,	I _text,	S "1",	I 2 ]
 ,[ N 608,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 609,	I 0,	I 4,	I _text,	S "Regular",	I 2 ]
 ,[ N 610,	I 4,	I 3,	I _elem,	S "interval",	I 2 ]
 ,[ N 611,	I 1,	I 4,	I _elem,	S "start",	I 2 ]
 ,[ N 612,	I 0,	I 5,	I _text,	S "06/16/1999",	I 2 ]
 ,[ N 613,	I 1,	I 4,	I _elem,	S "end",	I 2 ]
 ,[ N 614,	I 0,	I 5,	I _text,	S "05/12/2001",	I 2 ]
 ,[ N 615,	I 173,	I 1,	I _elem,	S "closed_auctions",	I 2 ]
 ,[ N 616,	I 53,	I 2,	I _elem,	S "closed_auction",	I 2 ]
 ,[ N 617,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 618,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 619,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 620,	I 2,	I 3,	I _elem,	S "buyer",	I 2 ]
 ,[ N 621,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 622,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 623,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 624,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 625,	I 0,	I 5,	I _text,	S "item1",	I 2 ]
 ,[ N 626,	I 1,	I 3,	I _elem,	S "price",	I 2 ]
 ,[ N 627,	I 0,	I 4,	I _text,	S "113.87",	I 2 ]
 ,[ N 628,	I 1,	I 3,	I _elem,	S "date",	I 2 ]
 ,[ N 629,	I 0,	I 4,	I _text,	S "06/06/2000",	I 2 ]
 ,[ N 630,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 631,	I 0,	I 4,	I _text,	S "1",	I 2 ]
 ,[ N 632,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 633,	I 0,	I 4,	I _text,	S "Regular",	I 2 ]
 ,[ N 634,	I 35,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 635,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 636,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 637,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 638,	I 29,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 639,	I 28,	I 5,	I _elem,	S "parlist",	I 2 ]
 ,[ N 640,	I 9,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 641,	I 8,	I 7,	I _elem,	S "parlist",	I 2 ]
 ,[ N 642,	I 4,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 643,	I 3,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 644,	I 0,	I 10,	I _text,	S "\012farewells religion fetch bells rage names valued exeunt soul albans ungently advised serving ratcliff braggarts knowest desp sheep died repeat toy corrupted michael help dunghill trembles pill reap office early secure desires hated garland carriage impatient deserts feel challenger evil ",	I 2 ]
 ,[ N 645,	I 1,	I 10,	I _elem,	S "bold",	I 2 ]
 ,[ N 646,	I 0,	I 11,	I _text,	S " editions depart laur hereford richer ",	I 2 ]
 ,[ N 647,	I 2,	I 8,	I _elem,	S "listitem",	I 2 ]
 ,[ N 648,	I 1,	I 9,	I _elem,	S "text",	I 2 ]
 ,[ N 649,	I 0,	I 10,	I _text,	S "\012proudest lust approve rey should spectacles fiery perfect worshipp foul quod yes remorse young tyburn thrust attending spear shun doctor wild \012",	I 2 ]
 ,[ N 650,	I 2,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 651,	I 1,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 652,	I 0,	I 8,	I _text,	S "\012throng grandam awak helpless ventidius tread defeat teem durst wonderful attaint chaste sees fulfill mortality arme expedient attendants themselves performed leading sing villain skill store mischief see consciences sail text speed sons spleen die oft girl atomies commodity honor fall stopp they \012",	I 2 ]
 ,[ N 653,	I 14,	I 6,	I _elem,	S "listitem",	I 2 ]
 ,[ N 654,	I 13,	I 7,	I _elem,	S "text",	I 2 ]
 ,[ N 655,	I 0,	I 8,	I _text,	S "\012rain pays spilling rancour reasons grieves camp bachelor crow can whom soldiers growth invite less for vaughan properties ",	I 2 ]
 ,[ N 656,	I 1,	I 8,	I _elem,	S "keyword",	I 2 ]
 ,[ N 657,	I 0,	I 9,	I _text,	S " record penury herself reasons merits villainous whereupon wrote penny mar ",	I 2 ]
 ,[ N 658,	I 0,	I 8,	I _text,	S " preventions followed best eternity bestow blots rocks barnardine torn cassio tailor fame forfeit triumphant conceived deem cowardly merciful topgallant flint purgation whosoever ventidius befits forever bankrupt choughs stains certain violated burgundy shadows possesseth men repent predominant burns revelry swore prodigious next tyrant oath noses apart balth trade feasting field importunity expect experience kingly stay babe hopes liege astonished suspicion unmannerd alexander crown soil committed god stately incensed trance oracle slowness fast princes damned corn grandsire change tender end fields slain palm softly samp shore notion herod messengers horseman ",	I 2 ]
 ,[ N 659,	I 1,	I 8,	I _elem,	S "bold",	I 2 ]
 ,[ N 660,	I 0,	I 9,	I _text,	S " riggish ",	I 2 ]
 ,[ N 661,	I 0,	I 8,	I _text,	S " quirks shut thence beware jewels sland preventions has sells assails influences oppression pow maggot caught methought mechanical durst liker not seat ",	I 2 ]
 ,[ N 662,	I 4,	I 8,	I _elem,	S "emph",	I 2 ]
 ,[ N 663,	I 0,	I 9,	I _text,	S " assigns flesh made his third ",	I 2 ]
 ,[ N 664,	I 1,	I 9,	I _elem,	S "keyword",	I 2 ]
 ,[ N 665,	I 0,	I 10,	I _text,	S " seemeth ",	I 2 ]
 ,[ N 666,	I 0,	I 9,	I _text,	S " peril gain they stroke forsworn scape full determin professes commons ",	I 2 ]
 ,[ N 667,	I 0,	I 8,	I _text,	S " lordship clear operation practice pyrrhus earnest broke devil posterity company text misbegotten oregon strike saw arthur earnestly brow popilius ugly serves presentation commandment metal comparing thereon true secretly gallows preventions horridly slack lieutenant hers stop clown rosalinde wed pretty wildly \012",	I 2 ]
 ,[ N 668,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 669,	I 0,	I 5,	I _text,	S "9",	I 2 ]
 ,[ N 670,	I 28,	I 2,	I _elem,	S "closed_auction",	I 2 ]
 ,[ N 671,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 672,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 673,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 674,	I 2,	I 3,	I _elem,	S "buyer",	I 2 ]
 ,[ N 675,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 676,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 677,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 678,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 679,	I 0,	I 5,	I _text,	S "item2",	I 2 ]
 ,[ N 680,	I 1,	I 3,	I _elem,	S "price",	I 2 ]
 ,[ N 681,	I 0,	I 4,	I _text,	S "96.92",	I 2 ]
 ,[ N 682,	I 1,	I 3,	I _elem,	S "date",	I 2 ]
 ,[ N 683,	I 0,	I 4,	I _text,	S "12/05/2001",	I 2 ]
 ,[ N 684,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 685,	I 0,	I 4,	I _text,	S "1",	I 2 ]
 ,[ N 686,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 687,	I 0,	I 4,	I _text,	S "Featured",	I 2 ]
 ,[ N 688,	I 10,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 689,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 690,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 691,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 692,	I 4,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 693,	I 3,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 694,	I 0,	I 6,	I _text,	S "\012hitherto queen painted seat fords clay recall countryman divided delicate mocking active bills filth pledge surrender madness sufficiency moved converse goot claw show edmundsbury torment tough fish mediators tarquin pyrrhus ",	I 2 ]
 ,[ N 695,	I 1,	I 6,	I _elem,	S "keyword",	I 2 ]
 ,[ N 696,	I 0,	I 7,	I _text,	S " heathen ",	I 2 ]
 ,[ N 697,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 698,	I 0,	I 5,	I _text,	S "6",	I 2 ]
 ,[ N 699,	I 26,	I 2,	I _elem,	S "closed_auction",	I 2 ]
 ,[ N 700,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 701,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 702,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 703,	I 2,	I 3,	I _elem,	S "buyer",	I 2 ]
 ,[ N 704,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 705,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 706,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 707,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 708,	I 0,	I 5,	I _text,	S "item3",	I 2 ]
 ,[ N 709,	I 1,	I 3,	I _elem,	S "price",	I 2 ]
 ,[ N 710,	I 0,	I 4,	I _text,	S "53.85",	I 2 ]
 ,[ N 711,	I 1,	I 3,	I _elem,	S "date",	I 2 ]
 ,[ N 712,	I 0,	I 4,	I _text,	S "05/11/1999",	I 2 ]
 ,[ N 713,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 714,	I 0,	I 4,	I _text,	S "1",	I 2 ]
 ,[ N 715,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 716,	I 0,	I 4,	I _text,	S "Featured",	I 2 ]
 ,[ N 717,	I 8,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 718,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 719,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 720,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 721,	I 2,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 722,	I 1,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 723,	I 0,	I 6,	I _text,	S "\012strives occasion question sticks shall ingenious sinews liquid ashy gentlewomen authority assay hole selves living near doting modest wiltshire mocker eton profess forgeries butt wade lawful maccabaeus wert forced succeeding becomes wayward got \012",	I 2 ]
 ,[ N 724,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 725,	I 0,	I 5,	I _text,	S "6",	I 2 ]
 ,[ N 726,	I 29,	I 2,	I _elem,	S "closed_auction",	I 2 ]
 ,[ N 727,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 728,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 729,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 730,	I 2,	I 3,	I _elem,	S "buyer",	I 2 ]
 ,[ N 731,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 732,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 733,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 734,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 735,	I 0,	I 5,	I _text,	S "item4",	I 2 ]
 ,[ N 736,	I 1,	I 3,	I _elem,	S "price",	I 2 ]
 ,[ N 737,	I 0,	I 4,	I _text,	S "123.52",	I 2 ]
 ,[ N 738,	I 1,	I 3,	I _elem,	S "date",	I 2 ]
 ,[ N 739,	I 0,	I 4,	I _text,	S "02/11/1999",	I 2 ]
 ,[ N 740,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 741,	I 0,	I 4,	I _text,	S "1",	I 2 ]
 ,[ N 742,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 743,	I 0,	I 4,	I _text,	S "Regular",	I 2 ]
 ,[ N 744,	I 11,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 745,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 746,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 747,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 748,	I 5,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 749,	I 4,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 750,	I 0,	I 6,	I _text,	S "\012vowed keys imperial were swinstead forsake cat aliena spies crave requite forfeit doctor ",	I 2 ]
 ,[ N 751,	I 1,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 752,	I 0,	I 7,	I _text,	S " possess ",	I 2 ]
 ,[ N 753,	I 0,	I 6,	I _text,	S " aught demand ceremonies obscure engross hero restraint bolingbroke neighbour crimes dominions common turns conduct wav therewithal abandon yet hunger \012",	I 2 ]
 ,[ N 754,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 755,	I 0,	I 5,	I _text,	S "5",	I 2 ]
 ,[ N 756,	I 32,	I 2,	I _elem,	S "closed_auction",	I 2 ]
 ,[ N 757,	I 2,	I 3,	I _elem,	S "seller",	I 2 ]
 ,[ N 758,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 759,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 760,	I 2,	I 3,	I _elem,	S "buyer",	I 2 ]
 ,[ N 761,	I 1,	I 4,	I _elem,	S "person",	I 2 ]
 ,[ N 762,	I 0,	I 5,	I _text,	S "person0",	I 2 ]
 ,[ N 763,	I 2,	I 3,	I _elem,	S "itemref",	I 2 ]
 ,[ N 764,	I 1,	I 4,	I _elem,	S "item",	I 2 ]
 ,[ N 765,	I 0,	I 5,	I _text,	S "item5",	I 2 ]
 ,[ N 766,	I 1,	I 3,	I _elem,	S "price",	I 2 ]
 ,[ N 767,	I 0,	I 4,	I _text,	S "96.06",	I 2 ]
 ,[ N 768,	I 1,	I 3,	I _elem,	S "date",	I 2 ]
 ,[ N 769,	I 0,	I 4,	I _text,	S "04/24/1999",	I 2 ]
 ,[ N 770,	I 1,	I 3,	I _elem,	S "quantity",	I 2 ]
 ,[ N 771,	I 0,	I 4,	I _text,	S "2",	I 2 ]
 ,[ N 772,	I 1,	I 3,	I _elem,	S "type",	I 2 ]
 ,[ N 773,	I 0,	I 4,	I _text,	S "Featured",	I 2 ]
 ,[ N 774,	I 14,	I 3,	I _elem,	S "annotation",	I 2 ]
 ,[ N 775,	I 2,	I 4,	I _elem,	S "author",	I 2 ]
 ,[ N 776,	I 1,	I 5,	I _elem,	S "person",	I 2 ]
 ,[ N 777,	I 0,	I 6,	I _text,	S "person0",	I 2 ]
 ,[ N 778,	I 8,	I 4,	I _elem,	S "description",	I 2 ]
 ,[ N 779,	I 7,	I 5,	I _elem,	S "text",	I 2 ]
 ,[ N 780,	I 0,	I 6,	I _text,	S "\012jove superiors prolong which conspirator crowns fellowship indisposition skins filthy divers fault apparell worthiness supposition parchment restitution rings rages remains lass dependent pelican contrive paradoxes unmask desdemona weak pleases shame wisely cheek poison avoid ulysses exeunt answer smoothing punishment much anointed bloody shook here armado supply four digestion unresisted consummate glou ding figure made unwrung worst repute envious meanest read nan stake shriek tower nights armed drinking instant scruple citizens rightful nonino shame hills dismal other fasting attends judge aspire hand putting repeal grounds bestrid commission crave mess tarries sport view freely lame done intend cast shun kills presented body landed question hem same burdens plenty esteem weak sigh sunday body preventions revenge horses cleomenes thrust what albeit foolishly mirror gently mock allow index evils should consider deeds suit damsons willoughby thousand number morn banish barricado unfolding perhaps gently stalk degree oblivion wars monsieur companies swords shifted clay strives frozen jour ",	I 2 ]
 ,[ N 781,	I 1,	I 6,	I _elem,	S "emph",	I 2 ]
 ,[ N 782,	I 0,	I 7,	I _text,	S " ajax states mark parcels advertised utterly virtue flatter sleeping ope ",	I 2 ]
 ,[ N 783,	I 0,	I 6,	I _text,	S " lucilius tybalt glow killed account obdurate kindly ",	I 2 ]
 ,[ N 784,	I 1,	I 6,	I _elem,	S "bold",	I 2 ]
 ,[ N 785,	I 0,	I 7,	I _text,	S " heart light bosom garden cog yet daughters tott ",	I 2 ]
 ,[ N 786,	I 0,	I 6,	I _text,	S " lifted offer \012",	I 2 ]
 ,[ N 787,	I 1,	I 4,	I _elem,	S "happiness",	I 2 ]
 ,[ N 788,	I 0,	I 5,	I _text,	S "4",	I 2 ]

 ]