# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

SWIGFLAGS = $(MONETDB_INCS) $(CLIENTS_INCS)
INCLUDES = ../../../include ../../../common ../../../storage ../../../server \
	$(MONETDB5_INCS) $(CLIENTS_INCS) $(MONETDB_INCS) $(PYTHON_INCS)

#  Both GNU's gcc and Intel's icc do not like to compile swig-generated code
#  with our strict X_CFLAGS.
#  Instead of diabling the strict X_CFLAGS completely,
#  we use GCC_SWIG_CFLAGS and ICC_SWIG_CFLAGS, respectively,
#  to disable only the problematic warnings/errors as locally as possbile.
#  See buildtools/conf/MonetDB.m4 for details.
#CFLAGS = $(GCC_SWIG_CFLAGS) $(ICC_SWIG_CFLAGS)
#
#  However, there are situations where user-chosen CFLAGS and/or X_CFLAGS
#  are beyond our control. Hence, for the sake of a smooth compilation, we
#  have to take the freedom to overrule the user's deliberate choice for
#  X_CFLAGS by locally disabling them indifferently.
X_CFLAGS =

lib_monetdb5 = {
	PREFIX =
	NAME = _monetdb5
	SOURCES = monetdb5.py.i
	LIBS = ../../monet5/libembeddedsql5 ../../../server/libsqlserver ../../../storage/libstore ../../../storage/bat/libbatstore ../../../common/libsqlcommon \
		$(MONETDB5_MODS) -l_logger -l_bat5 -l_tablet $(MONETDB5_LIBS) -lmal \
		$(CLIENTS_LIBS) $(MONETDB_LIBS) -lbat -lMapi -lmutils -lstream $(PYTHON_LIBS) $(READLINE_LIBS) $(PTHREAD_LIBS)
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}

headers_py = {
	HEADERS = py
	SOURCES = monetdb5.py.i
	TARGETS = monetdb5.py
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}
