INCLUDES = -I../modules/atoms \
	-I../mal $(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(PCL_FLAGS) $(PCRE_CFLAGS)


MTSAFE

LIBS = {
	NAME = sched
	DIR = pkglibdir
	SEP = _
	SOURCES = \
	mal_scheduler.mx mal_mes.mx

	HEADERS = h 
	#SCRIPTS = mal
	LIBS = ../mal/libmal $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mal_scheduler.mx mal_mes.mx
}
