INCLUDES = -I../modules/atoms -I../optimizer \
	-I../mal $(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(PCL_FLAGS) $(PCRE_CFLAGS)


MTSAFE

LIBS = {
	NAME = sched
	DIR = pkglibdir
	SEP = _
	SOURCES = \
	mal_isolation.mx mal_scheduler.mx mal_mes.mx mal_memorun.mx

	HEADERS = h 
	#SCRIPTS = mal
	LIBS = ../mal/libmal ../optimizer/lib_optimizer $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mal_isolation.mx mal_scheduler.mx mal_mes.mx mal_memorun.mx
}

EXTRA_DIST_DIR = Tests
