# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2008 CWI.
# All Rights Reserved.

INCLUDES = -I../modules/atoms -I../optimizer \
	-I../mal $(MONETDB_INCS) \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(PCL_FLAGS) $(PCRE_CFLAGS)


MTSAFE

LIBS = {
	NAME = sched
	DIR = libdir/MonetDB5
	SEP = _
	SOURCES = \
	mal_isolation.mx mal_scheduler.mx mal_mes.mx mal_memorun.mx

	#SCRIPTS = mal
	LIBS = ../mal/libmal ../optimizer/lib_optimizer $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

headers_h = {
	DIR = includedir/MonetDB5/scheduler
	SOURCES = \
	mal_isolation.mx mal_scheduler.mx mal_mes.mx mal_memorun.mx
	HEADERS = h 
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = mal_isolation.mx mal_scheduler.mx mal_mes.mx mal_memorun.mx
}

EXTRA_DIST_DIR = Tests
