# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

INCLUDES = \
	../../optimizer \
	../../mal \
	../../../gdk \
	../../../common/stream \
	../../../common/options

MTSAFE

lib_opt_sql_append = {
	MODULE
	DIR = libdir/monetdb5
	SEP = _
	SOURCES = opt_sql_append.c opt_sql_append.h
	LIBS = ../../tools/libmonetdb5 \
		../../../gdk/libbat \
		../../../common/stream/libstream \
		$(MALLOC_LIBS)
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = opt_sql_append.mal
}

headers_opt_sql_append_autoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 91_opt_sql_append.mal
}

EXTRA_DIST = 91_opt_sql_append.mal

EXTRA_DIST_DIR = Tests
