# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

SWIGFLAGS = -I$(srcdir)/../../mapilib $(PERL_INCS)
INCLUDES = ../../mapilib ../../../common/options $(PERL_INCS)

#  Both GNU's gcc and Intel's icc do not like to compile
#  swig-generated code with our strict X_CFLAGS.
#  Instead of disabling the strict X_CFLAGS completely, we use
#  GCC_SWIG_CFLAGS and ICC_SWIG_CFLAGS, respectively, to disable only
#  the problematic warnings/errors as locally as possible.  See
#  configure.ag for details.
#CFLAGS = $(GCC_SWIG_CFLAGS) $(ICC_SWIG_CFLAGS) -D_GNU_SOURCE
#
#  However, at least with gcc 4.2.2 and swig 1.3.31 on Gentoo 1.12.9,
#  we still get
#  MapiLib.pm.c: In function 'boot_MapiLib':
#  MapiLib.pm.c:6157: warning: passing argument 2 of '_swig_create_magic' discards qualifiers from pointer target type
#  Hence, we have to disable (override) our X_CFLAGS completely:
X_CFLAGS = -D_GNU_SOURCE

#  Likewise, we need to disable W_CFLAGS=-WX (i.e., treating warnings
#  as errors) for swig-generated code on Windows
W_CFLAGS =

lib_MapiLib = {
	PREFIX =
	NAME = MapiLib
	SOURCES = MapiLib.pm.i
	LIBS = ../../mapilib/libmapi $(PERL_LIBS) $(MATH_LIBS)
	DIR = $(prefix)/$(PERL_LIBDIR)
	# we need this flag to allow for a name that does not start with "lib"
	LDFLAGS = -module
}

headers_pm = {
	HEADERS = pm
	SOURCES = MapiLib.pm.i
	TARGETS = MapiLib.pm
	DIR = $(prefix)/$(PERL_LIBDIR)
}
