INCLUDES = $(MONETDB_INCS) ../mal

#YFLAGS = -v -p mil -d

#bin_M2m = {
#	LIB = pkglibdir
#	SOURCES = M2m.mx  mil.mx mil_compiler.mx mil_conformance.mx \
#		mil_commands.mx mil_scenario.mx 
#	LIBS = $(MONETDB_LIBS) -lbat -lstream ../mal/libmal \
#                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
#		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
#}
#
##doc_M2m = {
#	DIR = pkgdatadir/docs/mil
#	SOURCES = M2m.mx  mil_compiler.mx mil_conformance.mx \
#		mil_commands.mx mil_scenario.mx
#}
lib_mil_scenario = {
	NAME = _mil_scenario
	DIR = pkglibdir
	SOURCES = mil_parser.mx mil_scenario.mx mil_conformance.mx  \
	mil_commands.mx

	HEADERS = h
	SCRIPTS = mal mil ""
	LIBS = $(MONETDB_LIBS)
}

scripts_mal = {
	DIR = pkglibdir
	SOURCES = mil_scenario.mx
}
