
INCLUDES = -I../common -I../gdk  

YFLAGS = -v -d

bin_M2m = {
	SOURCES = M2m.mx  mil_parser.mx conformance.mx
	LIBS = ../common/libmutils ../common/libstream ../gdk/libbat \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
