# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

INCLUDES = .. \
       ../.. \
       ../../../../include \
	   ../../../../common \
	   ../../../../storage \
	   ../../../../server \
	   ../../../../../monetdb5/modules/atoms \
	   ../../../../../monetdb5/modules/kernel \
	   ../../../../../monetdb5/mal \
	   ../../../../../monetdb5/modules/mal \
	   ../../../../../monetdb5/optimizer \
	   ../../../../../monetdb5/scheduler \
	   ../../../../../common/options \
	   ../../../../../common/stream \
	   ../../../../../common/utils \
	   ../../../../../gdk \
	   $(cfitsio_CFLAGS)

lib__fits = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = fits.c fits.h
	LIBS = NATIVE_WIN32?../../../../../monetdb5/tools/libmonetdb5 \
	       $(cfitsio_LIBS)
}

headers_fitsmal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = fits.mal
}

headers_fitssql = {
	HEADERS = sql
	DIR = libdir/monetdb5/createdb
	SOURCES = 72_fits.sql
}

headers_fitsautoload = {
	HEADERS = mal
	DIR = libdir/monetdb5/autoload
	SOURCES = 72_fits.mal
}
