# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2012 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../mal \
		   ../../optimizer \
		   ../../../common/options \
		   ../../../common/stream \
		   ../../../gdk

AM_YFLAGS = -d
AM_LFLAGS = -o$(LEX_OUTPUT_ROOT).c --header-file=$(LEX_OUTPUT_ROOT).h

# flex' output isn't up to the strictness of our flags
X_CFLAGS = #$(X_CFLAGS:-Werror=) <- recursive

lib__json = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = json.c json.h

	LIBS = ../../tools/libmonetdb5
}

lib__jaql = {
	MODULE
	DIR = libdir/monetdb5
	SOURCES = jaql.y jaql.l jaql.c jaql.h jaqlgencode.c jaqlgencode.h

	LIBS = ../../tools/libmonetdb5
}

headers_json_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = json.mal
}

headers_jaql_mal = {
	HEADERS = mal
	DIR = libdir/monetdb5
	SOURCES = jaql.mal
}

headers_autoload = {
        HEADERS = mal
        DIR = libdir/monetdb5/autoload
        SOURCES = 30_jaql.mal
}

EXTRA_DIST = json.mal jaql.mal 30_jaql.mal
