#!/bin/bash

pf -s9 <<'EOT'
typeswitch (42)
  case element(foo)         return 1
  case item()               return 2
  case node()               return 3
  case empty()              return 4
  default                   return 5
EOT
echo $?
