#!/bin/sh

NAME="$1"
PRELUDE="$2"

Mlog -x mkdir Dump Dump_n

worker () {
	Mlog -x sleep 9
	Mlog -x $MDUMP    $TSTTRGDIR/Dump
	Mlog -x $MDUMP -n $TSTTRGDIR/Dump_n
}

pseudo_user () {
	worker 2> dump.tmp.err 1> dump.tmp.out
	echo "quit;"
} 

pseudo_user | Mlog -x $MSERVER --dbname=$TSTDB $PRELUDE

echo
cat dump.tmp.out
cat dump.tmp.err >&2

for i in Dump/* Dump_n/* ; do
	Mlog -x cat $i
done

Mlog -x mkdir -p $GDK_DBFARM/Dump
Mlog -x mkdir -p $GDK_DBFARM/Dump_n
Mlog -x $MSERVER --dbname=Dump   Dump/DBrestore   dump.check.mil
Mlog -x $MSERVER --dbname=Dump_n Dump_n/DBrestore dump.check_n.mil

