#!/bin/sh

NAME="$1"
PRELUDE="$2"

Mlog -x mkdir Dump Dump_n

worker () {
	Mlog -x sleep 9
	Mlog -x $MDUMP    $TSTTRGDIR/Dump
	Mlog -x $MDUMP -n $TSTTRGDIR/Dump_n
}

pseudo_user () {
	worker 2> dump.tmp.err 1> dump.tmp.out
	echo "quit;"
} 

pseudo_user | Mlog -x $MSERVER -db $TSTDB $PRELUDE

echo
cat dump.tmp.out
cat dump.tmp.err >&2

for i in Dump/* Dump_n/* ; do
	Mlog -x cat $i
done

Mlog -x $MCREATEDB -db Dump
Mlog -x $MCREATEDB -db Dump_n
Mlog -x $MSERVER -db Dump   -prelude Dump/DBrestore   dump.check.mil
Mlog -x $MSERVER -db Dump_n -prelude Dump_n/DBrestore dump.check_n.mil

