#!/bin/sh

NAME=$1

mserver="`echo $MSERVER' ' | sed 's| -d8 | |g'`"

Mlog -x $MLOAD $NAME.data -db $TSTDB -oid 1000000 -f $NAME.format
Mlog -x $MSERVER -db $TSTDB < $NAME.mil
Mlog -x $mserver -db $TSTDB < $NAME.mil
