#!/bin/sh

NAME=$1

mserver="`echo $MSERVER' ' | sed 's| -d8 | |g'`"

Mlog -x $MLOAD $NAME.data -db $TSTDB -oid 1000000 -f $NAME.format
Mlog   "$MSERVER --dbname=$TSTDB < $NAME.mil"
        $MSERVER --dbname=$TSTDB < $NAME.mil
Mlog   "$mserver --dbname=$TSTDB < $NAME.mil"
        $mserver --dbname=$TSTDB < $NAME.mil
