
INCLUDES = -I../../modules/atoms \
        -I../../mal $(MONETDB_INCS) \
        $(Z_CFLAGS) $(BZ_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = x100core.mx 

	HEADERS = h 
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lbat -lstream \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
scripts_mal = {
	DIR = pkglibdir/x100
	SOURCES = x100core.mx
}
