INCLUDES =  -I../../common -I../../gdk \
        -I../../modules/atoms \
        -I../../mal $(Z_CFLAGS) $(BZ_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = x100core.mx 

	HEADERS = h 
	SCRIPTS = mil ""
	LIBS = ../common/libmutils ../common/libstream ../../gdk/libbat \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
scripts_mal = {
        DIR = sysconfdir/MonetDB/x100
        SOURCES = x100core.mal
}
