# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2015 MonetDB B.V.
# All Rights Reserved.

MTSAFE

INCLUDES = ../../monetdb5/mal \
		   ../../monetdb5/modules/atoms \
		   ../../monetdb5/modules/mal \
		   ../../monetdb5/modules/kernel \
		   ../../monetdb5/extras/rapi \
		   ../../gdk \
		   ../../common/stream \
		   ../../common/utils \
		   ../../common/options \
		   ../../clients/mapilib \
		   ../../sql/include \
		   ../../sql/server \
		   ../../sql/common \
		   ../../sql/storage \
		   ../../sql/storage/bat \
		   ../../sql/backends/monet5 \
		   $(pcre_CFLAGS)

lib_embedded  = {
	SOURCES = embedded.c embedded.h inlined_scripts.c
	VERSION = 1
	LIBS = ../../monetdb5/tools/libmonetdb5 \
		../../gdk/libbat \
		$(pcre_LIBS) $(PSAPILIB) \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}

lib_embeddedr  = {
	SOURCES = embeddedr.c embeddedr.h
	VERSION = 1
	LIBS = libembedded \
		../../gdk/libbat \
		$(pcre_LIBS) $(PSAPILIB) \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}
