# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../include ../../common ../../storage ../../server ../ \
	$(MONETDB5_INCS) $(CLIENTS_INCS) $(MONETDB_INCS) $(READLINE_INCS) $(MSEED_CFLAGS)

lib__vault = {
	DIR = libdir/MonetDB5/
	SOURCES = vault.mx
	LIBS = $(MONETDB5_LIBS) -lmonetdb5 \
		$(MONETDB_LIBS) -lbat
}

headers_h = {
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = vault.mx
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = vault.mx vault.sql
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 70_vault.mal
}

lib__mseed = {
	COND = HAVE_MSEED
	DIR = libdir/MonetDB5/
	SOURCES = mseed.mx
	LIBS = $(MONETDB5_LIBS) -lmonetdb5 \
		$(MONETDB_LIBS) -lbat $(MSEED_LIBS)
}

headers_mseedautoload = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 71_mseed.mal
}

headers_mseedh = {
	COND = HAVE_MSEED
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = mseed.mx
}

headers_mseedmal = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = mseed.mx
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 70_vault.mal 71_mseed.mal vault.sql
