# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../../include ../../../common ../../../storage ../../../server .. \
	../../../../../MonetDB5/src/modules/atoms \
	../../../../../MonetDB5/src/compiler \
	../../../../../MonetDB5/src/modules/kernel \
	../../../../../MonetDB5/src/mal \
	../../../../../MonetDB5/src/modules/mal \
	../../../../../MonetDB5/src/optimizer \
	../../../../../MonetDB5/src/scheduler \
	../../../../../clients/src/mapilib \
	../../../../../MonetDB/src/common \
	../../../../../common/stream \
	../../../../../MonetDB/src/gdk \
	$(READLINE_INCS) $(MSEED_CFLAGS) $(CFITSIO_CFLAGS)

lib__vault = {
	DIR = libdir/MonetDB5
	SOURCES = vault.mx
	LIBS = ../../../../../MonetDB5/src/tools/libmonetdb5 \
		../../../../../MonetDB/src/gdk/libbat $(MSEED_LIBS) 
}

lib__mseed = {
	COND = HAVE_MSEED
	DIR = libdir/MonetDB5
	SOURCES = mseed.mx
	LIBS = ../../../../../MonetDB5/src/tools/libmonetdb5 \
		../../../../../MonetDB/src/gdk/libbat $(MSEED_LIBS)
}

lib__fits = {
    COND = HAVE_CFITSIO
    DIR = libdir/MonetDB5
    SOURCES = fits.mx
    LIBS = ../../../../../MonetDB5/src/tools/libmonetdb5 $(CFITSIO_LIBS)
}

headers_h = {
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = vault.mx
}

headers_mseedh = {
	COND = HAVE_MSEED
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = mseed.mx
}

headers_fitsh = {
	COND = HAVE_CFITSIO
	HEADERS = h
	DIR = includedir/MonetDB5/sql
	SOURCES = fits.mx
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = vault.mx
}

headers_sql = {
	HEADERS = sql
	DIR = libdir/MonetDB5
	SOURCES = vault.mx
}

headers_mseedmal = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = mseed.mx
}

headers_fitsmal = {
	COND = HAVE_CFITSIO
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = fits.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 70_vault.mal
}

headers_mseedautoload = {
	COND = HAVE_MSEED
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 71_mseed.mal
}

headers_fitsautoload = {
    COND = HAVE_CFITSIO
    HEADERS = mal
    DIR = libdir/MonetDB5/autoload
    SOURCES = 72_fits.mal
}

EXTRA_DIST_DIR = Tests
EXTRA_DIST = 70_vault.mal 71_mseed.mal 72_fits.mal
