# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

EXTRA_DIST = \
		Test_Cautocommit.java \
		Test_Clargequery.java \
		Test_Cmanycon.java \
		Test_Creplysize.java \
		Test_Csavepoints.java \
		Test_Ctransaction.java \
		Test_PSgeneratedkeys.java \
		Test_PSlargeresponse.java \
		Test_PSlargeamount.java \
		Test_PStimedate.java \
		Test_PStimezone.java \
		Test_PStypes.java \
		Test_Rbooleans.java \
		Test_Rmetadata.java \
		Test_Rpositioning.java \
		Test_Rtimedate.java \
		Test_Sbatching.java \
		BugConcurrent_clients_SF_1504657.java \
		build.xml build.properties

ant_jar_jdbctests = {
	DIR = datadir/monetdb/lib
	FILES = jdbctests.jar
}
