# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

EXTRA_DIST = \
		Test_Cautocommit.java \
		Test_Clargequery.java \
		Test_Cmanycon.java \
		Test_Creplysize.java \
		Test_Csavepoints.java \
		Test_Ctransaction.java \
		Test_Dobjects.java \
		Test_PSgeneratedkeys.java \
		Test_PSlargeresponse.java \
		Test_PSlargeamount.java \
		Test_PStimedate.java \
		Test_PStimezone.java \
		Test_PStypes.java \
		Test_Rbooleans.java \
		Test_Rmetadata.java \
		Test_Rpositioning.java \
		Test_Rtimedate.java \
		Test_Sbatching.java \
		Test_Int128.java \
		BugConcurrent_clients_SF_1504657.java \
		BugDatabaseMetaData_Bug_3356.java \
		build.xml build.properties

ant_jar_jdbctests = {
	DIR = datadir/monetdb/lib
	FILES = jdbctests.jar
}
