#!/usr/bin/perl
print "execute 500 simple sessions against the server\n";
$host='192.16.196.210'; # IP nummber is faster as name 'orion.ins.cwi.nl';
$port=50001;
$user=mk;
$passwd=xx;
$action="print(1);";
for ($x=0; $x<500; $x++) {
	system("Mclient -h ".$host." -p ".$port." -u ". $user.
		" -P ".$passwd . ' --language mal -e "'.$action. '"');
}
	#system("Mclient -h ".$host." -p ".$port." -u ". $user.
		#" -P ".$passwd . ' --language mal </dev/null');

