#!/usr/bin/perl
print "execute 500 simple sessions against the server\n";
$host='192.16.196.210'; # IP nummber is faster as name 'orion.ins.cwi.nl';
$port=50001;
$user=mk;
$passwd=xx;
$action="select count(*) from tables;";
for ($x=0; $x<500; $x++) {
	# simple connection without SQL init
	   system("Mclient -h ".$host." -p ".$port." -u ". $user.
		" -P ".$passwd ." </dev/null");
	# perform SQL action
	  # system("Mclient -h ".$host." -p ".$port." -u ". $user.
		#" -P ".$passwd . ' --language sql -e "'.$action. '"');
	# just initialize SQL
	#system("Mclient -h ".$host." -p ".$port." -u ". $user.
		#" -P ".$passwd . ' --language sql </dev/null');
}

