	#include(/usr/share/cmake/libLAS/liblas-config.cmake)
	#include(/usr/share/cmake/libLAS/liblas-config-version.cmake)

	#if(LIBLAS_FOUND)
	#set(LIBLAS_VERSION_REQUIRED_MIN "1.8.0")
	#if(LIBLAS_VERSION VERSION_LESS "${LIBLAS_MINIMUM_VERSION}")
	##if(${WITH_LIBLAS} STREQUAL "YES")
	##	message(FATAL_ERROR "liblas library found, but the version is too old: ${LIBLAS_VERSION} < ${LIBLAS_MINIMUM_VERSION}")
	##else()
	#message(STATUS "liblas library found, but the version is too old: ${LIBLAS_VERSION} < ${LIBLAS_MINIMUM_VERSION}")
	##endif()
	#else()
	#set(HAVE_LIDAR "${LIBLAS_FOUND}")
	#endif()
	##else()
	##	message(FATAL_ERROR "liblas library required for lidar module")
	#endif()
