#!/usr/bin/env bash

# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.monetdb.org/Legal/MonetDBLicense
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

# Make a clone from a local database on a remote server.
# usage: monetdbbincopy <dbname> <passphrase> <host-list> 
# copies <dbname> to <host-list> 
# The passphrase should be sent as well for remote servers
# We presume monetdb, mclient, mnc are in PATH!
#
# If you need anything special (such as a port number) on the local or
# remote host to be passed onto monetdb, you can set the
# MONETDB_EXTRA_OPTS and RMONETDB_EXTRA_OPTS variables in the
# environment.

dbname=$1
passphrase=$2
shift 2 
hostlist=$*

if [[ -z ${dbname} || -z ${passphrase} ]] ; then
	echo "usage: monetdbbincopy <dbname> <passphrase> <host-list>"
	exit 1
fi

# take the local database down
# we don't care if the database is already locked
monetdb -q ${MONETDB_EXTRA_OPTS} lock $dbname 
# and if it's already stopped it's fine too
monetdb -q ${MONETDB_EXTRA_OPTS} stop $dbname
lpath=$(monetdb ${MONETDB_EXTRA_OPTS} status -l $dbname | \
	grep "location:" | cut -d: -f2)
# if we have no lpath, $dbname probably doesn't exist
[[ -z ${lpath} ]] && exit 1

for host in ${hostlist} ; do
	echo "$(date +%D:%H:%M): start the copy to ${host}"
	# skip doing anything if creation fails
	monetdb -q ${RMONETDB_EXTRA_OPTS} -h$host -P$passphrase create $dbname || continue
	rpath=$(monetdb ${RMONETDB_EXTRA_OPTS} -h$host -P$passphrase status -l $dbname | \
		grep "location:" | cut -d: -f2)
#	ssh -n $host "mnc -l -B $host 54321 | tar -C $rpath -jxf -" &
#	there=$!
#	sleep 1
#	tar -C ${lpath} --exclude=.mapi.sock -jcf - . | mnc -B $host 54321
#	wait $there
	tar -C ${lpath} --exclude=.mapi.sock -cf - . | xz -0 -c - | \
		ssh $host "xzcat - | tar -C $rpath -xf -"
	monetdb -q ${RMONETDB_EXTRA_OPTS} -h$host -P$passphrase release $dbname
done
echo "$(date +%D:%H:%M): done"
monetdb -q ${MONETDB_EXTRA_OPTS} release $dbname
