## Process this file with automake to produce Makefile.in

INCLUDES =  ../parser ../../mal ../../modules/mal \
        ../../modules/atoms ../../gdk ../../common ../clients


lib__sql_server = {
	DIR = pkglibdir
	SOURCES = sql_privileges.mx sql_logger.mx sql_mvc.mx sql_server.mx  \
		sql_connect.mx sql_bm.mx \
		sql_codegen.mx sql.mx sql_scenario.mx
	WINLIBS = -lbat -lmonet -lstream -l_streams -l_kernel -l_ascii_io
	LIBS = ../parser/libsql $(MONET_LIBS)
	LDFLAGS = -module
}

scripts_mal = {
	DIR = sysconfdir/MonetDB/sql
	SOURCES = sql_server.mal sql.mal sql_scenario.mal
}
