# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2004 CWI.
# All Rights Reserved.

SWIGFLAGS = -I../../C
INCLUDES = -I../../C -I../../../../common -I@PYTHONINC@

# we need this flag to allow for a name that does not start with "lib"
_MapiLib_la_LDFLAGS = -module

# with gcc we could use these
#X_CFLAGS = -Wno-unused-parameter -Wno-unused-function
# but we certainly have to override the default X_CFLAGS:
X_CFLAGS =

SUBDIRS = MonetSQLdb

lib_MapiLib = {
	PREFIX =
	NAME = _MapiLib
	SOURCES = MapiLib.py.i
	LIBS = ../../C/libMapi
	DIR = pkgdatadir/python
}

headers_py = {
	HEADERS = py
	SOURCES = MapiLib.py.i CMapi.py
	TARGETS = MapiLib.py CMapi.py
	DIR = pkgdatadir/python
}
