# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

SUBDIRS = src conf scripts

EXTRA_DIST = bootstrap lady.gif configure.ag RunMtest.in \
		RunMtest.bat.in RunMapprove.in RunMapprove.bat.in \
		sysdefs.h.in MonetDB.spec MonetDB.spec.in HowToStart \
		HowToStart-Win32.txt HowToStart-MinGW.txt \
		HowToStart-MinGW-pcre.txt HowToStart-MinGW-swig.txt \
		RunMserver.bat.in rpm.mk.in RunMapiClient.bat.in RunMserver.in

EXTRA_DIST_DIR = NT tests

EXTRA_HEADERS = monetdb4_config.h sysdefs.h

scripts_gif = {
	DIR = pkgdatadir
	SOURCES = lady.gif
}

headers_pc = {
	HEADERS = pc
	SOURCES	= MonetDB.pc.in
	DIR = libdir/pkgconfig
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
