# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

MTSAFE

man_MANS = mserver5.1

EXTRA_DIST = $(man_MANS)

INCLUDES = ../../monetdb5/mal \
		   ../../gdk \
		   ../../common/stream \
		   ../../common/utils \
		   ../../common/options \
		   $(openssl_CFLAGS) $(pcre_CFLAGS) $(libxml2_CFLAGS)

bin_mserver5 = {
	# hack: include mserver5.1.in here to get it expanded
	SOURCES = mserver5.c monet_version.h monet_version.c.in \
		mserver5.1.in
	LIBS = ../../monetdb5/tools/libmonetdb5 \
		../../gdk/libbat \
		$(curl_LIBS) $(pcre_LIBS) $(openssl_LIBS) $(PSAPILIB) \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(DL_LIBS) $(PTHREAD_LIBS)
}
