# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2018 MonetDB B.V.

MTSAFE

man_MANS = mserver5.1

EXTRA_DIST = mserver5.1.in

INCLUDES = ../../monetdb5/mal \
		   ../../gdk \
		   ../../common/stream \
		   ../../common/utils \
		   ../../common/options \
		   ../../monetdb5/modules/atoms \
		   ../../monetdb5/modules/mal \
		   ../../sql/backends/monet5 \
		   ../../sql/common \
		   ../../sql/include \
		   ../../sql/server \
		   ../../sql/storage \
		   $(openssl_CFLAGS) $(pcre_CFLAGS) $(libxml2_CFLAGS)

headers_docx = {
	HEADERS = docx
	SOURCES = tomographintro.docx
	DIR = datadir/doc/MonetDB-client-tools
}

headers_pdf = {
	HEADERS = pdf
	SOURCES = tomographintro.pdf
	DIR = datadir/doc/MonetDB-client-tools
}

# see clients/mapiclient/Makefile.ag for use of logo file
headers_png = {
	HEADERS = png
	SOURCES = monetdblogo.png
	DIR = datadir/doc/MonetDB
}

bin_mserver5 = {
	# hack: include mserver5.1.in here to get it expanded
	SOURCES = mserver5.c monet_version.h monet_version.c.in
	LIBS = ../../monetdb5/tools/libmonetdb5 \
		../../gdk/libbat \
		../../common/stream/libstream \
		../../clients/mapilib/libmapi \
		$(UUID_LIBS) \
		$(MATH_LIBS) \
		$(SOCKET_LIBS) \
		$(MALLOC_LIBS) \
		$(PTHREAD_LIBS) \
		$(DL_LIBS) \
		$(openssl_LIBS) \
		$(pcre_LIBS) \
		$(libxml2_LIBS) \
		$(PSAPILIB) \
		$(KVM_LIBS) \
		$(zlib_LIBS) \
		$(bzip2_LIBS) \
		$(snappy_LIBS) \
		$(lz4_LIBS) \
		$(liblzma_LIBS) \
		$(curl_LIBS) \
		$(LTLIBICONV)
}

bin_shutdowntest = {
	CONDINST = HAVE_TESTING
	SOURCES = shutdowntest.c
	LIBS = ../../monetdb5/tools/libmonetdb5 \
		../../gdk/libbat \
		../../common/stream/libstream \
		../../clients/mapilib/libmapi \
		$(UUID_LIBS) \
		$(MATH_LIBS) \
		$(SOCKET_LIBS) \
		$(MALLOC_LIBS) \
		$(PTHREAD_LIBS) \
		$(DL_LIBS) \
		$(openssl_LIBS) \
		$(pcre_LIBS) \
		$(libxml2_LIBS) \
		$(PSAPILIB) \
		$(KVM_LIBS) \
		$(zlib_LIBS) \
		$(bzip2_LIBS) \
		$(snappy_LIBS) \
		$(lz4_LIBS) \
		$(liblzma_LIBS) \
		$(curl_LIBS) \
		$(LTLIBICONV)
}
