#ifdef TEXT /* Windows defines a symbol TEXT */
#undef TEXT
#endif

#define MAP_PID             0
#define PRE_SIZE            1
#define PRE_LEVEL           2
#define PRE_PROP            3
#define PRE_KIND            4
#define PRE_NID             5
#define NID_RID             6
#define FRAG_ROOT           7
#define QN_HISTOGRAM        8
#define QN_PREFIX_URI_LOC   9
#define QN_URI_LOC         10
#define QN_PREFIX          11
#define QN_URI             12
#define QN_LOC             13
#define PROP_TEXT          14
#define PROP_COM           15
#define PROP_INS           16
#define PROP_TGT           17
#define PROP_VAL           18
#define ATTR_OWN           19
#define ATTR_QN            20
#define ATTR_PROP          21
#define QN_NID             22
#define QN_NID_DEL         23
#define QN_NID_INS         24
#define QN_NID_UNQ         25
#define VX_HSH_NID         26
#define VX_HSH_NID_INS     27
#define VX_HSH_NID_DEL     28
#define PRE_CONT           29
#define ATTR_CONT          30
#define PID_MAP            31
#define ATTR_OWN_PRIVATE   32
#define ATTR_OWN_SHARED    33
#define REGION_PRE         34
#define REGION_START       35
#define REGION_END         36
#define OPEN_NAME          37
#define OPEN_DOCID         38
#define OPEN_CONT          39
#define CONT_COLL          40
#define CONT_NAME          41
#define CONT_RUNTIME       42
#define CONT_LOCKED        43
#define XRPC_PARTICIPANTS  44
#define _MAP_PID           45
#define _RID_SIZE          46
#define _RID_LEVEL         47
#define _RID_PROP          48
#define _RID_KIND          49
#define _RID_NID           50
#define _NID_RID           51
#define _FRAG_ROOT         52
#define _QN_HISTOGRAM      53
#define _QN_PREFIX_URI_LOC 54
#define _QN_URI_LOC        55
#define _QN_PREFIX         56
#define _QN_URI            57
#define _QN_LOC            58
#define _PROP_TEXT         59
#define _PROP_COM          60
#define _PROP_INS          61
#define _PROP_TGT          62
#define _PROP_VAL          63
#define _ATTR_OWN          64
#define _ATTR_QN           65
#define _ATTR_PROP         66
#define WS_SIZE  67
#define QNAME     2
#define BOOL      3
#define INT       4
#define DEC       5
#define DBL       6
#define STR       7
#define U_A       8
#define ATOMIC   31
#define NODE     32
#define ATTR     33
#define ELEM     34
#define ELEMENT    0
#define TEXT       1
#define COMMENT    2
#define PI         3
#define DOCUMENT   4
#define COLLECTION 5
#define REFERENCE  6
#define NS_ACCEL_SEP '|'

#define XS_BOOLEAN       0
#define XS_INTEGER       1
#define XS_DECIMAL       2
#define XS_FLOAT         3
#define XS_DOUBLE        4
#define XS_ANYURI        5
#define XS_STRING        6
#define XS_UNTYPEDATOMIC 7
#define XS_ANYATOMICTYPE 8
#define XS_ANYSIMPLETYPE 9
#define XS_ATTRIBUTE     10
#define XS_COMMENT       11
#define XS_DOCUMENT      12
#define XS_ELEMENT       13
#define XS_PI            14
#define XS_TEXT          15
#define XS_NODE          16
#define XS_ANYNODE       17
#define XS_ANYTYPE       18
#define XS_ITEM          19
#define XS_ILLEGAL       20 

#define XQUERY_TYPES 20
#define XQUERY_ABSTRACT 8
