#!/bin/bash

# Invoke Pathfinder-internal test routines.
#
# There's no means to feed a pair of types for testing purposes
# into the compiler.  Hence, we hardcode test cases into the
# compiler (only if --enable-assert) and invoke them with the
# -d command line option.

echo 42 | pf -d subtyping -s10
