#[[
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2020 MonetDB B.V.
#]]

function(monetdb_configure_defines)
  check_symbol_exists("opendir" "dirent.h" HAVE_DIRENT_H)
  find_path(HAVE_DISPATCH_DISPATCH_H "dispatch/dispatch.h")
  find_path(HAVE_DLFCN_H "dlfcn.h")
  find_path(HAVE_FCNTL_H "fcntl.h")
  find_path(HAVE_ICONV_H "iconv.h")
  find_path(HAVE_IO_H "io.h")
  find_path(HAVE_KVM_H "kvm.h")
  find_path(HAVE_LANGINFO_H "langinfo.h")
  find_path(HAVE_LIBGEN_H "libgen.h")
  find_path(HAVE_LIBINTL_H "libintl.h")
  find_path(HAVE_MACH_MACH_INIT_H "mach/mach_init.h")
  find_path(HAVE_MACH_TASK_H "mach/task.h")
  find_path(HAVE_MACH_O_DYLD_H "mach-o/dyld.h")
  check_symbol_exists("gethostbyname" "netdb.h" HAVE_NETDB_H)
  find_path(HAVE_NETINET_IN_H "netinet/in.h")
  find_path(HAVE_POLL_H "poll.h")
  find_path(HAVE_PROCFS_H "procfs.h")
  find_path(HAVE_PWD_H "pwd.h")
  find_path(HAVE_STRINGS_H "strings.h")
  find_path(HAVE_STROPTS_H "stropts.h")
  find_path(HAVE_SYS_FILE_H "sys/file.h")
  find_path(HAVE_SYS_IOCTL_H "sys/ioctl.h")
  find_path(HAVE_SYS_IOCTL_H "sys/sysctl.h")
  find_path(HAVE_SYS_MMAN_H "sys/mman.h")
  find_path(HAVE_SYS_PARAM_H "sys/param.h")
  find_path(HAVE_SYS_RESOURCE_H "sys/resource.h")
  check_symbol_exists("setsockopt" "sys/socket.h" HAVE_SYS_SOCKET_H)
  check_symbol_exists("gettimeofday" "sys/time.h" HAVE_SYS_TIME_H)
  find_path(HAVE_SYS_TIMES_H "sys/times.h")
  find_path(HAVE_SYS_UIO_H "sys/uio.h")
  find_path(HAVE_SYS_UN_H "sys/un.h")
  find_path(HAVE_SYS_UTIME_H "sys/utime.h")
  find_path(HAVE_SYS_WAIT_H "sys/wait.h")
  find_path(HAVE_TERMIOS_H "sys/termios.h")
  find_path(HAVE_UNISTD_H "unistd.h")
  find_path(HAVE_UUID_UUID_H "uuid/uuid.h")
  find_path(HAVE_WINSOCK_H "winsock2.h")

  find_path(HAVE_SYS_TYPES_H "sys/types.h")
  find_path(HAVE_SEMAPHORE_H "semaphore.h")
  find_path(HAVE_GETOPT_H "getopt.h")
  if(HAVE_GETOPT_H)
    set(HAVE_GETOPT 1 PARENT_SCOPE)
  endif()

  check_include_file("stdatomic.h" HAVE_STDATOMIC_H)

  # Linux specific, in the future, it might be ported to other platforms
  check_symbol_exists("S_ISREG" "sys/stat.h" HAVE_SYS_STAT_H)
  check_symbol_exists("getaddrinfo" "netdb.h" UNIX_GETADDRINFO)
  check_symbol_exists("getaddrinfo" "ws2tcpip.h" WIN_GETADDRINFO)
  if(UNIX_GETADDRINF)
	  set(HAVE_GETADDRINFO 1 PARENT_SCOPE)
  endif()
  if(WIN_GETADDRINF)
	  set(HAVE_GETADDRINFO 1 PARENT_SCOPE)
  endif()

  #check_symbol_exists("WSADATA" "winsock2.h" HAVE_WINSOCK_H)
  check_symbol_exists("fdatasync" "unistd.h" HAVE_FDATASYNC)

  check_symbol_exists("accept4" "sys/types.h;sys/socket.h" HAVE_ACCEPT4) # Some libc versions on Linux distributions don't have it
  check_symbol_exists("asctime_r" "time.h" HAVE_ASCTIME_R)
  check_symbol_exists("clock_gettime" "time.h" HAVE_CLOCK_GETTIME)
  check_symbol_exists("ctime_r" "time.h" HAVE_CTIME_R)
  check_symbol_exists("dispatch_semaphore_create" "dispatch/dispatch.h" HAVE_DISPATCH_SEMAPHORE_CREATE)
  check_symbol_exists("fallocate" "fcntl.h" HAVE_FALLOCATE) # Linux specific, in the future, it might be ported to other platforms
  check_function_exists("fcntl" HAVE_FCNTL)
  check_symbol_exists("fork" "unistd.h" HAVE_FORK)
  check_symbol_exists("fsync" "unistd.h" HAVE_FSYNC)
  check_symbol_exists("ftime" "sys/timeb.h" HAVE_FTIME)
  check_function_exists("getexecname" HAVE_GETEXECNAME)
  check_function_exists("getlogin" HAVE_GETLOGIN)
  check_symbol_exists("getopt_long" "getopt.h" HAVE_GETOPT_LONG)
  check_function_exists("getrlimit" HAVE_GETRLIMIT)
  check_function_exists("gettimeofday" HAVE_GETTIMEOFDAY)
  check_function_exists("getuid" HAVE_GETUID)
  check_symbol_exists("gmtime_r" "time.h" HAVE_GMTIME_R)
  check_symbol_exists("localtime_r" "time.h" HAVE_LOCALTIME_R)
  check_symbol_exists("strerror_r" "string.h" HAVE_STRERROR_R)
  check_function_exists("lockf" HAVE_LOCKF)
  check_symbol_exists("madvise" "sys/mman.h" HAVE_MADVISE)
  check_symbol_exists("mremap" "sys/mman.h" HAVE_MREMAP)
  check_function_exists("nanosleep" HAVE_NANOSLEEP)
  check_function_exists("nl_langinfo" HAVE_NL_LANGINFO)
  check_function_exists("_NSGetExecutablePath" HAVE__NSGETEXECUTABLEPATH)
  check_symbol_exists("pipe2" "fcntl.h;unistd.h" HAVE_PIPE2) # Some libc versions on Linux distributions don't have it
  check_function_exists("poll" HAVE_POLL) 
  check_symbol_exists("popen" "stdio.h" HAVE_POPEN)
  check_symbol_exists("posix_fadvise" "fcntl.h" HAVE_POSIX_FADVISE) 
  check_symbol_exists("posix_fallocate" "fcntl.h" HAVE_POSIX_FALLOCATE) # Some POSIX systems don't have it (e.g. Macos)
  check_symbol_exists("posix_madvise" "sys/mman.h" HAVE_POSIX_MADVISE)
  check_function_exists("putenv" HAVE_PUTENV) 
  check_function_exists("setsid" HAVE_SETSID) 
  check_function_exists("shutdown" HAVE_SHUTDOWN) 
  check_function_exists("sigaction" HAVE_SIGACTION) 
  check_function_exists("stpcpy" HAVE_STPCPY) 
  check_function_exists("strcasestr" HAVE_STRCASESTR) 
  check_symbol_exists("strncasecmp" "strings.h" HAVE_STRNCASECMP)
  check_function_exists("strptime" HAVE_STRPTIME) 
  check_function_exists("strsignal" HAVE_STRSIGNAL) 
  check_symbol_exists("sysconf" "unistd.h" HAVE_SYSCONF)
  check_function_exists("task_info" HAVE_TASK_INFO) 
  check_function_exists("times" HAVE_TIMES) 
  check_function_exists("uname" HAVE_UNAME) 
  # Some libc versions on Linux distributions don't have it
  check_symbol_exists("semtimedop" "sys/types.h;sys/ipc.h;sys/sem.h" HAVE_SEMTIMEDOP)
  if(HAVE_PTHREAD_H)
    check_function_exists("pthread_kill" HAVE_PTHREAD_KILL)
    check_function_exists("pthread_sigmask" HAVE_PTHREAD_SIGMASK)
  endif()
endfunction()

macro(monetdb_macro_variables)
  # Set variables to define C macro's
  # These are related to the detected packages
  # These names are legacy. When the code is changed to use the cmake
  # variables, they can be removed.
  set(HAVE_ICONV ${Iconv_FOUND})
  set(HAVE_PTHREAD_H ${CMAKE_USE_PTHREADS_INIT})
  set(HAVE_LIBPCRE ${PCRE_FOUND})
  set(HAVE_OPENSSL ${OPENSSL_FOUND})
  set(HAVE_COMMONCRYPTO ${COMMONCRYPTO_FOUND})
  set(HAVE_LIBBZ2 ${BZIP2_FOUND})
  set(HAVE_CURL ${CURL_FOUND})
  set(HAVE_LIBLZMA ${LIBLZMA_FOUND})
  set(HAVE_LIBXML ${LibXml2_FOUND})
  set(HAVE_LIBZ ${ZLIB_FOUND})
  set(HAVE_LIBLZ4 ${LZ4_FOUND})
  set(HAVE_PROJ ${PROJ_FOUND})
  set(HAVE_SNAPPY ${SNAPPY_FOUND})
  set(HAVE_UUID ${HAVE_UUID_GENERATE})
  set(HAVE_VALGRIND ${VALGRIND_FOUND})
  set(HAVE_NETCDF ${NETCDF_FOUND})
  set(HAVE_READLINE ${READLINE_FOUND})

  set(SOCKET_LIBRARIES "")
  if (WIN32)
    set(SOCKET_LIBRARIES "ws2_32")
  endif()

  set(DIR_SEP  "/")
  set(PATH_SEP ":")
  set(DIR_SEP_STR  "/")
  set(SO_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
  set(SO_EXT "${CMAKE_SHARED_LIBRARY_SUFFIX}")

  set(BINDIR "${CMAKE_INSTALL_FULL_BINDIR}")
  set(LIBDIR "${CMAKE_INSTALL_FULL_LIBDIR}")
  set(DATADIR "${CMAKE_INSTALL_FULL_DATADIR}")
  set(DATA_DIR "${CMAKE_INSTALL_FULL_DATADIR}")
  set(LOCALSTATEDIR "${CMAKE_INSTALL_FULL_LOCALSTATEDIR}")
  if(WIN32)
    # Fix cmake conversions
    string(REPLACE "/" "\\\\" QXLOCALSTATEDIR "${LOCALSTATEDIR}")
  endif()
  set(MONETDB_PREFIX "${CMAKE_INSTALL_PREFIX}")
  if(WIN32)
    # Fix cmake conversions
    string(REPLACE "/" "\\\\" MONETDB_PREFIX "${CMAKE_INSTALL_PREFIX}")
  endif()

  set(DATAROOTDIR "${CMAKE_INSTALL_FULL_DATAROOTDIR}")
  set(BIN_DIR "${CMAKE_INSTALL_FULL_BINDIR}")
  set(INCLUDEDIR "${CMAKE_INSTALL_FULL_INCLUDEDIR}")
  set(INFODIR "${CMAKE_INSTALL_FULL_INFODIR}")
  set(LIB_DIR "${CMAKE_INSTALL_FULL_LIBDIR}")
  set(LIBEXECDIR "${CMAKE_INSTALL_FULL_LIBEXECDIR}")
  set(LOCALSTATE_DIR "${CMAKE_INSTALL_FULL_LOCALSTATEDIR}")
  # set(MANDIR "${CMAKE_INSTALL_FULL_MANDIR}")
  set(SYSCONFDIR "${CMAKE_INSTALL_FULL_SYSCONFDIR}")
  set(LOGDIR "${CMAKE_INSTALL_FULL_LOCALSTATEDIR}/log/monetdb"
    CACHE PATH
    "Where to put log files (default LOCALSTATEDIR/log/monetdb)")
  set(PKGCONFIGDIR "${LIBDIR}/pkgconfig")
  set(RUNDIR
    "${CMAKE_INSTALL_FULL_LOCALSTATEDIR}/run/monetdb"
    CACHE PATH
    "Where to put pid files (default LOCALSTATEDIR/run/monetdb)")
endmacro()

macro(monetdb_configure_crypto)
  cmake_push_check_state()
  if(COMMONCRYPTO_FOUND)
    #set(CMAKE_REQUIRED_INCLUDES "${COMMONCRYPTO_INCUDE_DIR}")
    set(CMAKE_REQUIRED_LIBRARIES "${COMMONCRYPTO_LIBRARIES}")

    check_symbol_exists("CC_MD5_Update" "CommonCrypto/CommonDigest.h" HAVE_MD5_UPDATE)
    check_symbol_exists("CC_SHA1_Update" "CommonCrypto/CommonDigest.h" HAVE_SHA1_UPDATE)
    check_symbol_exists("CC_SHA224_Update" "CommonCrypto/CommonDigest.h" HAVE_SHA224_UPDATE)
    check_symbol_exists("CC_SHA256_Update" "CommonCrypto/CommonDigest.h" HAVE_SHA256_UPDATE)
    check_symbol_exists("CC_SHA384_Update" "CommonCrypto/CommonDigest.h" HAVE_SHA384_UPDATE)
    check_symbol_exists("CC_SHA512_Update" "CommonCrypto/CommonDigest.h" HAVE_SHA512_UPDATE)

    add_library(OpenSSL::Crypto UNKNOWN IMPORTED)
    set_target_properties(OpenSSL::Crypto PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${COMMONCRYPTO_INCLUDE_DIR}")
    set_target_properties(OpenSSL::Crypto PROPERTIES
      IMPORTED_LINK_INTERFACE_LANGUAGES "C"
      IMPORTED_LOCATION "${COMMONCRYPTO_LIBRARIES}")
  endif()
  if(OPENSSL_FOUND)
    #set(CMAKE_REQUIRED_INCLUDES "${OPENSSL_INCUDE_DIR}")
    #set(CMAKE_REQUIRED_LIBRARIES "${OPENSSL_LIBRARIES}")

    set(HAVE_OPENSSL ON CACHE INTERNAL "OpenSSL is available")
    set(CRYPTO_INCLUDE_DIR "${OPENSSL_INCLUDE_DIR}" CACHE INTERNAL "crypto include directory")
    set(CRYPTO_LIBRARIES "${OPENSSL_CRYPTO_LIBRARY}" CACHE INTERNAL "crypto libraries to link")
    set(CMAKE_REQUIRED_INCLUDES "${CMAKE_REQUIRED_INCLUDES};${CRYPTO_INCLUDE_DIR}")
    set(CMAKE_REQUIRED_LIBRARIES "${CMAKE_REQUIRED_LIBRARIES};${CRYPTO_LIBRARIES}")

    check_symbol_exists("MD5_Update" "openssl/md5.h" HAVE_MD5_UPDATE)
    check_symbol_exists("RIPEMD160_Update" "openssl/ripemd.h" HAVE_RIPEMD160_UPDATE)
    check_symbol_exists("SHA1_Update" "openssl/sha.h" HAVE_SHA1_UPDATE)
    check_symbol_exists("SHA224_Update" "openssl/sha.h" HAVE_SHA224_UPDATE)
    check_symbol_exists("SHA256_Update" "openssl/sha.h" HAVE_SHA256_UPDATE)
    check_symbol_exists("SHA384_Update" "openssl/sha.h" HAVE_SHA384_UPDATE)
    check_symbol_exists("SHA512_Update" "openssl/sha.h" HAVE_SHA512_UPDATE)
  endif()
  cmake_pop_check_state()
endmacro()
