# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

MTSAFE
INCLUDES = $(MONETDB_CFLAGS) -I../mapilib $(READLINE_INCS) $(OPENSSL_INCS)

MAPI_LIBS = $(SOCKET_LIBS) $(OPENSSL_LIBS)

lib_mcutil = {
	NOINST
	SOURCES = dump.c prompt.c
}

bin_MapiClient = {
	SOURCES = MapiClient.mx ReadlineTools.mx
	LIBS = libmcutil ../mapilib/libMapi $(MAPI_LIBS) $(READLINE_LIBS) \
		$(MONETDB_LIBS) -lmutils -lstream \
		$(ICONV_LIBS)
}

bin_msqldump = {
	SOURCES = msqldump.c
	LIBS = libmcutil ../mapilib/libMapi $(MAPI_LIBS) \
		$(MONETDB_LIBS) -lmutils -lstream \
		$(ICONV_LIBS)
}

EXTRA_DIST = msqldump.h mprompt.h

#doc_MapiClient = {
#	DIR = pkgdatadir/docs/tools
#	SOURCES = MapiClient.mx
#}
