# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

scripts_sh = {
	COND = HAVE_DEVELOPER
	EXT = ""
	DIR = bindir
	SOURCES = Maddlog
}

headers_bmp = {
	COND = NATIVE_WIN32
	HEADERS = bmp
	DIR = prefix
	SOURCES = banner.bmp
}

headers_rtf = {
	COND = NATIVE_WIN32
	HEADERS = rtf
	DIR = prefix
	SOURCES = license.rtf
}

headers_ico = {
	COND = NATIVE_WIN32
	HEADERS = ico
	DIR = prefix
	SOURCES = monetdb.ico
}

headers_html = {
	COND = NATIVE_WIN32
	HEADERS = html
	DIR = prefix
	SOURCES = website.html
}

EXTRA_DIST = rules.mk
