# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

INCLUDES = -I../../atoms -I../../kernel \
        -I../../../mal $(CLIENTS_INCS) $(MONETDB_INCS) $(RAPTOR_INCS) \
        $(Z_CFLAGS) $(BZ_CFLAGS) $(PCRE_CFLAGS) \
        $(LIBXML2_CFLAGS) $(READLINE_INCS)

MTSAFE

lib__rdf = {
	DIR = libdir/MonetDB5
	SOURCES = rdf.mx rdf_shredder.mx
	LIBS = ../../../mal/libmonetdb5 $(MONETDB_LIBS) -lbat -lstream \
           ../../atoms/lib_url \
                $(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
                $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
                $(RAPTOR_LIBS)
}

headers_rdf = {
	DIR = includedir/MonetDB5/rdf
	SOURCES = rdf.mx rdf_shredder.mx
	HEADERS = h
}

headers_mal = {
	HEADERS = mal
	DIR = libdir/MonetDB5
	SOURCES = rdf.mx
}

headers_autoload = {
	HEADERS = mal
	DIR = libdir/MonetDB5/autoload
	SOURCES = 10_rdf.mal
}

#EXTRA_DIST_DIR = Tests
EXTRA_DIST = 10_rdf.mal
