# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../monet \
	../../../common/options \
	../../../common/stream \
	../../../clients/mapilib \
	../../../gdk \
	$(zlib_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS) \
	$(pcre_CFLAGS)
MTSAFE

lib__streams = {
	DIR = libdir/monetdb4
	SOURCES = streams.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) $(curl_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) 
}

lib__str = {
	DIR = libdir/monetdb4
	SOURCES = str.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(LTLIBICONV)
}

lib__xtables = {
	DIR = libdir/monetdb4
	SOURCES = xtables.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet lib_algebra \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

lib__logger = {
	DIR = libdir/monetdb4
	SOURCES = logger.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet lib_bat \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}

LIBS = {
	DIR = libdir/monetdb4
	SEP = _
	SOURCES = \
		algebra.mx arith.mx bat.mx builtin.mx sys.mx trans.mx \
		mkey.mx profiler.mx constant.mx \
		aggr.mx alarm.mx ascii_io.mx bat_arith.mx blob.mx \
		decimal.mx enum.mx lock.mx mmath.mx monettime.mx \
		stats.mx unix.mx url.mx pqueue.mx 
		#radix.mx tcpip.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(MATH_LIBS)
}

lib__aggrX3 = {
	DIR = libdir/monetdb4
	SOURCES = aggrX3.mx \
		aggrX3_be_sum.mx aggrX3_be_prod.mx aggrX3_be_avg.mx aggrX3_be_minmax.mx aggrX3_be_count.mx \
		aggrX3_bge_sum.mx aggrX3_bge_prod.mx aggrX3_bge_avg.mx aggrX3_bge_minmax.mx aggrX3_bge_count.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet
}

EXTRA_DIST = aggrX3_ri.mx

lib__counters = {
	DIR = libdir/monetdb4
	SOURCES = counters.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(HWCOUNTERS_LIBS)
}

lib__pcl = {
	DIR = libdir/monetdb4
	SOURCES = pcl.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(PCL_LIBS)
}

lib__pcre = {
	DIR = libdir/monetdb4
	SOURCES = pcre.mx
	#SCRIPTS = mil ""
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(pcre_LIBS)
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	SOURCES = streams.mx str.mx xtables.mx constant.mx \
         	algebra.mx arith.mx bat.mx builtin.mx sys.mx trans.mx \
                mkey.mx profiler.mx \
                aggr.mx aggrX3.mx alarm.mx ascii_io.mx bat_arith.mx \
		blob.mx decimal.mx enum.mx lock.mx mmath.mx \
		monettime.mx stats.mx \
		unix.mx url.mx counters.mx pcl.mx pcre.mx pqueue.mx \
		logger.mx
		# radix.mx tcpip.mx
}

EXTRA_DIST_DIR = Tests
