# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the PfTijah Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://dbappl.cs.utwente.nl/Legal/PfTijah-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the PfTijah system.
#
# The Initial Developer of the Original Code is the "University of Twente".
# Portions created by the "University of Twente" are
# Copyright (C) 2006-2011 "University of Twente".
#
# Portions created by the "CWI" are
# Copyright (C) 2008-2011 "CWI".
#
# All Rights Reserved.
# 
# Author(s): Henning Rode 
#            Jan Flokstra
	
PARSERNAME = tjc
YFLAGS = -d -p $(PARSERNAME)
LFLAGS = -P$(PARSERNAME)

CC = $(C99)
INCLUDES = \
	../../../../monetdb4/monet \
	../../../../monetdb4/modules/plain \
	../../../../monetdb4/modules/contrib \
	../../../../monetdb4/mapi \
	../../../../monetdb4/modules/calibrator \
	../../../../common/options \
	../../../../common/stream \
	../../../../gdk

#  Some versions of flex & bison seem to generate code
#  that does not compile with `gcc -Wundef`;
#  we use GCC_BISON_CFLAGS to disable the respective warning as
#  locally as possible via "-Wno-undef"
#  (see also monetdb4/monet/Makefile.ag, sql/src/server/Makefile.ag,
#  buildtools/conf/monet.m4).
#
#  Some versions of flex & bison seem to generate code that icc does not like;
#  we use ICC_BISON_CFLAGS to disable the respective warning as
#  locally as possible via "-wd177"
#  (#177: label "." was declared but never referenced)
#  (see also MonetDB/conf/monet.m4).
CFLAGS = $(ICC_BISON_CFLAGS) $(GCC_BISON_CFLAGS)

lib_tjc = {
	NOINST
	SOURCES = \
		tjc_main.c \
		tjc_scan.l \
		tjc_parse.y \
		tjc_conf.h \
		tjc_abssyn.h \
		tjc_abssyn.c \
		tjc_main.c \
		tjc_milprint.h \
		tjc_milprint.c \
		tjc_normalize.h \
		tjc_normalize.c \
		tjc_optimize.h \
		tjc_optimize.c \
		tjc_normalize_query.h \
		tjc_normalize_query.c \
		tjc_phys_optimize.h \
		tjc_phys_optimize.c
}
