# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

SWIGFLAGS = $(MONETDB_INCS) $(CLIENTS_INCS)
INCLUDES = ../../../include ../../../common ../../../storage ../../../server \
	 $(MONETDB4_INCS) $(CLIENTS_INCS) $(MONETDB_INCS) $(PYTHON_INCS)

#  Both GNU's gcc and Intel's icc do not like to compile swig-generated code
#  with our strict X_CFLAGS.
#  Instead of diabling the strict X_CFLAGS completely,
#  we use GCC_SWIG_CFLAGS and ICC_SWIG_CFLAGS, respectively,
#  to disable only the problematic warnings/errors as locally as possbile.
#  See buildtools/conf/MonetDB.m4 for details.
#CFLAGS = $(GCC_SWIG_CFLAGS) $(ICC_SWIG_CFLAGS)
#
#  However, there are situations where user-chosen CFLAGS and/or X_CFLAGS
#  are beyond our control. Hence, for the sake of a smooth compilation, we
#  have to take the freedom to overrule the user's deliberate choice for
#  X_CFLAGS by locally disabling them indifferently.
X_CFLAGS =

GDK_LIBS = $(PTHREAD_LIBS) $(MALLOC_LIBS)
EXTRA_LIBS = $(SOCKET_LIBS) $(DL_LIBS) $(GDK_LIBS) 

STATIC_MODS = $(MONETDB4_MODS) \
	-l_builtin -l_arith -l_bat -l_algebra -l_sys -l_trans -l_str -l_constant

lib_monetdb = {
	PREFIX =
	NAME = _monetdb
	SOURCES = monetdb.py.i
	LIBS = ../../monet4/libinitmodules STATIC_MODS @SHARED_LIBS@ ../../monet4/lib_sql_server $(EXTRA_LIBS) \
		../../monet4/libembeddedsql \
		$(MONETDB_LIBS) -lbat -lmutils -lstream $(MONETDB4_LIBS) -lmonet $(CLIENTS_LIBS) -lMapi $(PYTHON_LIBS)
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}

headers_py = {
	HEADERS = py
	SOURCES = monetdb.py.i
	TARGETS = monetdb.py
	DIR = $(prefix)/$(PYTHON_LIBDIR)
}
