
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# is now maintained by the Database Systems Group at the Technische
# Universitaet Muenchen, Germany.  Portions created by the University of
# Konstanz and the Technische Universitaet Muenchen are Copyright (C)
# 2000-2005 University of Konstanz and (C) 2005-2006 Technische
# Universitaet Muenchen, respectively.  All Rights Reserved.
#

INCLUDES = ../../runtime $(MONETDB_INCS) $(MONETDB4_INCS) $(LIBXML2_CFLAGS) ../../compiler/include
PF_LIBS = $(LIBXML2_LDADD) $(LIBXML2_LIBS) $(DL_LIBS)

LFLAGS = -olex.yy.c
YFLAGS = -d -p nexi

#  Some versions of flex & bison seem to generate code that icc does not like;
#  we "mis-use" the NO_INLINE_CFLAGS to disable the respective warning as
#  locally as possible via "-wd177"
#  (#177: label "." was declared but never referenced)
#  (see also MonetDB/conf/monet.m4).
CFLAGS = $(NO_INLINE_CFLAGS)

lib__pftijah = {
	DIR = libdir/MonetDB
	SOURCES = \
	        termdb.mx \
		pftijah.mx \
		pftijah_stem.mx \
		snb_header.h \
		snb_utilities.c \
		snb_api.h \
		snb_api.c \
		stem_UTF_8_dutch.h \
		stem_UTF_8_dutch.c \
		stem_UTF_8_english.h \
		stem_UTF_8_english.c \
		stem_UTF_8_porter.h \
		stem_UTF_8_porter.c \
		pftijah_tokenize.l \
		serialize_pftijah.mx \
		serialize_pftijah_options.mx \
		nexi.c \
		nexi.y \
		nexi.l \
		nexi_preprocessor.c \
		nexi_rewriter.c \
		nexi_generate_mil.c \
		nexi_generate_plan.c

	LIBS = \
		$(PF_LIBS) \
		$(MONETDB_LIBS) -lbat -lstream $(MONETDB4_LIBS) -lmonet \
		$(MONETDB4_MODS) -l_streams -l_builtin -l_ascii_io -l_algebra -l_constant
}

scripts_mil = {
	DIR = libdir/MonetDB
	SOURCES = pftijah.mx
}

