
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

SUBDIRS = tjc

INCLUDES = \
	../../runtime \
	../../compiler/include \
	../../../monetdb4/monet \
	../../../monetdb4/modules/plain \
	../../../monetdb4/modules/contrib \
	../../../monetdb4/modules \
	../../../monetdb4/modules/calibrator \
	../../../common/options \
	../../../common/stream \
	../../../gdk \
	$(libxml2_CFLAGS)
PF_LIBS = $(libxml2_LIBS) $(DL_LIBS)

YFLAGS = -d -p nexi

#  Some versions of flex & bison seem to generate code
#  that does not compile with `gcc -Wundef`;
#  we use GCC_BISON_CFLAGS to disable the respective warning as
#  locally as possible via "-Wno-undef"
#  (see also monetdb4/monet/Makefile.ag, sql/src/server/Makefile.ag,
#  buildtools/conf/monet.m4).
#
#  Some versions of flex & bison seem to generate code that icc does not like;
#  we use ICC_BISON_CFLAGS to disable the respective warning as
#  locally as possible via "-wd177"
#  (#177: label "." was declared but never referenced)
#  (see also MonetDB/conf/monet.m4).
CFLAGS = $(ICC_BISON_CFLAGS) $(GCC_BISON_CFLAGS)

# ignore warning "too many struct/union initializers"
# with Sun Studio 12 compiler
pftijah_stem_CFLAGS = $(SUN_NOERR_CFLAGS)

lib__pftijah = {
	DIR = libdir/monetdb4
	SOURCES = \
		termdb.mx \
		pftijah.mx \
		pftijah_stem.mx \
		snb_header.h \
		snb_utilities.c \
		snb_api.h \
		snb_api.c \
		stem_UTF_8_dutch.h \
		stem_UTF_8_dutch.c \
		stem_UTF_8_english.h \
		stem_UTF_8_english.c \
		stem_UTF_8_german.h \
		stem_UTF_8_german.c \
		stem_UTF_8_french.h \
		stem_UTF_8_french.c \
		stem_UTF_8_porter.h \
		stem_UTF_8_porter.c \
		porter_eng.h \
		porter_eng.c \
		porter_dutch.h \
		porter_dutch.c \
		pftijah_tokenize.l \
		pftijah_util.mx \
		serialize_pftijah.mx \
		serialize_pftijah_options.mx \
		nexi.h \
		nexi.c \
		nexi.y \
		nexi.l \
		nexi_preprocessor.c \
		nexi_rewriter.h \
		nexi_rewriter.c \
		nexi_generate_mil.h \
		nexi_generate_mil.c \
		nexi_generate_plan.h \
		nexi_generate_plan.c

	LIBS = \
		./tjc/libtjc  \
		../../runtime/libserialize \
		../../runtime/lib_pf_support $(PF_LIBS) \
		../../../gdk/libbat4 \
		../../../common/stream/libstream4 \
		../../../monetdb4/monet/libmonet \
		../../../monetdb4/modules/plain/lib_streams \
		../../../monetdb4/modules/plain/lib_builtin \
		../../../monetdb4/modules/plain/lib_ascii_io \
		../../../monetdb4/modules/plain/lib_algebra \
		../../../monetdb4/modules/plain/lib_constant \
		../../../monetdb4/modules/plain/lib_str
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	SOURCES = pftijah.mx
}

EXTRA_DIST_DIR = Tests
