# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2008-2015 MonetDB B.V.

## Process this file with automake to produce Makefile.in

MTSAFE

INCLUDES = $(openssl_CFLAGS)

lib_mutils  =  {
	NOINST
	SOURCES = mutils.h mutils.c
}

lib_mcrypt = {
	NOINST
	SOURCES = mcrypt.h mcrypt.c
}

lib_muuid = {
	NOINST
	SOURCES = muuid.h muuid.c
}

lib_msabaoth = {
	NOINST
	SOURCES = msabaoth.h msabaoth.c
}

EXTRA_DIST = s_nextafterf.c math_private.h
