
INCLUDES =  top_builddir/src/gdk top_builddir/src/monet \
        top_builddir/include/atoms \
        top_builddir/src/mal $(Z_CFLAGS) $(BZ_CFLAGS)

MTSAFE

# install these libs in the pkglib
LIBDIR = pkglib

LIBS = {
	SEP = _
	SOURCES = squeezer.mx mal.mx startup.mx box.mx multiplex.mx  \
		atoms.mx profiler.mx batcalc.mx const.mx bbp.mx io.mx \
		enum.mx

	HEADERS = h 
	SCRIPTS = mal mil ""
	LIBS = ../../gdk/libbat ../../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
scripts_mal = {
        DIR = pkgdatadir
        SOURCES = startup.mal
}


EXTRA_DIST_DIR = Tests
