# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2006 CWI.
# All Rights Reserved.

SUBDIRS = conf src 
EXTRA_DIST = rules.mk RunMtest.in RunMtest.bat.in \
		RunMapprove.in RunMapprove.bat.in \
		MonetDB-SQL.spec.in MonetDB-SQL.spec \
		rpm.mk.in RunMserver.bat.in
EXTRA_DIST_DIR = NT

EXTRA_HEADERS = sql_config.h

headers_pc = {
	HEADERS = pc
	SOURCES	= MonetDB-SQL.pc.in
	DIR = libdir/pkgconfig
}

scripts_txt = {
	SOURCES = HowToStart-SQL-Win32.txt dump-restore.txt 
	DIR = datadir/doc/MonetDB-SQL-${VERSION}
}

scripts_html = {
	SOURCES = dump-restore.html
	DIR = datadir/doc/MonetDB-SQL-${VERSION}
}

scripts_docs = {
	EXT = ""
	SOURCES = HowToStart-SQL 
	DIR = datadir/doc/MonetDB-SQL-${VERSION}
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
