# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2010 MonetDB B.V.
# All Rights Reserved.

SUBDIRS = conf src 
EXTRA_DIST = RunMtest.in RunMtest.bat.in \
		RunMapprove.in RunMapprove.bat.in \
		RunMserver.in RunMserver.bat.in \
		MonetDB-SQL.spec.in MonetDB-SQL.spec \
		rpm.mk.in RunMserver.bat.in
EXTRA_DIST_DIR = NT debian

headers_pc = {
	HEADERS = pc
	SOURCES	= MonetDB-SQL.pc.in
	DIR = libdir/pkgconfig
}

headers_txt = {
	HEADERS = txt
	SOURCES = dump-restore.txt 
	DIR = datadir/doc/MonetDB-SQL-$(VERSION)
}

headers_html = {
	HEADERS = html
	SOURCES = dump-restore.html
	DIR = datadir/doc/MonetDB-SQL-$(VERSION)
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
