
SUBDIRS = conf src 
EXTRA_DIST = rules.mk RunMtest.in RunMtest.bat.in \
		MonetDB-SQL.spec.in MonetDB-SQL.spec
EXTRA_DIST_DIR = NT

EXTRA_HEADERS = sql_config.h

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
