# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

INCLUDES = $(MONETDB_INCS) -I../../monet -I../plain \
	$(Z_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS)

MTSAFE

LIBS = {
	DIR = pkglibdir
	SEP = _
	SOURCES = \
		bitset.mx bitvector.mx iterator.mx malalgebra.mx \
		mel.mx oo7.mx uchr.mx qt.mx salgebra.mx vector.mx \
		wisc.mx ddbench.mx \
		bat_mmath.mx bat_cast.mx array.mx color.mx \
		image.mx txtsim.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet ../plain/lib_algebra \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(MATH_LIBS)
}

LIB_mprof = {
	DIR = pkglibdir
	SEP = _
	COND = NOT_WIN32
	SOURCES = mprof.mx 
	HEADERS = h proto.h m
	LIBS = $(MONETDB_LIBS) -lstream -lbat \
		../../monet/libmonet ../plain/lib_algebra \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) $(MATH_LIBS)
}

headers_mprof = {
	HEADERS = mil
	DIR = pkglibdir
	COND = NOT_WIN32
	SOURCES = mprof.mx 
}

headers_mil = {
	HEADERS = mil
	DIR = pkglibdir
	SOURCES = \
		bitset.mx bitvector.mx iterator.mx malalgebra.mx \
		mel.mx oo7.mx uchr.mx qt.mx salgebra.mx vector.mx \
		wisc.mx ddbench.mx \
		bat_mmath.mx bat_cast.mx array.mx color.mx \
		image.mx txtsim.mx
}

EXTRA_DIST_DIR = Tests
