# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2007 CWI.
# All Rights Reserved.

INCLUDES = $(MONETDB_INCS) -I../monet \
	   -I../modules/plain -I../modules/plain/stream \
	   $(OPENSSL_INCS)

MTSAFE

# install these libs in the pkglib
lib__mapi = {
	DIR = pkglibdir
	SOURCES = mapi.mx
	HEADERS = h proto.h m
	#SCRIPTS = mil ""
	LIBS =  $(MONETDB_LIBS) -lmutils -lstream -lbat \
		../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) \
		$(DL_LIBS) $(OPENSSL_LIBS)

}

headers_mil = {
	HEADERS = mil
	DIR = pkglibdir
	SOURCES = mapi.mx
}

EXTRA_DIST_DIR = Tests
