# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-July 2008 CWI.
# Copyright August 2008-2011 MonetDB B.V.
# All Rights Reserved.

INCLUDES = ../../monet ../plain \
	../../../common/options \
	../../../common/stream \
	../../../gdk \
	$(zlib_CFLAGS) $(BZ_CFLAGS) $(HWCOUNTERS_INCS) $(PCL_CFLAGS) \
	$(netcdf_CFLAGS)
MTSAFE

LIB_mnetcdf = {
	DIR = libdir/monetdb4
	SEP = _
	COND = HAVE_NETCDF
	SOURCES = mnetcdf.mx 
	LIBS = ../../../common/stream/libstream4 \
		../../../gdk/libbat4 \
		../../monet/libmonet ../plain/lib_algebra \
		$(SOCKET_LIBS) $(zlib_LIBS) $(BZ_LIBS) \
		$(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS) \
		$(netcdf_LIBS) $(MATH_LIBS)
}

headers_mil = {
	HEADERS = mil
	DIR = libdir/monetdb4
	COND = HAVE_NETCDF
	SOURCES = mnetcdf.mx 
}

EXTRA_DIST_DIR = Tests
