
INCLUDES = top_builddir/src/gdk  top_builddir/src/monet 
# top_builddir/src/mal

YFLAGS = -v -d

bin_M2m = {
	SOURCES = M2m.mx  mil_parser.mx conformance.mx
	LIBS = ../gdk/libbat ../monet/libmonet \
		$(SOCKET_LIBS) $(MALLOC_LIBS) $(PTHREAD_LIBS) $(DL_LIBS)
}
