#!/bin/sh

prg=`basename $1 .c`

# will change to a dynamic lookup using monetdb-config
# should be generalized 
top_builddir=$HOME/monet5/build/MonetDB5/
prefix=$HOME/monet5/Linux
libdir=$prefix/lib/MonetDB5

# we need libtool to be installed somewhere!
LIBTOOL=$top_builddir/libtool

# next list is to be filled in using configure
CC=gcc
CCLD=$CC
DEFS=-DHAVE_CONFIG_H
CFLAGS="-Wall -Wextra -std=c99 -g -D_REENTRANT"
LDFLAGS= 
INSTALL="/usr/bin/install -c"

# the libs and includes are found via monetdb(5)-config
LIBS="`monetdb-config --libs` `monetdb5-config --libs`"
INCLUDES="`monetdb-config --cflags` `monetdb5-config --cflags`"

$LIBTOOL --tag=CC --mode=compile $CC $DEFS $INCLUDES $CFLAGS -c $prg.c 
$LIBTOOL --tag=CC --mode=link $CCLD $CFLAGS $LDFLAGS -o lib_$prg.la -rpath $libdir $LDFLAGS $prg.lo $LIBS
$LIBTOOL --mode=install $INSTALL lib_$prg.la $DESTDIR/$libdir
$LIBTOOL --mode=finish $DESTDIR/$libdir
