# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# is now maintained by the Database Systems Group at the Technische
# Universitaet Muenchen, Germany.  Portions created by the University of
# Konstanz and the Technische Universitaet Muenchen are Copyright (C)
# 2000-2005 University of Konstanz and (C) 2005-2007 Technische
# Universitaet Muenchen, respectively.  All Rights Reserved.
#

SUBDIRS = conf compiler MONET4?runtime MONET5?runtime5 modules src

EXTRA_DIST = extra.mk.in RunMtest.in RunMtest.bat.in \
		RunMapprove.in RunMapprove.bat.in \
		MonetDB-XQuery.spec.in MonetDB-XQuery.spec rpm.mk.in 
EXTRA_DIST_DIR = NT tests benchmarks 

EXTRA_HEADERS = pf_config.h

scripts_txt = {
	SOURCES = HowToStart-MinGW.txt
	DIR = datadir/doc/MonetDB-XQuery-$(VERSION)
}

scripts_docs = {
	EXT = ""
	SOURCES = HowToStart-PF 
	DIR = datadir/doc/MonetDB-XQuery-$(VERSION)
}

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
