# Copyright Notice:
# -----------------
# 
# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
# 
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
# 
# The Original Code is the ``Pathfinder'' system. The Initial
# Developer of the Original Code is the Database & Information
# Systems Group at the University of Konstanz, Germany. Portions
# created by U Konstanz are Copyright (C) 2000-2004 University
# of Konstanz. All Rights Reserved.
#
# Contributors:
#         Torsten Grust <torsten.grust@uni-konstanz.de>
#         Maurice van Keulen <M.van.Keulen@bigfoot.com>
#         Jens Teubner <jens.teubner@uni-konstanz.de>
#

SUBDIRS = conf burg compiler runtime

EXTRA_DIST = rules.mk extra.mk RunMtest.in RunMtest.bat.in \
		RunMapprove.in RunMapprove.bat.in \
		MonetDB-PF.spec.in MonetDB-PF.spec rpm.mk.in
EXTRA_DIST_DIR = NT

EXTRA_HEADERS = pf_config.h

TESTS = RunMtest
TESTS_ENVIRONMENT = $(SHELL)
