name: MacOS

on:
  push:
    branches: 
      - '*'
      - 'branches/*'
  workflow_dispatch:

  schedule:
    - cron:  '15 1 * * *'

jobs:
  test:
    strategy:
      fail-fast: false  # don't stop other jobs
      matrix:
        branch: [ master ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: brew packages
        run: brew install bison
      - name: make MonetDB on macos
        run: |
          mkdir build
          cd build 
          cmake ..  -DCMAKE_INSTALL_PREFIX=$HOME/${{ matrix.branch }} -DPY3INTEGRATION=OFF -DCMAKE_BUILD_TYPE=Release -DASSERT=OFF -DRINTEGRATION=OFF  \
            -DBISON_EXECUTABLE=/usr/local/opt/bison/bin/bison
          make install -j3
      - name: ctest 
        run: |
          cd build 
          cmake --build . --target test
          #-
          #uses: actions/upload-artifact@v3
          #name: Publish Linux binary wheels
          #with:
          #name: monetdbe-linux-wheel-${{ matrix.branch }}-${{ matrix.python-version }}
          #path: dist/*.whl
