# The contents of this file are subject to the MonetDB Public
# License Version 1.0 (the "License"); you may not use this file
# except in compliance with the License. You may obtain a copy of
# the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.0.html
#
# Software distributed under the License is distributed on an "AS
# IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
# implied. See the License for the specific language governing
# rights and limitations under the License.
#
# The Original Code is the Monet Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

YFLAGS = -d
# LDFLAGS = -all-static

bin_mel = {
	SOURCES = \
	FileInfo.mx      atomops.mx     mil.mx       list.mx      prelude.mx \
	ListIterator.mx  bat_arg.mx     epilogue.mx  var_arg.mx   proto.mx \
	builtin.mx     glue.mx      mel.mx       symbol.mx \
	command.mx     html.mx      module.mx    symtable.mx \
	any_arg.mx       debug.mx       iterator.mx  object.mx    type_arg.mx \
	atom.mx          depend.mx      language.mx  operator.mx  use.mx \
	atom_arg.mx      dependency.mx  link.mx      ops.mx

	LIBS = $(MEL_LIBS)
}
