# The contents of this file are subject to the MonetDB Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/MonetDBLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the MonetDB Database System.
#
# The Initial Developer of the Original Code is CWI.
# Portions created by CWI are Copyright (C) 1997-2005 CWI.
# All Rights Reserved.

YFLAGS = -d
# LDFLAGS = -all-static

# (At least on Fedora Core 3,) g++ 4.0.0 complains about
# "language.h:32: warning: ‘class language’ has virtual functions but non-virtual destructor"
# (not only for language.h/.mx!); hence,
# we "mis-use" the NO_INLINE_CFLAGS to switch off -Werror
# (see also conf/monet.m4).
# (At least on Fedora Core 4,) when mel is compiled with 
# g++ 4.0.0 ("Red Hat 4.0.0-8") and optimization enabled (-O2),
# mel segfaults (at least on src/modules/plain/streams.mx); hence,
# we "mis-use" the NO_INLINE_CFLAGS to switch off optimization (-O0)
# (see also conf/monet.m4).
X_CXXFLAGS = $(NO_INLINE_CFLAGS)

bin_mel = {
	SOURCES = \
	FileInfo.mx      atomops.mx     mil.mx       list.mx      prelude.mx \
	ListIterator.mx  bat_arg.mx     epilogue.mx  var_arg.mx   proto.mx \
	builtin.mx     glue.mx      mel.mx       symbol.mx \
	command.mx     html.mx      module.mx    symtable.mx \
	any_arg.mx       debug.mx       iterator.mx  object.mx    type_arg.mx \
	atom.mx          depend.mx      language.mx  operator.mx  use.mx \
	atom_arg.mx      dependency.mx  link.mx      ops.mx

	LIBS = $(MEL_LIBS)
}
