## Process this file with automake to produce Makefile.in
#
# Copyright Notice:
# -----------------
#
# The contents of this file are subject to the Pathfinder Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://monetdb.cwi.nl/Legal/PathfinderLicense-1.1.html
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
# the License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is the Pathfinder system.
#
# The Original Code has initially been developed by the Database &
# Information Systems Group at the University of Konstanz, Germany and
# the Database Group at the Technische Universitaet Muenchen, Germany.
# It is now maintained by the Database Systems Group at the Eberhard
# Karls Universitaet Tuebingen, Germany.  Portions created by the
# University of Konstanz, the Technische Universitaet Muenchen, and the
# Universitaet Tuebingen are Copyright (C) 2000-2005 University of
# Konstanz, (C) 2005-2008 Technische Universitaet Muenchen, and (C)
# 2008-2011 Eberhard Karls Universitaet Tuebingen, respectively.  All
# Rights Reserved.
#

CC = $(C99)
INCLUDES = ../include ../../../common/options ../../../gdk

# avoid "[PFty_is2ns]:ube: error: Assert has been violated at '/set/mars_patch/builds.intel-S2/nightly.Fri/intel-S2/lang/ube/hf/src/type.c 1583'"
# with Sun Studio 12 compiler and -xOn & n>1
subtyping_CFLAGS = $(SUN_NOOPT_CFLAGS)

lib_semantics = {
	NOINST
	DIR = libdir
	SOURCES = \
		functions.c \
		normalize.brg \
		heuristic.c \
		ns.c \
		options.c \
		subtyping.c \
		typecheck.brg \
		types.c \
		varscope.c \
		xquery_fo.c 
}

lib_ns = {
	NOINST
	DIR = libdir
	SOURCES = \
		ns.c
}

lib_options = {
	NOINST
	DIR = libdir
	SOURCES = \
		options.c
}

EXTRA_DIST_DIR = tests
