CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY RANGE ON (d); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY RANGE ON (b); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY VALUES ON (c); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY VALUES ON (a);
DROP TABLE testme;
