CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY RANGE (d); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY RANGE (b); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY VALUES (c); --error
CREATE MERGE TABLE testme (a INT, b MULTIPOLYGON, c json) PARTITION BY VALUES (a);
DROP TABLE testme;
