
INCLUDES = -I$(MONET_BUILD)/src/gdk -I$(MONET_BUILD)/src/monet \
	$(Z_CFLAGS) $(BZ_CFLAGS)
MTSAFE

lib_stream  =  {
	SOURCES = stream.mx
	HEADERS = h
	LIBS = \
		$(SOCKET_LIBS) $(Z_LIBS) $(BZ_LIBS) 
}

